### ISSUE TITLE
License: Create a Nuget package

### ISSUE THREAD

**Issue by kjeremy** [unosquare/ffmediaelement#1]
It would be great if you could put a nuget package up on nuget.org.  Even if it requires the user to download the ffmpeg libs separately.

**Comment by mariodivece** [comment]
Not enough people seem to be interested in this project to create and maintain a NuGet package... Only 3 stargazers... I'll create a NuGet package if more interest is shown...

**Comment by superware** [comment]
Hello Mario,

There is much interest :) Keep in mind people search NuGet for terms like "wpf media element" or "wpf player" etc, so this should actually help promote the project.

Great work!

**Comment by dmansurov83** [comment]
Hello! This is best solution for play x264 in wpf. Please make nuget package!

**Comment by jogibear9988** [comment]
If you use appveyor to create your nuget. Then your nugets can be created after each commit, so there is no time needed to maintain anything

**Comment by DininduInduwara** [comment]
Yeah please do put this up on Nuget.

**Comment by BKranz** [comment]
I signed up for GitHub just so I can say that I would really, REALLY appreciate this up on Nuget!

**Comment by mariodivece** [comment]
Guys, I really need help from someone who is able to tell me if I can release this as a NuGet Package. Here's the problem:
- My code I would like to distribute with a license as permissive as possible (Ms-PL or MIT preferably)
- It uses a heavily modified code from NAudio (Licensed as MS-Pl);
- It uses bindings generated by FFmpeg.Autogen (the tool is licensed as LGPL3, but the generated code does not state a license so I need to know if I am still able to release the nuget as MS-Pl or MIT).
- It uses images created by someone else: (CC BY-NC-SA 3.0). I need to know if I can use them if I create an MS-Pl or MIT NuGet Package
- I will not be including FFmpeg binaries with the release.

I want to be respectful of the original authors and not violate any of their license restrictions.
Please help me get my LICENSE file right so that I am able to release this as a NuGet. Thanks!

**Comment by xupefei** [comment]
Hi, I have made some research on the license issues. Here is the finding:

Conclusion: One question remaining.

Soved:
1. The MS-Pl license allows you to distribute the original or modified works freely, the only restriction is to have a copyright notice and a license file attached.
2. The output of FFmpeg.Autogen is not covered by LPGL 3.0, unless "... when the program displays **a full screen of text** and/or art that comes from the program."[[ref](https://www.gnu.org/licenses/gpl-faq.en.html#WhatCaseIsOutputGPL)]. However one more question raises here, see below.
3. CC BY-NC-SA 3.0 license is very friendly for distribution, as long as you stated the original author.

Remaining problem: 
1. Does the generated files from FFmpeg.Autogen covered by GPL **from FFmpeg** as the outputs are generated from a GPL-ed header files?

If the answer of above problem is "yes", then I am afraid you have to switch the whole ffmediaelement project to GPL.

**Comment by mariodivece** [comment]
Thank you so much for this work you are doing. I do not believe the header files are GPL but rather LGPL which is much more permissive. I am still quite unclear on the compatibility or feasability of releasing my library under something more permissive. I believe our best bet would be to ask the author of the AutoGen project what the license is for the generated files. Would you be willing to help out and ask the author and post back with your findings? https://github.com/Ruslan-B/FFmpeg.AutoGen

**Comment by xupefei** [comment]
> Would you be willing to help out and ask the author and post back with your findings

Sure I'll do it.

> I do not believe the header files are GPL but rather LGPL which is much more permissive.

I am afraid not. The zeranoe build of FFmpeg is with the parameter `--enable-gpl` [[ref](https://ffmpeg.zeranoe.com/builds/readme/win32/shared/ffmpeg-3.3.2-win32-shared-readme.txt)], so those binaries are not protected by LGPL anymore. [see [here](http://www.ffmpeg.org/doxygen/3.0/md_LICENSE.html) and [here](https://www.ffmpeg.org/legal.html)].

It seems that we need a LGPL build of FFmpeg.

**Comment by mariodivece** [comment]
It does not matter if the zeranoe binaries are compiled with that option. GPL code is in some of the internal code and not on the public API which is whar the header files are and whar the call stubs are generated from. In either case I appreciate your continued help.

**Comment by mariodivece** [comment]
Thanks to @xupefei I think I have a better idea of how I should approach NuGet package releases.
https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/51#issuecomment-312001097

**Comment by xupefei** [comment]
You are welcome. Thanks for this wonderful work!

**Comment by xmedeko** [comment]
I think the option may be to make a package without FFmpeg, as you have already mentioned. Plus a package with FFmpeg only (something like FFME.non-free, or FFME.ffmpeg, ...) , under different licensing.

Note: I am not a licensing expert, just the [NReco.VideoConverter](https://www.nuget.org/packages/NReco.VideoConverter/) ships the FFmpeg in the NuGet package. Technically the problem may be in the deployment for other platforms, so they have a version without FFmpeg [NReco.VideoConverter.LT](https://www.nuget.org/packages/NReco.VideoConverter.LT/).

**Comment by mrtylerzhou** [comment]
Many people like it,looking for it and staring it.Please try to make it more conveninent.

**Comment by BKranz** [comment]
Maybe we could make it?  Ondrej,  think you're onto something.  Why not
just structure the packages for compliance and make FFmpeg a dependency?

**Comment by mariodivece** [comment]
I'll have a prerelease nuget out today or tomorrow. I hope it's not confusing for everyone else that they still need the ffmpeg binaries.

**Comment by mariodivece** [comment]
Nuget package now available! -- Will continue the releases as we move forward.
https://www.nuget.org/packages/FFME.Windows/

**Comment by mrtylerzhou** [comment]
Thanks for your work sir

**Comment by BKranz** [comment]
Yes!  Thank you!

**Comment by MusaZ** [comment]
Unknown build error, 'Cannot resolve dependency to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.'	Unosquare.FFME.Windows.Sample

I get error like above.I am using NET 4.6.1 and VS 2015.And "InitailizeComponent();" won't run when i added ffmpeg.common.dll to References.if you help me i rejoice.
I thank You.

**Comment by mariodivece** [comment]
Please See:
https://github.com/unosquare/ffmediaelement#windows-troubleshooting

Also please note that while you can always use VS2015 to develop applications with FFME, the FFME project itself is designed to work with VS2017.

**Comment by MusaZ** [comment]
I thank you for explain.I setuped .NET Core SDK the latest version but i get error still.
![ffmpeg](https://user-images.githubusercontent.com/6318180/34016855-1cec04ba-e12c-11e7-9a1e-e1cfa3293533.jpg)
Also VS gives me error on the MainWindow when i add MediaElement code in XAML editor.I put an image about that error message.
I thank you again....
