### ISSUE TITLE
Exception when detaching event cause memory leak

### ISSUE THREAD

**Issue by xupefei** [unosquare/ffmediaelement#100]
https://github.com/unosquare/ffmediaelement/blob/d51a30d24b3aabd4ad9186db1df2cba2295f19b5/Unosquare.FFME/Rendering/AudioRenderer.cs#L427-L432

Since the `Destroy()` method is not called on the UI thread, therefore, removing this handler throws an Exception and then being swallowed. This surviving handler keeps MediaElement alive and causes a memory leak.
It should be 

```
if (Application.Current != null)
{
    Runner.UIInvoke(DispatcherPriority.Send, () =>
    {
        Application.Current.Exit -= OnApplicationExit;
    });
}
```

**Comment by mariodivece** [comment]
Accepting Change. Please see related commit.
