### ISSUE TITLE
Build Issue.

### ISSUE THREAD

**Issue by 9Arca9** [unosquare/ffmediaelement#101]
Building the same is throwing a plethora of issues for me.

https://gyazo.com/3223a5614f6757dc17a2e43f14658c7c

Not sure what's going on. Followed instruction but, there are just a lot of syntaxial errors?

**Comment by xupefei** [comment]
Try using a newer version of Visual Studio.

**Comment by mariodivece** [comment]
@xupefei is correct. Closing this issue
See configuration details here: https://github.com/unosquare/ffmediaelement/blob/master/appveyor.yml
