### ISSUE TITLE
Using the MediaElement as a SoundPlayer

### ISSUE THREAD

**Issue by TomTomB** [unosquare/ffmediaelement#105]
I tried using the MediaElement to play short sound, e.g a "click" sound, if someone clicks on a button.
For doing so I have the following method:

```c#
        private static MediaElement ClickPlayer = new MediaElement();

        public static void PlayClickSound(SoundFile filename)
        {
            if (filename == SoundFile.None) return;
            //If the player is busy return / else the ffme.dll is going to crash at this point
            if (ClickPlayer.IsPlaying) return; 
            ClickPlayer.Source =
                new Uri($"{GlobalVars.ExecutePath}Assets/Sound/" + ConvertSoundToString(filename) + ".ogg");
            ClickPlayer.Play();
        }
```
Once I try to use this method mostly nothing happens. Well- sometimes a "crickling fragment" sound gets played but thats about it. 

Any advice on how to implement a proper sound player? 

W/e I really like the ffmediaelement so far...

**Comment by mariodivece** [comment]
you need to provide a sample program with source so I can reproduce the issue. Have you tried the MediaEnded event?

**Comment by TomTomB** [comment]
Hi there, 
thanks for your quick reply. 
I dont understand in which way you would solve this problem via the MediaEnded event. 

I´ve created a small sample project. Its by far not the cleanest code but it should get you going.
[FFMESoundTest.zip](https://github.com/unosquare/ffmediaelement/files/1417669/FFMESoundTest.zip)

**Comment by mariodivece** [comment]
I am happy to tell you that downloading your program and adding references to the build of my latest commit today, works exactly as expected. No clicking or hissing or anything! New Beta 8 NuGet Package (Prerelease) will be submitted tomorrow. Please reopen this issue if you find more problems.
