### ISSUE TITLE
Allow settting codec and transport URI

### ISSUE THREAD

**Issue by TheAtlantis** [unosquare/ffmediaelement#107]
Hello, 

thank you for this project.
I would like to open URL with specific syntax (work on VLC).

Syntax is : `rtp/h264://239.0.0.21:3500`

`<transport>/<codec>://<ip>:<port>
`

The streamer send RTP packet without description.

Have you a solution for me ?

Best Regards, 

Michel

**Comment by mariodivece** [comment]
could you send me the full command line arguments on how to make this work in ffplay?
Thanks.

**Comment by TheAtlantis** [comment]
unfortunately, I have failed to open my stream (RTP multicast with Payload type 98) on ffplay ...

**Comment by mariodivece** [comment]
If it can't be opened in ffplay, I can't do much as FFME is heavily based on ffplay. Have you tried handling the MediaOpening event and setting the codecoptions object properties? I am closing this one for now and if you have further feedback please reopen.
