### ISSUE TITLE
Resizing ffmediaelement UserControl slows down the decoding process

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#108]
When I use the sample app and if I resize the window, video and audio freeze/glitch a lot. Maybe because the decoding process is made by the UI thread.

**Comment by mariodivece** [comment]
Is this on the debug or release build mode? What kind of processor and OS are you running FFME on?

**Comment by bbougot** [comment]
It occurs only in debug build mode. I have a i7-4980-HQ running on Windows 10 Fall Creators Update.

**Comment by mariodivece** [comment]
This is typically XAML debugging with some plugin. Example:
https://developercommunity.visualstudio.com/content/problem/9637/wpf-projects-debugging-is-very-slow.html
This issue is unrelated to FFME.
