### ISSUE TITLE
Error on test play following instructions provided

### ISSUE THREAD

**Issue by JohnGalt1717** [unosquare/ffmediaelement#11]
Using the ffmpeg link provided and starting it up I get the following:

Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in \Repos\ffmediaelement\Unosquare.FFmpegMediaElement.Tests\bin\Debug\Unosquare.FFmpegMediaElement.Tests.vshost.exe'.

Additional information: The runtime has encountered a fatal error. The address of the error was at 0x7349260b, on thread 0x5820. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.

**Comment by mariodivece** [comment]
Does this happen with a particular video file or any media file you throw at it?

**Comment by JohnGalt1717** [comment]
From what I can tell, any file. I specifically was trying to play an azure HLS stream but I also tried some local video files with MP4 wtih AVC level 4 video and AAC 2.0 audio

**Comment by mariodivece** [comment]
Sample file please?

**Comment by mariodivece** [comment]
This seems to be invalid and no other comments were made by the person who reported it. Closing.
