### ISSUE TITLE
High-definition audio (and hi-resolution video files) plays intermediately 

### ISSUE THREAD

**Issue by xupefei** [unosquare/ffmediaelement#110]
Some audio and video files with high bitrates are played intermediately, seems that the decoding loops does not catch up with the player.

The `Sine 1kHz 24bits 44.1khz.wav` in the attachment has this problem. A 4K video file also suffers from this issue. Moreover, when playing a 4K video, the debug log outputs the follows:
```

   Warning - SYNC AUDIO: LATENCY:     -0.041 | WAIT (samples being rendered too early)
     Debug - SYNC-BUFFER: Started.
   Warning - SYNC AUDIO: LATENCY:      0.035 | SKIP (samples being rendered too late)
     Debug - SYNC-BUFFER: Finished. Clock set to      2.204
     Debug - VideoRenderer: Frame skipped at 00:00:02.2374222
   Warning - SYNC AUDIO: LATENCY:     -0.051 | WAIT (samples being rendered too early)
     Debug - VideoRenderer: Frame skipped at 00:00:02.3040889
   Warning - SYNC AUDIO: LATENCY:      0.043 | SKIP (samples being rendered too late)
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to      2.405
     Debug - VideoRenderer: Frame skipped at 00:00:02.4374000
   Warning - SYNC AUDIO: LATENCY:     -0.039 | WAIT (samples being rendered too early)
   Warning - SYNC AUDIO: LATENCY:      0.061 | SKIP (samples being rendered too late)
     Debug - VideoRenderer: Frame skipped at 00:00:02.5375333
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to      2.739
     Debug - VideoRenderer: Frame skipped at 00:00:02.7708444
   Warning - SYNC AUDIO: LATENCY:     -0.038 | WAIT (samples being rendered too early)
     Debug - VideoRenderer: Frame skipped at 00:00:02.8709222
   Warning - SYNC AUDIO: LATENCY:      0.062 | SKIP (samples being rendered too late)
     Debug - SYNC-BUFFER: Started.
   Warning - SYNC AUDIO: LATENCY:     -0.036 | WAIT (samples being rendered too early)
     Debug - SYNC-BUFFER: Finished. Clock set to      3.072
     Debug - VideoRenderer: Frame skipped at 00:00:03.1377222
   Warning - SYNC AUDIO: LATENCY:      0.059 | SKIP (samples being rendered too late)
     Debug - VideoRenderer: Frame skipped at 00:00:03.2710556
     Debug - SYNC-BUFFER: Started.
```

Playing the 24K audio file does not produce the above log, however, the intermediate is the same as for video.

`ffplay.exe` plays them correctly without intermediates.

[Sine.WAV.zip](https://github.com/unosquare/ffmediaelement/files/1451336/Sine.WAV.zip)

**Comment by mariodivece** [comment]
I can reproduce. I have to look into it more closely. It seems that timestamps don't catch up with playback quickly enough.

**Comment by mariodivece** [comment]
Could you try again with the latest commit? Please reopen the issue if it continues.

**Comment by IcecreamBurglar** [comment]
@mariodivece, So I tried again. The stuttering is no longer there, but now it freezes a second or two after playback of a livestream starts.
Here's a video followed by a code snippet
https://drive.google.com/open?id=1ZUBXf-paGN0HRCXa-ZmtpaLuu98s--ZG
```cs
        public MainWindow()
        {
            InitializeComponent();

            Unosquare.FFME.MediaElement.FFmpegMessageLogged += MediaElement_FFmpegMessageLogged;
            Unosquare.FFME.MediaElement.FFmpegDirectory = "C:\\ffmpeg";

            var client = new YoutubeClient();
            var streamInfoTask = client.GetVideoMediaStreamInfosAsync("RtU_mdL2vBM");

            //Yes, yes. This is bad, but it'll do for a short snippet .
            streamInfoTask.Wait();
            var streamInfo = streamInfoTask.Result;

            mediaElement.Source = new Uri(streamInfo.HlsLiveStreamUrl);
        }

        private void MediaElement_FFmpegMessageLogged(object sender, MediaLogMessageEventArgs e)
        {
            Console.WriteLine("[" + e.MessageType.ToString() + "] " +  e.Message);
        }
```

**Comment by mariodivece** [comment]
Are you using the nuget package beta 7 or latest commit build?

**Comment by xupefei** [comment]
Thanks for your hard work!
I have tried the latest commit with FFmpeg 3.4.0 with both 24bit audio and 4K 30fps video files and can confirm that the lagging is gone.

@IcecreamBurglar, despite the latest build, also make sure that you are using the FFmpeg binaries from zeranoe. I still have the lagging issue with my home-made FFmpeg build.

**Comment by mariodivece** [comment]
@IcecreamBurglar What does the HlsLiveStreamUrl variable hold?

**Comment by IcecreamBurglar** [comment]
I'm building everything from source, using ffmpeg 3.4.
The hls url property contains:
`"https://manifest.googlevideo.com/api/manifest/hls_variant/gcr/us/sparams/ei%2Cgcr%2Cgo%2Chfr%2Cid%2Cip%2Cipbits%2Citag%2Cmaudio%2Cplaylist_type%2Cratebypass%2Crequiressl%2Csource%2Cexpire/dover/8/ei/hORbWuvDAoah4QTvzo2oDQ/expire/1515993316/ip/104.137.97.86/source/yt_live_broadcast/maudio/1/hfr/1/ipbits/0/id/RtU_mdL2vBM.2/playlist_duration/30/keepalive/yes/key/yt6/go/1/requiressl/yes/signature/A3CE3D58E47525D0EB1A416DC87B4795B4F4C823.0BEE7DCDD809DE60162F2107226A662029E55A6F/playlist_type/DVR/itag/0/manifest_duration/30/ratebypass/yes/file/index.m3u8"`

**Comment by mariodivece** [comment]
There's something wrong with that HLS stream. I tried playing it with FFPLAY and I get the exact same results as with FFME. I also tried playing it with VLC and made it crash.

**Comment by IcecreamBurglar** [comment]
Ah, interesting. I'll head back over to YoutubeExplode and see what they say about this. Thanks.

**Comment by songyinghao** [comment]
hi, mr mariodivece. when play 4k video, Sound doesn't play smoothly.(lastest source 2019.1.3)
video file:
https://sharefun.songyh.cn/video/4K%20Canada.webm
or
https://sharefun.oss-cn-beijing.aliyuncs.com/video/4K%20Canada.webm

**Comment by mariodivece** [comment]
nice video! it plays normally using the latest master commit. try it out!
