### ISSUE TITLE
Exception after adding source

### ISSUE THREAD

**Issue by MatyashVladislav** [unosquare/ffmediaelement#112]
Hello!
I caught strange exception (probably cos i didnt understand how to work with this lib)

I've just tried to add Source to mediaelement like this (from OpenFileDialog):
`mediaElement.Source = new Uri(((OpenFileDialog)sender).FileName);`

MediaElement in xml:
`<ffme:MediaElement x:Name="mediaElement" Background="Gray" MediaOpened="mediaElement_MediaOpened" LoadedBehavior="Play" UnloadedBehavior="Manual"/>`

and after adding file from OpenFileDialog this:

![image](https://user-images.githubusercontent.com/13140275/32835578-47a0a974-ca0f-11e7-888b-7ecf854daa8f.png)

What am i doing wrong?

**Comment by RulixQc** [comment]
Same problem here.

**Comment by mariodivece** [comment]
Could you try again with the latest nuget package?

**Comment by MatyashVladislav** [comment]
Yeah, i will try it on this weekend and reply you

**Comment by mariodivece** [comment]
Any updates here? This should be gone with the latest commit. NuGet package Beta 7 coming tomorrow. Please test and reopen this issue if you still encounter the error.
