### ISSUE TITLE
IsMuted resets while paused

### ISSUE THREAD

**Issue by Symbai** [unosquare/ffmediaelement#116]
The IsMuted state resets if the video is paused. While it is restored if you play the video again there is is a slight delay of a few miliseconds where the original audio is still played. Imagine you turned on your speakers to max and muted the video and hit play/pause then you will understand why this is an issue.

**Comment by mariodivece** [comment]
Let me check this issue out. Sorry for the late reply. I've been extremely busy

**Comment by mariodivece** [comment]
@Symbai any updates here?

**Comment by Symbai** [comment]
Sorry I'm not regularing logging into Github. I've tried reproducing it again but I cant so I'm closing this issue for now.
