### ISSUE TITLE
Tip for compilation: Error "The current SDK does not support .NET 2.0"

### ISSUE THREAD

**Issue by tenisak** [unosquare/ffmediaelement#118]
Many thanks for NuGet package! :-) 

I found your project and installed it using NuGet in my VS 2017 (on Win 7). Following error occurred in console when it was opened: _"The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0."_
![image](https://user-images.githubusercontent.com/34473563/33877669-64358422-df29-11e7-8a21-f696ec0048f3.png)
This was solved by installing [.NET Core SDK v2.1.2](https://www.microsoft.com/net/download/windows).

Maybe everyone except me already have .NET Core installed ;-) If not, I'm sending it as a tip for improving the [Compiling, Running and Testing](https://github.com/unosquare/ffmediaelement#compiling-running-and-testing) section.

**Thanks for the great project!**

**Comment by mariodivece** [comment]
Thanks. I just updated the readme file.

**Comment by tenisak** [comment]
Thank you very much for the update and for your great work on this project!
