### ISSUE TITLE
[Possible?] Force size mode

### ISSUE THREAD

**Issue by Dokman** [unosquare/ffmediaelement#119]
So for example i have a 4:3 video i can force it to Widescreen at 16:9? 
Is posible?

**Comment by mariodivece** [comment]
Try with MediElement control size/scale and let me know if you can accomplish what you need. Specifically, look at how I have implemented the Zoom functionality in the reference player:
![image](https://user-images.githubusercontent.com/351978/33954112-f7aed590-dffc-11e7-8f9a-3b18285941b9.png)

**Comment by Dokman** [comment]
i want a feature to force the videos automatically to 16:9 because i have a lot of videos at 4:3 and make it one by one or convert it....

**Comment by mariodivece** [comment]
Like I said, look at the Layout transform and do the proper scaling and clipping yourself.
http://www.c-sharpcorner.com/uploadfile/mahesh/scaletransform-in-wpf/
and:
http://www.c-sharpcorner.com/uploadfile/raj1979/cropping-or-clipping-in-wpf/
