### ISSUE TITLE
Issue with RTSP streaming

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#12]
FIrst of all, I would like to thank you for this .NET implementation of this FFmpeg player, it is such a great project!

I have only one issue, regarding real time streaming using RTSP protocol.

I would like to stream with the least delay as possible, but every RTSP stream I tried freeze very quickly.

The URI tested is : rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/definst/mp4:bigbuckbunnyiphone_400.mp4
ffmediaelement plays the first frames and freezes quickly. I don't know why there is such a freeze playing the stream.

Thank you in advance!

**Comment by mariodivece** [comment]
I still have not looked very closely at streaming scenarios -- see my code comments regarding media buffering events -- but it seems they require special handling as ffplay does it
https://www.ffmpeg.org/doxygen/3.0/ffplay_8c_source.html#l03009
I will try to take a look at this in the following days. In the meantime it would be helpful if you could get me a couple more streaming samples... maybe some hls and rtsp samples that work corrctly with ffplay would be ideal for testing.

**Comment by mariodivece** [comment]
This is working now thanks to @9Arca9 suggestions
I will continue streaming improvements on issue #13 
Thanks!
