### ISSUE TITLE
How to clone a video from one Media element to another?

### ISSUE THREAD

**Issue by tenisak** [unosquare/ffmediaelement#121]
Is it possible to copy a video that runs in one Media Element to run at the same time in another Media Element?
My idea:
```
<ffme:MediaElement x:Name="MediaEl" Background="Gray" LoadedBehavior="Play" ... />
<ffme:MediaElement x:Name="MediaElTwo" CloneOf="MediaEl" ... />
```
What is the Goal: Video preview, controls, etc. will be on the first monitor. The second monitor (projector or large TV) displays the same video on full screen.

Thank you very much for the great project and the quick response to the comments!

**Comment by mariodivece** [comment]
On my latest commit, please see the on MainWindow.xaml.cs, ```Media.RenderingVideo += ...``` around line 444, you'll see you can get direct access to the back-buffer to modify it, or copy the back buffer reference of the writable bitmap to display the image as many times you want upon rendering.

**Comment by tenisak** [comment]
Thank you very much for the answer. I'm excited that this is possible.
I understand that overlayBackBuffer is a pointer on a video image bitmap. But somehow I can not deal with it :-( Could you please advise me how to display the video in other element? Or at least a reference to an example where something similar addresses. 

Working with video is new to me, so it's a problem for me. I guess it's going to be easy, but I do not know how to :-(

**Comment by mariodivece** [comment]
Like this?
![image](https://user-images.githubusercontent.com/351978/34111138-7fdf3430-e3ce-11e7-8f79-6574644df2f4.png)

I have attached a sample project.
[FFME.CloneVideoSample.zip](https://github.com/unosquare/ffmediaelement/files/1568274/FFME.CloneVideoSample.zip)

Read through the code carefully.

**Comment by tenisak** [comment]
Wou! This is super! **Great** thanks - example works perfectly, just as I imagined.

**Comment by mariodivece** [comment]
The event arguments have changed a little bit. They allow for the decoupling of bitmap data from a specific type of bitmap source. Here's what it should look like in newer versions:

```csharp
        private void OnRenderingVideo(object sender, RenderingVideoEventArgs e)
        {
            if (wb == null || wb.BackBufferStride != e.Bitmap.Stride || wb.PixelHeight != e.Bitmap.PixelHeight)
            {
                wb = new WriteableBitmap(
                    e.Bitmap.PixelWidth, e.Bitmap.PixelHeight, e.Bitmap.DpiX, e.Bitmap.DpiY, PixelFormats.Bgr32, null);
                duplicated.Source = wb;
            }

            wb.Lock();
            CopyMemory(wb.BackBuffer, e.Bitmap.Scan0, (uint)(e.Bitmap.Stride * e.Bitmap.PixelHeight));
            wb.AddDirtyRect(e.Bitmap.UpdateRect);
            wb.Unlock();
        }
```

**Comment by tenisak** [comment]
Thank you very much for your quick reply.
