### ISSUE TITLE
Best way to play part of the video? (from time - to time)

### ISSUE THREAD

**Issue by tenisak** [unosquare/ffmediaelement#124]
My code is: 
```
Media.Source = link;

private void OnMediaOpened(object sender, RoutedEventArgs e)
{
    Media.Position = new TimeSpan(0, 1, 10);
    Media.Play();
}

private void Timer100ms_Tick(object sender, EventArgs e)
{
    if (Media.Position > new TimeSpan(0, 1, 40)) Media.Stop();
}
```
It's OK? 

ffmpeg [can use](https://ffmpeg.org/ffmpeg.html#Main-options) to play "from time - to time" parameters `-ss` and `-to`. Are these parameters implemented? Can I use them? Or my code (above) does not need to improve?

**Comment by mariodivece** [comment]
I personally like to stay away from timers as much as possible. The code you provided certainly works but I think you should just listen to changes in the position property itself.

# Option 1 (standard):
- Create a ViewModel for your UI that implements INotifyPropertyChanged
- In your ViewModel implement the Position property and fire a change notification in the setter
- In your XAML bind the FFME Position property to your ViewModel's Position Property
- Add an event handler for your ViewModel's PropertyChanged.

# Option 2 (hackiest):
If you don't understand the above steps then you need to read up on MVVM, Dependency Properties and INotifyPropertyChanged. If you don't have time to study, then you can just use:

```csharp
        /// <summary>
        /// Registers a new dependency property that is bound to the supplied source dependency property.
        /// This is useful when you need to listen for changes of dependency properties that have not been bound to a 
        /// data model or if the data model does not implement INotifyPropertyChanged.
        /// </summary>
        /// <param name="sourcePropertyName">Name of the source property.</param>
        /// <param name="source">The source.</param>
        /// <param name="callback">The callback.</param>
        private void BindToDependencyProperty(string sourcePropertyName, object source, PropertyChangedCallback callback)
        {
            var binding = new Binding(sourcePropertyName)
            {
                Source = source
            };

            var dependencyProperty = DependencyProperty.RegisterAttached(
                $"Listener{sourcePropertyName}",
                typeof(object),
                this.GetType(),
                new PropertyMetadata(callback));

            BindingOperations.SetBinding(this, dependencyProperty, binding);
        }
```

and then simply:
```csharp
            // Example of binding to the Position Dependency Property
            BindToDependencyProperty(nameof(Media.Position), Media, (s, e) =>
            {
                Debug.WriteLine($"{nameof(Media.Position)} = {Media.Position}");
            });
```

# Option 3 (easiest)
Or in my latest commit (coming to NuGet later) I have added the PositionChanged event:
```csharp
            Media.PositionChanged += (s, e) =>
            {
                Debug.WriteLine($"{nameof(Media.Position)} = {e.Position}");
            };
```

Please reopen this issue if problem was not solved.

**Comment by tenisak** [comment]
Thank you very much for the perfect and detailed explanation. I implemented Option 2 and it works great!
