### ISSUE TITLE
Player hangs when Media.Dispose() is called

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#126]

**Comment by mariodivece** [comment]
I need to take a closer look at this and reproduce.

**Comment by bbougot** [comment]
Actually it hangs when Dispose is called by the UI thread (the one that holds the player), otherwise it does not when Dispose is called using Task.Run

**Comment by mariodivece** [comment]
yep. Working on this as we speak.

**Comment by mariodivece** [comment]
I will commit changes in a few minutes co you can test.

**Comment by bbougot** [comment]
Perfect! Thanks!

**Comment by mariodivece** [comment]
Ok, looks like I was able to fix this issue. Please take a look and test with my latest commit.

**Comment by bbougot** [comment]
Looks good to me, no more hang!

**Comment by mariodivece** [comment]
Let's ask @geoperez he's in charge of nugget releases. It shouldn't go beyond Jan 2

**Comment by olegsavelos** [comment]
I updated today both libs and FFMpeg and have same behavior , hangs when calling dispose :(
The dispose hangs with this simple code 
  ```
Unosquare.FFME.MediaElement mediaView = new Unosquare.FFME.MediaElement();
 mediaView.Open(new Uri("http://techslides.com/demos/sample-videos/small.mp4"));
 mediaView.Play();
 mediaView.Close();
 mediaView.Dispose();
```
