### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Vaquitta** [unosquare/ffmediaelement#127]
Cloned the entire project and tried to build a release version, it came back with 

Error	CS0012	The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.	Unosquare.FFME.Common	C:\ffmediaelement-master\Unosquare.FFME.Common\Core\AudioParams.cs	56	N/A

Any idea what this error is about. I am using VS2017. I could see that the target framework for the FFME.Common is empty, when clicked to set a framework its showing upto .Net Standard 1.6.

Any idea where i am going wrong.

**Comment by mariodivece** [comment]
The answer is right on the Readme file. (troubleshooting windows builds)
