### ISSUE TITLE
Video from capture device?

### ISSUE THREAD

**Issue by tenisak** [unosquare/ffmediaelement#128]
Thank you very much for your great work on this project! Would it be possible to implement the option to enter a capture device as a video source? Here is an example from which you can see what parameters is need to enter into _ffplay_:
`ffplay -f dshow -video_size 768x576 -framerate 25 -pixel_format yuyv422 -i video="Osprey-460e Video Device 1C"`

**Comment by mariodivece** [comment]
Duplicate of #48 Closing.
