### ISSUE TITLE
WinForms Compatibility

### ISSUE THREAD

**Issue by Vaquitta** [unosquare/ffmediaelement#129]
Hi,

I wanted to use the mediaelement in a winform. So i created a new WPF User Control library, in that added the fme:mediaelement.. and then called the custom control inside the form using a ..

But i am getting the following error:

   at Unosquare.FFME.Core.Runner.<UIEnqueueInvoke>d__3.MoveNext() in C:\ffmpegclientview\ffmediaelement-master\Unosquare.FFME.Windows\Core\Runner.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Unosquare.FFME.MediaElementCore.<Open>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Unosquare.FFME.MediaElement.<OnSourcePropertyChanged>d__93.MoveNext() in C:\ffmpegclientview\ffmediaelement-master\Unosquare.FFME.Windows\MediaElement.DependencyProperties.cs:line 268

Would be of great help if you could let me know what i wouyld be doing wrong.. Have been trying to figure out last few hours on what could be issue but was unable to fu=igure out..

The only thing i could notice is , when i am running the sample as -is it moves past the ,  async Task UIEnqueueInvoke with action {Method = {Void <CreateAsynchronousPumpWaiter>b__0()}},
whereas in my winform custom control case it fails at this point and subsequently no action with {Method = {Void <UpdatePosition>b__38_0(System.TimeSpan)}} is called.

**Comment by Vaquitta** [comment]
Forgot to mention , the error is 

System.NullReferenceException: 'Object reference not set to an instance of an object.'

and happens when executing,  await element.mediaElementCore.Open(uri) of the private static async void OnSourcePropertyChanged function.

**Comment by tpetrina** [comment]
Maybe the dispatcher is not available in WinForms and you need to provide your implementations like MacOS sample does. I will look into it.

**Comment by Vaquitta** [comment]
Hi,. Thank you for your prompt response, appreciate the reply.

I thought the dispatcher is more os or platform specific.. 

Here we are wrapping the wpf in winform, so wouldn't it logically use same dispatcher as in wpf app itself..

**Comment by mariodivece** [comment]
could you please provide a sample app in a zip file (source code please) that reproduces your issue?

**Comment by Vaquitta** [comment]
Hi,

I have uploaded what i was attempting in a simple form here.
https://github.com/Vaquitta/mediasample.git

Please let me know if you are facing any issue in running it,,

**Comment by mariodivece** [comment]
Good starting reference point:
https://social.msdn.microsoft.com/Forums/en-US/a45f5e83-b05a-474e-bc36-032e62a58088/how-to-get-hold-of-the-dispatcher-when-running-wpf-in-winforms?forum=wpf

**Comment by mariodivece** [comment]
The **AbortSeek branch** adds WinForms compatibility. The only caveat is that you need to add the following assembly reference to your WinForms app (otherwise the Open command fails mysteriously).
![image](https://user-images.githubusercontent.com/351978/34470866-904c6846-ef00-11e7-97c6-a56abdbe5b4c.png)

Here's a screenshot of the running sample:
![image](https://user-images.githubusercontent.com/351978/34470857-5b5cb7a8-ef00-11e7-9ff8-7d885cc75343.png)

I will merge this branch with Master but I am still working on some other stuff.
Reopen this issue if you need further help.

**Comment by mariodivece** [comment]
As of the latest commit, it is now not even necessary to reference the addition RuntimeInfo assembly.
