### ISSUE TITLE
Freeze full windows UI, external code break

### ISSUE THREAD

**Issue by granoviter** [unosquare/ffmediaelement#130]
[sorry my bad english]
Hi. 

 I Write an automated player witch play an rtsp stream from a link. When stream is end or maybe happend something wrong, in the separate thread I call CloseCommand.Execute(); and                    OpenCommand.Execute(); command. The thread check the last rendeing time [in MediaElement_RenderingVideo refresh last time] and if the Datetime.Now and last rendering difference is bigger than 4 sec tne restarting process started.

My problem: 
When I stopp the streaming from the remote server the MediaElement_MediaFailed running many times, with my checking thread. When I click on the WPF windows the MediaElement_MediaFailed be stop the running and the full Windows 10 UI was freezed, So now just my thread running (I see the output windows). When I press Ctrl+Alt+Del and after the Esc the Windows (Win10 full UI not just the program ) will be responsible again. Sometime the Visual Studio 2017 Enterprive last version write this: the program is in braking mode , the brake is in the external code. (or similar)

I do something wrong?

[thank you for your work, it helped me a lot!!]

Here is my code:

    public partial class MainWindow : Window
    {
        int mediaElementRestartingTimeDelay = 10000; //ms
        DateTime lastFrameRefreshTime = DateTime.Now;
        DateTime actualTime = DateTime.Now;
        int ms = 0;
        bool streamCheckingRun = true;
        Thread th;

        private DelegateCommand m_OpenCommand = null;
        private DelegateCommand m_PauseCommand = null;
        private DelegateCommand m_PlayCommand = null;
        private DelegateCommand m_StopCommand = null;
        private DelegateCommand m_CloseCommand = null;

        public MainWindow()
        {
            InitializeComponent();

            Unosquare.FFME.MediaElement.FFmpegDirectory = Directory.GetCurrentDirectory() + "\\ffmpeg";
            //Unosquare.FFME.MediaElement mediaElement = new Unosquare.FFME.MediaElement();
            //mediaElement.Source = new Uri("rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov");
            mediaElement.Source = new Uri("rtsp://192.168.1.4:1935/live/myStream");
            mediaElement.MediaFailed += MediaElement_MediaFailed;
            mediaElement.MediaEnded += MediaElement_MediaEnded;
            mediaElement.MediaOpened += MediaElement_MediaOpened;
            mediaElement.MediaOpening += MediaElement_MediaOpening;
            mediaElement.RenderingVideo += MediaElement_RenderingVideo;

            mediaElement.Play();
            //mediaElement.Stop();

            th = new Thread(new ThreadStart(CheckState));
            th.Start();
        }

        #region Properties: Commands

        /// <summary>
        /// Gets the open command.
        /// </summary>
        /// <value>
        /// The open command.
        /// </value>
        public DelegateCommand OpenCommand
        {
            get
            {
                if (m_OpenCommand == null)
                {
                    m_OpenCommand = new DelegateCommand(a =>
                    {
                        try
                        {
                            mediaElement.Source = new Uri("rtsp://192.168.1.4:1935/live/myStream");
                        }
                        catch (Exception ex)
                        {
                            MessageBox.Show(
                                $"Media Failed: {ex.GetType()}\r\n{ex.Message}",
                                "MediaElement Error",
                                MessageBoxButton.OK,
                                MessageBoxImage.Error,
                                MessageBoxResult.OK);
                        }
                    });
                }

                return m_OpenCommand;
            }
        }

        /// <summary>
        /// Gets the pause command.
        /// </summary>
        /// <value>
        /// The pause command.
        /// </value>
        public DelegateCommand PauseCommand
        {
            get
            {
                if (m_PauseCommand == null)
                    m_PauseCommand = new DelegateCommand(o => { mediaElement.Pause(); });

                return m_PauseCommand;
            }
        }

        /// <summary>
        /// Gets the play command.
        /// </summary>
        /// <value>
        /// The play command.
        /// </value>
        public DelegateCommand PlayCommand
        {
            get
            {
                if (m_PlayCommand == null)
                    m_PlayCommand = new DelegateCommand(o => { mediaElement.Play(); });

                return m_PlayCommand;
            }
        }

        /// <summary>
        /// Gets the stop command.
        /// </summary>
        /// <value>
        /// The stop command.
        /// </value>
        public DelegateCommand StopCommand
        {
            get
            {
                if (m_StopCommand == null)
                    m_StopCommand = new DelegateCommand(o => { mediaElement.Stop(); });

                return m_StopCommand;
            }
        }

        /// <summary>
        /// Gets the close command.
        /// </summary>
        /// <value>
        /// The close command.
        /// </value>
        public DelegateCommand CloseCommand
        {
            get
            {
                if (m_CloseCommand == null)
                    m_CloseCommand = new DelegateCommand(o => { mediaElement.Close(); });

                return m_CloseCommand;
            }
        }

        #endregion

        public void CheckState()
        {
            while (streamCheckingRun)
            {
                actualTime = DateTime.Now;
                TimeSpan span = actualTime - lastFrameRefreshTime;
                ms = (int)span.TotalMilliseconds;
                if (ms > 1000 && ms <= 2000) System.Diagnostics.Debug.WriteLine("Slow network:" + ms);
                else if (ms > 2000)
                {
                    if (streamCheckingRun && !mediaElement.IsOpening && !mediaElement.IsBuffering)
                    {
                        System.Diagnostics.Debug.WriteLine("Need restart Player:" + ms);
                        CloseCommand.Execute();
                        OpenCommand.Execute();
                        Thread.Sleep(500);
                    }
                    
                    continue;
                }
                else System.Diagnostics.Debug.WriteLine("OK:" + ms + "\tBufferingProgress:" + mediaElement.BufferingProgress);
                Thread.Sleep(2000);
            }
            CloseCommand.Execute();
        }
        private void MediaElement_RenderingVideo(object sender, Unosquare.FFME.RenderingVideoEventArgs e)
        {
            lastFrameRefreshTime = DateTime.Now;
        }

        private void MediaElement_MediaOpening(object sender, Unosquare.FFME.MediaOpeningRoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("Media opening");
        }

        private void MediaElement_MediaOpened(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("Media opened");
        }

        private void MediaElement_MediaEnded(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("Media ended");
        }

        private void MediaElement_MediaFailed(object sender, ExceptionRoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("HResualt: " + e.ErrorException.HResult + "/tMessage: " + e.ErrorException.Message);
        }
        protected override void OnClosing(CancelEventArgs e)
        {
            if (th.IsAlive)
                streamCheckingRun = false;
            th.Join();
            CloseCommand.Execute();
            base.OnClosing(e);
        }

    }

**Comment by mariodivece** [comment]
correct. This is a known Issue. This issue has been fixed in the AortSeek branch (https://github.com/unosquare/ffmediaelement/tree/AbortSeek). I will be merging it in the following days to come and releasing the NuGet package soon.

**Comment by granoviter** [comment]
You are amazing, THANKS!!!

**Comment by mariodivece** [comment]
I have tested WinForms integration and it's working correctly! NuGet package b7 will be released by @geoperez . Closing this issue for now. Please reopen if you run into any additional issues.
![image](https://user-images.githubusercontent.com/351978/34643449-0dd968e4-f2ea-11e7-9af2-314d2e0300de.png)

```csharp
using System;
using System.Windows.Forms;

namespace Unosquare.FFME.WinForms
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

        }

        private async void MediaEl_MediaOpened(object sender, System.Windows.RoutedEventArgs e)
        {
            await (sender as MediaElement).Play();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            Unosquare.FFME.MediaElement.FFmpegDirectory = @"c:\ffmpeg";
            var mediaEl = new Unosquare.FFME.MediaElement();
            mediaEl.Source = new Uri("file:///C:/Users/unosp/Desktop/TestSuite/bigbuckbunnympeg4.mp4");
            mediaEl.MediaOpened += MediaEl_MediaOpened;
            elementHost1.Child = mediaEl;
        }
    }
}

```

**Comment by geoperez** [comment]
Done: https://www.nuget.org/packages/FFME.Windows/3.4.0.2-b7
