### ISSUE TITLE
Cannot change FFmpeg path once it's set

### ISSUE THREAD

**Issue by Atulin** [unosquare/ffmediaelement#131]
Initially, by mistake, I put `C:\Users\Angius\Documents\Visual Studio 2017\Projects\ffmediaelement-master` as `FFmpegPath`, which was a level below where the actual FFmpeg files lie. Now I changed it to correct `C:\Users\Angius\Documents\Visual Studio 2017\Projects\ffmediaelement-master\ffmpeg-bin`, however the program still believes the files are in the old path.
![image](https://user-images.githubusercontent.com/11233299/34587281-fe5829e8-f1a7-11e7-9081-aca4e871af7c.png)
I tried:
 - Rebulding the project
 - Restarting VS
 - Removing the `bin` and `obj` folders from the project

**Comment by tpetrina** [comment]
Actually, the configuration is stored in in `config.xml`. Look at the code in `ConfigRoot.cs`.

**Comment by mariodivece** [comment]
@tpetrina is right. Closing.
