### ISSUE TITLE
Beta 9 - NuGet Package

### ISSUE THREAD

**Issue by mariodivece** [unosquare/ffmediaelement#134]
- [x] Fix README
- [x] Logo not showing in NuGet page or package browser
- [x] Verify DocFX configuration
- [x] Publish Beta 9 Package

**Comment by mariodivece** [comment]
README has been fixed.

**Comment by geoperez** [comment]
New release https://www.nuget.org/packages/FFME.Windows/3.4.0.2-b9

**Comment by mariodivece** [comment]
Thanks. Closing now.

**Comment by tenisak** [comment]
Since the last NuGet package b9, VS 2017 reports one bug and two alerts:
![obrazek](https://user-images.githubusercontent.com/34473563/35164084-377a6a2c-fd49-11e7-8b18-9d47a470f8f4.png)
With error and both alerts, the program can be compiled and works. `LoadedBehavior="Manual"` works correctly.

**Comment by mariodivece** [comment]
I know what this is. I'll get it fixed. Thanks for reporting it.
