### ISSUE TITLE
Get volume level of video

### ISSUE THREAD

**Issue by liknes** [unosquare/ffmediaelement#136]
Thanks for making this great MediaElement replacement. I am fairly new to WPF and I am using ffmediaelement in a mediaplayer project. My application plays music videos from a playlist and when playing a video I want to start the next one as soon as the audio level of the currently playing video drops below a predefined threshold.

Could you give me some hints of how I would go about getting the audiolevel of the currently playing video?

Thanks in advance

PS! Tried to add a Help Wanted label but did not manage...

**Comment by mariodivece** [comment]
Easy. In the ```Unosquare.FFME.Windows.Sample``` project, in the file ```MainWindow.RenderingEvents.cs```, there is a line starting with ```Media.RenderingAudio += ...``` This is the event handler for when samples are queued to be sent to the sound card. Examine the sample code and see how I accumulate samples being queued to get a pseudo-RMS measure and draw the right and left channel levels on the video (certainly a more complicated example than what you need).
Use a ManualResetEvent.Set for when this condition is met, and execute the desired logic somewhere else after the WaitOne. Maybe inside a Task or a Timer...

**Comment by liknes** [comment]
Thanks a lot for the fast response! I will try this out!
