### ISSUE TITLE
Buffer progress indication

### ISSUE THREAD

**Issue by jmacato** [unosquare/ffmediaelement#137]
Hi, I'd like to say thank you for your wonderfully written library! I'd also like to ask if it is possible to include an API of some sort in ffmediaelement for reporting the actual progress of the stream, akin to this : https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/buffering_seeking_time_ranges

**Comment by mariodivece** [comment]
Yep, good feature request. For now it is only possible to use the DownloadProgress property which is a percentage of the DownloadCacheLength. There is also a BufferingProgress and a BufferCacheLength.
Buffer refers to the estimated number of bytes per second
Download is a factor of Buffer: 30 times the Buffer for lives streams and 4 times the buffer for non-live streams.

I'll see what I can do in the next iteration of this lib.

**Comment by jmacato** [comment]
Thank you for considering this feature request!

**Comment by jmacato** [comment]
@mariodivece Good day! I do wonder if this feature is still possible?

**Comment by Vasilich** [comment]
just to beat stale bot here

**Comment by Vasilich** [comment]
and de-stale again
