### ISSUE TITLE
Incorrect String Encoding for Metadata

### ISSUE THREAD

**Issue by tenisak** [unosquare/ffmediaelement#140]
Some videos are divided into chapters. Each chapter has its _Start_, _End_ and _Title_. The ffmpeg library allows you to retrieve this data using the [ffmetadata](https://ffmpeg.org/ffmpeg-formats.html#Metadata-1) parameter. (For example, in VLC or MPC-HC you can browse chapters through the program menu.) 
Is it possible to get information about chapters using ffmediaelement?

**Comment by mariodivece** [comment]
easy. Handle the MediaOpening event as in the sample application. Here's an example of what you are looking for:
![image](https://user-images.githubusercontent.com/351978/35062005-7e5ed0b2-fb88-11e7-8d3c-1ab618ba00a4.png)

**Comment by tenisak** [comment]
**Wou! That's great! Thank you very much!** 
But something seems to be wrong with metadata character encoding. Instead of characters in Czech language (e.g. "Žluťoučký", "Název") returns me incorrectly coded string ("Ĺ˝luĹĄouÄŤkĂ˝", "NĂˇzev"). Could you please do something about it?

**Comment by mariodivece** [comment]
Sample file please?

**Comment by tenisak** [comment]
Sure, here is test file: [test.zip](https://github.com/unosquare/ffmediaelement/files/1644198/test.zip)
Archive also contains a text file created with this command:
_ffmpeg.exe -i test.mp4 -f ffmetadata test.txt_

**Comment by mariodivece** [comment]
Ah, I see... It's an internal ffmpeg issue -- not an FFME issue. Sorry I can't help :(

**Comment by tenisak** [comment]
Thank you for your message. Can you please write in more detail why this is a ffmpeg error? 
The _text.txt_ file is generated using ffmpeg and it is correct: 
![obrazek](https://user-images.githubusercontent.com/34473563/35119549-966f8792-fc95-11e7-93c9-f03e28ed4999.png)

**Comment by mariodivece** [comment]
Ahh.. you're right... I am decoding this as ANSI string. Hold on. As a reference:
https://stackoverflow.com/questions/19024139/encoding-and-reading-id3-tags/19024743

**Comment by mariodivece** [comment]
Could you try again with my latest commit please? It seems to be fixed now! Reopen this issue if you still run into problems.
