### ISSUE TITLE
Review UnloadedBehavior Property

### ISSUE THREAD

**Issue by mariodivece** [unosquare/ffmediaelement#141]
I don't think the property does anything at this point. Will review.

**Comment by mariodivece** [comment]
Unloaded behavior now implemented. Closing this issue.

**Comment by igvk** [comment]
There is another element that doesn't use UnloadedBehavior - it's ElementHostBase, in HandleUnloadedEvent method.
Is it possible to respect the UnloadedBehavior value there too?
