### ISSUE TITLE
working with ffmpeg lgpl v2.1 compliant version?

### ISSUE THREAD

**Issue by rgherzog** [unosquare/ffmediaelement#142]
I hope this is the right place to ask this question. I'd like to use the ffmediaelement in a commercial project. Is the ffmediaelement working with the lgpl v.2.1 compliant version of ffmpeg? The version downloadable at https://ffmpeg.zeranoe.com is - as far as I've recognized - GPL v3 licensed. I havn't tried compiling ffmpeg on my own - using the compiler options "--enable-gpl" and without "--enable-nonfree" which seem to create a lgpl version of ffmpeg. Or is there lgpl version of ffmpeg availble for download, so that I can try the ffmediaelement with the lgpl version of ffmpeg?

**Comment by tpetrina** [comment]
You should be able to use LGPL version with no problems as far as I am  concerned.

**Comment by mariodivece** [comment]
I am not a lawyer but I think @tpetrina is right. On a separate note it would be nice to know which commercial product is using ffme
