### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Mitra-M** [unosquare/ffmediaelement#143]
I want to compile the last version for windows 10 ( installed the NET Core SDK v2.1.4 ) but get many error like these : 

![snap2](https://user-images.githubusercontent.com/17668160/35183000-e2ed4578-fdf3-11e7-8f5f-5a51dcb0fc5a.png)

**Comment by mariodivece** [comment]
Are you using vs 2017? You need 2017. 2015 will not work.

**Comment by Mitra-M** [comment]
aha , Thank you.
