### ISSUE TITLE
AudioBuffer: Check for null

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#145]
https://github.com/unosquare/ffmediaelement/blob/d5d24caa3b7267797c0d9310cbc816d0eb8a5486/Unosquare.FFME.Windows/Rendering/AudioRenderer.cs#L340

AudioBuffer should be checked for null (Exception when media is closed on my side).

**Comment by mariodivece** [comment]
Did you try with the NuGet or try with the latest commit?

**Comment by bbougot** [comment]
I tried with the master branch/last commit.

**Comment by mariodivece** [comment]
ok, could you try with my latest commit. I have synchronized access to the Destroy method and the null ref exception should not be there anymore. Let me know the results.

**Comment by bbougot** [comment]
Fixed 👍
