### ISSUE TITLE
More `IsDisposed` checking

### ISSUE THREAD

**Issue by xupefei** [unosquare/ffmediaelement#147]
In files `MediaEngine.Worker.cs` and `MediaEngine.BlockRenderingWorker.cs` there are totally three places like:

```
catch (ThreadAbortException)
{
}
catch
{
    throw;
}
finally
{
    FrameDecodingCycle.Set();
}
```
which may cause unexpected throwing when the MediaElement is being disposed, because the loop may also throw `ObjectDisposedException` when the safe handle has been closed elsewhere, and loop itself has not been aborted yet.
Therefore it will be safer to have a check before throwing:
```
catch (ThreadAbortException)
{
}
catch
{
	if (!m_IsDisposing.Value && !m_IsDisposed)
		throw;
}
finally
{
	// Always exit notifying the cycle is done.
	if (!FrameDecodingCycle.SafeWaitHandle.IsClosed)
		FrameDecodingCycle.Set();
}
```

I tried the fix with my software by quickly switching between media files, and it works flawlessly.

**Comment by mariodivece** [comment]
is this in the Beta 9 nuget? Or in source? This should not really happen in the  master branch.

**Comment by xupefei** [comment]
It is in Beta 9. I will try the master branch and report results soon.

**Comment by xupefei** [comment]
Hi, I have tried the master branch, and it still happens:
![image](https://user-images.githubusercontent.com/1687847/35470778-58cfa510-0358-11e8-99ea-dbc3cf0df89a.png)

The above exception can be reproduced by disposing the MediaElement before a media file is fully loaded, for example:
```
Media.Source = target;
Task.Delay(10).ContinueWith(t => Dispatcher.BeginInvoke(new Action(() => Media.Dispose()), DispatcherPriority.Render));
```

**Comment by mariodivece** [comment]
OK. Slightly different issue here as you are synchronously triggering a dispose. I need to check for this scenario regardless. I will investigate more.

**Comment by mariodivece** [comment]
Could you try again with the latest commit and let me know if it works as expected? Thanks.

**Comment by xupefei** [comment]
I have tried the latest commit and everything works fine now. Thank you for the excellent work!
