### ISSUE TITLE
[Help] How to asyncronous recieve the video?

### ISSUE THREAD

**Issue by Dokman** [unosquare/ffmediaelement#149]
so i've been watching a tutorial in ASP 
https://www.strathweb.com/2013/01/asynchronously-streaming-video-with-asp-net-web-api/

but right now i don't know how to handle the recieving from the server so how i can do it?

Thanks <3

**Comment by Dokman** [comment]
@bbougot i am asking help. is not anything bad.

**Comment by bbougot** [comment]
@Dokman Well, this is not linked to ffmedialement repo You should better ask in Stackoverflow, I will get more answers IMO.
