### ISSUE TITLE
Check for null

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#150]
https://github.com/unosquare/ffmediaelement/blob/2deaa9351e7f5caacf05ffae45bc345b5800aba3/Unosquare.FFME.Windows/Rendering/VideoRenderer.cs#L225

A System.NullReferenceException is thrown on TargetBitmap (the reference is null) when I close the media.
I use the master branch with latest commit.

**Comment by mariodivece** [comment]
Could you try again with the latest commit and let me know if the issue is still there?

**Comment by bbougot** [comment]
I confirm everything is working fine 👍
