### ISSUE TITLE
TaskCancelledException when media has been opened

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#151]
When media has been opened after setting Media.Source property, the OnMediaOpened method is called (WindowsMediaConnector l.105) and then calls the sender.Play() method (sender.State.CanPause is false).
However, the state of the sender is still set to "IsOpening = true" whereas RaiseMediaOpenedEvent has been called. Thus, the command completes immediately and prevent the media to be played.
Tested with latest commit on master branch, reproduced using Windows.Sample.

**Comment by mariodivece** [comment]
Could you test again with the latest commit and let me know your results?

**Comment by bbougot** [comment]
I confirm everything is working fine 👍
