### ISSUE TITLE
[Help] Gopro Hero 5 Black Streaming delay

### ISSUE THREAD

**Issue by arman04** [unosquare/ffmediaelement#152]
Hi, I have a wpf project for video stream. I connect with the gopro hero 5 black via wifi and i can display the video, but with delays between 5 or 6 seconds (some times more or least).

There is a way to synchronize it with a minimun delay like 1 second or least?. maybe delete the cache or buffer? how do this correctily

I realize wath the streaming starts before the frames display, i mean, when i see the first video images, this images are for few seconds before.

the idea is have the video in real time, any idea?. thanks!.

**Comment by mariodivece** [comment]
If you can't do it in ffplay.exe, you won't be able to do it in ffme -- That's just how ffmpeg works. Please give me the full command-line arguments in ffplay that accomplishes the results you expects. In FFME options, some pointers include MaxAnalyzeDuration, EnableReducedBuffering, and ProbeSize. Please post your results here.

**Comment by arman04** [comment]
This is the command in a python script for real time preview with no delay.

subprocess.Popen("ffplay " + loglevel_verbose + " -fflags nobuffer -f:v mpegts -probesize 8192 udp://10.5.5.9:8554﻿", shell=True)

thanks.

**Comment by mariodivece** [comment]
Oh cool. Easy then. Handle the MediaInitializing event like this:

```csharp
        private void Media_MediaInitializing(object sender, MediaInitializingRoutedEventArgs e)
        {
            // In realtime streams these settings can be used to reduce latency
            e.Options.Format.FlagNoBuffer = true;
            e.Options.Format.ProbeSize = 8192;
            e.Options.Format.MaxAnalyzeDuration = System.TimeSpan.FromSeconds(1);
        }
```

**Comment by arman04** [comment]
Excelent, works great.. Thanks!!

**Comment by arman04** [comment]
My friend, sorry i reopend this, but i have a problem.

When livestreaming for gopro hero 5 black is open, the video render delays is least a second, well thats ok, but the delays increase with the time, after 3minute of stream, the delays can be over 5 seconds. Maybe the mediaelement is buffering, i dont know. Is there a way of free the buffer in the videorender function?

I am use the config that you giveme the last time.

Thanks.

**Comment by mariodivece** [comment]
Have you tested with ffplay? What results do you see? Same? Different? What do you see for there values when you open the reference player? 
![image](https://user-images.githubusercontent.com/351978/37606526-48d1242e-2b5b-11e8-8977-e08c67ac3006.png)

**Comment by arman04** [comment]
this is the result:

bufferingProgress: 100%
Is Buffering True
Max Buffer 5,24
Has Video True

**Comment by mariodivece** [comment]
please post ffplay results as well. What do you see?

**Comment by arman04** [comment]
I tested with your project, with the same config for nobuffer and probesize. this is the result.

![captura](https://user-images.githubusercontent.com/4480130/37608230-c4aadd2a-2b78-11e8-9e5b-efd4ac01cca9.JPG)

**Comment by mariodivece** [comment]
seems like an old version. Additionally, I was asking for ffplay (ffmpeg's player) and NOT ffmeplay (my reference player which you are using an old version of).

**Comment by AwesomeSharp** [comment]
Hello, I am using the solution described above for broadcasting a GoPro camera.
Once every 10 seconds, you must send an HTTP request to the camera to update the stream.
http://10.5.5.9/gp/gpControl/execute?p1=gpStream&c1=restart

I use the command for FFMPEG:
ffplay -an -fflags nobuffer -f: v mpegts -probesize 8192 rtp: //10.5.5.9: 8554
the image is going great.

but when I use your WPF application for an example, after sending the HTTP request, the video stops. in the title there is a switch between Play and Manual.

what do you say?

P.S. Sorry for my English.
