### ISSUE TITLE
NuGet package 3.4.0.2-rc1 can not be installed

### ISSUE THREAD

**Issue by tenisak** [unosquare/ffmediaelement#153]
Thank you very much for the new installation package! I try to install it into an existing project (with NuGet b9, target fw 4.6.1) and it does not work. The same error will appear even when you insert it into a completely new project. Installation does not work even after switching to target framework 4.6.

Here is a complete listing of package installation:

> PM> Install-Package FFME.Windows -Version 3.4.0.2-rc1
> 
> Attempting to gather dependency information for package 'FFME.Windows.3.4.0.2-rc1' with respect to project 'WpfApp5', targeting '.NETFramework,Version=v4.6.1'
> Gathering dependency information took 653,32 ms
> Attempting to resolve dependencies for package 'FFME.Windows.3.4.0.2-rc1' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'FFME.Windows.3.4.0.2-rc1'
> Resolved actions to install package 'FFME.Windows.3.4.0.2-rc1'
> Retrieving package 'FFME.Windows 3.4.0.2-rc1' from 'nuget.org'.
> Install failed. Rolling back...
> Package 'FFME.Windows.3.4.0.2-rc1' does not exist in project 'WpfApp5'
> Package 'FFME.Windows.3.4.0.2-rc1' does not exist in folder 'C:\Users\User1\source\repos\WpfApp5\packages'
> Executing nuget actions took 133,94 ms
> Install-Package : Could not install package 'FFME.Windows 3.4.0.2-rc1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.
> 6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package au
> thor.
> At line:1 char:16
> + Install-Package <<<<  FFME.Windows -Version 3.4.0.2-rc1
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Time Elapsed: 00:00:00.8229064

**Comment by mariodivece** [comment]
You are right! I have re-targeted to v4.6.1 Thanks for reporting this issue. Please wait for RC2 or R1 NuGet Package.
