### ISSUE TITLE
Wait handle should be checked for closed

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#154]
https://github.com/unosquare/ffmediaelement/blob/98713b4ed172ee89f5153a23e3b82d1f731869c3/Unosquare.FFME.Common/MediaEngine.Controller.cs#L80

When I close the media, OpenOrCloseCommandDone handle is already closed so there is ObjectDisposedException on it. 
Tested with master branch on latest commit.

**Comment by mariodivece** [comment]
Do you mean when you Dispose() and then Close()? BTW, I just downloaded your Popcorn client and it's super cool!

**Comment by mariodivece** [comment]
Ok, I have improved the checks based on your suggestions. It should be good now. Could you test and let me know if my latest commit fixes the issue? I will close the issue for now but please reopen if you are still running into problems.

**Comment by bbougot** [comment]
Everything is fine thanks!
