### ISSUE TITLE
SSA/ASS Subtitle Decoding Issue

### ISSUE THREAD

**Issue by Ravenglass** [unosquare/ffmediaelement#155]
Not a major issue but tags within text in SSA/ASS files aren't being decoded properly. I'm not sure if these tags are old and have been discontinued, or if these tags are new.

Example
_Dialogue: 0,0:00:07.55,0:00:08.57,Script Font,,0000,0000,0000,,Lorem...**{\alpha&HFF&}** ipsum dolor sit amet..._

... is decoded to...

_Lorem...**\alpha&HFF&** ipsum dolor sit amet..._

**Comment by mariodivece** [comment]
Could you please check again with my latest commit?

**Comment by mariodivece** [comment]
I am closing the issue for now but please reopen if issues are still there.

**Comment by Ravenglass** [comment]
@mariodivece, I want expecting a fix that quickly. Thanx, this is way better than the default mediaelement. Awesome work!

And yes, I can confirm that it works. I tried with a couple of other tags as well, and they all work fine. 

Any idea when a new NuGet package will be available? Thanx again.

Cheers,

**Comment by mariodivece** [comment]
Cool. Expect a release during this coming weekend. I will let people report issues and fix as many as I can. I think we are ready fro a final 2.0 release!
