### ISSUE TITLE
Application hangs when switch between 2 MediaElement (short videos 5-7 sec)

### ISSUE THREAD

**Issue by Fatalex76** [unosquare/ffmediaelement#160]
Hello! After commit at 01 feb "Imporiving dispose support for MediaElement. Related to issue #147" my application began to hang when switching between 2 MediaElement (short videos 5-7 sec). 
This problem solved with rollback of line 209 in VideoRenderer.cs (method Close()):
GuiContext.Current.EnqueueInvoke => GuiContext.Current.Invoke
Please include this change in nearest commit.

**Comment by mariodivece** [comment]
Did you accidentally close this? The VideoRenderer uses Invoke now instead of EnqueueInvoke.

**Comment by Fatalex76** [comment]
It's not only this is the problem. For some reason, the thread hangs when it is call twice (from separate async calls) OpenOrCloseCommandDone.WaitOne() in MediaEngine.Close() for one MediaEngine object.

**Comment by mariodivece** [comment]
Sample code or project please

**Comment by Fatalex76** [comment]
Hello!
I've found "error" in my code.
It's looks like:
`
await mediaElement.Dispatcher.InvokeAsync(() => {
	// play
	mediaElement.Play();
});
ThreadPool.QueueUserWorkItem(async q => {
	// terminate if media duration > 5000 msec
	if(mediaElement.NaturalDuration != Duration.Automatic) await Task.Delay(5000);
	mediaElement.Dispatcher.Invoke(() => {
		if(mediaElement.IsPlaying || mediaElement.IsOpening || mediaElement.IsOpen) {
			if(mediaElement.IsOpen) mediaElement.Close();
			mediaElement.Source = null;
		}
	});
});
`
If i've commented line "mediaElement.Source = null;", all works normally, else hangs in MediaEngine.Close()

**Comment by mariodivece** [comment]
not sure I understand the issue. Is this a problem? or are you just reporting how you fixed it? Furthermore, I think your approach to closing the video after 5 seconds of playback has better alternatives. Use for example the PositionChanged event.

**Comment by Fatalex76** [comment]
I just report how I fixed it. Thank you.
