### ISSUE TITLE
Image Sequence input possible?

### ISSUE THREAD

**Issue by flipswitchingmonkey** [unosquare/ffmediaelement#163]
Is there a way to open image sequences (at a pre-defined framerate) for input? ffmpeg support it, but I haven't found anything in the code to set the Source of the MediaElement to an image sequence and set the required input parameters.

**Comment by flipswitchingmonkey** [comment]
I'll answer this myself - it works, you just need to encode the placeholder in the path properly as an URI, e.g.
`new Uri("file://d:/Output/tmp/img_%2503d.jpg");`
rather than
`new Uri("file://d:/Output/tmp/img_%03d.jpg");`

**Comment by flipswitchingmonkey** [comment]
Re-opened, sorry. There seems to be no way to specify the framerate or modify it once the media has loaded?

**Comment by mariodivece** [comment]
no way to modify it once media has loaded -- not a feature of ffmpeg or ffplay.You can specify a framerate with the medianitializing event. Set the framerate option in as: `e.Input["framerate"] = "XX";`

**Comment by klflv** [comment]
I am trying to do the same, but there is no e.Input on medianitializing event. Tried `e.Options.VideoForcedFps` but it is not working.

**Comment by flipswitchingmonkey** [comment]
Something like this works for me:

``` c#
MediaElement a;
//...
a.MediaInitializing += A_MediaInitializing;
//...
private void A_MediaInitializing(object sender, Unosquare.FFME.Events.MediaInitializingEventArgs e)
{
//... if Image Sequence
      e.Configuration.PrivateOptions["framerate"] = MyFrameRateAsAString;
// ..
}
```

**Comment by klflv** [comment]
Thank You! this works.

**Comment by mariodivece** [comment]
Another option that may also be related is the VideoRefreshRateLimit of the the Renderer options.
See example here:
https://github.com/unosquare/ffmediaelement/blob/31674e9ab8ae595a79229e31a988ea3073c1a177/Unosquare.FFME.Windows.Sample/MainWindow.MediaEvents.cs#L163
