### ISSUE TITLE
LoadedBehavior does not set Media states correctly

### ISSUE THREAD

**Issue by flipswitchingmonkey** [unosquare/ffmediaelement#164]
3.4.200
LoadedBehavior="Play" plays the video as expected, the others do not. So far so good, however none of the others, especially LoadedBehavior="Pause" set Media.IsPaused to true. All states start as false.

**Comment by mariodivece** [comment]
good catch!

**Comment by mariodivece** [comment]
Could you give it a run with my latest commit in the rootvm branch please?

**Comment by flipswitchingmonkey** [comment]
Looks good.

**Comment by mariodivece** [comment]
Thanks. Closing
