### ISSUE TITLE
set FFmpegDirectory problem

### ISSUE THREAD

**Issue by majorlinkPeter** [unosquare/ffmediaelement#165]
i have set :
            Unosquare.FFME.MediaEngine.FFmpegDirectory = @".\ffmpeg\";
and i already drop all files to the path :[project]\bin\Debug\ffmpeg\

but when i run the program also have a exception and can't play the video.Please help

![1](https://user-images.githubusercontent.com/36466354/36188194-793715d2-1185-11e8-9de7-b77f4d70ab9e.jpg)

**Comment by tenisak** [comment]
It is necessary to specify an absolute path: 
`Unosquare.FFME.MediaElement.FFmpegDirectory = @"c:\Users\User1\Documents\ffmpeg\";`

If you need to specify a path relative to the application directory:
`Unosquare.FFME.MediaElement.FFmpegDirectory = Path.Combine(System.Environment.CurrentDirectory, @"ffmpeg\");`

**Comment by majorlinkPeter** [comment]
i try the path in Unosquare.FFME.Windows.Sample project is work but same path in my own project don't work , how can i find out the problem?

**Comment by flipswitchingmonkey** [comment]
I use this and it works:
```
   AppDirectory = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
   Unosquare.FFME.MediaElement.FFmpegDirectory = AppDirectory + "\\ffmpeg";
```

**Comment by mariodivece** [comment]
I am closing this issue as it seems to be a misuse of paths. Largely unrelated to this project. Thanks to @flipswitchingmonkey and @tenisak for providing some pointers on how to properly set the path. I always recommend using Path.Combine and Path.GetFullPath methods.
