### ISSUE TITLE
Cannot build without Zeranoe ffmpeg

### ISSUE THREAD

**Issue by O-Olsen** [unosquare/ffmediaelement#17]
hi there!

I am in need of WPF MediaElement/MediaPlayer replacement since playback freezing problems, and got upon your player. I downloaded the sources, but I cannot build it since https://ffmpeg.zeranoe.com/ is forbidden now. can you post a link to the ffmpeg32 folder content that you have (3.1.4 version AFAIK), so I can try your player out? I trined some other version, but it didn`t work - Test project just does nothing after opening a video.
thank you!

PS  sorry if I posted this here, while there is some more suitable place for such quesions, just couldn`t find.

**Comment by 9Arca9** [comment]
The site doesn't seem forbidden to me.

how are you trying to access it?

**Comment by O-Olsen** [comment]
ok, now https://ffmpeg.zeranoe.com/ works, maybe I was too lucky yesterday :)
I`ve successfully built the solution, and tried opening the file in the Test project. I pasted the path to .mp4 file, clicked the "Open" button, and nothing happened, except window`s header updated, so now it contains the media path.
what might be wrong? build configuration is "Any CPU", by default - I didn`t touch it. 
thanks.

**Comment by mariodivece** [comment]
This issue is unrelated to the library. FFmpeg binaries cannot be stored in this repo or provided with the library. Closing.
