### ISSUE TITLE
The Play/Pause async commands don't seem to return as expected

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#174]
Hi Mario,

Since I upgraded ffmediaelement NuGet package to 3.4.210, the Play/Pause async commands don't seem to return as expected.

For example, in the sample code below, the NotifyPropertyChanged method is never hit.
You can try to place a breakpoint on this line in software provided in #161 to test for yourself.

Thanks.

```cs
private async Task PauseResumeAsync()
{
   if (mediaElement.IsPlaying)
       await mediaElement.Pause();
   else
      await mediaElement.Play();

   NotifyPropertyChanged(nameof(IsPaused));
   NotifyPropertyChanged(nameof(IsPlaying));
}
```

**Comment by mariodivece** [comment]
You are correct. I have managed to reproduce. Very strange that it never returns...

**Comment by mariodivece** [comment]
Could you give it a spin with my latest commit please?

**Comment by CyberSinh** [comment]
Hi,
The issue seems to be fixed. Thanks!

But in the output pane, I get the following message:
Exception levée : 'System.DllNotFoundException' dans ffme.win.dll

The message comes from SoundTouch.IsAvailable in AudioRender.cs (line 380).
Perhaps you could just use File.Exists instead of trying to call native method on a missing dll then catch error.

**Comment by CyberSinh** [comment]
Hi Mario,
When do you plan to update the ffmediaelement NuGet package (even in prerelease) ?
Because the 2.1 release contains several blocking issues.
Thanks.

**Comment by mariodivece** [comment]
Hey Sylvain possibly this week end when I get some spare time. I will leave this issue open so I remember

**Comment by CyberSinh** [comment]
This week? Thanks!

**Comment by mariodivece** [comment]
Coming in a few minutes. Closing issue
