### ISSUE TITLE
Having trouble playing rtsp media

### ISSUE THREAD

**Issue by shamsadzaman** [unosquare/ffmediaelement#175]
I have been trying to play rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov using ffmediaelement, weird thing is, sometimes it runs the other times it just stops after what it seems to be buffering for a while. 

I'm using an old dll (3.4.0.0 from the dlls properties) as the later builds totally fails to play the link where this version sometimes does.  Feel free to look at my simple player: https://github.com/shamsadzaman/ffme_player

Note: it assumes the ffmpeg dlls are in "C:\\ffmpeg"

**Comment by mariodivece** [comment]
If the connection is not stable enough, and fails more than 2 times, ffmpeg will not retry it. Please see issue #156 for a similar discussion. And in #71 I explain how ffmpeg handles connections internally and I have no control over them. If you can accomplish something in ffplay that works as you expect, share the full command line and reopen this issue. I will review then.
