### ISSUE TITLE
Drop late frames

### ISSUE THREAD

**Issue by Val-Code** [unosquare/ffmediaelement#178]
# How to drop late frames

I could not find a way to drop late frames and to watch a streaming real-time, without growing delays.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [X ] NuGet Package 3.4
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

Well, just stream from a camera ;)

## Expected Results

Real-time video.

**Comment by mariodivece** [comment]
Could you provide me with the full command line of ffplay that accomplishes the result you are looking for?

**Comment by Val-Code** [comment]
I only know that using VLC the option is "--drop-late-frames", I'm looking for the corresponding option in ffmediaelement

**Comment by mariodivece** [comment]
any chance you could help me find the equivalent in ffplay? FFMe is based off FFmpeg -- not VLC.

**Comment by mariodivece** [comment]
@Val-Code any updates or feedback? I need to know what the equivalent option in ffplay.exe is.

**Comment by AaronWatsonSubC** [comment]
Is it "-framedrop"?

**Comment by mariodivece** [comment]
As of the latest master commit you can now handle the 'MediaOpening' event and `e.Options.DropLateFrames = true;` -- please try it out and let me know if it produces the expected results.

**Comment by mariodivece** [comment]
API has changed. cLosing issues for release. Please file a new issue if you wish to provide firther feedback.

```csharp
	// You can render audio and video as it becomes available but the downside of disabling time
	// synchronization is that video and audio will run on their own independent clocks.
	// Do not disable Time Sync for streams that need synchronized audio and video.
	e.Options.IsTimeSyncDisabled =
		e.Info.Format == "libndi_newtek" ||
		e.Info.InputUrl.StartsWith("rtsp://uno");

	// You can disable the requirement of buffering packets by setting the playback
	// buffer percent to 0. Values of less than 0.5 for live or network streams are not recommended.
	e.Options.MinimumPlaybackBufferPercent = e.Info.Format == "libndi_newtek" ? 0 : 0.5;

	// The audio renderer will try to keep the audio hardware synchronized
	// to the playback position by default.
	// A few WMV files I have tested don't have continuous enough audio packets to support
	// perfect synchronization between audio and video so we simply disable it.
	// Also if time synchronization is disabled, the recommendation is to also disable audio synchronization.
	Media.RendererOptions.AudioDisableSync =
		e.Options.IsTimeSyncDisabled ||
		e.Info.InputUrl.EndsWith(".wmv");
```

**Comment by jsymon** [comment]
> As of the latest master commit you can now handle the 'MediaOpening' event and `e.Options.DropLateFrames = true;` -- please try it out and let me know if it produces the expected results.

Did `DropLateFrames` get replaced with `MinimumPlaybackBufferPercent`?
