### ISSUE TITLE
Control: Setting Position pauses the video

### ISSUE THREAD

**Issue by Tyrrrz** [unosquare/ffmediaelement#18]
I'm playing an HTTP video stream and whenever I seek to a specific part of the video via setting the Position property, it pauses the video. Invoking Play() from the same method/thread that set the position doesn't help in any way, but calling Play() after 1 second on a separate thread continues the video from the new position.

**Comment by mariodivece** [comment]
This is still true on the new control but I know how to fix it. I will work on it! Thanks for reporting this issue.

**Comment by mariodivece** [comment]
The new CommandManager architecture no longer fails to resume the media. Please see the code region of Seek and Resume Behavior in the reference player implementation and let me know if this is what you are expecting. Thanks.

**Comment by Tyrrrz** [comment]
Hi, thanks for the update.
Unfortunately I'm no longer using this control, so I can't really test it anymore.

**Comment by mariodivece** [comment]
Which control are you using instead?

**Comment by Tyrrrz** [comment]
Neither. The project I was working on changed goals a while ago so playing video was no longer necessary anymore.

**Comment by mariodivece** [comment]
Ok thanks anyways.
