### ISSUE TITLE
Handling TaskCanceledException on MediaCommand.RunSynchronously()

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#181]
Hi Mario,

The bug reporting system used in my software reported me the following unhandled exception:
```
System.Threading.Tasks.TaskCanceledException: "Se canceló una tarea."
-> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
-> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
-> Unosquare.FFME.Commands.MediaCommand+<StartAsync>d__20.MoveNext()
-> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
-> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
-> Unosquare.FFME.Commands.MediaCommand.RunSynchronously()
-> Unosquare.FFME.Commands.MediaCommandManager.ProcessNext()
-> Unosquare.FFME.MediaEngine.RunFrameDecodingWorker()
-> System.Threading.ThreadHelper.ThreadStart_Context(Object state)
-> System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-> System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-> System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
-> System.Threading.ThreadHelper.ThreadStart()
```

I cannot find any trace of my code in the stack trace.

Is this an expected behavior of ffmediaelement? 
If so, which method in the attached file should include the necessary catch to prevent my application from crashing?

[AudioPlayer.zip](https://github.com/unosquare/ffmediaelement/files/1796003/AudioPlayer.zip)

Thank you.

**Comment by mariodivece** [comment]
I don't know. Any steps to reproduce please?

**Comment by CyberSinh** [comment]
Unfortunately no.
Sorry, I forgot yesterday to attach the source code file. I updated the post.
I get one more occurrence of this issue today.

**Comment by CyberSinh** [comment]
45 crashes more for 4 days.

Is it possible that `MediaCommand.RunSynchronously()` executes a command previously canceled? 
If so, should not we plan to make sure it is not beforehand?

**Comment by mariodivece** [comment]
Would you mind working with the code itself and creatinga Pull Request that fixes it?

**Comment by CyberSinh** [comment]
I can of course do a PR to add `if (!StartAsync().IsCanceled)` before `StartAsync().GetAwaiter().GetResult();`

But having not yet understood what is the root problem, I am afraid that dealing with the consequence may hide a deeper design issue in the mechanics of the commands.

**Comment by CyberSinh** [comment]
PR done.

**Comment by alex-buraykin** [comment]
@mariodivece can you update nuget package with this fix?
