### ISSUE TITLE
Video shoot by android phone

### ISSUE THREAD

**Issue by wj985712588** [unosquare/ffmediaelement#182]
Hi,When i play the mp4 video shootted by android phone with ffme.win,the video is rotated -90°.
However ,it is Normally when i use ffplay cmd command.
![qq 20180312192045](https://user-images.githubusercontent.com/22348075/37281092-ca9b5456-262a-11e8-8a35-06300a810b10.png)
![qq 20180312192203](https://user-images.githubusercontent.com/22348075/37281093-cad06dd0-262a-11e8-9400-93a89e6ba790.png)

**Comment by mariodivece** [comment]
Attach a  small sample file please.

**Comment by wj985712588** [comment]
[MyVideoPlayer.zip](https://github.com/unosquare/ffmediaelement/files/1803094/MyVideoPlayer.zip)

**Comment by wj985712588** [comment]
[90.zip](https://github.com/unosquare/ffmediaelement/files/1803117/90.zip)
And this my sample video file
