### ISSUE TITLE
Microsoft C++ exception: EEFileLoadException,

### ISSUE THREAD

**Issue by wj985712588** [unosquare/ffmediaelement#183]
I add this Control to my wpf apps and set the FFmpegDirectory in Constructor Method of  app.xaml.cs 
The Colsole throw an exception but the wpf project can start .

`Exception thrown at 0x00007FF9C6653FB8 (in FaceMsg.exe): Microsoft C++ exception: EEFileLoadException at memory location 0x00000012C96FB1B0.`
`Exception thrown at 0x00007FF9C6653FB8 (in FaceMsg.exe): Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.`

and when i add the source property of control,the console write the info below:

`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\FFmpeg.AutoGen.dll" has been loaded.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\FFmpeg.AutoGen.dll" has been loaded.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\FFmpeg.AutoGen.dll" has been uninstalled`
`"FaceMsg.exe" (CLR v4.0.30319: FaceMsg.exe): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\FFmpeg.AutoGen.dll" is loaded. Load symbol skipped. The module is optimized and the debugger option "My code only" is enabled.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avcodec-57.dll" has been loaded. The module has been generated without symbols.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avcodec-57.dll" has been uninstalled`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avfilter-6.dll" has been loaded. The module has been generated without symbols.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avfilter-6.dll" has been uninstalled`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avformat-57.dll" has been loaded. The module has been generated without symbols.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avformat-57.dll" has been uninstalled`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avutil-55.dll" has been loaded. The module has been generated without symbols.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avutil-55.dll" has been uninstalled`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\swresample-2.dll" is loaded. The module has been generated without symbols.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\swresample-2.dll" is uninstalled`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\swscale-4.dll" has been loaded. The module has been generated without symbols.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\swscale-4.dll" has been uninstalled`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avdevice-57.dll" has been loaded. The module has been generated without symbols.`
`"FaceMsg.exe" (Win32): "D:\VisualProject\FaceMsg\FaceMsg\bin\Debug\ffmpeg\avdevice-57.dll" has been uninstalled`

But when i create a new blank wpf project,set the FFmpegDirectory works well.

**Comment by mariodivece** [comment]
That's  not nearly enough info to reproduce the issue. You will need to provide specific steps and code to reproduce. Hint: your application might be on x64 platform while ffme and ffmpeg are 32-bit. Reopen this issue when you are able to provide full steps to reproduce and all VS Solution files.
