### ISSUE TITLE
Change audio device for audio out

### ISSUE THREAD

**Issue by theneongrey** [unosquare/ffmediaelement#184]
Hi Mario,
I know that it is possible to change the audio out device by changing the DeviceNumber on the WavePlayer. Is there a way to access this value from outside, when I just have the access to the MediaElement?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package
 - [x] Build From *Master* branch, Commit *ec6aa43b*
 - [ ] Build from *Branch Name*

**Comment by mariodivece** [comment]
I am open to you providing a Pull Request that exposes this value. Please note that if you do expose it you will also need to prove a method to enumerate audio devices. You will also need to test this thoroughly. I know this is a lot of work already but it is doable and I would appreciate it if you could do it.

**Comment by AaronWatson1990** [comment]
Hey guys,

I'm currently working on this, I've worked out the enumeration stuff and have a class that manages the current audio devices, I'm adding the logic so it can also manage changes in state.  This should address #93 and once I get this all fully working in my test application(Right now it's working for the devices, I just need to handle the state changes).  I'll start moving it into the project and make a pull request if I can get it all working! :)

**Comment by theneongrey** [comment]
This sounds great. Unfortunately I won't be able to contribute to this until aprox. mid of next month.

**Comment by mariodivece** [comment]
It is now possible to call the `ChangeMedia` method, and select the new audio device.
Example below:
```csharp
        private void OnMediaChanging(object sender, MediaOpeningEventArgs e)
        {
            var m = sender as FFME.MediaElement;
            m.RendererOptions.UseLegacyAudioOut = false;
            var audioDevices = m.RendererOptions.EnumerateDirectSoundDevices();
            m.RendererOptions.DirectSoundDevice = audioDevices.First(a => a.IsDefault);
        }
```
