### ISSUE TITLE
Opening more than four instances

### ISSUE THREAD

**Issue by theneongrey** [unosquare/ffmediaelement#185]
Hi Mario,

when I'm trying to use more than four instances of the MediaElement the application will be flooded with following messages:
```
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "TaskWaitEnd"
```
Is this caused by some kind of limitations on my side, or is there something wrong?

Thank you!

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [x] Not sure

## Version Information

 - [ ] NuGet Package
 - [x] Build From *Master* branch, Commit *ec6aa43b*
 - [ ] Build from *Branch Name*

**Comment by mariodivece** [comment]
@theneongrey now that #202 has been fixed, are you experiencing the same effects? please come back with your comments and results.

**Comment by theneongrey** [comment]
Hi, I'm sorry, but I wasn't able to test it yet and unfortunately I won't be able to test it for a while. I think I will be able to get back to this project in a month at the earliest.

**Comment by Andyriod** [comment]
Hi Mario, before your change I wasn't able to start more that 3 ffmeplay.win.exe. After your last change I tried 7 and all is working well. But if I use ffme:MediaElement in my own app and try for example to put 6 of this controls in my window, it depends on whatever which control is showing the stream and which doesn't. Sometimes 4 of them are working and sometimes all 6 are showing the stream. There is no visible exception nor the application is hanging - it just doesn't show the stream.

**Comment by mariodivece** [comment]
Sample project please?

**Comment by Andyriod** [comment]
[WpfTest.zip](https://github.com/unosquare/ffmediaelement/files/1903632/WpfTest.zip)
You simply have to fill the FFMpeg-Directory and in MainWindow.xaml you can uncomment the other Player Instances.

**Comment by mariodivece** [comment]
I could not test the http streams (getting access denied). I did test with 4 to 8 simultaneous files. At more than 6 instances the CPU gets pegged at 100% and I start getting the following output on the output window:
```
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "AwaitTaskContinuationScheduled"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "AwaitTaskContinuationScheduled"
EventSourceException while processing event "TaskWaitEnd"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "TaskWaitEnd"
EventSourceException while processing event "TaskWaitEnd"
```
What exactly do you need to accomplish? There is only 1 thread that can be used for rendering in WPF so throwing millions of pixels per frame per second will obviously create a bottleneck. Now if you simply want to duplicate the image being rendered multiple times, why not use something like issue #121

What exactly do you need to accocmplish?

**Comment by Andyriod** [comment]
Of course not! This is just a demo to show you. I sure want to show different streams. If I enable 6 of the controls and start the application over and over, some of the controls showing streams and some not.
I can restrict the count of these controls to... maybe 4, but sometimes I see this issue on 4 controls also.

**Comment by mariodivece** [comment]
have you tried running it in Release mode? The WPF debugger is quite heavy on the CPU. Another alternative might be to start multiple App domains with `AppDomain.CreateDoman`. Like I asked, what exactly do you need to accomplish?

**Comment by Andyriod** [comment]
What I really wish to have is the following:
Up to 16 preview views for different streams (file or rtsp) in one app.
I also realize that this is pretty much for one thread but that would be what I would like to have. I have another control [http://www.codeproject.com/Articles/885869/Stream-Player-control](http://www.codeproject.com/Articles/885869/Stream-Player-control) which is able to view 12 streams without greater problems but is somewhat limited in source-types and customizing (VU-Meter etc.)

**Comment by mariodivece** [comment]
The reason the other control can handle more streams is precisely because of its limitations. If you need a preview wall you will need to somehow precomposite/combine the videos into a single stream or maybe apply video scaling filters? I have not tried this. These are suggestions only.

**Comment by Andyriod** [comment]
But the other control is based on ffmpeg also and it has no problems playing 12 rtsp streams simultaneously  (I can see all 12). Don't understand me wrong, I would prefer to use your control. It has much more useful features, but then I have to rely on it to work properly (and not showing n of 12 streams randomly).

**Comment by mariodivece** [comment]
Looking into the following info:
https://stackoverflow.com/questions/19905831/what-is-the-most-performant-way-to-render-unmanaged-video-frames-in-wpf
https://blogs.msdn.microsoft.com/dwayneneed/2007/04/26/multithreaded-ui-hostvisual/

**Comment by mariodivece** [comment]
I think I just found a good approach to image composition
https://github.com/higankanshi/Meta.Vlc/blob/master/Meta.Vlc.Wpf/ThreadSeparatedImage.cs

**Comment by mariodivece** [comment]
I have made massive performance improvements by enabling multi-threaded UI composition (See the ElementHostBase control). I can play 12 simultaneous streams at around 13% CPU usage. I am closing this issue for now. I am also posting example code and example results.

![image](https://user-images.githubusercontent.com/351978/40274616-a5924b96-5ba0-11e8-9372-9b1bf9604ad6.png)

```csharp
namespace SampleWpfApp
{
    using System;
    using System.Windows;
    using System.Windows.Controls;

    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        const string BaseDirectory = @"C:\Users\UnoSp\OneDrive\ffme-testsuite\";
        private readonly string[] Urls = new string[]
        {
            $"{BaseDirectory}video-elephants-loq-01.mp4",
            $"{BaseDirectory}audio-sync-test-01.mp4",
            $"{BaseDirectory}audio-sync-test-02.mp4",
            $"{BaseDirectory}audio-sync-test-03.mp4",
            $"{BaseDirectory}video-hd-01.mp4",
            $"{BaseDirectory}video-standard-01.mp4",
            $"{BaseDirectory}video-standard-02.mp4",
            $"{BaseDirectory}youtube-export-01.mp4",
            $"{BaseDirectory}video-subtitles-01.mkv",
            $"{BaseDirectory}video-subtitles-03.mkv",
            $"{BaseDirectory}youtube-export-02.mp4",
            $"{BaseDirectory}youtube-export-03.mp4",
        };

        public MainWindow()
        {
            Unosquare.FFME.MediaElement.FFmpegDirectory = @"c:\ffmpeg";
            InitializeComponent();
            Loaded += MainWindow_Loaded;
        }

        private void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            const int desiredInstences = 12;
            var maxInstances = Math.Min(desiredInstences, LayoutGrid.ColumnDefinitions.Count * LayoutGrid.RowDefinitions.Count);
            var instanceCount = 0;
            for (var rowIndex = 0; rowIndex < LayoutGrid.RowDefinitions.Count; rowIndex++)
            {
                for (var colIndex = 0; colIndex < LayoutGrid.ColumnDefinitions.Count; colIndex++)
                {
                    if (instanceCount >= maxInstances)
                        continue;

                    var url = Urls[instanceCount];
                    var player = new Unosquare.FFME.MediaElement
                    {
                        LoadedBehavior = MediaState.Play,
                        ScrubbingEnabled = true,
                        Source = new Uri(url)
                    };

                    player.MediaOpening += (snd, ev) =>
                    {
                        ev.Options.IsAudioDisabled = true;

                        if (ev.Options.VideoStream == null)
                            return;

                        // Scaling
                        var maxHeight = 1080 / LayoutGrid.RowDefinitions.Count;
                        if (ev.Options.VideoStream.PixelHeight > maxHeight)
                            ev.Options.VideoFilter = $"scale={maxHeight}:-1";
                    };

                    player.SetValue(Grid.ColumnProperty, colIndex);
                    player.SetValue(Grid.RowProperty, rowIndex);

                    LayoutGrid.Children.Add(player);
                    instanceCount++;
                }
            }
        }
    }
}
```

```xaml
<Window x:Class="SampleWpfApp.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
        xmlns:local="clr-namespace:SampleWpfApp"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid Background="HotPink" Name="LayoutGrid">
        <Grid.ColumnDefinitions>
            <ColumnDefinition />
            <ColumnDefinition />
            <ColumnDefinition />
            <ColumnDefinition />
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition />
            <RowDefinition />
        </Grid.RowDefinitions>
    </Grid>
</Window>

```

**Comment by mariodivece** [comment]
Please come back to this issue when the new 4.0.250 NuGetPackage is released and test again. Provide feedback or reopen if necessary.

**Comment by Andyriod** [comment]
Hi, I tried it with 12 http-streams. I get a around 70% CPU usage, and after some minutes of playing all mediaelements jerk (I don't know the english word for german 'ruckeln').
