### ISSUE TITLE
How to get video metadata synchronously in BackgroundWorker

### ISSUE THREAD

**Issue by tenisak** [unosquare/ffmediaelement#186]
Please is it possible to work synchronously with FFME in a separate thread? I want to gradually open all the files in the directory and retrieve the metadata from them. All this should take place outside the main thread.

I tried both the code below, but `FFmeta.IsOpening` never happens.
I also tried `FFmeta.Source = new Uri()` from a separate (third) thread and wait for the `OnMediaOpening` event. It also does not work - an inter-thread access error has fired.

## Issue Categories

 - [x] Question

## Version Information

 - [x] NuGet Package 3.4.200

## Sample Code C#
```csharp
private BackgroundWorker FFworker = new BackgroundWorker();
private Unosquare.FFME.MediaElement FFmeta;

FFmeta = new Unosquare.FFME.MediaElement();
FFworker.DoWork += FFworker_DoWork;
FFworker.RunWorkerAsync();

void FFworker_DoWork(object sender, DoWorkEventArgs e)
{
    FFmeta.Source = new Uri(@"C:\Users\Public\Videos\Sample Videos\Wildlife.wmv");

    while (!FFmeta.IsOpening) Thread.Sleep(100);

    string fTitle = "";
    FFmeta.Metadata.TryGetValue("title", out fTitle);
    ...
}
```

**Comment by mariodivece** [comment]
It is not possible. Not FFME. Not any other Wpf control. Please use  the MediaEngine class instead. This is what the WPF control uses behind the scenes.

**Comment by mariodivece** [comment]
If you could post a sample here, that would be helpful for everybody else in the future.

**Comment by tenisak** [comment]
Thanks for the tip on MediaEngine! I'm trying to figure it out... Can you please advise how to initialize MediaEngine? I see that without parameters it will not work:
`Unosquare.FFME.MediaEngine ME = new Unosquare.FFME.MediaEngine();`
Please, what do I set up as `parent` and `IMediaConnector`?

**Comment by mariodivece** [comment]
You will need to follow and understand the source code. A good starting point is to look at what the MacOS control does.
https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME.MacOS/MediaElement.cs

**Comment by tenisak** [comment]
Thanks for your patience. I found `MacMediaConnector` and its equivalent `WindowsMediaConnector`. But I can not create `WindowsMediaConnector`. I found it here: [ffmediaelement / Unosquare.FFME.Windows / Platform / WindowsMediaConnector.cs](https://github.com/unosquare/ffmediaelement/blob/3242f70c20da80790151d0ae33884c800b6a9503/Unosquare.FFME.Windows/Platform/WindowsMediaConnector.cs)
... but I do not know how to :-(

**Comment by tenisak** [comment]
I'm sorry, but I still can not figure out how to use `WindowsMediaConnector`. Is it not possible that it can not be used because it is the public interface of `IMediaConnector`, but the internal class?
I'm going through a sample app, I'm trying a few crazy things, but I can not do it:
![obrazek](https://user-images.githubusercontent.com/34473563/37541725-efa0d94a-295b-11e8-9463-716d5bd4b283.png)
Can you please advise me how to go? Thank you for your time. Sorry, but for me it's a lot of complex code.

**Comment by mariodivece** [comment]
It is a lot of complex code. Fortunately it is all there. But if you are having a hard time with Interfaces (I see you are trying to create an IMediaConnector instance) I am afraid digging deeper into the code might prove impossible to you before studying more. What I recommend you do instead is to use ffprobe.exe and parse the output. 

I also have created a great library (SWAN) with the help of my team that will get you doing things faster.
See here: https://github.com/unosquare/swan#the-processrunner-class

Example:
```csharp
// Execute a process asynchronously and return either the ouput or the error
var data = await ProcessRunner.GetProcessOutputAsync("ffprobe.exe", "your_args_here");

// Print the result
data.WriteLine();
```

Hope this info helps.

**Comment by tenisak** [comment]
Many thanks for the tip on the SWAN - some functions of it I really like.
However, my goal is only to get metadata (Duration, Metadata, and especially Chapters). When I see it, it could easily be done like this:
```c#
Unosquare.FFME.MediaEngine ME = new Unosquare.FFME.MediaEngine(?);
ME.Open(new Uri(@"file.m4v"));

ME.MediaInfo.Duration;
ME.MediaInfo.Metadata;
ME.MediaInfo.Chapters;
```
... I feel like a small piece of code might be enough. Is it really so difficult to initialize `Unosquare.FFME.MediaEngine` correctly?

It seems to me unnecessary to parse the output from ffprobe using SWAN when I already use FFME in my application. Especially when I see that MediaEngine can do it ... :-(

**Comment by mariodivece** [comment]
You can add your request in a separate issue. I'll put it in the back-burner.

**Comment by tenisak** [comment]
> I also have created a great library (SWAN) with the help of my team that will get you doing things faster.
See here: https://github.com/unosquare/swan#the-processrunner-class

Thanks for the SWAN tip! I'm trying to read the data from `ffprobe`. It looks very nice!
But I came across a [this mistake](https://github.com/unosquare/swan/issues/103) (probably) that makes the output of ffprobe distorted :-(
