### ISSUE TITLE
Select internal subtitles. Load external subtitle

### ISSUE THREAD

**Issue by leeminh310** [unosquare/ffmediaelement#188]
# Select internal subtitles. Load external subtitle

In case video has more than 1 internal subtitles, how can i select the one i want ? Same with the audio
Can i load external subtitle on playing (or pause) video. Can i do it by drag and drop ?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *3.4.220 *

**Comment by mariodivece** [comment]
This is not a video player. It's a control that will help you create a multimedia application. Your drag and drop question leads me to believe that you are either not understanding what this does, or that you have not invested any time into examining the sample code.
https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME.Windows.Sample/MainWindow.MediaEvents.cs#L120
