### ISSUE TITLE
IsPaused returns true when the file is closing

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#189]
## Issue Categories

 - [x] Bug

## Version Information

 - [x] Build From *Master* branch, Commit *1dff04100641d0801a291bc1cfa32d5c4d65509c*

## Steps to Reproduce

 1. set MediaElement.Source to null after MediaEnded event
 2. mediaElement.IsPaused is true during file closing

## Expected Results

 - mediaElement.IsPaused should be false unless mediaElement.Pause() was called
 
## Sample Code

The full source code is attached below.
Here is an extract:

### C#
```csharp
public class AudioPlayer : INotifyPropertyChanged
   {
      private readonly MediaElement mediaElement = new MediaElement();

      public bool IsPaused => mediaElement.IsPaused;
      public bool IsOpened => mediaElement.IsOpen;
      public bool IsPlaying => mediaElement.IsPlaying;

      public AudioPlayer()
      {
          mediaElement.MediaEnded += (s, e) => mediaElement.Source = null;
          mediaElement.MediaStateChanged += (s, e) =>
            {
               if (e.MediaState == System.Windows.Controls.MediaState.Play || e.MediaState == System.Windows.Controls.MediaState.Pause)
               {
                 // at the end of the audio file, when the file closing (after MediaEnded event):
                  NotifyPropertyChanged(nameof(IsPaused)); // IsPaused is true, the expected behavior is false unless mediaElement.Pause() was called
                  NotifyPropertyChanged(nameof(IsPlaying)); // IsPlaying is false which is correct as the file is closing
               }
            };
        }
}
```

[AudioPlayer.txt](https://github.com/unosquare/ffmediaelement/files/1821853/AudioPlayer.txt)

**Comment by mariodivece** [comment]
Please post your PR

**Comment by CyberSinh** [comment]
I tried to add an `IsClosing` property in the `MediaEngineState` class and adding an additional condition to the `IsPaused` property, `&& (IsClosing == false)`, but without success.

I found a way to avoid handling `MediaStateChanged` with `MediaState.Pause` when the media ended. It's probably more a workaround than a definitive fix, but it works for my code.

The PR is #190.

**Comment by CyberSinh** [comment]
Hi Mario,
Do you have any issue with my PR?

**Comment by mariodivece** [comment]
I am not entirely convinced!! Still debating whether this is the right state to put the engine in... I will for sure revisit this on the weekend.

**Comment by mariodivece** [comment]
I have merged the PR. Closing issue now.
