### ISSUE TITLE
64-bit build support

### ISSUE THREAD

**Issue by reallytommy** [unosquare/ffmediaelement#19]
Does this support 64-bit builds using the 64-bit ffmpeg shared binaries?

**Comment by xupefei** [comment]
Yes it does. But don't forget cleaning up the cache folder which is in your `TEMP` by default.
You may also make a `Any CPU` lib, e.g. https://github.com/xupefei/ffmediaelement/commit/08d8bd163b24351ee7cf3817a8de610ef0d315c0. One remaining problem is that the .dll will be quite big (~80MB).

**Comment by mariodivece** [comment]
The new control is built using AnyCPU -- This means you need to provide the approriate path to FFmpeg binaries to the architecture of your choosing. Closing as not relevant to the new version of the control.
