### ISSUE TITLE
Read metadata from a video file (without playing)

### ISSUE THREAD

**Issue by tenisak** [unosquare/ffmediaelement#191]
# Read metadata from a video file (without playing)

*Please add the option to read metadata from a video file (without playing). The goal is to be able to retrieve information about files in a separate thread. (#186)*

## Issue Categories

 - [x] Feature Request

### C#
Theoretical Code Example:
```csharp
var MR = MetaReader.Open(new Uri(@"file.m4v"));
var FileDuration = MR.Duration;  // File duration
var FileMetadata = MR.Metadata;  // Title, Copyright, etc.
var ChaptersList = MR.Chapters;  // All file chapters as list
```
### Command line ffprobe
```batch
ffprobe -v quiet -print_format json -show_format -show_chapters "test.m4v"
```

**Comment by mariodivece** [comment]
Added MediaEngine static method to do this. Example:
```csharp
var info = MediaEngine.RetrieveMediaInfo(inputUrl);
```
