### ISSUE TITLE
audio off

### ISSUE THREAD

**Issue by arman04** [unosquare/ffmediaelement#192]
#Audio Off

Is possible turn audio off?

## Expected Results

 NO audio rendering

**Comment by mariodivece** [comment]
Easy -- Siply handle the MediaOpening event and set the IsAudioDisabledOption to true. This will completely ignore all audio streams and packets.

```csharp
Media.MediaOpening += (s, e) =>
{
    e.Options.IsAudioDisabled = true;
}
```

**Comment by arman04** [comment]
it works, thanks!.
