### ISSUE TITLE
Low Latency Streaming

### ISSUE THREAD

**Issue by AaronWatsonSubC** [unosquare/ffmediaelement#199]
Hey Mario,

I'm trying to achieve a low latency H264 stream and I was wondering how I would achieve similar results as I do in ffplay. 

Here is the command

"ffplay -f h264 -framerate 60 -flags low_delay -strict experimental -sync video -probesize 32"

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [x] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

**Comment by tenisak** [comment]
Here's example how to specify the parameters when opening a file:
```c#
Media.OnMediaOpening(s, e) =>
{
    e.Options.Input["framerate"] = "60";
    e.Options.Input["flags"] = "low_delay";
    e.Options.Input["strict"] = "experimental";
    ...
};
```
It's not the perfect answer, but maybe it will help you... :-)

**Comment by AaronWatsonSubC** [comment]
Hey tenisak,

Thanks for the reply, I should have mentioned in my original post but I tried that and for some of the parameters it worked but not for all.

The specific ones I'm having an issue with are 
-flags low_delay
-sync video

**Comment by tenisak** [comment]
Okay. So this is probably just a question for @mariodivece ...

**Comment by mariodivece** [comment]
Closed by pull request

**Comment by KodeKooker** [comment]
Hello,
I too would like to know how to set those two parameters, as @AaronWatsonSubC asked:
-flags low_delay
-sync video

From this thread I didn't realize how is it possible. Thanks.

**Comment by AaronWatson2975** [comment]
Hey @KodeKooker 

I don' think I was able to figure out sync video, but that was a while ago now so it may have since been added I'm not sure.  I was able to add the low delay flag via pull request #200.  

To enable the low delay flag all you need to do is subscribe to OnMediaOpening and set it there.

Here is an example

```
//Subscribe to the event
Media.MediaOpening += OnMediaOpening;

//Set low delay flag
private void OnMediaOpening(object sender, MediaOpeningRoutedEventArgs e)
{
    e.Options.EnableLowDelay = true;
}
```

**Comment by KodeKooker** [comment]
Thanks, 
in effect the -sync parameter seems to be an ffplay feature that does not have an equivalent ffmpeg flag.
I were interested particularly in "-sync ext" to use an external master clock and get lower latency by avoiding video/audio sync.
