### ISSUE TITLE
Possible deadlock when using multiple instances in parallel

### ISSUE THREAD

**Issue by jnschulze** [unosquare/ffmediaelement#202]
# Possible deadlock when using multiple instances in parallel

Hi,
in a multi-window WPF application that runs multiple MediaElement instances in parallel (in the magnitude of 3-4) we're having a possible dead-lock issue. Each MediaElement instance is infinitely looping a playlist of videos. Occasionally, calling Play in the MediaOpened event handler (LoadBehavior is set to MediaState.Manual) blocks the UI thread forever.
It looks like this only happens when two players perform a video switch at the same time.
The unload behavior is set to "manual" as well. Setting it to "close" makes things even worse as this might block when closing media.

Do you've any clue what could go wrong there? Maybe there's some race when creating the decoding workers etc.?

## Issue Categories

 - [x ] Bug

## Version Information

 - [ x] NuGet Package 3.4.230

**Comment by jnschulze** [comment]
This apparently happens when opening the same video file from multiple players in parallel.

**Comment by mariodivece** [comment]
Very strange. It might be ffmpeg itself. Could you send some sample project where I can repro the issue please? Also what happens if you share a static lock when performing these action across all instances? Have you tried Play.GetAwaiter.GetResult()?

**Comment by mariodivece** [comment]
Is this possibly related to #185 ?

**Comment by jnschulze** [comment]
Hi Mario,
I'm currently investigating this and results look quite promising so far.
Having just started a long-running stability test, I hope that things are still running smoothly when getting back to office on Monday ;)

I'll keep you updated.
