### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by kfilbrun** [unosquare/ffmediaelement#21]
First, let me say this is an awesome project! My team is working with the Microsoft HoloLens and we have been having a very hard time finding a control that will render the video. This is working well overall and I was glad that it was so easy to add the frame capture because that was important to our project.

However, we are having an odd issue with the video rending a small stripe on the right hand side of the control. It appears like some sort of overflow or resolution issue. When I subscribe to the stream from the demo application there is no bug but even when I copy the control directly into our project it still shows up. Sometimes it's black and sometimes pieces of video that has played in the past.

![image](https://cloud.githubusercontent.com/assets/18154524/23317977/a573656e-fa9e-11e6-94b0-db3a5fc59a24.png)

If you have any questions or I can help resolve this, please let me know! I've tried many configurations and can't seem to get this straightened out so I decided to post as a last resort.

Thanks,
Kidron

**Comment by mariodivece** [comment]
Hmmm... very strange. Maybe try to make the control size the exact size of the video stream. If that fixes the issue you may have an issue with the width and height ratio creating some artifacts. Another thought would be to use a different version of the FFMpeg binaries and see if this still occurs.

**Comment by kfilbrun** [comment]
I've played with the control size extensively and that doesn't seem to have an impact. In your example program it renders fine and that control is not sized matched. Also, I'm using the same binaries for both sine they aren't distributed with the package.  I wonder if perhaps is something else strange in my XAML code. We do have code that is locking the aspect ratio of the window as it is scaled so that could be contributing. I'll try removing that and see if it helps. Thanks!

**Comment by kfilbrun** [comment]
It did indeed end up being an aspect ratio/sizing issue and I was prevent from discovering it because of the aspect ratio lock code that was running. I was able to disable that code and adjusted the window size with the stream running until the bar went away. Then I inspected the window and set the window starting height/width to correspond with the working ratio. Once I did that I was able to re-introduce the aspect ratio lock and had no issues with it reappearing when I adjusted the window size. Thanks for your help!

**Comment by mariodivece** [comment]
Is it something I need to change in the code? If so, where?

**Comment by kfilbrun** [comment]
If it is something that needs to be changed I'm not sure where it would be in your code. I fixed it for my app by just fixing the size of the WPF window which the control was set to fill. There may be another way to fix in which the control could detect the aspect ratio of the video incoming and adjust size accordingly (or at least adjust something about the way it's rendered). It seems to do this pretty well in the demo application so I'm not sure where it was broken in my project. Its obviously an issue precipitated by incorrect sizing of the control but I don't know where it originates.
