### ISSUE TITLE
Question about alpha channel

### ISSUE THREAD

**Issue by Mitra-M** [unosquare/ffmediaelement#211]
Hi,

I tried FFme to play gifs /Videos with transparent background. it does work very good to play gif animations, But for videos does not.

Is it possible to play a video with transparent background?

**Comment by jnschulze** [comment]
Yep. Just change the `VideoPixelFormat` in `Unosquare.FFME.Common/Shared/Constants.cs` from `AV_PIX_FMT_BGR0` to `AV_PIX_FMT_BGRA` and add a respective mapping to the `MediaPixelFormats` dictionary in  `Unosquare.FFME.Windows/Rendering/VideoRenderer.cs`:
`{ AVPixelFormat.AV_PIX_FMT_BGRA, PixelFormats.Bgra32 }`

We should default to BGRA in future or make the format configurable. But as the currently used BGR0 requires 32 bits per pixel as well there shouldn't be a performance hit.

**Comment by Mitra-M** [comment]
It's great. 
It did not have much impact on performance.
Thanks a lot.

But In general, ffme's CPU usage is much higher than WPF-mediaelement.
At least on my system :
Corei7
Win10
4G ram
GPU : AMD Radeon HD 5450 (it's not a good gpu)

**Comment by jnschulze** [comment]
@Mitra-M,
you should try turning on hardware acceleration in a MediaOpening handler (it‘s still off by default)

**Comment by mariodivece** [comment]
It's still very experimental and does not work on all builds. You can see that we are waiting on FFmpeg 3.5 for full HW acceleration support. Check the open issue #69 But @jnschulze is correct. The standard WPF media element renders and scales directly on the GPU memory and therefore does not need a round trip to the standard RAM that has to handled by the CPU. It's all planned but the FFmpeg API is still somewhat immature.

**Comment by Mitra-M** [comment]
@jnschulze , I set `e.Options.EnableHardwareAcceleration = true` and `e.Options.EnableFastDecoding = true` ,  but not works.

@mariodivece ,Thanks for the explanation, ffmediaelement is great.
WPF-mediaelement can't play any gif/Video with a transparent background.
So, It would be nice if you add those Feature to 'Features Overview'.

 I wait for FFmpeg 3.5 and full HW acceleration.
but , how LAVFilter does HWA with current FFmpeg API?

**Comment by mariodivece** [comment]
LAV filter supports HW ENCODING and DECODING facilities but there is no easy way of getting a memory handle on the GPU to display it directly. I currently have to retrieve that data off the GPU by copying all those pixels and sending them BACK to the GPU to display them. This is why there is very limited hw accel support in ffplay.exe

**Comment by mariodivece** [comment]
I am closing this issue as I have made the default pixel format BGRA in my latest commit.

**Comment by kelvinlawyer** [comment]
How can I configure to play video with alpha channel in current FFME Release 4.0.270?
