### ISSUE TITLE
Unable to load FFmpeg binaries from folder 'c:\ffmpeg'.

### ISSUE THREAD

**Issue by ashelleyPurdue** [unosquare/ffmediaelement#213]
# Unable to load FFmpeg binaries from folder 'c:\ffmpeg'.

*Please enter a general description for the issue. Delete sections that are not relevant and provide additional sections if necessary.*

When trying to set the control's source, I get the error "Unable to load FFmpeg binaries from folder 'c:\ffmpeg'."

I have copy/pasted all 11 of the required files into the folder 'c:\ffmpeg', so they are definitely there.  I also made sure to set Unosquare.FFME.MediaElement.FFmpegDirectory = @"c:\ffmpeg";  in App.xaml.cs.

## Issue Categories
 - [ ] Bug?
 - [ ] Question

## Version Information

 - [ ] NuGet Package *3.4.230*

## Steps to Reproduce

 1. Clone the following repo and checkout branch "FFME_video_player_issue_demonstration":
        https://github.com/ashelleyPurdue/JustTag.git
 2. Build and run the program
 3. The program has a built-in file browser.  Use it to navigate to any folder on your system that has a video file in it.
 4. Once you have navigated to a folder with a video in it, click on that video.

## Expected Results

 - The video should display on the MediaElement control
 - The "Play" button and time slider should enable themselves

## Actual Results

- The MediaFailed event will trigger, which will throw the following exception:
    An exception of type 'System.IO.FileNotFoundException' occurred in JustTag.exe but was not handled in user code
Unable to load FFmpeg binaries from folder 'c:\ffmpeg'.
 
### XAML
```xml
<UserControl x:Class="JustTag.VideoPlayer"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:JustTag"
             xmlns:paz="clr-namespace:Wpf.Controls.PanAndZoom;assembly=Wpf.Controls.PanAndZoom"
             xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition Height="38"/>
        </Grid.RowDefinitions>


        <paz:ZoomBorder Name="zoomBorder"
            Grid.Row="0"
            Stretch="None"
            ZoomSpeed="1.2" 
            ClipToBounds="True"
            Focusable="True"
            VerticalAlignment="Stretch"
            HorizontalAlignment="Stretch"
        >
            <ffme:MediaElement Name="videoPlayer"
                LoadedBehavior="Play"
                ScrubbingEnabled="True"
                MediaOpened="videoPlayer_MediaOpened"
                MediaOpening="videoPlayer_MediaOpening"
                MediaFailed="videoPlayer_MediaFailed"
             />
        </paz:ZoomBorder>

        <Grid x:Name="videoControls"
            Grid.Row="1"
            IsEnabled="False" 
        >
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="50"/>
                <ColumnDefinition Width="1*"/>
            </Grid.ColumnDefinitions>

            <Button x:Name="playButton"
                Grid.Column="0"
                Grid.Row="1"
                Content="Play"
                Margin="5,5,5,5"
                Click="playButton_Click"
             />

            <Slider x:Name="videoTimeSlider"
                    Grid.Column="1"
                    Grid.Row="1"
                    VerticalAlignment="Center"
                    Margin="5,5,5,5"
                    MouseMove="videoTimeSlider_MouseMoved"
                    PreviewMouseDown="videoTimeSlider_MouseDown"
             />
        </Grid>

    </Grid>
</UserControl>
```

### C#
```csharp
// App.xaml.cs
    public partial class App : Application
    {
        public App():base()
        {
            //string baseDir = AppDomain.CurrentDomain.BaseDirectory;
            //Unosquare.FFME.MediaElement.FFmpegDirectory = System.IO.Path.Combine(baseDir, "ffmpeg\\");
            Unosquare.FFME.MediaElement.FFmpegDirectory = @"c:\ffmpeg";
        }
    }

// VideoPlayer.xaml.cs
// -- snip --
        public void ShowFilePreview(FileInfo selectedFile)
        {
            // Disable the navigation controls
            videoControls.IsEnabled = false;

            // Put it in the media element and start playing.
            // We're going to pause it immediately during the MediaOpened event
            videoPlayer.Source = new Uri(selectedFile.FullName);
            //PlayOrPause(true);
        }

        // Event handlers

        private void videoPlayer_MediaOpening(object sender, Unosquare.FFME.Events.MediaOpeningRoutedEventArgs e)
        {
            MessageBox.Show("Opening");
        }

        private void videoPlayer_MediaOpened(object sender, RoutedEventArgs e)
        {
            // It's rude to suddenly start playing a video without asking,
            // so pause it after we've seen the first frame.
            PlayOrPause(false);

            // If it's a video, enable the playback controls
            videoControls.IsEnabled = videoPlayer.NaturalDuration.HasTimeSpan;
        }

        private void videoPlayer_MediaFailed(object sender, ExceptionRoutedEventArgs e)
        {
            // Swallowing exceptions is bad juju.
            throw e.ErrorException;
        }

// -- snip --
```

**Comment by mariodivece** [comment]
It works fine for me... Did not have to change a thing from your project for it to work.
![image](https://user-images.githubusercontent.com/351978/39205759-3aadcc4e-47c1-11e8-8294-0d5881d54c4a.png)
Are you sure your ffmpeg folde rlook like this?
![image](https://user-images.githubusercontent.com/351978/39205802-5a108202-47c1-11e8-9911-5bb35b21ede6.png)

**Comment by ashelleyPurdue** [comment]
I found the issue.  If you have "prefer 32 bit" unchecked in the build settings, you will get this error.  Sounds like something that needs to be added to the documentation, if it's not already there.

**Comment by mariodivece** [comment]
I did not have to change a thing in your project. But yes. If you have 32 bit ffmpeg binaries, then it's safer to check the prefer 32 bit in the build options I guess.

**Comment by mariodivece** [comment]
sure does. It's exactly the same. Just make sure you compile in 64-bit and that you use 64-bit binaries.

**Comment by maralihart** [comment]
how do I make it 64-bit?

**Comment by mariodivece** [comment]
https://blogs.msdn.microsoft.com/tolong/2007/03/20/use-visual-studio-to-build-64-bit-application/

**Comment by Kanhoto** [comment]
Hi,

I know this post is old but I would like to know if you got the issue in msvc project.
I tried all the things I could find on internet :
- Adding path "C:\FFmpeg" and "C:\FFmpeg\bin" to $PATH
- Putting bin content in solution destination
- compilling x64
- nugget packages

But none of them worked, I dunno where my problem come from.
https://github.com/Kanhoto/RobotController_v1

**Comment by interous** [comment]
I ended up having two problems. I got ffmpeg from https://github.com/BtbN/FFmpeg-Builds/releases and, first, you have to get the GPL version: postproc doesn't seem to be in the LGPL version. Second, it seems that the libraries present in the latest release are too new for FFME, but the file called ffmpeg-n4.4-latest-win64-gpl-shared-4.4.zip worked for me. (I ended up digging through the DLL loading code, in Unosquare.FFME\FFmpeg\FFLibrary.cs, and noticed that it explicitly listed library versions, which were lower than the versions I had from ffmpeg. Maybe there was a deprecation or something, I don't know, but as I said, switching to the older ffmpeg made my webcam start working.)

I know this is a transient solution for what may be a transient issue, but maybe Kanhoto is having the same issue(s)?

**Comment by darklinkpower** [comment]
@interous Thanks a lot for the info, it was also not working for me but I can also confirm that using 4.4's files solved it for me.
