### ISSUE TITLE
ffplay wasapi can’t intialize audio client

### ISSUE THREAD

**Issue by LYH8112** [unosquare/ffmediaelement#214]
# Issue Title (*change this title!*)

*Hi, please play the attachment
[viedo.zip](https://github.com/unosquare/ffmediaelement/files/1954314/viedo.zip)
.*

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Step 1
 2. Step 2
 3. Step 3

## Expected Results

 - Result 1
 - Result 2
 
### XAML
```xml
<MainWindow>
</MainWindow>
```

### C#
```csharp
System.Console.WriteLine("Change Me Please!");
```

### Command line ffplay
```batch
ffplay "hello.mp4"
```
## Delete This Section
- Please consider a donation here: https://www.paypal.me/mariodivece/50usd 
- I work on this project for fun and on my free time.
- Provide as much information as possible and any sample files

**Comment by LYH8112** [comment]
set SDL_AUDIODRIVER=directsound
ffplay  myVideo.mp4

this is OK

**Comment by mariodivece** [comment]
This is not a good description of the issue. Rejected.
