### ISSUE TITLE
Targeting x64 is impossible

### ISSUE THREAD

**Issue by PixelWeaver** [unosquare/ffmediaelement#215]
# Targeting x64 is impossible

Compiling gives no error at all but running nearly always get the "Could not load ffmpeg binaries from folder ..." error or completely freezes the whole window when playing webm files. I'm guessing it's how it is supposed to be but x86 is a really serious limitation for RAM usage, especially for image processing.

## Issue Categories

 - [x] Bug
 - [x]  Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

Build From *Master* branch, Commit 737ca20

## Steps to Reproduce

 1. Compile in x64
 2. Run any webm video (if you can get that far)

**Comment by mariodivece** [comment]
Any way you could provide some feedback or what your problem was so everyone running into your same issue can resolve it?
