### ISSUE TITLE
Sync subtitles

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#216]
# Sync subtitles
Would be great to add an option which lets the user change the sync of subtitles (moving forward or backward).

## Issue Categories

 - [ ] Bug
 - [x] Feature Request
 - [ ] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
Let me see what I can do with this one. seems like an easy feature.

**Comment by mariodivece** [comment]
example with the latest code:
```csharp
private void OnMediaOpening(object sender, MediaOpeningRoutedEventArgs e)
{
    // You can start off by adjusting subtitles delay
    e.Options.SubtitlesDelay = TimeSpan.FromSeconds(2.5);
}
```
