### ISSUE TITLE
Changing subtitle while playing a media

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#217]
# Changing subtitle while playing a media
Add the ability to change the subtitles while playing the media (the MediaOptions is not accessible outside of MediaOpening event, hence SubtitlesUrl can not be updated).

## Issue Categories

 - [ ] Bug
 - [x] Feature Request
 - [ ] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
Good suggestion. This is a duplicate of #57
