### ISSUE TITLE
System.InvalidOperationException: "Start may not be called on task that has completed."

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#220]
Here is an exception that was sent to me by my automated bug reporting system:

### StackTrace
```
System.InvalidOperationException: "Start may not be called on task that has completed."

-> System.Threading.Tasks.Task.Start(TaskScheduler scheduler)
-> Unosquare.FFME.Commands.MediaCommand+<StartAsync>d__20.MoveNext()
-> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
-> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
-> Unosquare.FFME.Commands.MediaCommand.RunSynchronously()
-> Unosquare.FFME.Commands.MediaCommandManager.ProcessNext()
-> Unosquare.FFME.MediaEngine.RunFrameDecodingWorker()
-> System.Threading.ThreadHelper.ThreadStart_Context(Object state)
-> System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-> System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
-> System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
-> System.Threading.ThreadHelper.ThreadStart()
```

Is it ok to simply replace, in the `MediaCommand.StartAsync` method :

```cs
if (IsDisposed || m.IsDisposed || TaskContext.IsCanceled || IsRunning) return;
```

with 

```cs
if (IsDisposed || m.IsDisposed || TaskContext.IsCanceled || IsRunning || TaskContext.IsCompleted) return;
```

Thanks.

**Comment by mariodivece** [comment]
Yes! Good Catch. Thanks!

**Comment by mschleicher** [comment]
The bug still persists in FFME.Windows 4.0.260 and FFmpeg.AutoGen 4.0.0.2 installed via NuGet:

> **[FrameDecodingTask] | ERROR | App.CurrentDomain_UnhandledExceptionThreadException Object: System.InvalidOperationException: "Start" kann nicht für eine Aufgabe aufgerufen werden, die abgeschlossen wurde.**
> 
> -    bei System.Threading.Tasks.Task.Start(TaskScheduler scheduler)
> -    bei Unosquare.FFME.Commands.MediaCommand.<StartAsync>d__24.MoveNext()
> - --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
> -    bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> -    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> -    bei Unosquare.FFME.Commands.MediaCommand.RunSynchronously()
> -    bei Unosquare.FFME.Commands.MediaCommandManager.ProcessNext()
> -    bei Unosquare.FFME.MediaEngine.RunFrameDecodingWorker()
> -    bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> -    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> -    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> -    bei System.Threading.ThreadHelper.ThreadStart() 
> 

The exception occurred after playing videos for about 4 hours.
I will investigate further.
