### ISSUE TITLE
could not open "xxxxxx.mp4"， error -22:Invalid argument

### ISSUE THREAD

**Issue by LYH8112** [unosquare/ffmediaelement#221]
# Issue Title (*change this title!*)

when open video, get error "could not open 'xxx.mp4', error -22:Invalid argument"

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Step 1
 2. Step 2
 3. Step 3

## Expected Results

 - Result 1
 - Result 2
 
### XAML
```xml
<MainWindow>
</MainWindow>
```

### C#
```csharp
System.Console.WriteLine("Change Me Please!");
```

### Command line ffplay
```batch
ffplay "hello.mp4"
```
## Delete This Section
- Please consider a donation here: https://www.paypal.me/mariodivece/50usd 
- I work on this project for fun and on my free time.
- Provide as much information as possible and any sample files

**Comment by mariodivece** [comment]
There is not enough information to reproduce the issue. Please fill out all relevant areas and format accordingly. Feel free to reopen when ready.
