### ISSUE TITLE
JPEG images have a natural duration of 0.04 seconds.  They shouldn't even HAVE a timespan in the first place.

### ISSUE THREAD

**Issue by ashelleyPurdue** [unosquare/ffmediaelement#223]
# Issue Title (*change this title!*)

If you load a JPEG image and check its NaturalDuration.HasTimeSpan property, it will return true.  Intuitively, one would expect an image file to have no time span, since it's just a still image.  If you check NaturalDuration.TimeSpan.TotalSeconds, you'll get a value of 0.04.  Always.

If you perform the same process with a PNG image, you'll get the expected result.  NaturalDuration.HasTimeSpan will return false.  Attempting to run NaturalDuration.TimeSpan.TotalSeconds will raise a System.InvalidOperationException, as it should.

## Issue Categories

 - [ ] Bug

## Version Information

 - [ ] NuGet Package 3.4.240

## Steps to Reproduce

 1. Open a JPEG image with FFME
 2. Call NaturalDuration.HasTimeSpan
 3. Observe an incorrect result of true.
 4. Call NaturalDuration.TimeSpan.TotalSeconds
 5. Observe a return value of 0.04
 6. Repeat the same with a PNG image
 7. Observe how HasTimeSpan returns false, as it should.

## Expected Results

 - Expectation: Calling NaturalDuration.HasTimeSpan should return false when the file loaded is a JPEG image.  Calling NaturalDuration.TimeSpan.TotalSeconds should raise a System.InvalidOperationException

- Reality: Calling NaturalDuration.HasTimeSpan returns true.  Calling NaturalDuration.TimeSpan.TotalSeconds returns 0.04.
 
### XAML
```xml
<MainWindow>
    <ffme:MediaElement Name="videoPlayer"
                LoadedBehavior="Manual"
                ScrubbingEnabled="True"
                MediaOpened="videoPlayer_MediaOpened"
                MediaFailed="videoPlayer_MediaFailed"
                PositionChanged="videoPlayer_PositionChanged"
    />
</MainWindow>
```

### C#
```csharp
public MainWindow()
{
    InitializeComponent();
    videoPlayer.Source = new Uri("cute_kittens.jpg");
}

private void videoPlayer_MediaOpened()
{
    Console.WriteLine(videoPlayer.NaturalDuration.HasTimeSpan);
    Console.WriteLine(videoPlayer.NaturalDuration.TimeSpan.TotalSeconds);
}
```

**Comment by mariodivece** [comment]
Well, this is an FFmpeg based control and ffmpeg indeed returns a duration of 0.04. Please check the output of ffprobe below. Nothing I can do about this. I suspect this is because the video codec to decode the image is mjpeg (motion jpeg) with only 1 picture.
![image](https://user-images.githubusercontent.com/351978/39971579-2f409d6c-56c3-11e8-9c10-e7a602d48834.png)
