### ISSUE TITLE
Little pitch and cracks in audio rendering

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#226]
# Little pitch and cracks in audio rendering

When playing a source, there are regularly small pitch and cracks in audio. I'm using SoundTouch for rendering and I've tested it with multiple sources (videos from Youtube, local files encoded in mp4 ,...)

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *3.4.240*

**Comment by mariodivece** [comment]
What happens when you don't use soundtouch?

**Comment by mariodivece** [comment]
All media files?

**Comment by bbougot** [comment]
Yes I get the issue playing any media file, local or streaming, and is occuring mainly when bass sound is present.

**Comment by mariodivece** [comment]
- Have you tried on a different computer?
 - Which operating system are you using?
 - Which Sound card?

**Comment by mariodivece** [comment]
you'll need to provide me with a small sample file and the feedback I am asking for. Otherwise I can't tell what the problem might be

**Comment by mariodivece** [comment]
I am closing for now. Please reopen with required feedback.
