### ISSUE TITLE
Is it possible to capture video file from dshow source (webcam) ?

### ISSUE THREAD

**Issue by saturne1606** [unosquare/ffmediaelement#227]
I saw it's possible to capture a frame, but not video at all.
Thanks

**Comment by mariodivece** [comment]
No. This is outside the scope of this project. This is a multimedia decoding control and does not intend to do encoding. Which by the way, should not be too hard to do on your own at all. You can check out an example here:  https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/encode_video.c
