### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by mtinnes** [unosquare/ffmediaelement#23]
I'm getting the following error at this line in Decoding.cs:
`receivedFrame = this.FillDecodedPictureHolderFrame(&readingPacket, emptyPacket);`

`{"Error decoding video packet. Code -1094995529 - Invalid data found when processing input"}`

Trying to load an MP4 (MOV) and using the latest 32bit shared build ffmpeg build from zeranoe. I've also ensured the build is targeted for x86. I've also tried a number of various video formats.

**Comment by mariodivece** [comment]
Sometimes using an older build (the one the readme states should be used) helps, as there might be discrepancies between the entry points in the wrapper and the binaries.

**Comment by wdcossey** [comment]
I can't play any videos when running the Test app, always get the same error _Invalid data found when processing input_.

I'm using the binaries listed in the readme file, also tried various others and always the same exception.

The odd thing is, I can play the files fine when I specify the Source in the .xaml, it renders and plays in the Visual Studio designer xD.

Perhaps there's an error unboxing the FFMpeg binaries from the resources?

**Comment by xupefei** [comment]
I can confirm this issue while using `ffmpeg-3.2.4-win32-shared.zip`.

Load any video in VS debugging mode failed at https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFmpegMediaElement/FFmpegMedia.Decoding.cs#L451
```
var decodeResult = ffmpeg.avcodec_decode_video2(VideoCodecContext, DecodedPictureHolder, &receivedFrame, readingPacket);
```
```
Error decoding video packet. Code -1094995529 - Invalid data found when processing input
```

However, the same video can be loaded smoothly outside VS (double click on the .exe).

**Comment by mariodivece** [comment]
FFmpeg unboxing is no longer perfomed in the new control. Closing.
