### ISSUE TITLE
Play video from frames received in a callback

### ISSUE THREAD

**Issue by khan990** [unosquare/ffmediaelement#230]
# Play Video from frames received in a callback

I am working on an application where I am using third party camera application suite. I get video stream of the camera in a callback function that has:

- number of bytes received
- frame bytes
- width
- height
- codec type

I need to play this as video. But I am struggling to find the right tool to do that.

Things I have already tried.

- Googled a lot, but no help.
- I managed to play maximum of two cameras by using https://github.com/Ruslan-B/FFmpeg.AutoGen for decoding frames to images and then playing them using `PictureBox `control of Windows Form. But that is not an elegant solution. As for more than two cameras the application is very slow due to high memory spikes in rendering... I need to use a tool that is specifically made for this purpose. 

So my **QUESTION** is:
Can I achieve the above mentioned feature by using this library? i.e. play encoded or decoded image sequence in real time?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ x ] Question
 - [ ] Not sure

## Version Information

 - [ 4.0.250 ] NuGet Package *Enter Version Number Here*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

**Comment by mariodivece** [comment]
No, sorry, this control is not intended to get arbitrary data from callbacks. If all you need to do is draw very fast, you could use a WriteableBitmap or an InteropBitmap. In WinForms I recommend using a GDI Bitmap directly.
