### ISSUE TITLE
UI Thread hangs

### ISSUE THREAD

**Issue by GAMP** [unosquare/ffmediaelement#231]
Hi.
I just referenced the latest build and v4 FFMpeg binaries and now observing a strange behavior.
Whenever MediaElement renders a video its impossible to create new window and if attempted it seems that UI/Dispathcer thread hangs.

This was not the case with previous build.

Edit:
The problem seem to be located here 

` internal ImageHost VideoView { get; } = new ImageHost(GuiContext.Current.Type == GuiContextType.WPF) { Name = nameof(VideoView) };`

and then when handling Unloaded event
```

       protected virtual void HandleUnloadedEvent(object sender, EventArgs e)
        {
            if (ElementDispatcher == null)
                return;

            ElementDispatcher.InvokeShutdown();
            RemoveLogicalChild(Host);
            RemoveVisualChild(Host);
            ElementDispatcher = null;
            Element = null;
        }
```

Attempt to shutdown main Dispatcher causing application to stop processing any messages and hang.

**Comment by mariodivece** [comment]
Could you try again with my latest commit? See he details of the above commit and reopen the issue if needed.

**Comment by GAMP** [comment]
Looks good :)
