### ISSUE TITLE
Debugging into ffmediaelement

### ISSUE THREAD

**Issue by shamsadzaman** [unosquare/ffmediaelement#232]
# Issue Title (*How to link pdb files with source files?*)

I am using the ffmediaelement (v 3.4.230) in my wpf app. Now I want to debug into the ffme source code. I have downloaded the pdb and source from [here](https://github.com/unosquare/ffmediaelement/releases/tag/v2.30.0). I loaded those pdb files but I can hit the breakpoint, which I'm assuming is probably not at the location the pdb files is looking for. Should I put the code somewhere else? 

I know I can build new dll/pdb from the source code and reference them, but I want to use the existing pdb/dlls. Please let me know if there's a way to achieve that.

## Issue Categories

 - [x] Question

## Version Information

 - [x] NuGet Package *3.4.230*

**Comment by mariodivece** [comment]
I am unsure. But have you tried placing the source files the following folder? `c:\projects\ffmediaelement`
Let me know if that works. Reopen if can provide additional feedback.
