### ISSUE TITLE
How can I playout to decklink SDI.

### ISSUE THREAD

**Issue by whamma** [unosquare/ffmediaelement#233]
# How can I playout to decklink SDI.

## I want't to playout to decklink SDI while playing the video. I want also those frames are same position. 
Please help me.

 - [ ] Bug
 - [x] Feature Request
 - [ ] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
I don't own that hardware and I am not sure how it works or what you might be requesting. Reopen if you wish to provide additional information.
