### ISSUE TITLE
Seek once, position changed twice

### ISSUE THREAD

**Issue by RyanYANG52** [unosquare/ffmediaelement#234]
# Issue Title (*Seek once, position changed twice*)

*Run Windows.Sample project, when i seek a video file by click on the `PositionSlider`, `MediaElement.Position` changed twice, first to the intended seek position, then back to the Position before Seek, at last to the intended seek position. I try with 2 mkv and 2 mp4, both seek while pausing and seek while playing are the same result. If you look the slide closely, you can see it go back and forward*

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *4.0.25*
 - [x] Build From *Master* branch, Commit *278aaff*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Open any mkv or mp4 video file
 2. Pause at any position, eg. 0:00:01
 3. Set a breakpoint here https://github.com/unosquare/ffmediaelement/blob/278aaffc61b327764e82e6e712acc7a499afe44e/Unosquare.FFME.Windows/MediaElement.PropertyUpdates.cs#L149
 4. Click on the Position Slide somewhere else, eg. 0:00:50

## Expected Results

 - Breakpoint will enter twice
 - First time is from 0::00:50 to 0:00:01, Second time is from 0:00:01 to 0:00:50

Hope my explanation make sense, thanks.

**Comment by mariodivece** [comment]
This is one of the best, easiest bugs I have had to resolve in this project. That was a great catch which vastly increased seeking performance! Thanks for the bug report!

**Comment by RyanYANG52** [comment]
I test you fix, works great. But Seek while playing still have the same issue. You can test by playing a video, and click the slide couple of times, look closely you will see, sometimes(not all the time, before fix is all the time) the slide will still go back and forward

**Comment by RyanYANG52** [comment]
I find a way to debug it, and with 3 different file, it all have the some problem
First, here https://github.com/unosquare/ffmediaelement/blob/c8043f5f2cc364b5c37fa7cb768e580710fc13ea/Unosquare.FFME.Windows/MediaElement.DependencyProperties.cs#L203
```
        private static bool isUserSeek = false;
        private static Stopwatch sw = new Stopwatch();

        private static object OnPositionPropertyChanging(DependencyObject d, object value)
        {
            var element = d as MediaElement;
            if (element == null || element.MediaCore == null || element.MediaCore.IsDisposed) return TimeSpan.Zero;
            if (element.MediaCore.State.IsSeekable == false) return element.MediaCore.State.Position;

            if (element.PropertyUpdatesWorker.IsExecutingCycle)
            {
                lock (element.ReportablePositionLock)
                {
                    if (element.m_ReportablePosition != null)
                    {
                        // coming from underlying engine
                        if (isUserSeek)
                        {
                            isUserSeek = false;
                            sw.Stop();
                            Console.WriteLine($"m_ReportablePosition:{element.m_ReportablePosition.Value} seek duration:{sw.ElapsedMilliseconds}");
                            sw.Reset();
                        }

                        return element.m_ReportablePosition.Value;
                    }
                }
            }

            // Clamp from 0 to duration
            var targetSeek = (TimeSpan)value;
            if ((element.MediaCore?.MediaInfo?.Duration ?? TimeSpan.Zero) != TimeSpan.Zero)
                targetSeek = ((TimeSpan)value).Clamp(TimeSpan.Zero, element.MediaCore.MediaInfo.Duration);

            // coming in as a seek from user
            element.MediaCore?.RequestSeek(targetSeek);
            isUserSeek = true;
            Console.WriteLine($"targetSeek:{targetSeek}");
            sw.Start();
            return targetSeek;
            // return element.MediaCore.State.Position;
        }
```

Add a global variable to log only user's seek and next position changed from engine. Switch to **release** mode, so it'll be clear on your output.

here is the output:
```
targetSeek:00:57:31.2050952
m_ReportablePosition:00:57:31.1990000 seek duration:123
targetSeek:01:11:04.8173903
m_ReportablePosition:00:57:32.8284404 seek duration:13
targetSeek:00:39:37.0241565
m_ReportablePosition:00:39:37.0090000 seek duration:118
targetSeek:00:28:42.9436839
m_ReportablePosition:00:28:42.9706274 seek duration:93
targetSeek:01:23:39.9346839
m_ReportablePosition:01:23:39.9819838 seek duration:103
targetSeek:00:42:37.8268887
m_ReportablePosition:00:42:37.8580129 seek duration:140
targetSeek:00:26:08.7295887
m_ReportablePosition:00:26:08.7395561 seek duration:75
targetSeek:00:18:10.1341210
m_ReportablePosition:00:26:12.6140145 seek duration:0
targetSeek:00:41:44.6496145
m_ReportablePosition:00:41:44.6710469 seek duration:136
```

you can see, most of time is OK, user seek some position, next change is nearby, but those seek duration is less , engine still give a position changed by the last position.

I think because the seek is enqueue command, while playing, maybe it will wait until the render command before it to execute(which will fire a position changed from the position before seek) .

I try to change the user seek return from `targetSeek` to `element.MediaCore.State.Position`, and the UI works fine, BUT I don't think that is the right fix, because seek take some time( >100ms in my pc) , UI would look like less responsive.

I also test on the `OnMediaPositionChanged`, it didn't have the same problem. So it's only visible when use Position to binding a wpf slide.

**Comment by mariodivece** [comment]
Maybe I need to implement a state property called IsSeekEnqueued... Any other ideas on how to resolve this?

**Comment by mariodivece** [comment]
Another option: Set the IsSeeking flag to true when a seek command is enqueued

**Comment by RyanYANG52** [comment]
IsSeeking seems to be used by decodingworker, if set to true directly, it may not go in here:https://github.com/unosquare/ffmediaelement/blob/20f97326a3f57cf3e713a671f9f231298fa4446b/Unosquare.FFME.Common/MediaEngine.Workers.Decoding.cs#L62
 I think you only need to remove the pending properties update after user seek,  I add `element.m_ReportablePosition = null;` after `element.MediaCore?.RequestSeek(targetSeek);` so 'UpdateDependencyProperties' will ignore the pending `ReportablePosition` set by decoder before user seek command, then when decoding next frame, `IsSeeking` will be set to true, the 'UpdateDependencyProperties' will not notify property changed until SeekCommand is finished.

I test with couples of video file, it seems OK, but I am not sure if my logic here is 100% tight.

Another thing I notice is, seek duration(using stopwatch to log between user seek and next reportablePosition changed) is longer when I use HW accelerated about 150ms, without it, it's less then 100ms, it's that normal?

**Comment by mariodivece** [comment]
Thanks @RyanYANG52 Seems to work well.
on your comment about seeking, you are correct. HW decoding tends to be slower than direct CPU decoding. And it's not only the decoding itself that takes time but also the need to transfer packet data into the GPU and then transfer decoded frame data from GPU memory into regular CPU memory for filtering and bitmap data rendering. The advantage of using HW decoding is that it offloads some of the CPU time on to the GPU. On fast CPUs this is not significant abd I would recommend using CPU decoding instead. On lower end CPUs like Atoms/Centrinos/etc it might be beneficial to use HW GPU decoding facilities.
