### ISSUE TITLE
ffmediaelement doesn't allow special character in filepath

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#235]
## Issue Categories

 - Bug

## Version Information

 - Latest NuGet Package

## Steps to Reproduce

Try to open a file named "力 ちから.mp3".

## Expected Results
The file should be played.

But the `ffmpeg.avformat_open_input` function failed with the following exception:  
_Exception levée : 'Unosquare.FFME.Shared.MediaContainerException' dans ffme.common.dll
Could not open '力 ちから.mp3'. Error -22: Invalid argument_
 
You can get more info about this known issue in this thread:
https://github.com/filoe/cscore/issues/298

**Comment by mariodivece** [comment]
What do you suggest I do?

**Comment by CyberSinh** [comment]
Maybe including a helper to wrap `GetShortPathName` function coumd works. 
cscore seems to have found another workaround for this issue:
https://github.com/filoe/cscore/commit/dff8d0d226270190dbc84f1070c0667947c13b1d

I don't know what is the best option.

**Comment by CyberSinh** [comment]
Hi Mario,

From the time my C++/CLI audio processing library (https://github.com/CyberSinh/Luminescence.Audio/commit/a7f20bf59227f5aa5dd270f23cc6b0d7d8e0cccf#diff-fe64f658d44e496f11be3c6317bca86a) supported file playback (before recommending ffmediaelement), I used this code to convert .NET strings to native UTF8 strings.

And compatibility with non-Latin caracters was pretty good. 

I hope this snippet can help you.

```cpp
void Play(String^ path)
{
   avformat_open_input(_container, ManagedStringToNativeUtf8One(path).c_str(), NULL, NULL);
}

static std::string ManagedStringToNativeUtf8One(String^ s)
{
   array<Byte>^ encodedBytes = Encoding::UTF8->GetBytes(s);
   std::string utf8;
   utf8.resize(encodedBytes->Length);
   Marshal::Copy(encodedBytes, 0, IntPtr((void*)utf8.data()), encodedBytes->Length);
   return utf8;
}
```

**Comment by mariodivece** [comment]
I already have such method in FFInterop.cs check out a similarly named method. I think the real problem is that ffmpeg can only open 8.3 formatted paths. I'll see what can be done

**Comment by mariodivece** [comment]
I have been looking into this and I think I am going to leave it up to the user to perform path conversion to keep portability of ffme.common.dll You can of course also use a custom stream (a feature I added a few minute ago) to open paths of any kind. In the sample application you can open the file with special chars like this:
`customfile:///C:/Users/UnoSp/Downloads/力 ちから.wmv`

Check out the OpenCommand in `App.Command.cs` and see how it uses the customfile:// scheme to instantiate a custom file stream and open, read, and seek within the file.
That, or simply use the following class to format your special paths:

```csharp
private static class NativeMethods
            {
                private const int MAX_PATH = 255;

                /// <summary>
                /// Gets the short path.
                /// </summary>
                /// <param name="path">The path.</param>
                /// <returns>The short path for 8.3 support</returns>
                public static string GetShortPath(string path)
                {
                    var shortPath = new StringBuilder(MAX_PATH);
                    GetShortPathName(path, shortPath, MAX_PATH);
                    return shortPath.ToString();
                }

                [DllImport("kernel32.dll", CharSet = CharSet.Auto)]
                private static extern int GetShortPathName(
                    [MarshalAs(UnmanagedType.LPTStr)] string path,
                    [MarshalAs(UnmanagedType.LPTStr)] StringBuilder shortPath,
                    int shortPathLength);
            }
```

Closing for now but feel free to provide additional feedback.

**Comment by CyberSinh** [comment]
Using the `GetShortPathName` function seems to be an acceptable workaround. This solution is not perfect (ReFS does not support short names for example), so I hope that ffmpeg will have one day native support for unicode windows paths.

**Comment by CyberSinh** [comment]
Using the `GetShortPathName` function is not really a permanent solution because the creation of short file names could be disabled for some users (with "NtfsDisable8dot3NameCreation" registry value). 
There is a `FileInputStream` in `Unosquare.FFME.Windows.Sample.Foundation`. This class is it ready for production use? What would be the best approach to solve this issue permanently, ideally by a builtin solution? Thanks.

**Comment by AntonyCorbett** [comment]
I think we can insert this line before the call to avformat_open_input (in MediaContainer.StreamInitialize):

openUrl = Encoding.GetEncoding(1252).GetString(Encoding.UTF8.GetBytes(openUrl));

But it may be best to leave the caller to do the work.

**Comment by CyberSinh** [comment]
Thanks @AntonyCorbett. 

Adding this line in the user code before calling MediaElement.Open does not work:
```cs
string path = Encoding.GetEncoding(1252).GetString(Encoding.UTF8.GetBytes(@"C:\Downloads\mp3\力 ちから.mp3"));
await mediaElement.Open(new Uri(path));
// openUrl in MediaContainer.StreamInitialize() == åŠ› ã%C2%81¡ã%C2%81‹ã‚‰.mp3
// Error -2: No such file or directory
```

But adding this line directly in the MediaContainer.StreamInitialize() method works:
```cs
string openUrl = Encoding.GetEncoding(1252).GetString(Encoding.UTF8.GetBytes($"{prefix}{MediaUrl}"));
// openUrl = åŠ› ã¡ã‹ã‚‰.mp3
// No error
```

@mariodivece, what do you think about that?

Thanks.

**Comment by mariodivece** [comment]
I have opened a new issue.
