### ISSUE TITLE
Reopen about Decklink SDI playout.

### ISSUE THREAD

**Issue by whamma** [unosquare/ffmediaelement#237]
ffmpeg supports decklink playout, is it possible with ffmediaelement?
Please see the link below.
[https://www.ffmpeg.org/ffmpeg-devices.html#Examples-11](url)

Can't I ask ffmediaelement for features available in FFmpeg?

**Comment by tenisak** [comment]
**1) Standard Zeranoe compilation ffmpeg does not contain Decklink support.** You can compile your own using [this script](https://github.com/jb-alvarado/media-autobuild_suite).

**2) I have tried these examples how to display the video using ffplay with DeckLink Mini Recorder:**  

_Here's how to check out the formats supported by device:_
`ffmpeg -f decklink -list_formats 1 -i "DeckLink Mini Recorder"`
The output is for example:
```
[decklink @ 07d91080] Supported formats for 'DeckLink Mini Recorder':
        format_code     description
        ntsc            720x486 at 30000/1001 fps (interlaced, lower field first)
        pal             720x576 at 25000/1000 fps (interlaced, upper field first)
        ntsp            720x486 at 60000/1001 fps
        palp            720x576 at 50000/1000 fps
        23ps            1920x1080 at 24000/1001 fps
        24ps            1920x1080 at 24000/1000 fps
        Hp25            1920x1080 at 25000/1000 fps
        Hp29            1920x1080 at 30000/1001 fps
        Hp30            1920x1080 at 30000/1000 fps
        Hi50            1920x1080 at 25000/1000 fps (interlaced, upper field first)
        Hi59            1920x1080 at 30000/1001 fps (interlaced, upper field first)
        Hi60            1920x1080 at 30000/1000 fps (interlaced, upper field first)
        hp50            1280x720 at 50000/1000 fps
        hp59            1280x720 at 60000/1001 fps
        hp60            1280x720 at 60000/1000 fps
```
_Video playback goes to run as follows:_ 
`ffplay -f decklink -video_input sdi -format_code Hp25 -i "DeckLink Mini Recorder"`

**3) This should go play through ffmediaelement.** The parameters should be entered as follows: 
```
Media.OnMediaOpening(s, e) =>
{
    e.Options.Input["f"] = "decklink";
    e.Options.Input["video_input"] = "sdi";
    e.Options.Input["format_code"] = "Hp25";
    e.Options.Input["i"] = "DeckLink Mini Recorder";
};
```
I did not have the opportunity to set up the source and test it. But with Osprey, I tested and ffmediaelement worked (see issue #48 ). 
Resource setup (uri) should work as follows: 
`Media.Source = new Uri("device://decklink/?video=DeckLink Mini Recorder");` 

(I'm sorry for my bad English.)

**Comment by mariodivece** [comment]
Thanks for the support @tenisak! The options Api has changed a little bit but it's easy enough to figure out.

**Comment by mariodivece** [comment]
@whamma do you wish to provide additional feedback before I close this issue?

**Comment by whamma** [comment]
@tenisak Thank you so much! I will try it.
@mariodivece No, Thank you. You can close this issue.
