### ISSUE TITLE
InvalidOperationException while disposing MediaElement

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#239]
## Issue Categories

 - Bug

## Version Information

 - Latest NuGet Package

## Steps to Reproduce

 1. Add the following line of code: 
`AppDomain.CurrentDomain.ProcessExit += (s, e) => mediaElement.Dispose();`
 2. Start the program in debug mode in Visual Studio, play a media, then exit
 3. The Visual Studio debugger should catch the exception

The issue has been introduced by this commit:
https://github.com/unosquare/ffmediaelement/commit/fa9c2000a674e1d6b9306e1b1b65bae3c89b3bf8

## Expected Results

A smooth exiting. Dispose method should never throw any exception.

## StackTrace
```
System.InvalidOperationException
  HResult=0x80131509
  Message=L'opération n'est pas valide en raison de l'état actuel de l'objet.
  Source=PresentationCore
  Arborescence des appels de procédure :
   à System.Windows.ContextLayoutManager.From(Dispatcher dispatcher)
   à System.Windows.UIElement.remove_LayoutUpdated(EventHandler value)
   à Unosquare.FFME.MediaElement.Dispose()
```

**Comment by mariodivece** [comment]
What do you suggest as a fix?

**Comment by CyberSinh** [comment]
I just sent you a PR to fix this issue.

**Comment by mariodivece** [comment]
COuld you test again with my latest commit please?

**Comment by CyberSinh** [comment]
Yes, it works! Thank you very much Mario.

**Comment by mariodivece** [comment]
I released the latest NuGet a couple of hours ago. This fix is included in the package.
