### ISSUE TITLE
How to know that ffmpeg is initialized correctly and has the correct version?

### ISSUE THREAD

**Issue by tenisak** [unosquare/ffmediaelement#242]
*If I specify any existing directory as the ffmpeg directory, initialization will take place. There is no error even when the directory is empty.*

## Issue Categories
 - [x] Feature Request
 - [x] Question

## Version Information
 - [x] NuGet Package *3.4.200*

## Steps to Reproduce
 1. Set `FFmpegDirectory` to any existing directory. 
 2. The error occurs only when you try to open the file. There will be no error, but it will not be opened.

## Expected Results
 - The ability to find out if he has succeeded in correctly initializing ffmpeg.
 - Ideally, detect if ffmpeg is in the correct version.
 
### C#
```csharp
Unosquare.FFME.MediaElement.FFmpegDirectory = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
```

**Comment by mariodivece** [comment]
Check out the new method `MediaElement.LoadFFmpeg();` and the new property `MediaElement.FFmpegVersionInfo` ! See the method `protected override void OnStartup(StartupEventArgs e)` in the sample app for a usage example. Thanks. This was a good idea!
