### ISSUE TITLE
Copying Memory Fails: AccessViolationException

### ISSUE THREAD

**Issue by jfquarto** [unosquare/ffmediaelement#243]
I have a WPF application which plays videos from a list continuously. 
The list contains 5 videos in different formats.
After 4 hours or so the app crashes with this Windows error:

> .Net Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception
> Exception Info: System.AccessViolationException
>    at Unosquare.FFME.Platform.WindowsNativeMethods+NativeMethods.CopyMemory(IntPtr, IntPtr, UInt32)
>    at Unosquare.FFME.Platform.WindowsNativeMethods+<>c__DisplayClass14_0.<CopyMemoryParallel>b__0(Int32)
>    at System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task)
>    at System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(System.Object)
>    at System.Threading.Tasks.Task.ExecuteSelfReplicating(System.Threading.Tasks.Task)
>    at System.Threading.Tasks.Task.Execute()
>    at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
>    at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
>    at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
>    at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
>    at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean)
>    at System.Threading.Tasks.Task.RunSynchronously(System.Threading.Tasks.TaskScheduler)
>    at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action`1<Int32>, System.Action`2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func`4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
>    at System.Threading.Tasks.Parallel.For(Int32, Int32, System.Action`1<Int32>)
>    at Unosquare.FFME.Platform.WindowsNativeMethods.CopyMemoryParallel(IntPtr, IntPtr, UInt32)
>    at Unosquare.FFME.Platform.WindowsNativeMethods.CopyMemory(IntPtr, IntPtr, UInt32)
>    at Unosquare.FFME.Rendering.VideoRenderer.LoadTargetBitmapBuffer(Unosquare.FFME.Events.BitmapDataBuffer, Unosquare.FFME.Shared.VideoBlock)
>    at Unosquare.FFME.Rendering.VideoRenderer+<>c__DisplayClass24_0.<Render>b__1()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Application.RunDispatcher(System.Object)
>    at System.Windows.Application.RunInternal(System.Windows.Window)
>    at System.Windows.Application.Run(System.Windows.Window)
>    at QSecondScreen.App.Main()

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
-  [x]  Not sure

## Version Information

 - [x] NuGet Package *4.0.260.0*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

**Comment by jnschulze** [comment]
@mariodivece 
I've encountered this issue myself some time ago but apparently it is less likely to occur in the recent releases. This is due to a race where the UI thread attempts to access a video frame that was already released by the media engine.

**Comment by mariodivece** [comment]
Ok, thanks guys... I'll look more closely into this as this has in fact happened to me once or twice and I thought it was just FFmpeg acting up. @jnschulze This gives me a good starting point where to look at.

**Comment by jnschulze** [comment]
@mariodivece 
Using a `ReaderWriterLockSlim` to guard the VideoBlockBuffer's PictureBuffer fixes this, but there might be better ways to fix this. I'd move the actual CopyMemory call to a new `Copy(IBitmapDataBuffer target)` method of VideoBlockBuffer to avoid the need of publicly exposing the lock.

**Comment by mariodivece** [comment]
could you guys test again and let me know if my latest commit fixes the issue?

**Comment by jfquarto** [comment]
Started my app at 10:24 this morning and it is still running fine; the exception didn’t occur so far.
I will let it continue to run this weekend and report back Monday.


Met vriendelijke groet,
​
Johan Fontijne
Software developer
 
 
Quarto B.V.
Westbaan 200
Moordrecht
2841 MC
Nederland
Tel: +31 182 700 500
Email: johan.fontijne@quarto.nl
Web: www.quarto.nl
De disclaimer van toepassing op e mail van Quarto Betaalsystemen vindt u op https://www.quarto.nl/disclaimer-quarto
Van: Mario Di Vece <notifications@github.com>
Verzonden: Thursday, 7 June 2018 20:23
Aan: unosquare/ffmediaelement <ffmediaelement@noreply.github.com>
CC: Johan Fontijne <johan.fontijne@quarto.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [unosquare/ffmediaelement] Copying Memory Fails: AccessViolationException (#243)


could you guys test again and let me know if my latest commit fixes the issue?

**Comment by jfquarto** [comment]
My application (playing a list of videos continuously) has been running for more than two days now without any errors, so I guess the problem has been solved. Thanx!

**Comment by mariodivece** [comment]
Thanks for the feedback. Closing now.
