### ISSUE TITLE
How to correctly dispose off ffmediaelement?

### ISSUE THREAD

**Issue by rexn8r** [unosquare/ffmediaelement#245]
I are trying to implement a video player in wpf using ffmediaelement. The media element is hosted on a user control and media files are played in a sequence. Once the current playlist is finished playing, the user control is disposed off and new user control is loaded with another playlist with another set of video files.

During the switch over from one user control to another, following code is executed in the user control Unload event;

video.Stop();
video.Close();
//video.Source = null;          this is not allowed if Close method is called
video.Dispose();

In the task manager memory section, one can see a memory of 30 mb left over between the swich over and ultimately the memory keep on increasing.

can someone point me to correct code to completely dispose off ffmedia element to free up the memory?

Thanks
Rex

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
You need to provide a samplea pplication to repro the issue.

**Comment by rexn8r** [comment]
hi mario, thanks for you response. i am trying out the element in digital signage player software. i will build a sample to repro in a day or two and get back to you.

Thanks
Raxit

**Comment by mariodivece** [comment]
Have you tried Dispose() directly? Without Stop or Close?

**Comment by rexn8r** [comment]
Hi MarioYes I did try that. Interestingly if I don't pass source value to the element and just load/unload the user control with just video.dispose method then there was no memory spike. As soon as I played videos, it started memeory leak.ThanksOn Jun 11, 2018 9:15 AM, Mario Di Vece <notifications@github.com> wrote:Have you tried Dispose() directly? Without Stop or Close?

**Comment by mariodivece** [comment]
ok, I'll wait for the sample application

**Comment by mariodivece** [comment]
any updates here?

**Comment by rexn8r** [comment]
Hi MarioI am bit stuck with work at the moment. So I guess you can close the issue at the moment. When I get a chance I will build the sample and re open the issue.ThanksRexOn Jun 18, 2018 10:20 AM, Mario Di Vece <notifications@github.com> wrote:any updates here?

**Comment by mariodivece** [comment]
ok.. let me know.  Thanks.
