### ISSUE TITLE
# MediaSource file path. Does not open files with special characters

### ISSUE THREAD

**Issue by AndreyGrishin** [unosquare/ffmediaelement#247]
# MediaSource file path. Does not open files with special characters

*Please enter a general description for the issue. Delete sections that are not relevant and provide additional sections if necessary.*

## Issue Categories

 - [x] Bug

## Version Information

 - [x] NuGet Package *4.0.260*

## Steps to Reproduce
For example
 1. Use a source file with a name that contains special characters like Video•♣.avi
 2. MediaPlayerOnMediaFailed => Could not open '@\Video•♣.avi'. Error -2: No such file or directory

## Expected Results

 - The file will open correctly

![2018-06-19_14-55-05](https://user-images.githubusercontent.com/12128096/41595812-cb2c875c-73d0-11e8-9284-4f4ee658e2ff.png)

**Comment by mariodivece** [comment]
See issues #99 and #235 Closing.
