### ISSUE TITLE
Implement Recording Capabilities

### ISSUE THREAD

**Issue by ramtinak** [unosquare/ffmediaelement#248]
Hi, first of all thank you for your hard work.
I have an question, Is there anyway to record live streaming? 
I created an app which can streaming all FIFA 2018 wordcup, I want to know is there any option that I will record these games?

Thanks

**Comment by mariodivece** [comment]
There are no recording capabilities, but I have added this as a future enhancement.

**Comment by rcarrico** [comment]
Yes this would be a great enhancement, I'm looking to display and record from multiple webcams.

**Comment by mariodivece** [comment]
in v2.70, I have added a starting point for this where frames are spit out in a callback and can be fed to an encoder. This is just the start obviously. It need a lot more work to fully implement.

**Comment by mariodivece** [comment]
Good starting point here:
https://github.com/FFmpeg/FFmpeg/blob/master/fftools/ffmpeg.c
`static int init_output_stream_streamcopy(OutputStream *ost)`

**Comment by mariodivece** [comment]
another good example of remuxing
https://github.com/FFmpeg/FFmpeg/blob/a0ac49e38ee1d1011c394d7be67d0f08b2281526/doc/examples/remuxing.c

**Comment by mariodivece** [comment]
This is now completed. Check out the TransportStreamRecorder class example implementation. Closing issue.
