### ISSUE TITLE
Pause() not working

### ISSUE THREAD

**Issue by ramtinak** [unosquare/ffmediaelement#249]
Hi, maybe I'm wrong but I used Pause() to pause streaming, but my video still playing!

I test Stop function and it will pause my video:| why is that?
here is my test link:

```http://63.237.48.28/ios/PMC/PMC.m3u8```

**Comment by mariodivece** [comment]
youir test link returns 403 forbidden. Did you check the CanPause Property? Calling Stop on a non-seekable source pauses the playback and seeks to the start of the stream but since the stream is not seekable, you only see it paused. Makes sense?
