### ISSUE TITLE
UI hang (task deadlock?) when quickly changing Source

### ISSUE THREAD

**Issue by mgpreston** [unosquare/ffmediaelement#252]
# UI hang (task deadlock?) when quickly changing Source

Hi, thanks for the great project!

I'm currently running into an issue when rapidly changing the Source property that seems to cause the UI to hang. If I pause the debugger when the hang occurs, VS shows four tasks, three of them in the Awaiting state, and the fourth is Scheduled. They are awaiting each other in the order shown in the attached screenshot:

![tasks](https://user-images.githubusercontent.com/32184718/42382176-c4a28a74-8133-11e8-8e11-3a594d68cdc3.png)

Is my usage of Source correct, or should I be waiting for the MediaElement's state to change to a particular value, before setting it again?

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package 4.0.260
 - [ ] Build From *Master* branch, Commit 
 - [ ] Build from *Branch Name*, Commit 

## Steps to Reproduce

 1. Add a MediaElement to a WPF Window.
 2. Add a button to the window and change the MediaElement's Source to a video file.
 3. Rapidly press the button, or hold the Enter key.

## Expected Results

 - The video will freeze and the UI will hang.
 
### XAML
```xml
<Window x:Class="FFMediaElement_Test.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <DockPanel>
        <Button DockPanel.Dock="Top" Click="Button_Click">Test</Button>
        <ffme:MediaElement x:Name="Media" Background="Gray" LoadedBehavior="Play" UnloadedBehavior="Manual" />
    </DockPanel>
</Window>
```

### C#
```csharp
private void Button_Click(object sender, RoutedEventArgs e) {
	this.Media.Source = new Uri("VideoPathHere");
}
```

**Comment by mariodivece** [comment]
This will be resolved. Please stand by.

**Comment by mariodivece** [comment]
This should be fixed with the new CommandManager implementation. Please reopen if the issue persists after the 270 Nuget Package release.

**Comment by RyanYANG52** [comment]
Same problem, wait for new release

**Comment by srollinet** [comment]
I also have the same problem.

It occurs for example when I try to open a bad stream (the url doesn't exist) and quickly try to open another stream, before the first operation times out.

On a first thread:
```
 Dispatcher.Invoke(async () =>
{
    MediaElement.Source = badStreamUrl;
    await MediaElement.Play();
}
```

on a second thread, a few seconds later
```
 Dispatcher.Invoke(async () =>
{
    await MediaElement.Close();
    MediaElement.Source = streamUrl;
    await MediaElement.Play(); //Hangs here
}
```

![image](https://user-images.githubusercontent.com/12350967/46581800-b946ad00-ca3e-11e8-9718-121bd14bd0fb.png)

**Comment by srollinet** [comment]
Here is an example that simulates the behavior:

````
        public MainWindow()
        {
            InitializeComponent();

            Media.MediaInitializing += (sender, args) =>
            {
                args.Configuration.ReadTimeout = TimeSpan.FromSeconds(5);
            };

            Task.Run( () =>
            {
                Dispatcher.Invoke(async () =>
                {
                    // The url does not exist
                    Media.Source = new Uri("rtsp://184.72.239.150/vod/mp4:BigBuckBunny_115k.mov");
                    await Media.Play();
                });
            });

            Task.Run( () =>
            {
                Dispatcher.Invoke(async () =>
                {
                    await Task.Delay(TimeSpan.FromSeconds(3));

                    await Media.Stop();
                    Media.Source = new Uri("rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov");
                    await Media.Play();
                });
            });
        }
```

**Comment by srollinet** [comment]
> Your sample code is not intended usage.
So maybe you can help me find the correct approach.

In the real application, I have a view model with an URI and it is updated from the outside.
It can change quickly and can be null in case we want to stop the stream. My goal is to display the new stream as soon as the URL changes.

I first tried to simply use a Databinding this way

        <ffme:MediaElement Name="MediaElement" 
                           LoadedBehavior="Play"
                           UnloadedBehavior="Stop"
                           Source="{Binding CameraUrl}"/>

But as soon as CameraUrl becomes null, I cannot re-assign a new stream. It seems that the value is written locally by the control and thus, the binding is lost.

**Comment by mariodivece** [comment]
yeah... selecting an invalid or non responsive stream makes it impossible to assign a new source quickly -- it needs to time out before anything else can happen. Let me try to find a way around this.

**Comment by mariodivece** [comment]
This will be implemented as Support Close() while media IsOpening (abort reads)

**Comment by mariodivece** [comment]
There is initial progress here. Still need further testing but with the latest commit you are now able to call Close while media is currently opening.

**Comment by mariodivece** [comment]
Source property has now been downgraded to a read-only notification property.
Please call the asynchronous methods Open and Close as follows
```csharp
await media.Open(newUri("path here"));
await media.Close();
```
