### ISSUE TITLE
The player does not revert to it's original position when being resized.

### ISSUE THREAD

**Issue by julesx** [unosquare/ffmediaelement#253]
## Issue Categories

 - [ X ] Bug

## Version Information

 - [ X ] NuGet Package *FFME.Windows 4.0.260*

## Expected Results

When expanding upwards, the player stretches properly.
When shrinking back down, the player moves to the right.  I would expect it to return to its original position.  You'll also notice that the green background extends past the playing video, consuming blank space that is no longer available to be used. 
 
### XAML
```xml
<MainWindow>

    <Grid>

        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition Height="5" />
            <RowDefinition />
        </Grid.RowDefinitions>

        <GridSplitter Grid.Row="1" Height="5" HorizontalAlignment="Stretch" />

        <ffme:MediaElement Grid.Row="2" HorizontalAlignment="Left" Background="Green" Source="moviePath" LoadedBehavior="Play" />
        
    </Grid>

</MainWindow>
```

**Comment by Elchzone** [comment]
I'm experiencing the same behavior when I use the following PanAndZoom module:
https://github.com/wieslawsoltes/PanAndZoom

Zooming into the Player works fine, but when coming back to regular it doesn't correctly scale and position itself.

**Comment by mariodivece** [comment]
yes, I am aware of this issue. I will review.

**Comment by mariodivece** [comment]
I belive this is just an artifact of your layout not specifying any columns. The behavior you see is by design as there is no set width, the control performs an initial layout. When it resizes it uses available space without any width specified -- regardless of the direction of the resize. You'll need to change your layout to something where the width is predictable just like with any other control. Something like this will work. If you still see a problem please reopen/add a new comment. This will work with the current master branch (I will be releasing version 2.70 soon):

```xml
<Window x:Class="Unosquare.FFME.Playground.Resizing.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Unosquare.FFME.Playground.Resizing"
        xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>

        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition Height="5" />
            <RowDefinition />
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="50*" />
            <ColumnDefinition Width="50*" />
        </Grid.ColumnDefinitions>

        <GridSplitter Grid.Row="1" Height="5" HorizontalAlignment="Stretch" Grid.ColumnSpan="2" Background="DeepPink" />

        <ffme:MediaElement Grid.Column="0" Grid.Row="2" HorizontalAlignment="Stretch"
                           Background="Green" Source="pathtovideo"
                           LoadedBehavior="Play" />
    </Grid>
</Window>

```
