### ISSUE TITLE
Could not open Rtsp Stream - Invalid data found when processing input

### ISSUE THREAD

**Issue by mbullock976** [unosquare/ffmediaelement#255]
# Issue Title (Could not open Rtsp Stream - Invalid data found when processing input)

I'm currently suffering with playing back a rtsp stream from my rtsp server using the ffmediaelement.

Unosquare.FFME.Shared.MediaContainerException: 'Could not open 'rtsp://{stream name omitted here}. Error -1094995529: Invalid data found when processing input'

This seems to happen on the DESCRIBE request because the handler for the DESCRIBE verb can be quite time consuming.
Is there anyway we could have a timeout I can configure to keep the connection alive on the client side please?

Thank you

## Issue Categories

 - [ ] Bug
 - [  ] Feature Request
 - [X ] Question
 - [ ] Not sure

## Version Information

 - [X] NuGet Package *4.0.260*

**Comment by mariodivece** [comment]
Closing. Please reopen when you have more feedback.
