### ISSUE TITLE
NUGET package does not expose ChangeMedia method

### ISSUE THREAD

**Issue by midium** [unosquare/ffmediaelement#257]
# NUGET package does not expose ChangeMedia method

Using latest NUGET package (4.0.260) it is not available the ChangeMedia method as long as some other things like the MediaOpening event.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [x] Not sure

## Version Information

 - [x] NuGet Package *4.0.260*

## Steps to Reproduce

 1. Start a new project
 2. Include FFME.Windows package
 3. Try to use the ChangeMedia from the MediaElement (it is not listed)

## Expected Results

 - The method is available

**Comment by mariodivece** [comment]
You'll need to wait for realease 4.0.270 which has much better performance a a ton of issues addressed. Thanks for your patience.
