### ISSUE TITLE
How to preload many Video/Audio files in FFME?

### ISSUE THREAD

**Issue by Plurdis** [unosquare/ffmediaelement#258]
# How to preload many Video/Audio files in FFME?

Hi, thank for this library!

I want to preload many Video/Audio files in FFME and play with no loading.
I checked FFME's methods. But, I can't find about that feature.

If that feature is exists, how i can access that feature?
If that feature is not supporting. can you develop this feature please?

thank you.

## Issue Categories

 - [ ] Bug
 - [x] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *4.0.260*

**Comment by mariodivece** [comment]
You'll need to implement your own `IMediaInputStream` and call the `Open` method with your own instance. You can check out the examples by searching:
https://github.com/unosquare/ffmediaelement/search?q=IMediaInputStream&unscoped_q=IMediaInputStream
