### ISSUE TITLE
MediaElement and Sample's CPU, Memory usage is different.

### ISSUE THREAD

**Issue by Plurdis** [unosquare/ffmediaelement#259]
# MediaElement and Sample's CPU, Memory usage is different.

today i was play some video file in my project using ffme.
cpu usage was over **60%.**

Of course, this file may be high quality video.

So, I get ffmeplay.win.exe from this repository and play same file again.

Result

![image](https://user-images.githubusercontent.com/23194065/43678856-a44a30ea-9855-11e8-973b-e07d3e2b275f.png)
in my project

![image](https://user-images.githubusercontent.com/23194065/43678875-db02b3b4-9855-11e8-90dc-f4a1bad950a0.png)
in ffmeplay.win.exe

------

I think my code is problem, so i create new project and add only ffme and play again. but result is same.

------

![image](https://user-images.githubusercontent.com/23194065/43678906-c405c2e0-9856-11e8-8bc3-c6dd54e4ba0d.png)

in new project for testing

------

Memory usage is also higher than ffmeplay.win.exe

why this happen?

In sample project contain more optimization code?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *4.0.260*

**Comment by mariodivece** [comment]
Thank you for reporting this. I belive it is because of the separated visual tree of the video renderer in non-debug mode. I'll take a look.

**Comment by mariodivece** [comment]
I have performed numerous optimizations to the code in the current repository. I will be releasing the new control very soon (version 2.70). I am closing this issue for now. But you can play around with the static property  ` MediaElement.EnableWpfMultiThreadedVideo = false;` and see if it helps with the current nuget. Again, the new codebase is much more optimized in both, memory usage and CPU usage. Please post new results AFTER the release of version 2.70.
