### ISSUE TITLE
Setting Volume Property gets ignored

### ISSUE THREAD

**Issue by mmeissner** [unosquare/ffmediaelement#261]
# Setting Volume Property gets ignored
If no media element with audio is loaded setting the Volume Property gets ignored.

## Issue Categories
 - [ x] Bug

## Version Information
 - [ x] Build From *Master* branch

## Steps to Reproduce
Set Volume before you load any media

## Expected Results
Value gets not ignored and if an Media has audio it gets played with the volume previously set

```c#
private static object OnVolumePropertyChanging(DependencyObject d, object value)
{
.....
if (element.HasAudio == false) return Constants.Controller.DefaultVolume;
....
}
 ```
## Question
Commenting out of the above line provided the wanted result, however I'm not sure if there are any side effects to be expected. From my limited point of view this condition makes little sense at that particular place in the code. Does I'm right or did I overseen something ?

**Comment by mariodivece** [comment]
you're right. Let me see how I can change this. This also applies to the Balance property I believe.

**Comment by mariodivece** [comment]
This should be fixed in the latest commit. IsMuted, Volume and Balance are kept across changes in media sources.
