### ISSUE TITLE
Feature Request: Reload Method

### ISSUE THREAD

**Issue by Elchzone** [unosquare/ffmediaelement#266]
A method that stops playing and reinitializes the player with the current settings. Main Idea is to reload the loaded video input in case something went wrong. This is especially useful for live streams.

## Issue Categories

 - [ X] Feature Request

## Steps to Reproduce

1. Create FFME object
2. Prepare Player with parameters
3. Load source
4. source crashes/ends/stops/whatever
5. Player.Reload()
6. Player initializes again and plays 
6a. either from beginning
6b. from last position (not sure on 6a/6b)

**Comment by mariodivece** [comment]
Seems like something very specific to your scenario. What have you tried on your own?

**Comment by mariodivece** [comment]
Since there was no further feedback and this is something that is too specific of a use case I am closing this issue. Feel free to provide further feedback.
