### ISSUE TITLE
Player freezes after few minutes using windows 10 embedded

### ISSUE THREAD

**Issue by tspierre** [unosquare/ffmediaelement#267]
# Player freezes after few minutes using windows 10 embedded  

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [x] Not sure

## Version Information

 - [x] NuGet Package v4.0.260

## Steps to Reproduce

 1. Create FFME object 
 2. Load source
 3. when media has ended or failed we call next video by load new source

### C#
_mediaElement = new FFMEMediaElement {LoadedBehavior = MediaState.Play};
_mediaElement.MediaEnded += OnMediaEnded;
NextMedia();

private void OnMediaEnded(object sender, RoutedEventArgs e)
{
         NextMedia();
 }

private void NextMedia()
{
_mediaElement.Source = new Uri(video);
}

**Comment by mariodivece** [comment]
Have you tried awaiting for the new `Open` method in the latest master branch as opposed to setting the `Source` property? I am closing this issue as the commands have changed significantly. Please feel free to provide further feedback and I'll reopen if necessary.
