### ISSUE TITLE
Increase Client Timeout

### ISSUE THREAD

**Issue by mbullock976** [unosquare/ffmediaelement#268]
Hi, Sometimes our live rtp/rtsp stream can take a while to be created. 
As a result the ffmediaelement player is timing out after about 8 secs because it cannot open the rtsp stream.

Is it possible for the ffmediaElement player connection to our rtsp server can be kept alive i.e
Is there a timeout configuration I can apply to the player where it will wait much longer please?

Thanks

 - [X] Question

## Version Information

 - NuGet Package *4.0.260*

## Steps to Reproduce

 1. Create FFMediaElement instance
 2. Set source to be rtsp stream address
 3. Set LoadingBehaviour to play

## Expected Results

- FFMediaElement instance to wait for the stream by increasing timeout through configuration
 
### XAML
```xml
<MainWindow>
<ffme:MediaElement Grid.Row="0" x:Name="Media2" Background="Black" LoadedBehavior="Play"  UnloadedBehavior="Manual" Margin="2"/>
</MainWindow>
```

### C#
`public MainWindow()
        {
            InitializeComponent();

            Unosquare.FFME.MediaElement.FFmpegDirectory = Path.Combine(Environment.CurrentDirectory, "ffmpeg");            
            
        }             

        private void Player1_Play_Click(object sender, RoutedEventArgs e)
        {
            if (!string.IsNullOrEmpty(PlayerOneUrlTextBox.Text))
            {                             
                Media1.Source = new Uri(PlayerOneUrlTextBox.Text);
            }
        }
```

**Comment by mariodivece** [comment]
Have you tried:
```csharp
        private void OnMediaInitializing(object sender, MediaInitializingEventArgs e)
        {
            e.Configuration.ReadTimeout = TimeSpan.FromSeconds(45);
            ...
```

Check out the e.Configuration options in the sample app please!

**Comment by mariodivece** [comment]
Looks like there is no further feedback. I'm closing. Feel free to add comments and feedback and I'll reopen.
