### ISSUE TITLE
Video content alignment not working 

### ISSUE THREAD

**Issue by tuomaslaa** [unosquare/ffmediaelement#269]
When showing 720p landscape video with stretching in (almost) square mediaelement then the horizontal content alignment is not working. Screen actually always starts from the left side of the video.

### C#
```
VideoPreview2.Stretch = Stretch.UniformToFill;
VideoPreview2.StretchDirection = StretchDirection.Both;
VideoPreview2.HorizontalAlignment = HorizontalAlignment.Right;
VideoPreview2.HorizontalContentAlignment = HorizontalAlignment.Right;
```

This might be duplicate to this closed issue but this is still not solved on this repo.
https://github.com/unosquare/ffmediaelement/issues/7

**Comment by mariodivece** [comment]
I believe this is finally fixed! Could you please give the latest commit a shot and let me know if it's working properly? Closing for now but if there is more feedback I will reopen.
