### ISSUE TITLE
Play live video, stop after one frame.

### ISSUE THREAD

**Issue by madgeckdotnet** [unosquare/ffmediaelement#271]
# Play live video, stop after one frame.

## Issue Categories

 - [ ] Not sure

## Version Information

 - [x] NuGet Package 4.0.260

## Steps to Reproduce

1. Publish a tcp video stream user ffmpeg.exe
```cli
ffmpeg -f dshow -i video=“screen-capture-recorder” -vcodec libx264 -preset:v ultrafast -tune:v zerolatency -f flv tcp://127.0.0.1:6666/live
```

2. Play video user ffplay. and it worked.
```cli
ffplay -x 640 -y 480 -fflags nobuffer tcp://127.0.0.1:6666/live?listen
```

3. But when i use sample-player(Unosquare.FFME.Windows.Sample) play this video,after frist frame,player station will changed to stop.and this tcp connection still working.

**Comment by mariodivece** [comment]
This should be fixed in the current master branch. I will verify.

**Comment by mariodivece** [comment]
The problem was that the Play command was checking for the duration of the media. In this case it was Zero! I have fixed the issue. Please test with the latest commit and provide feedback. I will reopen if the issue persists.

**Comment by Ezorrio** [comment]
Workaround for current version is to play live video onMediaOpened()
```
public static async void OnMediaOpened(object sender, RoutedEventArgs e)
        {
            await ((MediaElement) sender).Play();
        }
```
