### ISSUE TITLE
Run sample project fail

### ISSUE THREAD

**Issue by hengway1989** [unosquare/ffmediaelement#276]
Sorry that I am a newbie to visual studio. I try to run project by follow instruction at readme, but look like not successful, can anyone please help advice, thank you

Below is the screen shot of my error:

<img width="1679" alt="screen shot 2018-09-11 at 7 29 46 pm" src="https://user-images.githubusercontent.com/13148479/45360315-602f5900-b5f9-11e8-902b-9b0eaeb65fd4.png">

**Comment by mariodivece** [comment]
Sorry... this seems to be more related to Visual Studio itself. The issues reported here have to be specifically related to FFME.
