### ISSUE TITLE
After Call PositionNext Over 9 Times,PositionPrevious Seek Wrong

### ISSUE THREAD

**Issue by quickmoney** [unosquare/ffmediaelement#278]
After Call PositionNext Over 9 Times,PositionPrevious Seek Wrong

## Issue Categories

 - [ ] Bug

## Version Information

 - [ ] NuGet Package 4.0.270
 - [ ] Build From *Master* branch, Commit *157d5bb*

## Steps to Reproduce

i test load a video with 720p, frame rate is 30, first seek position to any frame ,when i fast press key right to call "PositionNext",then "PositionPrevious" is not seek properly after several times。if fast press times less than 9 times，PositionPrevious seek seems right。
 
### C#
```csharp
 protected override bool ProcessCmdKey(ref System.Windows.Forms.Message Msg, System.Windows.Forms.Keys keyData)
        {
            int WM_KEYDOWN = 256;
            int WM_SYSKEYDOWN = 260;

            if (Msg.Msg == WM_KEYDOWN | Msg.Msg == WM_SYSKEYDOWN)
            {
                switch (keyData)
                {
                    case Keys.Left:
                        if (Media.IsPlaying) Pause();
                        Media.Position = Media.PositionPrevious;
                        break;
                    case Keys.Right:
                        if (Media.IsPlaying) Pause();
                        Media.Position = Media.PositionNext;
                        break;
                    case Keys.Up:
                        Media.SpeedRatio += 0.05;
                        break;
                    case Keys.Down:
                        Media.SpeedRatio -= 0.05;
                        break;
                }
            }
            return false;
        }
```

**Comment by mariodivece** [comment]
Yes I was made aware of these inconsistencies. These are going away in the upcoming version please don't use them anymore and check out the entire discussion of issue #277 and use the new API for frame-by-frame seeking when the new version arrives or build yourself from current master branch source. If you want to test it out, feedback is always appreciated!
