### ISSUE TITLE
Interop: Using WPF MediaElement in an audio only oriented program

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#28]
Hi Mario,
Thank you for having enabled more flexible ffmpeg binaries deployment model!
But is it possible to have a finer level of granularity regarding the DLLs to be loaded? For my audio-only oriented project, I would like to not having to deploy/load/initialize the avdevice-57.dll, avfilter-6.dll, postproc-54.dll and swscale-4.dll that I don't use.
Thanks.

**Comment by mariodivece** [comment]
Thanks for the suggestion. I will look into this. It will be difficult to selectively load parts of FFmpeg but I will look into this.

**Comment by CyberSinh** [comment]
Thanks!
You will find below optimized (at least in size) x86 ffmpeg VS 2017 build, compiled with only audio related features:
https://github.com/CyberSinh/Luminescence.Audio/tree/master/lib/ffmpeg/lib

Here is the DLL size:
- avcodec-57.dll -> 1.38 MB
- avformat-57.dll -> 565 KB
- avutil-55.dll -> 538 KB
- swresample-2.dll -> 182 KB

**Comment by mariodivece** [comment]
Could you try it now and let me know if this is what you were expecting?

**Comment by CyberSinh** [comment]
Thank you very much for your excellent work.

I think it needs to come back to the developer to clarify his intention explicitly, for example by adding an “audio only” parameter to the RegisterFFmpeg method (which may be “false” by default), without presuming it from the presence or not of some DLLs on disk:

1.	If the developer chooses to use FFME in “audio only” mode:
  a.	The avdevice-57.dll, avfilter-6.dll, postproc-54.dll and swscale-4.dll DLLs should not be loaded even though they are present on the disk (the developer should be able to use the “full features” VS “audio only”, without affecting the deployment of DLLs)
  b.	An exception should be raised if the developer makes the error of calling a method that only makes sense in the context of a video (InvalidOperationException?)
  c.	Another control lighter than the MediaElement should be able to be used, descending directly from DependencyObject and not from UserControl (which itself descends from Visual, UIElement, FrameworkElement, Control, ContentControl) because no visual control is needed
  d.	Parsing a video should be possible but only the soundtrack should be played back. In the current implementation, I get a DllNotFoundException in the VideoComponent class

2.	If the developer chooses to use FFME in “full features” mode:
  a.	An exception should be thrown if any required DLL to use all of the FFME features was missing

**Comment by CyberSinh** [comment]
Hi Mario,
Do you know when this feature request would be implemented?
Thanks.

**Comment by mariodivece** [comment]
I have higher priority items at this point. But I would encourage you to provide me with a pull request so I see your implementation ideas or even apply the code directly. What do you think?

**Comment by CyberSinh** [comment]
I would like to be able to help but I am not sufficiently familiar with the architecture of ffmediaelement and ffmpeg to propose you a code of quality in a reasonable time.

**Comment by mariodivece** [comment]
That's ok. Let me just finish with hardware decoding implementation (which I'm sure you will agree has much higher priority) and I will move on to this one.

**Comment by CyberSinh** [comment]
Ok. Thank you very much.

**Comment by CyberSinh** [comment]
Hi Mario,
Can you give us any news regarding the progress of ffmediaelement v2?
Thanks.

**Comment by mariodivece** [comment]
@tpetrina is working on refactoring the code so it can be made cross-platform! Please chack out the details here: https://github.com/unosquare/ffmediaelement/pull/113

**Comment by mariodivece** [comment]
With my latest commit this has been resolved. Hope I was able to help on time. Please test and reopen if you run into any issues. Thanks!
```csharp
            // You can pick which FFmpeg binaries are loaded. See issue #28
            // Full Features is already the default.
            Unosquare.FFME.MediaElement.FFmpegLoadModeFlags = FFmpegLoadMode.FullFeatures;
```
