### ISSUE TITLE
Seekable RTMP network video Cannot fire MediaEnded Event When the Play Ends

### ISSUE THREAD

**Issue by quickmoney** [unosquare/ffmediaelement#282]
Seekable RTMP network video Cannot fire MediaEnded Event When the Play Ends

## Issue Categories

 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *4.0.270*
 - [ ] Build From *Master* branch, Commit *4173c8a*

## Steps to Reproduce

i load a network video by rtmp protocol,just like video on demand ,the video is seekable,can call seek command,when the video played over,i want to replay, there seems 2 ways to do it,use "Source" property or call "Open"，i want to use "Position" property to seek to video starttime in "MediaEnded" event,local video can fire "MediaEnded" Event,i am not sure if it's normal,aslo RTMP video cannot use "position" property to seek after playing ends,forgive my poor english, thank you for your great contribution for ffme project.

**Comment by mariodivece** [comment]
Let me see what I can do here... Maybe I am not firing the event when the stream is a network stream. Let me see what I can do here.

**Comment by mariodivece** [comment]
Will test with the following streams:
rtmp://184.72.239.149/vod/mp4:bigbuckbunny_1500.mp4
rtmp://184.72.239.149/vod/mp4:bigbuckbunny_1100.mp4
rtmp://184.72.239.149/vod/mp4:bigbuckbunny_750.mp4
rtmp://184.72.239.149/vod/mp4:bigbuckbunny_450.mp4

**Comment by mariodivece** [comment]
I have tested with these streams and everything works fine as long as the internal stream does not reach it's state of EOS. Once it reaches it seems like the FFmpeg implementation prevents moving anywhere else within the stream. There is nothing I can do to change this. In fact, try it out in ffplay (FFmpegs play tool) and the same thing happens. Sorry man -- won't fix unless the internal container implementation of FFmpeg gets fixed.
