### ISSUE TITLE
Seek while playing cause buffering 100%

### ISSUE THREAD

**Issue by RyanYANG52** [unosquare/ffmediaelement#283]
# *Seek while playing cause buffering 100%*

*I am testing with the new release, found some video would stop playing after seek, and buffering progress became 100%. I am not sure the reason, maybe audio decoder, same operation will succeed in Commit [f62b31b](https://github.com/unosquare/ffmediaelement/commit/f62b31bfb515cb5724957da168c429d42091c6a2)*

## Issue Categories

 -  Bug

## Version Information

 -  NuGet Package *2.70*

## Steps to Reproduce

 1. Step 1
[mockVideos.zip](https://github.com/unosquare/ffmediaelement/files/2418276/mockVideos.zip)
Download the sample video.
 2. Step 2
add 
```
 var timer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(1) };
 timer.Tick += async (s, e) => await Current.MediaElement.Seek(TimeSpan.FromSeconds(1));
 timer.Start();
``` 
in here OpenCommand https://github.com/unosquare/ffmediaelement/blob/4173c8a83a69c4edd980df597c59078477af6bbb/Unosquare.FFME.Windows.Sample/App.Commands.cs#L64
 3. Step 3
Open *mock.mkv*

## Expected Results

 - After couple seconds, video would stop playing, and program will wait forever in here
https://github.com/unosquare/ffmediaelement/blob/c81830c0b5e9ced1be175a623e551323b05f1e47/Unosquare.FFME.Windows/Rendering/Wave/DirectSoundPlayer.cs#L304
 - Same operation with *mockNoAudio.mkv*, it works fine.

**Comment by mariodivece** [comment]
This has been fixed for the current master branch. Thanks again for reporting!
