### ISSUE TITLE
Opening HLS flow is slower than before.

### ISSUE THREAD

**Issue by cust1105** [unosquare/ffmediaelement#284]
Hi, I'd like to say thank you for your hard work. I have an question。I found that opening the HLS stream was a few seconds slower than the previous version. 

## Issue Categories
 - [ *] Question

## Version Information
This problem appears in  4.0.260.0

## Steps to Reproduce

 1. Step 1
 2. Step 2
 3. Step 3

## Expected Results

 -The efficiency of opening is similar to that of 3.4.240.
 
## Sample Code

```

**Comment by mariodivece** [comment]
Could you post the log messages you are getting. I suspect this is because the new release performs something called sync-buffering which ensures the buffers are full with 1 second worth of data. Please post the log entries!

**Comment by cust1105** [comment]
The log:
  Debug - CloseCommand: Entered
     Debug - CloseCommand: Completed
     Debug - OpenCommand: Entered
      Info - FFInterop.Initialize: FFmpeg v4.0.1
   Warning - Iavformat_open_input_star: '2018/9/27 19:51:46'
   Warning - avformat_open_input_close: '2018/9/27 19:51:47'
     Debug - COMP AUDIO: Start Offset:      1.467; Duration:   1240.880
     Debug - COMP VIDEO: Start Offset:      1.560; Duration:   1240.880
     Debug - SYNC-BUFFER: Started.
   Warning - [swscaler @ 1537E680] Warning: data is not aligned! This can lead to a speed loss
     Debug - SYNC-BUFFER: Finished. Clock set to      0.093
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to      0.173
     Debug - OpenCommand: Completed
   Warning - SYNC AUDIO: LATENCY: 140.1215 ms. | SKIP (samples being rendered too late)
   Warning - [mpegts @ 0C12F740] PES packet size mismatch
   Warning - [mpegts @ 0C12F740] PES packet size mismatch
   Warning - [mpegts @ 0C12F740] PES packet size mismatch

Dear: mario divece 
This function“avformat_open_input” will take at least 1 seconds to open and close.

**Comment by mariodivece** [comment]
There are many improvements to this coming in a new worker model and sync-buffering logic. I will be posting updates soon so you can try it out.

**Comment by cust1105** [comment]
Thank you very much for your interest in this issue. I tested the latest ffmediaelement and found that the opening speed improved a lot. This is a very good improvement.

**Comment by mariodivece** [comment]
there's even more coming. I am getting local RTSP streams to open in about 1 second. I will merge the better-rendering branch hopefully in a couple of days. Will keep this open to get your feedback on opening speed.

**Comment by cust1105** [comment]
This is a big surprise. I will continue to pay attention to this issue.

**Comment by mariodivece** [comment]
Could you test it out using the latest master commit? It should be good now. Furthermore, if you want to render video and audio frames as they come, just handle the `MediaOpening` event and do `e.Options.IsTimeSyncDisabled = true;` so that video and audio run on independent playback clocks and are rendered as they come in. Looking forward to your comments!

**Comment by mariodivece** [comment]
Using the latest `master` commit, could you please test by handling the `MediaOpening` event and adjusting the following `Options` to your needs? Please let me know the results. If there are no further comments before the end of this week, I will package and publish the new NuGet and consider this issue closed.

```csharp
	// You can render audio and video as it becomes available but the downside of disabling time
	// synchronization is that video and audio will run on their own independent clocks.
	// Do not disable Time Sync for streams that need synchronized audio and video.
	e.Options.IsTimeSyncDisabled =
		e.Info.Format == "libndi_newtek" ||
		e.Info.InputUrl.StartsWith("rtsp://uno");

	// You can disable the requirement of buffering packets by setting the playback
	// buffer percent to 0. Values of less than 0.5 for live or network streams are not recommended.
	e.Options.MinimumPlaybackBufferPercent = e.Info.Format == "libndi_newtek" ? 0 : 0.5;

	// The audio renderer will try to keep the audio hardware synchronized
	// to the playback position by default.
	// A few WMV files I have tested don't have continuous enough audio packets to support
	// perfect synchronization between audio and video so we simply disable it.
	// Also if time synchronization is disabled, the recommendation is to also disable audio synchronization.
	Media.RendererOptions.AudioDisableSync =
		e.Options.IsTimeSyncDisabled ||
		e.Info.InputUrl.EndsWith(".wmv");
```

**Comment by mariodivece** [comment]
Closing issue! New NuGet coming today! Please create a new issue if you wish to provide further feedback.
