### ISSUE TITLE
Cannot build when added from Nuget in a new WPF project

### ISSUE THREAD

**Issue by srollinet** [unosquare/ffmediaelement#286]
# Cannot build when added from Nuget in a new WPF project

I try to use the library in a new WPF project created from VS 2018 V.15.8.6 but it systematically fails with the error `The tag 'MediaElement' does not exist in XML namespace 'clr-namespace:Unosquare.FFME;assembly=ffme.win'. Line 11 Position 10.	`

I tried on Win10 with .Net Framework 4.7.2 then 4.6.1 but the result is the same.

Am I missing something?

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [x] Not sure

## Version Information

 - [x] NuGet Package 4.0.270

## Steps to Reproduce

 1. Create a new WPF project in VS 2018
 2. Add FFME.Windows package
 3. Add an element `<ffme:MediaElement />` in the main window -> as expected VS propose to add the namespace, so add it
 4. Build -> the build fails with error  `The tag 'MediaElement' does not exist in XML namespace 'clr-namespace:Unosquare.FFME;assembly=ffme.win'. Line 11 Position 10.	`

## Expected Results

 - The project can be build
 
### XAML
```xml
<Window x:Class="FfmeTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <ffme:MediaElement />
    </Grid>
</Window>
```

**Comment by srollinet** [comment]
I found the problem.

In the csproj, the package was configured by default this way:

```xml
    <PackageReference Include="FFME.Windows">
      <Version>4.0.270</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```

I changed it to

```xml
    <PackageReference Include="FFME.Windows">
      <Version>4.0.270</Version>
    </PackageReference>
```

and now the build is ok

**Comment by PhilJenson** [comment]
Had the same problem after updating to latest release. This solved it for me. Many thanks for posting the solution

**Comment by mariodivece** [comment]
Is there something I need to do??

**Comment by CyberSinh** [comment]
It seems that PackageReference doesn't support well developmentDependency tag:
https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference

Removing `<developmentDependency>true</developmentDependency>` from ffme.win.nuspec file should solve the issue.

Hope this help.

**Comment by mariodivece** [comment]
I have removed the tag from the nuspec. The next release should not present this issue anymore. Thanks for reporting!

**Comment by LeiYangGH** [comment]
my .net 8 wpf project has
`  <ItemGroup>
    <PackageReference Include="FFME.Windows" Version="4.4.350" />
  </ItemGroup>`

and same error:

> The tag 'MediaElement' does not exist in XML namespace 'clr
-namespace:Unosquare.FFME.Controls;assembly=FFME.Windows'
