### ISSUE TITLE
Cant find ffmpeg binaries when WPF App is param "Preferred 32 bits" is unchecked

### ISSUE THREAD

**Issue by LouisCPro** [unosquare/ffmediaelement#288]
# FFME and WPF 64 bit App problem

In my WPF App settings, if I uncheck the "Preferred 32 bits" build param (when Active Project Settings are "Any CPU", at runtime Unosquare.FFME.MediaElement.LoadFFmpeg() throw an IOFileNotFOundException.

## Issue Categories

 - [X] Bug

## Version Information

 - [X] NuGet Package 4.0.270
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Create a WPF App to target 64 bit plaforms and add a FFME MedialElement
 2. Initiate Unosquare sequence
 3. Launch the App

## Expected Results

 - Be compliant with 64 bits target
 
### C#

Unosquare.FFME.MediaElement.FFmpegDirectory = _FFMPEGDirectory;
Unosquare.FFME.MediaElement.EnableWpfMultiThreadedVideo = false;
Unosquare.FFME.MediaElement.LoadFFmpeg(); <= Throw Exception here

**Comment by mariodivece** [comment]
Are you sure you are trying to load 64 bit ffmpeg binaries?

**Comment by LouisCPro** [comment]
Yes, I check like this :

            if(Environment.Is64BitProcess)
                Unosquare.FFME.MediaElement.FFmpegDirectory = _FFMPEGDirectory64;
            else
                Unosquare.FFME.MediaElement.FFmpegDirectory = _FFMPEGDirectory32;

Issue is the same ! Unable to find in 64 bit version…. No problem in 32 bits

**Comment by mariodivece** [comment]
I think you might be missing the instructions on the README. I tried to reproduce but your problem is that you either have the wrong version of the binaries, the wrong architecture or the wrong package (you need the Shared pasckage). Closing.
