### ISSUE TITLE
Issue while loading local subtitles

### ISSUE THREAD

**Issue by bbougot** [unosquare/ffmediaelement#289]
Using ffmedialement 2.70 release, it seems loading subtitles through e.Options.SubtitlesUrl does not work anymore. I use several .srt files and method is called, but no subtitle is displayed.

## Issue Categories

 - [ x] Bug

## Version Information

 - [ x] NuGet Package 2.70

## Steps to Reproduce

 1. Edit Unosquare.FFME.Windows.Sample, in MainWindow.MediaEvents.cs edit line 121 to update mediaFilePath with a value pointing to a local srt file.
 2. Build and Run
 3. Play a media
 4. No subtitle

## Expected Results

 - Subtitle should be displayed

**Comment by mariodivece** [comment]
Let me look into this. It looks like this only happens with local files

**Comment by mariodivece** [comment]
I have tested with local SRT files and it works just fine... Did you try with the latest version of the master branch. There was a commit related to SRT timestamps here:
https://github.com/unosquare/ffmediaelement/commit/6c72b9b891145d035ab4b6a0dd36b9d335a3d772
Maybe that fixed the issue? Could you give it a hot and let me know if it works?

**Comment by bbougot** [comment]
Yes I've just checked it and it worked too... I don't remember the exact use case at that time of writing the issue but never mind, I will keep you updated if I catch it again.

However, I still have issues while trying to change an already setup subtitle. If I change the affectation of e.Options.SubtitlesUrl to an other file while playing, the change is not reflected.

**Comment by mariodivece** [comment]
yeah, for the options object to apply changes you need to call the `ChangeMedia()` method. This is by design. Could you give it a shot and let me know if it works fine?

**Comment by bbougot** [comment]
Basically I just do:

    // vm is my ViewModel which handle events
    vm.SubtitleChanged += OnSubtitleChanged;
    // Media is the name of the ffmedialement instance
    Media.MediaChanging += OnMediaChanging;

    private async void OnSubtitleChanged(object sender, Events.SubtitleChangedEventArgs e)
    {
        await Media.ChangeMedia();
    }

    private void OnMediaChanging(object sender, MediaOpeningEventArgs e)
    {
        DispatcherHelper.CheckBeginInvokeOnUI(() =>
        {
            try
            {
                var url = new Uri(vm.CurrentSubtitle.FilePath);
                if (url.IsFile || url.IsUnc)
                {
                    if (System.IO.File.Exists(vm.CurrentSubtitle.FilePath))
                        e.Options.SubtitlesUrl = vm.CurrentSubtitle.FilePath;
                }
            }
            catch (Exception ex)
            {
                Logger.Error(ex);
            }
        });
    }

The flow is: 
* CurrentSubtitle is changed in the view model
* OnSubtitleChanged is triggered
*  await Media.ChangeMedia(); is called
* OnMediaChanging is called and the affectation e.Options.SubtitlesUrl = vm.CurrentSubtitle.FilePath; is executed with the right FilePath of the new subtitle.

The flow is working (my debugger stepped through), but the new subtitle is not applied, it does not change. I've teste with release 2.70

**Comment by mariodivece** [comment]
I have tested your report and it now seems to be fixed in my latest commit. Will you please check it out and let me know if it's working well now? Thanks!

**Comment by bbougot** [comment]
Working great! Thank you very much, your lib is awesome.
