### ISSUE TITLE
Does ffme support Unicode file names?

### ISSUE THREAD

**Issue by 9cvele3** [unosquare/ffmediaelement#290]
**Unicode support in ffme**

I am able to use you sample appliaction (Unosquare.FFME.Windows.Sample) to play video files with "normal" (ASCII) file names. But when I try to play a valid file that contains non ASCII characters in it's file path, I get MediaElement Error (screenshot attached). 

Is there Unicode support in ffme? 

![ffme fails](https://user-images.githubusercontent.com/20195455/47094183-ff63f380-d22a-11e8-8a62-1b553762eb1f.png)
## Issue Categories

 - [ ] Not sure

## Version Information

 - NuGet Package *FFME.Windows.4.0.270*
 - Build From *Master* branch, Commit *3c3733c *

**Comment by mariodivece** [comment]
This is a duplicate issue.
See: https://github.com/unosquare/ffmediaelement/issues/99#issuecomment-338000095
and related issues #99, #235 , #247, #115
