### ISSUE TITLE
GetPixelFormat bug

### ISSUE THREAD

**Issue by zgabi** [unosquare/ffmediaelement#291]
# Issue Title GetPixelFormat bug

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [X] Not sure

## Version Information

Current latest code (commit 3c3733c) on master branch. 

## Steps to Reproduce

https://github.com/unosquare/ffmediaelement/blob/91322f26e231d0770cbf3e0380042069cc55d4e3/Unosquare.FFME.Common/Decoding/HardwareAccelerator.cs#L132-L153

I haven't tried to change or build the code, but it looks like that you are iterating through the pixelFormats, and comparing it always with the first value.

I think it should be:
`if (*p == PixelFormat)`

I haven't tested it.

**Comment by zgabi** [comment]
I checked it now. It is also iterating, and it is using the "p" in the loop.

```
    for (p = pix_fmts; *p != AV_PIX_FMT_NONE; p++) {
        const AVPixFmtDescriptor *desc = av_pix_fmt_desc_get(*p);

```

**Comment by mariodivece** [comment]
This has been updated in the latest commit! Thanks!
