### ISSUE TITLE
 Protocol not found with ffmpeg-4.0.2-win64-shared

### ISSUE THREAD

**Issue by shinyrabbit** [unosquare/ffmediaelement#292]
# Issue Title (*change this title!*)

* I create a wpf application on x64 , I use ffmpeg-4.0.2-win32-shared，It show unable load folder.Then 
replace with  ffmpeg-4.0.2-win64-shared , it show error with Protocol not found with.

## Issue Categories

 - [ ] Feature Request
 - [ ] Question

## Version Information

 - [ ] NuGet Package *4.0.2*

**Comment by mariodivece** [comment]
Which potocol was not found? Could you post the full URI you are trying to open please?

**Comment by shinyrabbit** [comment]
I use rstp with ffmpeg-4.0.2-win64-shared. but i change it to x86 ,it is fine.

**Comment by mariodivece** [comment]
I tested with both x64 and x86 and RTSP is working fine on both. Just make sure your application and the FFmpeg binaries match on architecture. Closing now.
