### ISSUE TITLE
IP camera stream

### ISSUE THREAD

**Issue by B0nisek** [unosquare/ffmediaelement#294]
IP Camera stream via RTSP

Hi,

I'd like to have stream into media element WPF. The problem is when I try to add it as URL to your sample, it does not authenticate. Is there some workaround? 

Best regards,
Boni

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
What is the full ffplay.exe command line that works as expected?

**Comment by Tam66662** [comment]
I'm interested in knowing how to authenticate an RTSP stream as well.

**Comment by mariodivece** [comment]
If the full `ffplay` command line arguments that work are not provided, it is impossible for me to provide any advice on how to make it work with `ffme`. Feel free to comment and reopen this issue.
