### ISSUE TITLE
HLS Time-Shift

### ISSUE THREAD

**Issue by semiem** [unosquare/ffmediaelement#295]
# Issue Title (*HLS Time-Shift*)

*The WPF player does not support playing past .ts files (Time Shifting) on hls (.m3u8) live stream (manifest does not have #EXT-X-ENDLIST Tag!)*

## Issue Categories

 - [x] Bug
 - [x] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *Last Version*
 - [ ] Build From *Master* branch, Commit *3c3733c*
 - [ ] Build from *Branch Name*, Commit *3c3733c*

## Expected Results

 - Sample 1 ( Native HLS Playback, Chrome Extension)
![image](https://user-images.githubusercontent.com/19623552/48346584-e0714980-e690-11e8-9aaa-d4353f2c92d7.png)

### .m3u8 Sample File Content:
```batch
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:14
#EXT-X-KEY:METHOD=AES-128,URI="stream-3278466270.key",IV=0x000000000000000000000000C3696CDE
#EXTINF:5.240,
stream-3281594670.ts
#EXTINF:5.440,
stream-3282066270.ts
#EXTINF:5.160,
stream-3282555870.ts
#EXTINF:6.000,
stream-3283020270.ts
```

**Comment by semiem** [comment]
And Player does not support to open .m3u8 offline files on disk!!!
We got this error message:
Message = "Could not open 'C:\\test.m3u8'. Error -1094995529: Invalid data found when processing input"
But we put this file on server, and called by http address, that's work and played movie well!

**Comment by mariodivece** [comment]
Please provide *THE FULL COMMAND-LINE ARGUMENTS* for a working ffplay.exe command that works. This control is *NOT* based on a Google Chrome extension.

**Comment by mariodivece** [comment]
Since there has not been any comments on this one I am closing it. Feel free to add comments and reopen the issue.
