### ISSUE TITLE
Change Video And Audio Streams (Like Quality Bitrate) Dynamically

### ISSUE THREAD

**Issue by semiem** [unosquare/ffmediaelement#296]
# Issue Title (*Change Video Stream Quality Bitrate Dynamically*)

*How can i change audio or video between Stream? Its now selected automaticly by connection quality.
its beter to have option to select between avalaible stream medias(audio and video)

## Issue Categories

 - [ ] Bug
 - [x] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *Last Version*
 - [ ] Build From *Master* branch, Commit *3c3733c*
 - [ ] Build from *Branch Name*, Commit *3c3733c*

## Expected Results
- Like This Dialog
 
![image](https://user-images.githubusercontent.com/19623552/48397812-3945ee00-e734-11e8-937c-2791ae99fb03.png)

### C#
```csharp
Media.MediaInfo.Streams.Value.Metadata["variant_bitrate"]
```

**Comment by mariodivece** [comment]
Do it on your own with  the ChangeMedia method. Outside the scope of this control.

**Comment by semiem** [comment]
Can you give me a sample to select a certain media from available video or audio in .m3u8 list?
