### ISSUE TITLE
Getting video codec and resolution without loading the video file

### ISSUE THREAD

**Issue by patricioafernandes** [unosquare/ffmediaelement#297]
# Issue Title (*Getting video codec, width and height without loading the video file*)

We would like to have video codec and resolution without loading the video file. 
On the existing example the metadata is presented when the video is playing. We would like to have access to the video codec, width and height before playing the video, i.e., without loading the video for validation purposes.
Is it possible? How can we do it?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ X] Question
 - [ ] Not sure

## Version Information

 - [ X] NuGet Package *4.0.270*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Step 1
 2. Step 2
 3. Step 3

## Expected Results

 - Result 1
 - Result 2
 
### XAML
```xml
<MainWindow>
</MainWindow>
```

### C#
```csharp
System.Console.WriteLine("Change Me Please!");
```

### Command line ffplay
```batch
ffplay "hello.mp4"
```
## Delete This Section
- Please consider a donation here: https://www.paypal.me/mariodivece/50usd 
- I work on this project for fun and on my free time.
- Provide as much information as possible and any sample files

**Comment by mariodivece** [comment]
This is a playback control. Use the ffmpeg api yourself to do this. Example ffprobe.C
