### ISSUE TITLE
MediaElement stop playing video when opening in a new Window from second time onwards

### ISSUE THREAD

**Issue by vandralca** [unosquare/ffmediaelement#298]
# MediaElement stop playing video when opening in a new Window from second time onwards

I'm developing an application where the video player is not the main functionality, but a secondary feature.  I mean that the player is opened in a secondary Window each time the user needs to preview the video; this auxiliary Window container is instantiated each time the user wants to play his video, but the MediaElement instance is reused (it is instantiated just once at the beginning, and not disposed until the main application is closed).  I need to explain that the MediaElement is embedded inside a UserControl called Player.xaml, with all the functionality of a player (play, stop and pause buttons, volume, etc); and this UserControl is what is opened inside the Window; and this UserControl is instantiated just once (as well the MediaElement).

When the first playing-Window is opened, everything works and MediaElement plays the video fine, but when I close the auxiliary window and open it again (remember, new window, same MediaElement and  Player.xaml), the player does not work: behavior is: audio is listening, but video not.  Also, the "rendering video event" has stopped raising. 

## Issue Categories

 - Bug
 - Not sure

## Version Information

 - NuGet Package *4.0.270*

## Steps to Reproduce

 1. Create main application.
 2. Instance MediaElement, and add handler for 'rendering video event'.
 3. Create and Open new Window with Content a singleton UserControl that contains in a Grid this MediaElement.  (This UserControl has buttons for playing, stopping, etc).  Play your video.
 4. Close window.
 5. Open new Window and add the same instance of singleton UserControl (that has the same instance of MediaElement).
 6. Try to play your video.

## Expected Results

 - The second time, MediaElement would play in the same way than first.  In fact, this second time audio is listening fine, but video not.
 - The 'video rendering' event must continue raising this second time when playing video.
 
### C#
```csharp
//Instantiation (occurs once) (MainWindow.xaml.cs)
ctrlFFME = new MediaElement();
ctrlFFME.Name = "ffmePlayer_1";
ctrlFFME.LoadedBehavior = System.Windows.Controls.MediaState.Play;
ctrlFFME.RenderingVideo -= OnMediaRenderingVideo;
ctrlFFME.RenderingVideo += OnMediaRenderingVideo;

//Opening the auxiliary window (occurs everytime) (MainWindow.xaml.cs)
//
//myPlayer is an instance trated like a singleton, of type Player.xaml, that is a UserControl, and that has a grid called "gridPlayer", where the instance of the MediaElement is placed.
Window window = new Window()
{
    Content = myPlayer
};
window.Show();


//Adding to grid (occurs once) (Player.xaml.cs)
//
//CtrlPlayer is an instance of MediaElement
gridPlayer.Children.Add(CtrlPlayer);
```

**Comment by mariodivece** [comment]
I can't reporduce your issue. it looks like a misuse of WPF on your side. HEre's my test code. Feel free to submit a project where I can repro the issue.

```csharp
namespace FFme.Playground
{
    using System;
    using System.Windows;
    using System.Windows.Controls;

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            Unosquare.FFME.MediaElement.FFmpegDirectory = @"c:\ffmpeg";
            SampleUrl = @"C:\Users\UnoSp\OneDrive\ffme-testsuite\video-issue-251.mpg";

            InitializeComponent();

            LayoutGrid = new Grid();
            LayoutGrid.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });
            LayoutGrid.RowDefinitions.Add(new RowDefinition { Height = new GridLength(40, GridUnitType.Pixel) });

            var buttonsPanel = new StackPanel { Orientation = Orientation.Horizontal };
            var openButton = new Button { Content = "Open and Play" };
            var changeButton = new Button { Content = "Change Window" };
            buttonsPanel.Children.Add(openButton);
            buttonsPanel.Children.Add(changeButton);

            Grid.SetRow(buttonsPanel, 1);
            LayoutGrid.Children.Add(buttonsPanel);
            Content = LayoutGrid;

            openButton.Click += OnOpenClicked;
            changeButton.Click += OnChangeClicked;

            Media = new Unosquare.FFME.MediaElement
            {
                LoadedBehavior = MediaState.Play
            };

            Media.RenderingVideo += OnRenderingVideo;
            Media.MessageLogged += OnMessageLogged;
            ChangeMediaHost(LayoutGrid);
        }

        private string SampleUrl { get; set; }

        private Grid LayoutGrid { get; set; }

        private Unosquare.FFME.MediaElement Media { get; set; }

        private Grid CurrentMediaHost { get; set; }

        private void OnMessageLogged(object sender, Unosquare.FFME.Events.MediaLogMessageEventArgs e)
        {
            if (e.MessageType == Unosquare.FFME.Shared.MediaLogMessageType.Trace)
                return;

            Console.WriteLine($"{e.MessageType} | {e.Message}");
        }

        private void OnRenderingVideo(object sender, Unosquare.FFME.Events.RenderingVideoEventArgs e)
        {
            // Console.WriteLine("Rednered Video");
        }

        private void OnOpenClicked(object sender, RoutedEventArgs e) => Media.Source = new Uri(SampleUrl);

        private void OnChangeClicked(object sender, RoutedEventArgs e)
        {
            if (CurrentMediaHost != LayoutGrid)
                return;

            var window = new Window();
            var windowContent = new Grid();
            window.Content = windowContent;
            window.Closed += (s, ev) => ChangeMediaHost(LayoutGrid);

            ChangeMediaHost(windowContent);
            window.Show();
        }

        private void ChangeMediaHost(Grid newMediaHost)
        {
            CurrentMediaHost?.Children?.Remove(Media);
            CurrentMediaHost = newMediaHost;
            CurrentMediaHost?.Children?.Add(Media);
        }
    }
}

```

**Comment by babbanxhobeni** [comment]
I got a similar issue, that might be related.

Resolved it by setting:
MediaElement.EnableWpfMultiThreadedVideo = GuiContext.Current.IsInDebugMode == true;

When IsInDebugMode == false (Or if I don't have the debugger attached) I found that every-time the User-control with the MediaElement in was set to hidden and back to visible again the issue occurred.

I added some logging and found that the VideoRenderer.Render() method got called more and more. So initially when it works it only gets called one, but then after the user-control being hidden and visible again it gets called +1;

**Comment by babbanxhobeni** [comment]
I got a similar issue, that might be related.

Resolved it by setting:
MediaElement.EnableWpfMultiThreadedVideo = false;

When MediaElement.EnableWpfMultiThreadedVideo = true; I found that every-time the User-control with the MediaElement in was set to hidden and back to visible again the issue occurred.

I added some logging and found that the VideoRenderer.Render() method got called more and more. So initially when it works it only gets called one, but then after the user-control being hidden and visible again it gets called +1;

**Comment by mariodivece** [comment]
`EnableWpfMultiThreadedVideo ` is an experimental feature. Only use when you are completely familiar with the source code of FFME and understand the implications. Please avoid using this experimental and unsupported feature. Since there was no further feedback and a lot has changed since the issue was reported, I am closing this issue. Feel free to report a new issue referencing this one if further feedback can be provided.
