### ISSUE TITLE
GoPro Hero Streaming problem

### ISSUE THREAD

**Issue by AwesomeSharp** [unosquare/ffmediaelement#299]
Hello, I am using the solution described above for broadcasting a GoPro camera.
Once every 10 seconds, you must send an HTTP request to the camera to update the stream.
http://10.5.5.9/gp/gpControl/execute?p1=gpStream&c1=restart

I use the command for FFMPEG:
ffplay -an -fflags nobuffer -f: v mpegts -probesize 8192 rtp: //10.5.5.9: 8554
the image is going great.

but when I use your WPF application for an example, after sending the HTTP request, the video stops. in the title there is a switch between Play and Manual.

what do you say?

P.S. i check issues #152  
P.S.S Sorry for my English.

**Comment by AwesomeSharp** [comment]
I also found out about the error by subscribing to the MediaFiled event:
Fatal error initializing MediaContainer instance. Could not open 'udp://@10.5.5.9:8554/'. Error -5: I/O error

**Comment by mariodivece** [comment]
I can't really troubleshoot the problem as I don't own that hardware... Have you tried the ForcedInputFormat option?

```csharp
private void OnMediaInitializing(object sender, MediaInitializingEventArgs e)
{
    e.Configuration.ForcedInputFormat = "mpegts";
}
```
and then disable audio:

```csharp
private void OnMediaOpening(object sender, MediaOpeningEventArgs e)
{
    e.Options.AudioStream = null;
}
```

**Comment by mariodivece** [comment]
There is new timing logic in the latest master commit. Could you test it out and let me know if it works for you? you can also handle the `MediaOpening` event and do `e.Options.IsTimeSyncDisabled = true;` so that video and audio run on independent playback clocks and are rendered as they come in.

**Comment by mariodivece** [comment]
you could also add `e.Options.DropLateFrames = true` to render frames as quickly as they become available.

**Comment by mariodivece** [comment]
Using the latest `master` commit, could you please test by handling the `MediaOpening` event and adjusting the following `Options` to your needs? Please let me know the results. If there are no further comments before the end of this week, I will package and publish the new NuGet and consider this issue closed.

```csharp
	// You can render audio and video as it becomes available but the downside of disabling time
	// synchronization is that video and audio will run on their own independent clocks.
	// Do not disable Time Sync for streams that need synchronized audio and video.
	e.Options.IsTimeSyncDisabled =
		e.Info.Format == "libndi_newtek" ||
		e.Info.InputUrl.StartsWith("rtsp://uno");

	// You can disable the requirement of buffering packets by setting the playback
	// buffer percent to 0. Values of less than 0.5 for live or network streams are not recommended.
	e.Options.MinimumPlaybackBufferPercent = e.Info.Format == "libndi_newtek" ? 0 : 0.5;

	// The audio renderer will try to keep the audio hardware synchronized
	// to the playback position by default.
	// A few WMV files I have tested don't have continuous enough audio packets to support
	// perfect synchronization between audio and video so we simply disable it.
	// Also if time synchronization is disabled, the recommendation is to also disable audio synchronization.
	Media.RendererOptions.AudioDisableSync =
		e.Options.IsTimeSyncDisabled ||
		e.Info.InputUrl.EndsWith(".wmv");
```

**Comment by mariodivece** [comment]
Closing issue! New NuGet coming today! Please create a new issue if you wish to provide further feedback.
