### ISSUE TITLE
Its not playing at regular speed.

### ISSUE THREAD

**Issue by spoiledtechie** [unosquare/ffmediaelement#3]
I open up a new video after building.  First when I load a file larger than 10 minutes, its not currently playing or working.

Second, when I do find a video it plays, it plays at 1/10 speed.  I don't see the speed, but the video and frames don't update fast enough to where It even seems like it plays at regular speed.

Have you seen this before?

**Comment by mariodivece** [comment]
No... What happens when you play the same file with ffplay.exe? What is the output of ffprobe?

**Comment by spoiledtechie** [comment]
It might be due to different codecs, but for all the videos I have tried playing through it slow down or > 10 mins don't play at all.

I haven't tried playing it with ffplay nor completed a ffprobe on the file.

I can't seem to find ffplay on Google.  Can you point me to it so I can have a try?

**Comment by mariodivece** [comment]
ffplay and ffprobe are included in Zeranoe's ffmpeg builds... try downloading a statically linked build of FFmpeg here: https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-3.0.1-win32-static.7z and run the above command with the included executables. I have played HD video that is over 2 hours long without issues.

**Comment by mariodivece** [comment]
any comments or sample files you might want to provide so I can test?

**Comment by mariodivece** [comment]
Closing as I received no further comments.

**Comment by superware** [comment]
I can confirm that behavior happens to me as well, network playback plays good, file playback (tried several file formats/codecs etc) seems like x10 slower and very jittery. ffplay plays good.

ffprobe version 3.0.1 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3
 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --ena
ble-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --e
nable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-
libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame
--enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --ena
ble-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-
libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-lib
vo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libw
ebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable
-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'VID_20160421_170016.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-04-21 14:03:05
  Duration: 00:02:47.21, start: 0.000000, bitrate: 12241 kb/s
    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080, 12133 kb/s, SAR 1:1 DAR 16:9, 30.33 fps, 30 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2016-04-21 14:03:05
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2016-04-21 14:03:05
      handler_name    : SoundHandle

**Comment by superware** [comment]
Hi @mariodivece, can you please reopen? :)
