### ISSUE TITLE
How to capture(screenshot) at mediaelement pause state

### ISSUE THREAD

**Issue by jonadan95** [unosquare/ffmediaelement#300]
# how to capture(screenshot) at mediaelement pause state

Hi,

I'd like to have stream into media element WPF. 
API document describe screen shot in RenderingVideo event handler,  but it's useful only play state(rendering).  How can I capture(screenshot) media element pause state, it does not allow?  Is there some workaround?

Best regards,
jonadan95

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [X] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
Hmmm... good point. You could travese the WPF tree manually, find a reference to a WriteableBitmap used and get its data, but there currently is no API for it. A good feature to be added.

**Comment by jonadan95** [comment]
I find that the writeablebitmap(- probable TargetBitmap) is not in the mediaelement but in the video renderer and I don't know how to access the video renderer. Is there some workaround access videorenderer in mediaelement?

**Comment by longlongago-k** [comment]
I'd like to correspond between car dashboard camera video + GPS log.
GPS log includes time information.
Is there any better solution to capture video thumbnail at each GPS log time?
Currently I use following code and it works at Pause state, but it should wait for finishing render video frame.  This is maybe slow.
```C#
      await MediaElementMovie.Seek(TimeSpan.FromMilliseconds(gps_time)); //seek and wait for rendering
      //thumbnail size
      width = 320;
      height = 180;
      var bitmap = new RenderTargetBitmap( width, height, 96, 96, PixelFormats.Pbgra32);
      var vb = new VisualBrush(MediaElement1);
      DrawingVisual dv = new DrawingVisual();
      using (DrawingContext dc = dv.RenderOpen())
      {
        dc.DrawRectangle(vb, null, new Rect(new Size(width, height)));
      }
      bitmap.Render(dv);
```

**Comment by mariodivece** [comment]
in the latest commit you can now use the `MediaElement.CaptureBitmapAsync` call.
Example Usage:
```csharp
                    var bmp = await Media.CaptureBitmapAsync();
                    var pos = Media.FramePosition;
                    var positionString = $"{(int)pos.TotalHours:00}-{pos.Minutes:00}-{pos.Seconds:00}";
                    var screenshotPath = Path.Combine(
                        Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),
                        $"screenshot {positionString}.png");

                    bmp?.Save(screenshotPath, ImageFormat.Png);
```
