### ISSUE TITLE
FFmpeg error code -138 on an http url, but I don't know what this means.

### ISSUE THREAD

**Issue by Tam66662** [unosquare/ffmediaelement#301]
# FFmpeg error code -138 on an http url, but I don't know what it means.

*I'm trying to understand what this error code -138 means from ffmpeg.  I am able to play the following url directly in a web browser, as well as using the WPF MediaElement, but it is unable to play using FFME:

"http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"

Please take a look at the small sample project that I attached.  It is giving me a MediaFailed event with the error message:

Could not open 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'. Error -138: Error number -138 occurred
*

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [X] Not sure

## Version Information

 - [X] NuGet Package 4.0.270
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Under the "imports" directory of the attachment, download and extract ffmpeg-4.1-win64-shared into the location specified in the "ffmpeg-4.1-win64-shared.txt" file
 2. Build the project as Debug x64 (restore the missing FFME packages)
 3. Run the app.  You will see that after about 5 seconds, MediaFailed event will fire and display the following error message: Could not open 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'. Error -138: Error number -138 occurred

## Expected Results

 - I expected the FFME MediaElement control to play the http URL mp4 file.  The URL works if I copy/paste it directly into Chrome browser.  I've also tested the URL using standard WPF MediaElement and it is able to play the mp4 file.
 
## Sample Code
See attached sln/project (VS 2017, .NET 4.6.1) called "FfmeTestApp.zip"

### XAML
```xml
<Window x:Class="FfmeTestApp.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800" WindowState="Maximized">
    <Grid>
        <ffme:MediaElement x:Name="mediaElement" LoadedBehavior="Manual" Source="{Binding MediaUrl}"/>
        <TextBlock x:Name="textBlock" HorizontalAlignment="Center" VerticalAlignment="Center" FontSize="64" TextWrapping="Wrap">
            <TextBlock.Style>
                <Style TargetType="TextBlock">
                    <Style.Triggers>
                        <Trigger Property="Text" Value="{x:Null}">
                            <Setter Property="Visibility" Value="Collapsed"/>
                        </Trigger>
                    </Style.Triggers>
                </Style>
            </TextBlock.Style>
        </TextBlock>
    </Grid>
</Window>
```

### C#
```csharp
using System;
using System.ComponentModel;
using System.Windows;

namespace FfmeTestApp
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window, INotifyPropertyChanged
    {
        private Uri mediaUrl;

        public MainWindow()
        {
            InitializeComponent();

            this.MediaUrl = new Uri("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4");
            this.DataContext = this;
            this.Loaded += OnLoaded;
            this.mediaElement.MediaFailed += OnMediaFailed;
            Unosquare.FFME.MediaElement.FFmpegDirectory = @".\ffmpeg-4.1-win64-shared\bin\";
        }

        public Uri MediaUrl { get { return this.mediaUrl; } set { this.mediaUrl = value; this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(MediaUrl))); } }

        public event PropertyChangedEventHandler PropertyChanged;

        private void OnLoaded(object sender, RoutedEventArgs e)
        {
            this.mediaElement.Play();
        }

        private void OnMediaFailed(object sender, ExceptionRoutedEventArgs e)
        {
            textBlock.Text = e.ErrorException.Message;
        }
    }
}
```

### Command line ffplay
```
PS C:\FfmeTestApp\imports\ffmpeg\ffmpeg-4.1-win64-shared\bin> .\ffplay.exe "http://commondatast
orage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
ffplay version 4.1 Copyright (c) 2003-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[tcp @ 0000020e13b8d540] Connection to tcp://commondatastorage.googleapis.com:80 failed: Error number -138 occurred
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4: Unknown error

PS C:\FfmeTestApp\imports\ffmpeg\ffmpeg-4.1-win64-shared\bin>
```
[FfmeTestApp.zip](https://github.com/unosquare/ffmediaelement/files/2626217/FfmeTestApp.zip)
![ffme_error](https://user-images.githubusercontent.com/12551526/49175013-77c6d580-f2fc-11e8-9533-d08308e3f2f3.png)

**Comment by Tam66662** [comment]
Wow, I am super blind!  Looking again at the command line execution of ffplay, I can see the error was due to TCP error.

[tcp @ 0000020e13b8d540] Connection to tcp://commondatastorage.googleapis.com:80 failed: Error number -138 occurred
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4: Unknown error

This tells me that the issue is because my workplace firewall is preventing ffmpeg from using that port.  However, my browser (as well as the standard WPF MediaElement) is able to use that port, which is why it worked.

**Comment by songtaoshi** [comment]
Hi, thanks for your analysis, How to open the firewall to the ffmpeg to use the port?

**Comment by Tam66662** [comment]
@songtaoshi If you have administrative access to your machine, then you would need to open your Windows Defender Firewall and read up on how to open a port to ffmpeg on the port that you wish to open.  Otherwise, you need to talk to your network admins at your workplace to open the port for ffmpeg in order for it to work.  Alternatively, move to a network that may not have any firewall initially set up, such as your home.

**Comment by zhr147147** [comment]
Hi, did you solve the question? I meet the similar question.
[tcp @ 0000019af656b700] Connection to tcp://r2---sn-gxuo03g-3c2e.googlevideo.com:443 failed: Error number -138 occurred

I try to close the firewall and open port 443. But the error is still there. 

Looking forward to your reply.

**Comment by TheFairyTale** [comment]
> Hi, did you solve the question? I meet the similar question. [tcp @ 0000019af656b700] Connection to tcp://r2---sn-gxuo03g-3c2e.googlevideo.com:443 failed: Error number -138 occurred
> 
> I try to close the firewall and open port 443. But the error is still there.
> 
> Looking forward to your reply.

I also have this error.

**Comment by ChoOo7** [comment]
Hello
I also have this error sometime
My input is azure blob storage (https request), and le code is running on an azure function
I can handle it using retry logic but, it's not nice :(

**Comment by fireattack** [comment]
> Connection to tcp://asset.domand.nicovideo.jp:443 failed: Error number -138 occurred

It looks like you cannot connect to this domain.

Are you visiting niconico with proxies? Please notice that current download method we have (using ffmpeg) does not support proxy.
