### ISSUE TITLE
Further reducing latency

### ISSUE THREAD

**Issue by berant89** [unosquare/ffmediaelement#303]
Further reducing latency

Hello, 

Trying to capture a real time udp stream and, with the current settings there's about a half second delay. With a modified ffplay (code will be posted below), using the flags marked below, the latency is very low and, any actions performed appear instantaneous for example, using a joystick to look around.

Noticed in one of the Issues that it's mentioned there's by default a 0.5s delay, is there a way to change the default to a lower value? I also had a look through the source code though I'm inexperienced in regards to video playback so I'm not sure where to look if I wish to make modifications like what was done for ffplay.

Thank you

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package 4.0.270
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

N/A

## Expected Results

N/A
 
### XAML
```xml
<ffme:MediaElement
  x:Name="MediaTv"
  Background="BlueViolet"
  LoadedBehavior="Play"
  MediaInitializing="Media_OnMediaInitializing"
  Source="{Binding MediaTvAddress}"
  Stretch="Fill"
  Visibility="{Binding CameraTvVisibility}"/>
```

### C#
```csharp
        private void Media_OnMediaInitializing(object sender, MediaInitializingEventArgs e)
        {
            e.Configuration.GlobalOptions.FlagNoBuffer = true;
            e.Configuration.PrivateOptions["crf"] = "0";
            e.Configuration.PrivateOptions["flags"] = "low_delay";
        }
```

### C++
```cpp
//ffplay snippet
static void video_refresh(void *opaque, double *remaining_time)
{
  ...
retry:
        if (frame_queue_nb_remaining(&is->pictq) == 0) {
            // nothing to do, no picture to display in the queue
        } else {
            double last_duration, duration, delay;
            Frame *vp, *lastvp;

            /* dequeue the picture */
            lastvp = frame_queue_peek_last(&is->pictq);
            vp = frame_queue_peek(&is->pictq);

         //Added lines for modified ffplay
         if (frame_queue_nb_remaining(&is->pictq) > 1) {
             frame_queue_next(&is->pictq);
             goto retry;
          }


```

### Command line ffplay
```batch
ffplay -i udp://127.0.0.1:1234 -fflags nobuffer – flags low_delay
```

**Comment by mariodivece** [comment]
By default FFME waits for audio and video blocks to be in the same range so the playback has synchronized audio and video. In the latest master commit, I have added an option to disable this functionality and render the audio/video as soon as it comes in. Simply handle the 'OnMediaOpening' event and do the following: `e.Options.IsTimeSyncDisabled = true;` Could you test it out and let me know the results?

**Comment by mariodivece** [comment]
As of the latest master commit you can now handle the `MediaOpening` event and `e.Options.DropLateFrames = true;` -- please try it out and let me know if it produces the expected results.

**Comment by mariodivece** [comment]
Using the latest `master` commit, could you please test by handling the `MediaOpening` event and adjusting the following `Options` to your needs? Please let me know the results. If there are no further comments before the end of this week, I will package and publish the new NuGet and consider this issue closed.

```csharp
	// You can render audio and video as it becomes available but the downside of disabling time
	// synchronization is that video and audio will run on their own independent clocks.
	// Do not disable Time Sync for streams that need synchronized audio and video.
	e.Options.IsTimeSyncDisabled =
		e.Info.Format == "libndi_newtek" ||
		e.Info.InputUrl.StartsWith("rtsp://uno");

	// You can disable the requirement of buffering packets by setting the playback
	// buffer percent to 0. Values of less than 0.5 for live or network streams are not recommended.
	e.Options.MinimumPlaybackBufferPercent = e.Info.Format == "libndi_newtek" ? 0 : 0.5;

	// The audio renderer will try to keep the audio hardware synchronized
	// to the playback position by default.
	// A few WMV files I have tested don't have continuous enough audio packets to support
	// perfect synchronization between audio and video so we simply disable it.
	// Also if time synchronization is disabled, the recommendation is to also disable audio synchronization.
	Media.RendererOptions.AudioDisableSync =
		e.Options.IsTimeSyncDisabled ||
		e.Info.InputUrl.EndsWith(".wmv");
```

**Comment by mariodivece** [comment]
Closing issue! New NuGet coming today!
