### ISSUE TITLE
FFME MVVM

### ISSUE THREAD

**Issue by svcondor** [unosquare/ffmediaelement#304]
# FFME MVVM

I'm developing a Video player starting from your Unosquare.FFME.Windows.Sample

Did you use a particular framework or library for the MVVM in the project?  Can you point me at any tutorial or other info on your MVVM implementation?

## Issue Categories

 - [x] Question

**Comment by mariodivece** [comment]
Check out the sample project. My MVVM implementation is super simple. Just find the ViewModelBase file. Closing this as it is not related to the FFME project.
