### ISSUE TITLE
Select Audio Track

### ISSUE THREAD

**Issue by jadecordova** [unosquare/ffmediaelement#306]
Select Audio Track
I'm working with .MOV files containing 4 audio tracks. I need to be able to select any of them. Is it possible?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [X] 4.0.270
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Step 1
 2. Step 2
 3. Step 3

## Expected Results

 Instead of the default audio track, the user would be able to select one of the tracks available.
 
### XAML
```xml
<MainWindow>
</MainWindow>
```

### C#
```csharp
System.Console.WriteLine("Change Me Please!");
```

### Command line ffplay
```batch
ffplay "hello.mp4"
```
## Delete This Section
- Please consider a donation here: https://www.paypal.me/mariodivece/50usd 
- I work on this project for fun and on my free time.
- Provide as much information as possible and any sample files

**Comment by mariodivece** [comment]
please take a look at the sample project (FFME.Windows.Sample). It shows you how to select audio, video and subtitle tracks. Here is some code straight out of the sample:

```csharp
            // An example of specifically selecting an audio stream
            var audioStreams = e.Info.Streams.Where(kvp => kvp.Value.CodecType == AVMediaType.AVMEDIA_TYPE_AUDIO).Select(kvp => kvp.Value);
            var englishAudioStream = audioStreams.FirstOrDefault(s => s.Language != null && s.Language.ToLowerInvariant().StartsWith("en"));
            if (englishAudioStream != null)
            {
                e.Options.AudioStream = englishAudioStream;
            }
```

And changing it real-time:

```csharp
            // Cycle Through Audio Streams
            if (e.Key == Key.A)
            {
                StreamCycleMediaType = MediaType.Audio;
                await Media.ChangeMedia();
                return;
            }
```

Search for those in the sample project to see how they work.
