### ISSUE TITLE
Video Startup delay on low framerate with http mjpeg stream

### ISSUE THREAD

**Issue by ehemax** [unosquare/ffmediaelement#310]
# Video Startup delay on low framerate with http mjpeg stream

I'm trying to play a stream from a http source in mjpeg format. When the streams framerate is 15 or 30fps there are no problems and the video playback starts immediately. One of the streams I need to play has a framerate of 7.5fps and this one takes severall seconds (6-8s) to start playing.

When I connect to the stream with ffplay (cmd "ffplay http://localhost:xxxx/stream.mjpeg") all works correctly whitout delays in startup time.

I tried to set different settings in Media_OnMediaInitilizing event:
 - static framerate (Configuration.Privateoptions["framerate"]="7.5")
 - input format (Configuration.ForcedInputFormat = "mjpeg")
 - flags low_delay (Configuration.PrivateOptions["flags"] = "low_delay")
 - fflags nobuffer (Configuration.PrivateOptions["fflags"] = "nobuffer")
 
None helped. I set the options one at a time, all together and every possible combination.

Can you help me sorting this out?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [x] Build From *Master* branch, Commit *3c3733c*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

##FFPlay version
4.1 windows x64 shared from "https://ffmpeg.zeranoe.com/builds/"

## Steps to Reproduce

 1. Step 1
 2. Step 2
 3. Step 3

## Expected Results

 - Result 1
 - Result 2
 
### C#

using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Threading;

namespace AVMinimetro
{
    /// <summary>
    /// Logica di interazione per Vet.xaml
    /// </summary>
    public partial class VetFFMpeg : UserControl
    {
        #region Var
        Unosquare.FFME.MediaElement mePLayer = null;
        StreamSize ssSize = StreamSize.small;
        DispatcherTimer dt = new DispatcherTimer();
        #endregion

        #region Properties
        public StreamSize SetStreamSize
        {
            get { return ssSize; }
            set
            {
                if (ssSize != value)
                {
                    ssSize = value;
                    StartPlayer();
                }
            }
        }
        public string Title
        {
            get { return (string)lTitle.Content; }
            set { lTitle.Content = value; }
        }
        public bool CallIncoming
        {
            get { return rCallIncoming.Fill.Opacity == 0.0d; }
            set
            {
                if (value)
                    rCallIncoming.Fill.Opacity = 0.3d;
                else
                    rCallIncoming.Fill.Opacity = 0.0d;
            }
        }
        public bool IsPlaying
        {
            get => mePLayer.IsPlaying;
        }
        #endregion

        #region Methods
        public VetFFMpeg()
        {
            InitializeComponent();

            mePLayer = new Unosquare.FFME.MediaElement();
            mePLayer.LoadedBehavior = MediaState.Play;
            mePLayer.UnloadedBehavior = MediaState.Manual;

            mePLayer.HorizontalAlignment = HorizontalAlignment.Stretch;
            mePLayer.VerticalAlignment = VerticalAlignment.Stretch;
            mePLayer.Margin = new Thickness(5, 5, 5, 5);

            gGrid.Children.Add(mePLayer);
            Grid.SetColumn(mePLayer, 0);
            Grid.SetRow(mePLayer, 0);
            Grid.SetRowSpan(mePLayer, 3);
            Grid.SetZIndex(mePLayer, -1);
            
            dt.Interval = new TimeSpan(0, 0, 0, 5);
            dt.Tick += Dt_Tick;

            mePLayer.MediaEnded += Vlcc_MediaEnded;
            mePLayer.MediaFailed += Vlcc_MediaFailed;
            mePLayer.MediaInitializing += Vlcc_MediaInitializing;
            StartPlayer();
        }

        private void Vlcc_MediaInitializing(object sender, Unosquare.FFME.Events.MediaInitializingEventArgs e)
        {
            //e.Configuration.GlobalOptions.FlagNoBuffer = true;
            e.Configuration.ForcedInputFormat = "mjpeg";
            if (ssSize==StreamSize.small)
                e.Configuration.PrivateOptions["framerate"] = "30";
            if (ssSize == StreamSize.medium)
                e.Configuration.PrivateOptions["framerate"] = "15";
            if (ssSize == StreamSize.large)
                e.Configuration.PrivateOptions["framerate"] = "7.5";

            //e.Configuration.PrivateOptions["fflags"] = "nobuffer";
            //e.Configuration.PrivateOptions["flags"] = "low_delay";
            //e.Configuration.PrivateOptions["probesize"] = "8192";
            //e.Configuration.PrivateOptions["analyzeduration"] = "1";
        }
        private void Vlcc_MediaFailed(object sender, ExceptionRoutedEventArgs e)
        {
            dt.Start();
        }
        private void Vlcc_MediaEnded(object sender, RoutedEventArgs e)
        {
            dt.Start();
        }
        private void Dt_Tick(object sender, EventArgs e)
        {
            StartPlayer();
            dt.Stop();
        }
        private void gGrid_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (gGrid.RenderSize.Width<=416)
            {
                if (ssSize!= StreamSize.small)
                {
                    ssSize = StreamSize.small;
                    StartPlayer();
                }    
            }
            else if (gGrid.RenderSize.Width <= 640)
            {
                if (ssSize != StreamSize.medium)
                {
                    ssSize = StreamSize.medium;
                    StartPlayer();
                }
            }
            else
            {
                if (ssSize != StreamSize.large)
                {
                    ssSize = StreamSize.large;
                    StartPlayer();
                }
            }
        }

        public void StopPlayer()
        {
            try
            {
                mePLayer.Dispatcher.Invoke(() =>
                {
                    mePLayer.Stop();
                    mePLayer.Close();
                });
            }
            catch(Exception e)
            { }
        }
        public void StartPlayer()
        {
            try
            {
                StopPlayer();
            }
            catch (Exception e)
            { }
            try
            {
                mePLayer.Dispatcher.Invoke(() =>
                {
                    switch (ssSize)
                    {
                        case StreamSize.small:
                            mePLayer.Source = new Uri("http://10.10.20.173:8090/camera_small.mjpeg");
                            break;
                        case StreamSize.medium:
                            mePLayer.Source = new Uri("http://10.10.20.173:8090/camera_medium.mjpeg");
                            break;
                        case StreamSize.large:
                            mePLayer.Source = new Uri("http://10.10.20.173:8090/camera_large.mjpeg");
                            break;
                    }
                    mePLayer.Play();
                });
            }
            catch (Exception e)
            { }
        }
        #endregion

        #region Enums
        public enum StreamSize
        {
            small,
            medium,
            large
        }
        #endregion
    }
}

### Command line ffplay

ffplay http://10.10.20.173:8090/camera_large.mjpeg
```

**Comment by mariodivece** [comment]
This should be fixed now in the latest master. Could you test and let me know the results?

**Comment by mariodivece** [comment]
Using the latest `master` commit, could you please test by handling the `MediaOpening` event and adjusting the following `Options` to your needs? Please let me know the results. If there are no further comments before the end of this week, I will package and publish the new NuGet and consider this issue closed.

```csharp
	// You can render audio and video as it becomes available but the downside of disabling time
	// synchronization is that video and audio will run on their own independent clocks.
	// Do not disable Time Sync for streams that need synchronized audio and video.
	e.Options.IsTimeSyncDisabled =
		e.Info.Format == "libndi_newtek" ||
		e.Info.InputUrl.StartsWith("rtsp://uno");

	// You can disable the requirement of buffering packets by setting the playback
	// buffer percent to 0. Values of less than 0.5 for live or network streams are not recommended.
	e.Options.MinimumPlaybackBufferPercent = e.Info.Format == "libndi_newtek" ? 0 : 0.5;

	// The audio renderer will try to keep the audio hardware synchronized
	// to the playback position by default.
	// A few WMV files I have tested don't have continuous enough audio packets to support
	// perfect synchronization between audio and video so we simply disable it.
	// Also if time synchronization is disabled, the recommendation is to also disable audio synchronization.
	Media.RendererOptions.AudioDisableSync =
		e.Options.IsTimeSyncDisabled ||
		e.Info.InputUrl.EndsWith(".wmv");
```

**Comment by ehemax** [comment]
Thank you very much! Will test the new version the next view days.

**Comment by mariodivece** [comment]
Please remember that this issue will be closed tomorrow as a new NuGet package will be published. Any further feedback will need to be placed in a new issue.

**Comment by mariodivece** [comment]
Closing issue! New NuGet coming today!
