### ISSUE TITLE
MediaEnded event is called twice

### ISSUE THREAD

**Issue by fakepl** [unosquare/ffmediaelement#314]
After upgrading from 3.4.240 to 4.0.270 MediaEnded event was called twice instead of once, when video reached the end. Downgrading to 3.4.240 again helped.

**Comment by mariodivece** [comment]
Let me look into this... Any other events that you see being called twice?

**Comment by mariodivece** [comment]
You were right. Could you please try it with a build using the latest master?

**Comment by fakepl** [comment]
It works now fine.
