### ISSUE TITLE
Getting a frame from video stream

### ISSUE THREAD

**Issue by Nyasaki** [unosquare/ffmediaelement#316]
*Getting a frame from video stream*

*I'd like to get a frame from the video for further processing (Face detection).
Is there a way to get a frame from the video?*

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [X] Question
 - [ ] Not sure

**Comment by tenisak** [comment]
From a rendered video? Try to look at [this comment](https://github.com/unosquare/ffmediaelement/issues/121#issuecomment-358993066). Perhaps he would save one image from WriteableBitmap… 
(I do not know if the code snippet is compatible with the current version.)

**Comment by Nyasaki** [comment]
> From a rendered video? Try to look at [this comment](https://github.com/unosquare/ffmediaelement/issues/121#issuecomment-358993066). Perhaps he would save one image from WriteableBitmap…
> (I do not know if the code snippet is compatible with the current version.)
Is this a event from the MediaElement?
Because VS doesnt suggest it

**Comment by mariodivece** [comment]
I am closing since this is an old question that has been answered many times. I do not know why VS is not suggesting the event since it has been there for many versions of this control.

**Comment by nevaran** [comment]
Mind linking to the answered question? I cant find it. @mariodivece
