### ISSUE TITLE
Filter graph command line ffplay

### ISSUE THREAD

**Issue by sharslammer** [unosquare/ffmediaelement#317]
# Filter graph command line ffplay

I didnt find a way to run as ffplay -i <source>  -vf "lenscorrection=cx=0.5:cy=0.5:k1=-0.85:k2=0.25". To remove fisheye distortion.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [х] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package  4.0.270 
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce
Tried at OnMediaInitializing:
`e.Configuration.PrivateOptions["lenscorrection"] = "cx=0.5:cy=0.5:k1=-0.85:k2=0.25";`
or
`e.Configuration.PrivateOptions["vf"] = "lenscorrection=cx=0.5:cy=0.5:k1=-0.85:k2=0.25";`

## Expected Results

Ignored parameters
 
### XAML
```xml
<MainWindow>
</MainWindow>
```

### C#
```csharp
e.Configuration.PrivateOptions["lenscorrection"] = "cx=0.5:cy=0.5:k1=-0.85:k2=0.25";
```

### Command line ffplay
```batch
ffplay "hello.mp4"   -vf "lenscorrection=cx=0.5:cy=0.5:k1=-0.85:k2=0.25"
```

**Comment by mariodivece** [comment]
did you check out the sample reference player on how to apply filters? Search for yadif in the source.

**Comment by mariodivece** [comment]
BTW I just tested this filter on the sample app and it works just fine on the latest master commit.
