### ISSUE TITLE
Rewinding frame by frame, some frames aren't loaded/rendered

### ISSUE THREAD

**Issue by StevenGilligan** [unosquare/ffmediaelement#32]
First off : This project is awesome and is a life saver for me!

I'm currently working on using ffme for an application that needs fine-grained rewind/forward and frame-by-frame seeking. I have quickly implemented NextFrame and PrevFrame commands in the sample application and it works flawlessly when seeking forward, but when seeking backwards I get a lot of frames that simply don't render at all. So for example you go back frame by frame and only 1 frame out of 2 or 3 gets rendered, so it is not as smooth as seeking forward.

You can take a look at my fork to see how I implemented frame by frame seek : https://github.com/StevenGilligan/ffmediaelement

Did I implement it wrong? If not, is this something that can be fixed? I wouldn't mind fixing it myself if you can give me some direction, I just wouldn't know where to start looking to fix this. 

I tested with a couple different .avi mpeg4 files and .mkv h264 files with the same result.

**Comment by mariodivece** [comment]
Correct, seeking backwards is one of the main features of FFME and it will be available very soon! Glad you like this project.

Also, the the frame-exact seeking method will be called Step(int frameCount) where frameCount can be a positive or a negative integer. If there are video frames it will step on video frames before audio frames. If there is no video, then the stepping will still apply to audio audio frames. Thanks for posting this issue as it helps me keep track of my progress.

**Comment by catester** [comment]
Thank you for your efforts in creating this project. Finally we have a correct ffmpeg reader in c#, it's hard to get it right with this complicated ffmpeg API.

I am also interested in smooth backwards seeking so I look forward to it.

Also for future suggestion:
I know your main purpose is mediaelement but maybe "Frame Accurate Seeking" can be implemented too like this one:
https://github.com/lbrandy/ffmpeg-fas
Basically it's passing over frames (without materializing them) and creating an index for accurate seeking.
It can be good  feature for video editing UI:

```c#
using (var container = new MediaContainer(mediaUrl)) {
	container.IndexFrames(); //Takes a while
	
	//Now you can do Frame Accurate seeking
	
	//Save for later use, as it's expensive to create index.
	container.SaveIndex(indexFile); 
}


//Re-use previously saved index
using (var container = new MediaContainer(mediaUrl, indexFile)) {

	//Now you can do Frame Accurate seeking
	
}
```

**Comment by mariodivece** [comment]
I will look into the indexing solution but it will most likely be part of supplying it via the MediaOpeningEvent, in the MediaOptions and not standard behavior. I have improved the seeking functionality significantly. Could you try again and provide me with some feedback please?

**Comment by StevenGilligan** [comment]
Just tested using your reference player and the latest commit. You've made a ton of improvements! Frame-by-frame forwarding is perfect. Frame-by-frame rewinding is a little choppier because of the frequent buffering. 

I feel like my use case is a bit special where I need to pause/rewind/play while working (doing video transcribing) and often rewind frame-by-frame from between a few frames to a a few seconds.

It feels like the big bottleneck in rewinding is buffering. Basically I think what I need is similar to catester's comment in the thread : If I could pre-buffer large portions of the video beforehand to make sure I can seek with no buffering, it would fit my use case perfectly. 

So I'm thinking two things could help me, either : 
1) A way to pre-buffer parts of the video (even if it means large RAM usage, it's the drawback for smooth frame-by-frame rewind)
2) A way to expose a cache-policy, or a way to override the default cache implementation so I could keep the past frames in cache. Again, trading RAM usage for faster seek in my app. 

Again I want to thank you for the awesome work you've been doing! 👍

**Comment by catester** [comment]
Thank you! Backwards seeking is vastly improved.

**Comment by mariodivece** [comment]
I am closing this issue as the main point has been addressed. I have moved additional features to the new issue #139 but I need to finish the 2.0 engine first.
