### ISSUE TITLE
Add the ability to unload FFmpeg Libraries

### ISSUE THREAD

**Issue by premingiet** [unosquare/ffmediaelement#320]
Media element not disposed when launched from child form

suppose i have a parent form and from that form, i launch a child form, and child form is the form where media element and ffmpeg is initialized. Now when i play a video, and i close the child form, i can still hear the audio playing, until i close the main parent form. 

I guess media element is not getting disposed properly. 

If i use the Dispose() method, that solves the issue, but then it still consumes space and doesn't release it even if i close the child form. 

## Issue Categories

 - [x] Bug

## Version Information

 - [x] NuGet Package version 4.0.270

**Comment by mariodivece** [comment]
Closing windows in WPF does not necessarily dispose of them. 
https://social.msdn.microsoft.com/Forums/en-US/992b4aa3-f066-4ccf-8c14-aec871eccdb6/how-to-properly-close-dispose-a-wpf-window?forum=wpf

You need to call dispose on the MediaElement as you suggested.
The RAM usage you see is from the FFmpeg libraries that have been loaded into memory. There currently is no way to unload the FFMpeg libraries. I will leave this open so I can remember to add a method that unloads ffmpeg ddll modules.

Reference: https://stackoverflow.com/questions/2445536/unload-a-dll-loaded-using-dllimport
