### ISSUE TITLE
Mapping several channels from different audiotracks

### ISSUE THREAD

**Issue by Dartjek** [unosquare/ffmediaelement#324]
# Mapping several channels from different audiotracks

Hi, I search a opportunity for mapping nth channels from different audiotracks. For example, to map into stereo 1st channel from 1st audiotrack as the left channel and 1st channel from 3rd audiotrack as the right channel . It can be usefull since audiotracks could be recorded from several devices.

## Issue Categories

 - [x] Feature Request

## Sample Code
I imagine usage like in the following code.
### C#
```csharp
private void Player_MediaChanging(object sender, MediaOpeningEventArgs e)
{
    // Mapping channels into stereo from the 1st and the 3rt audiotracks.
    StreamInfo track1st = e.Info.Streams[1];
    StreamInfo track3rd = e.Info.Streams[3];
    e.Options.AudioTracks = new StreamInfo[] { track1st, track3rd };
    e.Options.AudioFilter = "[In1][In2]amerge=inputs=2,pan=stereo|c0=c0|c1=c2"
}
```

**Comment by mariodivece** [comment]
Kind of outside the scope of this project... Certainly a good suggestion... Any reason why you would not pre-process the stream with fffmpeg and use the resulting stream to render it with FFME?

**Comment by Dartjek** [comment]
Actually, I didn't consider this way and think I will try this. Thank you.

**Comment by yappcat** [comment]
Hi, Mario. I ran into the same problem as Dartjek.
I liked your idea of "pre-process the stream with fffmpeg...".
Could you please explain how to do this?
