### ISSUE TITLE
FFME needs Application() before it can be initialized

### ISSUE THREAD

**Issue by reinux** [unosquare/ffmediaelement#326]
# FFME needs Application() before it can be initialized

I'm using FFME in conjunction with [FsXaml](https://github.com/fsprojects/FsXaml), which lets me load Xaml files in F# scripts and programs with type-safety and all that.

The problem is that since F# needs to initialize the type within the IDE in order for Intellisense to work on the types it generates, it has to initialize FFME without an Application thread, so I get this error:

> The type provider 'FsXaml.XamlTypeProvider' reported an error: The type initializer for 'Unosquare.FFME.MediaElement' threw an exception.

I realize this is extremely cryptic, but I'm fairly confident that it's the threading issue, as I get this exception when I instantiate the Window before the Application:

> System.InvalidOperationException: 'The calling thread cannot access this object because a different thread owns it.'

It would be great if it could be made to defer any thread-dependent calls until after the MediaElement constructor -- perhaps in the Loaded event or in an OnLoaded override?

## Issue Categories

 - [x] Bug
 - [x] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package FFME.Windows 4.0.270
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

1. Create a Xaml Window that contains FFME.MediaElement
2. In Main, `new` the Window before the `new`ing an Application
3. Run

Results in exception:

> System.InvalidOperationException
>   HResult=0x80131509
>   Message=The calling thread cannot access this object because a different thread owns it.
>   Source=WindowsBase
>   StackTrace:
>    at System.Windows.Threading.Dispatcher.VerifyAccess()
>    at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
>    at Unosquare.FFME.Platform.PropertyMapper.DetectDependencyPropertyChanges(MediaElement m)
>    at Unosquare.FFME.MediaElement.UpdateDependencyProperties()
>    at Unosquare.FFME.Platform.GuiTimer.RunTimerCycle(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 954
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 902
>    at System.Threading.TimerQueueTimer.CallCallback() in f:\dd\ndp\clr\src\BCL\system\threading\timer.cs:line 705
>    at System.Threading.TimerQueueTimer.Fire() in f:\dd\ndp\clr\src\BCL\system\threading\timer.cs:line 662
>    at System.Threading.TimerQueue.FireNextTimers() in f:\dd\ndp\clr\src\BCL\system\threading\timer.cs:line 417

## Expected Results

- Run without the InvalidOperationException, even if the Window is initialized first
 
### XAML
```xml
<Window x:Class="WpfApp1Test.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1Test"
        mc:Ignorable="d"
        xmlns:ff="clr-namespace:Unosquare.FFME;assembly=ffme.win">
            <ff:MediaElement/>
</Window>
```

### C#
```csharp
[STAThread]
static void Main()
{
    var w = new MainWindow(); // swap this line with the next and it works just fine
    var app = new Application();
    app.Run(w);
}
```

**Comment by reinux** [comment]
I forgot to mention, the same problem will arise if MediaElement.FFmpegDirectory is assigned before an Application() is created, too.

**Comment by mariodivece** [comment]
ok... will look into this

**Comment by reinux** [comment]
Thanks!

**Comment by mariodivece** [comment]
The next version does not need Application anymore. you can load the 'MediaElement' control in the order you suggested. Please open a new issue referencing this one if you have additional feedback.

**Comment by reinux** [comment]
Sweet!
