### ISSUE TITLE
How can use in UWP appllicatiom

### ISSUE THREAD

**Issue by luguoci** [unosquare/ffmediaelement#331]
# How can use in UWP appllicatiom

*I have followed "Quick Usage Guide" at README.md and get following XAML error after adding the control*
```

Error	XLS0414	The type 'ffme:MediaElement' was not found. 
Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
```
## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *4.0.270*
 - [ ] Build From *Master* branch
 - [ ] Build from *Branch Name

## Expected Results

 -  UWP application compact ,target Windows 10 version 1803(10.0)

 
## Sample Code

```xml

<Page
    x:Class="Myapp.Views.TrtPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Myapp.Views"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <Grid Name="Player">
        <ffme:MediaElement x:Name="Media" Background="Gray" LoadedBehavior="Play" UnloadedBehavior="Manual" />
    </Grid>
</Page>

```

**Comment by mariodivece** [comment]
This is a WPF control. Feel free to use the library in the `Common` namespace to implement your own UWP control as I did with Windows. The `Common` library does not have any dependencies beyond dot net standard 2. Maybe with the upcoming dotnet core 3, the WPF control will be usable in UWP. Related issue #307

**Comment by luguoci** [comment]
Got it , Thank you !
