### ISSUE TITLE
Cannot pause/play beyond end of original state of media when opened

### ISSUE THREAD

**Issue by star-thoughts** [unosquare/ffmediaelement#332]
# Cannot pause/play beyond end of original state of media when opened

If you open a file that is being written by another process, it will play successfully, and will continue playing even beyond the duration of the file when it was originally opened.  But if you pause the media, it will not allow you to play it.

## Issue Categories

 [x ] Bug
 [ ] Feature Request
 [ ] Question
 [ ] Not sure

## Version Information

 [x ] NuGet Package 4.0.270
 [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. You'll need another process that writes a media file over time, generally in real time (I'm pulling an MPEG/TS stream from an HD-HomeRun PRIME TV tuner).
 2. Use the sample Windows application to open the media file after 4 or 5 seconds of media have been saved to the file
 3. Pause the media at 2 seconds and notice you can resume playing
 4. Let the media play beyond the 5 seconds that was originally in the file when opened and then pause it
 5. Notice you cannot resume playing the file

## Expected Results

The media continues playing correctly regardless of position.

Note that changing the following in the file CommandManager.Priority.cs does fix the issue, but I have no idea if it would cause unintended side effects:

 ````C#
        private bool CanResumeMedia
        {
            get
            {
                if (MediaCore.State.HasMediaEnded)
                    return false;

                return true;
            }
        }
````

**Comment by mariodivece** [comment]
This should work fine in the latest master commit. Check it out and reopen if you find further issues.
