### ISSUE TITLE
Lowering CPU usage

### ISSUE THREAD

**Issue by tehnetaholic** [unosquare/ffmediaelement#333]
# Lowering CPU usage

Hi! First of all - thank you for a great library!
In this issue https://github.com/unosquare/ffmediaelement/issues/244 you said, that it might be possible to reduce CPU usage by replacing WriteableBitmap with D3DImage or InteropBitmap for a cost of not using ffmpeg filters. I am not planning on using filters.
I'd like to ask you if you could give an estimation on how much work will that modification require? Also any hints would be much appreciated.
I would like to use ffmediaelement to display many videos simultaneously. I tried setting EnableWpfMultithreadedVideo but while it reduced cpu usage slightly - it brought new issues, like hanging when a video is unloaded and not playing some of video files from time to time.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x ] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [x ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

**Comment by mariodivece** [comment]
I have tested with InteropBitmap and D3DImage and the CPU usage is the same. In fact WriteableBitmap is the fastest. If you are displaying multiple videos at the same time have you tried a `scale` filter on the video stream?

`e.Options.VideoFilter = "scale=-1:240"` for example?
I could also add a render framerate limiter to display, say 10 FPS

**Comment by mariodivece** [comment]
There is a new Renderer parameter `VideoRefreshRateLimit` but it does not seem to help reduce CPU by too much -- proof that the WritableBitmap is very fast and efficient. The decoding is what takes up most of the CPU usage -- which makes sense. Sorry I am unable to help you more.

**Comment by OneB1t** [comment]
im running probably into same issue when i increase window size from 800x600 which is running 60fps to 1920x1080 it drops to about 20fps and 100% single cpu core load

is there some way to disable CPU scaling and let GPU handle this part? or some other way how to improve scaling performance?

also is there some profiler which will show me which part of code is causing this problem as im unable to see it inside visual studio...
