### ISSUE TITLE
the PictureNumber Property of RenderingVideoEventArgs is Larger than total frame count.

### ISSUE THREAD

**Issue by sunjianchuang** [unosquare/ffmediaelement#335]
the PictureNumber Property of RenderingVideoEventArgs is Larger than total frame count.

My Test wmv file:  C:\Users\Public\Videos\Sample Videos\Wildlife.wmv

The wmv file have 901 Frames；
After opened by MediaElement，at RenderingVideo Event Hander，the PictureNumber will be larger than 901.  
Why?

**Comment by mariodivece** [comment]
yeah it's in issue #281 this will get fixed in the 2.80 NuGet. SMTPE is also getting fixed.

**Comment by mariodivece** [comment]
this is now fixed in the latest master commit.
