### ISSUE TITLE
How to get some statistics like VLC Media Player when play HLS stream

### ISSUE THREAD

**Issue by namcigar** [unosquare/ffmediaelement#336]
# How to get some statistics like VLC Media Player when playing a HLS stream

I want to get some infos like this picture (VLC media player) when playing a HLS stream. How can I do it, thanks.

![question](https://user-images.githubusercontent.com/3125619/54346165-34a82c80-4677-11e9-866a-4e03b55a05ee.PNG)

## Issue Categories

 - [ ] Question

## Version Information

 - [ ] Build From *Master* branch

**Comment by mariodivece** [comment]
Related to #138

**Comment by namcigar** [comment]
Thank you, can't wait for it !

**Comment by mariodivece** [comment]
duplicate of #138
