### ISSUE TITLE
Switching videos without loading

### ISSUE THREAD

**Issue by iFrosten** [unosquare/ffmediaelement#337]
Hello, 
I would like to know if it is possible to preload videos using this library and play them without loading. I need this feature so that I can watch merged video before rendering it. 
Thanks.

## Issue Categories

 - [ ] Bug
 - [X] Feature Request
 - [X] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
I am not sure I understand... Maybe implement your own IMediaInputStream as in the sample project?

**Comment by iFrosten** [comment]
> I am not sure I understand... Maybe implement your own IMediaInputStream as in the sample project?

i mean Directshow DESCombine analog. So i can combine multiple videos into a single video and play it on player in real-time.

**Comment by mariodivece** [comment]
how do you do that in the standard ffplay.exe tool? Full command line arguments please

**Comment by mariodivece** [comment]
Since no firther feedback was received in a week, I am closing the issue. Feel free to provide additional feedback.
