### ISSUE TITLE
Scaler: Wrong aspect ratio for videos with PAR != 1

### ISSUE THREAD

**Issue by Vasilich** [unosquare/ffmediaelement#34]
Tested latest version (from 21.06.2017), and found out, that aspect ratio flag in movie file header isn't respected, It seems that currently the code calculates aspect ratio from video resolution. But all TV SD recordings have display aspect ratio (DAR) 16:9 though resolution is 720x576, so all such movies are shown compressed from both sides (long faces, tall people only, etc :) )
Some more information:
https://stackoverflow.com/questions/4422387/get-aspect-ratio-of-video-from-ffmpeg
I am looking forward to use this new version of the component, as it looks much better now, than 5 months back when i tested it last time !

**Comment by mariodivece** [comment]
Thabks you so much for this report! I kept wondering why some videos looked funny! I will work on this once I finish audio pitch shifting.

**Comment by mariodivece** [comment]
Could you please test again and let me know if the picture looks OK?

**Comment by Vasilich** [comment]
tested with newest code (23.06.2017, 11:00) - works as expected. thanks for fast response!
