### ISSUE TITLE
Memory leak when an m3u8 is stopped.

### ISSUE THREAD

**Issue by AaronAnz** [unosquare/ffmediaelement#346]
# Possible Memory Leak / Weird behavior while m3u8 is stopped.

MediaElement.Stop() is eating memory. I am unable to use MediaElement.Pause() as it does nothing and and when I use MediaElement.Stop() the memory usage gradually increases until you run out. Everything works fine while the stream is playing.

## Issue Categories

 - [X] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [X] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Pass an m3u8 ( I'm using twitch.tv ) to the MediaELement.
 2. use MediaElement.Stop(); ( MediaElement.Pause() does absolutely nothing. )
 3. Wait extended time and watch the memory usage gradually increase and never free.

My app is usually around ~50mb-100mb when a stream hasnt been started then stopped and sits at around ~350mb while a the stream is playing. Once the stream has been started then stopped it went as high as 4GB ( I was AFK ) when I left it running for an hour or two in this state.

I guess this may not be a memory leak so to speak, but it definitely is something that needs to be changed. If you stop a stream and play it again, it should just start at the current time. If you pause it, it should queue up some to an extent not all the way until it breaks the app.

## Expected Results

Running out of memory

**Comment by mariodivece** [comment]
The packet reader will read as much as possible for live streams. Pause does not work because it is not supposed to. The real issue is that you could still call Stop on a live stream. I will correct.

**Comment by AaronAnz** [comment]
I mean you should be able to call stop and then if you call play again it should just start at the current date time not queue up anything.

**Comment by mariodivece** [comment]
the correct usage is to call Close() and then reopen the stream. -- Effectively equivalent.

**Comment by AaronAnz** [comment]
Oh ok. I'll do that going forward. Thanks.

**Comment by mariodivece** [comment]
In the latest commit non-seekable streams cannot call stop() anymore (a good thing)
