### ISSUE TITLE
Media not properly ending

### ISSUE THREAD

**Issue by FancyFunction** [unosquare/ffmediaelement#347]
# Media not properly ending

I wanted to restart the played media once it ended as seamlessly as possible but sometimes it doesn't end properly and makes restarting the media ugly.

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [X] NuGet Package *4.1.280*
 - [X] Build From *Master* branch, I only downloaded the master branch source code and am not sure on how to get the commit id (I have no .git folder in source). I downloaded it on 17th March if that helps.

## Steps to Reproduce

 1. Set LoadedBehaviour to play and UnloadedBehaviour to manual
 2. Set media position to TimeSpan.Zero in MediaEnded event
 3. Play media

## Expected Results

 - Media is in a paused state at the end, setting position and playing the media should play the media from the beginning.
 - Media is somehow not in a paused state (but still fired the MediaEnded event) in which the third step would be optional.

## Actual Results

What I noticed when looking at my project and the provided sample project is that sometimes the loaded media does not reach the end time and instead stays in "Play" state but does not actually play or reach the end at all (in my test video it stays about 20 milliseconds before the end). MediaEnded is never fired in this case.

Tested sample video from this page https://peach.blender.org/download/ but also noticed this behavior in different videos. I think most of them were .webm files but that is just a guess.

![Screenshot of the media info from the sample project](https://user-images.githubusercontent.com/16601203/54866600-2e503980-4d76-11e9-8273-4e18c2b938ac.png)
 
### XAML
```xml
<MainWindow>
    <ffme:MediaElement x:Name="Media" LoadedBehavior="Play" UnloadedBehavior="Manual" MediaEnded="Media_Ended" />
</MainWindow>
```

### C#
```csharp
private async void Media_Ended(object sender, RoutedEventArgs e)
{
    Media.Position = TimeSpan.Zero;
    await Media.Play();
}
```

## Ugly solution

Despite this I still managed to loop videos but using a very ugly solution. Once the media starts playing I start a timer and each tick check if the position stayed same since the last tick. If it did, restart the media.

**Comment by mariodivece** [comment]
Remember that Position is a dependency property. If you set it to something and then the media core rewrites it in the middle of an update cycle, then it won't apply your changes. Fortunately you can instead do:

```csharp
private async void Media_Ended(object sender, RoutedEventArgs e)
{
    await Media.Seek(TimeSpan.Zero);
    await Media.Play();
}
```
