### ISSUE TITLE
Can I play the encrypted video?

### ISSUE THREAD

**Issue by tabatabaeifar** [unosquare/ffmediaelement#349]
Can I play the encrypted video?
Hi
I need to play encrypted video file that encrypted by ffmpeg with ffme user control.
How can I do this?

### Command line in ffplay
```batch
ffplay test_encrypted.mp4 -decryption_key ****************************************
```

**Comment by mariodivece** [comment]
Would you please post a sample encrypted media file and the correct key? I need an example so I can figure it out.

**Comment by mariodivece** [comment]
You can handle the `MediaInitializing` event and pass the decryption key as a demuxer private option -- exactly in the same way you do with `ffplay`.

Example:
```csharp
// A decryption key can be set by specifying a hexadecimal string.
if (e.MediaSource.EndsWith("03-encrypted.mp4", StringComparison.InvariantCultureIgnoreCase))
{
    e.Configuration.PrivateOptions["decryption_key"] = "76a6c65c5ea762046bd749a2e632ccbb";
}
```
