### ISSUE TITLE
How to change brightness contrast and RGB

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#354]
# How to change brightness contrast and RGB

*Is there a way to change the video brightness and contrast levels.  Also i would like to be able to adjust the RGB values if possible. So i would ideally like to use track/slider bars to adjust these values when the video is playing or paused. I could not find any properties that relate to these but maybe i missed something. I did find some info online that suggested these properties could be adjusted with parameters to the FFMPEG lib but i could not determine if that was during playback or for processing to a new video.
Any advice appreciated. this is a great library  *

## Issue Categories

 - [x] Question

## Version Information

 - [x] NuGet Package *4.1.280*

**Comment by mariodivece** [comment]
Look for e.Options.VideoFilter in the Sample project and a pply a filter as suggested here:
https://video.stackexchange.com/questions/20962/ffmpeg-color-correction-gamma-brightness-and-saturation

As far as changing the filter, you will have to call the ChangeMedia and ahandle the MEdiaCheanging event to set the new brightness/contrast in the e.Options.VideoFilter.

**Comment by manity42** [comment]
I will give that a go.
thanks.

**Comment by manity42** [comment]
Will close this for now.
When i get a chance to try it i will post new questions if i have problems.

thanks

**Comment by mariodivece** [comment]
Thanks. Please try to post your solution also so everybody can see how you resolved it.
