### ISSUE TITLE
Cant build the current master branch with either clone or zip download

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#355]
# Cant build the current master branch with either clone or zip download

Using zip download or clone in vs2017 the project seems to come down ok but i cant get it to build in vs2017 The error relates to .net core. i dont have that installed.
Is it a requirement now to build the sample projects ?

Please advise.

## Issue Categories
 - [ ] Not sure

## Version Information
 - [ ] Build From *Master* branch, Commit *Latest current*

## Steps to Reproduce

 1. clone or download the latest master branch
 2. Load in vs 2017
 3. Build

## Expected Results
Expect successful build
Get this error
Severity Code Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.	Unosquare.FFME.Common	C:\Program Files\dotnet\sdk\2.1.504\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137	

![image](https://user-images.githubusercontent.com/39360067/55144904-b3738e00-517c-11e9-82d6-75af0167def5.png)

**Comment by mariodivece** [comment]
The current master branch is using vs 2019. Please go to the released section and download the code from tag 2.80. that should build and run fine in vs 2017
