### ISSUE TITLE
How to get packet position when video playing?

### ISSUE THREAD

**Issue by TWJOINJACK** [unosquare/ffmediaelement#356]
# Issue Title (How to get packet position when video playing?)

## Issue Categories

 - [ * ] Question

## Version Information

 - [ * ] Build from Release 4.1.280

## Steps to Reproduce

 1. Step 1 : Old Version in Common.Decoding.MediaContainer.cs StreamRead will sync player.
 2. Step 2 This version will cache first , so I can't throw event when play on the packets.
 3. Step 3 I was overwrite  StreamRead method and throw notify event.But know will send notify when play first second.

## Expected Results

 - Result 1 Would you know how to change player's buffer to sync read ? 
 
## Sample Code
```
// Allocate the packet to read
            var readPacket = MediaPacket.CreateReadPacket();
            StreamReadInterruptStartTime.Value = DateTime.UtcNow;
            var readResult = ffmpeg.av_read_frame(InputContext, readPacket.Pointer);
            if (readPacket.Size == 1008)
            {
                NotificationCenter.Notify("GNSS", readPacket.Position);
            }
```

**Comment by mariodivece** [comment]
I really am unable to understand what you mean. Could you please explain a little further? The next release will have events that fire when packets are read but I am not sure I understand what you are asking

**Comment by TWJOINJACK** [comment]
Thanks Mario,
I try to explain more clearly. 
I have an encode video file and I will get some packet (not video's frame) in the stream buffers.
In your old version, I import your projects and add my paste code in the Stream Read function. I can follow video position and readPacket buffer size to check this is my data . And throw notification to My Application .
But in the newer version . I'll get all of the data when loaded. And I try to find problem. I found the newer version will at ``Loaded`` run Stream Read function not when load  video's position. 
I want to know how to get readpacket.Position when video playing.
Thanks for your kindly reply.
