### ISSUE TITLE
InvalidOperationException in Unosquare.FFME.Decoding.MediaContainer.Open()

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#358]
*System.InvalidOperationException: "The stream components are already open." in Unosquare.FFME.Decoding.MediaContainer.Open()*

## Issue Categories

 - [x] Bug

## Version Information

 - [x] NuGet Package *2.80*

## Steps to Reproduce

I don't know. I have just received an automated bug report with the following stack trace:
```
-> Unosquare.FFME.Decoding.MediaContainer.Open()
-> Unosquare.FFME.Commands.CommandManager.CommandOpenMedia(IMediaInputStream inputStream, Uri streamUri)
-> Unosquare.FFME.Commands.CommandManager+<>c__DisplayClass14_0.<OpenMediaAsync>b__0()
-> Unosquare.FFME.Commands.CommandManager+<>c__DisplayClass43_0.<ExecuteDirectCommand>b__0()
```

My code to open audio file is as simple as:
```cs
private async Task Play(string path)
{
    await mediaElement.Open(new Uri(path));
}
```
If I call this function with the same parameter, the file is just played again from the beginning, which is what I expect. So, I don't know under which circumstance the exception could be thrown.

Thanks for your help.

**Comment by mariodivece** [comment]
I am unable to repro this issue. If you can get me more information on how to do it please feel free to reopen or report in a new issue. Closing for now.
