### ISSUE TITLE
TransportStreamRecorder saving stream in incorrect order

### ISSUE THREAD

**Issue by kealist** [unosquare/ffmediaelement#359]
# `TransportStreamRecorder` saving stream in incorrect order

This seems ok with recording frames from a video like BigBuckBunny, but when I record in the sample application pressing `w` from a live feed from an IP Camera (Amcrest) the frames are recorded out of order.  Generally they proceed forward, but jump around in time all around.  Have you experienced this?

Any thoughts how to mitigate this?  Thank you for your work on adding this feature!

## Issue Categories

 - [x] Bug

## Version Information

 - [x] Build From *Master* branch, Commit e66028d567ab708dca5df954375e09fa82e4c120

## Steps to Reproduce

1. Connect to IP Cam in Sample Application
2. Press W to start recording
3. Press W to stop recording
4. View video file and see frames jumping

**Comment by mariodivece** [comment]
I have noticed the amcrest encoder sometimes sends frames and packets in incorrect order... I was wondering the same... Even when watching the video sometimes frames will jump around randomly. Maybe it's a problem with amcrest itself? I will investigate. Please investigate on your own and let me know your results

**Comment by kealist** [comment]
I would make the argument that when I use CLI ffmpeg tools to capture the stream in the same way, they are in order as far as I can see.  So there is likely something that can be done.   I'll try to look at RTP sequencing with the encoder, but not really familar with the inner workings.   I will let you know if I can diagnose anything

**Comment by kealist** [comment]
Not that I think Amcrest is bugfree by any means

**Comment by mariodivece** [comment]
> I would make the argument that when I use CLI ffmpeg tools to capture the stream in the same way, they are in order as far as I can see. So there is likely something that can be done. I'll try to look at RTP sequencing with the encoder, but not really familar with the inner workings. I will let you know if I can diagnose anything

What is the full command-line arguments for ffmpeg.exe you are using? is you are re-encoding then it would make sense that the frames appear in order

**Comment by mariodivece** [comment]
Another fact: the StreamTransportRecorder simply copies the packets into the stream as they are received. No additional processing takes place. I have tested other RTSP and UDP streams and they don't seem to have the same issue.

**Comment by mariodivece** [comment]
Any further feedback on this?

**Comment by kealist** [comment]
@mariodivece You are right.  I've mostly only dealt with simple audio RTP streams previously so I'm still learning.  Just working around this issue by converting.   Sometimes it seems to be better than others, but I doubt it's worth messing with this much more.

**Comment by mariodivece** [comment]
Ok, tahnks. Closing for now. Please file a new issue related tot his one if you can provider further feedback.
