### ISSUE TITLE
NullReferenceException from StopWorkers()

### ISSUE THREAD

**Issue by shazam19** [unosquare/ffmediaelement#361]
# *NullReferenceException on MediaElement.Dispose()*

If you dispose mediaelement without opening any media ffme.common throws exception from CommandManager.StopWorkers() because *Workers* is not set in this line yet: 
   MediaCore.Workers.Dispose();

## Issue Categories

 - [ ] Bug

## Version Information

 - [ ] NuGet Package *2.8*

## Steps to Reproduce

 1. Initialize a mediaElement 
 2. Call Dispose without opening a media

## Expected Results

 - MediaElement disposes without any exception
 
### C#

    var v = new MediaElement();
    v.Dispose();
```

**Comment by mariodivece** [comment]
This is fixed in the upcoming version. Thanks for the bug report.
