### ISSUE TITLE
Should I use MediaElement.EnableWpfMultiThreadedVideo feature

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#362]
# Issue Title (*Should I use MediaElement.EnableWpfMultiThreadedVideo feature *)

*Should i use MediaElement.EnableWpfMultiThreadedVideo feature ?
 I want to have 4 x videos running on the same PC. Each video natural size is H264 1920x1080.
Ideally the 4 videos would play in sync with each other.

 I understand this feature enabled is supposed to allow each video to run in its own thread separate from from the main UI thread, but i see in the documentation that it says this feature is experimental. Im not sure what that means.
 I was able to run same 4 videos using the standard WPF mediaelement ok bit it too limited compared to this control.

If i do use it do i need to use some kind of dispatcher.invoke to send commands to each player on separate threads If yes a code example would help ?
If it is experimental what kind of problems should i look out for ?
Do i really need to use it anyway ?
any advice appreciated

thanks
*

## Issue Categories
 - [X ] Question

## Version Information

 - [ ] NuGet Package *Release 4.1.280*

**Comment by mariodivece** [comment]
No you should not really use it unless you want to dig into the source of `FFME` and fully understand the implications and usage. That is what I mean when I state that this is an experimental, unsupported feature.

**Comment by JosephGarrone** [comment]
Just to chime in on the use of `EnableWpfMultiThreadedVideo`, please leave it in. My use case involves ensuring that the UI does not lock up when streaming multiple videos. Switching that value from `false` to `true` has ensured that the UI still remains responsive.

**Comment by mariodivece** [comment]
yeah I'll leave it in. It's certainly useful for some scenarios.
