### ISSUE TITLE
What is the best way to do a fast/normal reverse play

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#363]
# Issue Title (*What is the best way to do a fast reverse play*)

*What is the best way play to play a video in reverse ? in both normal speed and at the value set for the speed ratio parameter.
So play in reverse at normal play speed and fast "forward" in reverse at the speed ratio set.
I was thinking to use a timer to subtract the position value  by the Timespan  equivalent number of frames for the speed i want, So the timer would fire every 250ms or so.
Is that my best option ?

I did read something in the issues section about a play in reverse smoothly feature but i cant find it in the player properties.

any advice appreciated thanks *

## Issue Categories
 - [ ] Question

## Version Information

 - [ ] NuGet Package *Release 4.1.280*

**Comment by mariodivece** [comment]
you can call the await `StepBackward` method repeatedly on a timer. -- or as you stated, subtract the position. Please note that if a seek operation is required to step backward, and you don't have a small enough GOP setting in your (I Frames) then it will take some time to display the previous frame. Playing backwards is highly dependent on the GOP setting of the encoded video and your processing power.
