### ISSUE TITLE
MediaElement starts with wrong start time

### ISSUE THREAD

**Issue by shazam19** [unosquare/ffmediaelement#365]
# *MediaElement starts with wrong start time on opening media*

I just wanted to bring your attention to it. When I open my ts video using MediaElement it shows startTime 5h:15m although when the video length is 45 minutes. After looking at the source code I realized it's because ffme now uses startTime retrieved from ffmpeg which is a wrong value.

![image](https://user-images.githubusercontent.com/7633056/55308730-6e51a380-547d-11e9-98b8-170376be4bf4.png)

Here's the [video file](https://jmp.sh/12KahAA)

## Issue Categories

 - [ ] Question

## Version Information

 - [ ] NuGet Package *2.8*

**Comment by mariodivece** [comment]
Hey... the start time is just that -- the start time that is reported by the container format. If in your application you wish to go from 0 to Duration, simply offset everything by subtracting the start time. When reporting a position, for example, just use a value converter that will do the offset -- just giving you ideas here. 

If Start time were always 0 then what would the point be of having the property? :)
Related properties:
StartTime
EndTime
Duration

**Comment by shazam19** [comment]
> If Start time were always 0 then what would the point be of having the property? :)

True, but if the start time is greater than the duration, doesn't that indicate something is off? How would ffme behave in that case?

**Comment by mariodivece** [comment]
So you are saying that you can't have a stream that starts at time 20s and has a duration of 10s? That would mean the start time is 20s, the duration 10s, and the end time would be 30s. Make sense? FFME behaves as expected. Check out the sample app.

**Comment by qinjianzhanqing** [comment]
meaningful，Sometimes give the film does not meet the requirements, only need to broadcast interval period。The SDK can achieve this function？
