### ISSUE TITLE
MediaElement.Position does not update when the file is playing

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#367]
*MediaElement.Position does not update when the file is playing*

With the latest ffmediaelement nuget package, the MediaElement.Position doesn't seem to be updated while my audio files are playing.

## Issue Categories

 - [x] Bug

## Version Information

 - [x] NuGet Package *2.90*

## Steps to Reproduce

```cs
var mediaElement = new MediaElement();
mediaElement.LoadedBehavior = MediaPlaybackState.Play;
mediaElement.PositionChanged += (s, e) => Debug.WriteLine(mediaElement.Position);

await mediaElement.Open(new Uri(audio_file_path));
```

You should see in the Output window pane that `mediaElement.Position` is not updated.

Thanks.

**Comment by mariodivece** [comment]
does this happen with files with only audio or also with files having both audio and video?

**Comment by mariodivece** [comment]
That's weird. I just tried it and position updates just fine...

**Comment by mariodivece** [comment]
I did discover a bug with audio-only files where start time is always indeterminate.

**Comment by mariodivece** [comment]
Any further comments before I close?

**Comment by CyberSinh** [comment]
I will test the fix tonight (Paris time). 
Could you release a "bug fix" nuget package? If this is not possible, I will compile my own build from master for testing.

**Comment by mariodivece** [comment]
Sure. Test it and let me know if it works. If it does I'll publish a pre-release package in the next couple of days.

**Comment by CyberSinh** [comment]
I cannot build `ffmediaelement` because I cannot load the `FFME.Windows` project in Visual Studio. I have tried with Visual Studio 2017, Visual Studio 2019 (RTM) and with .Net core SDK (2.2 and 3.0 preview 3).

The error message is:

```
E:\Home\Temporary\Development\GitHub\effmediaelement\Unosquare.FFME.Windows\Unosquare.FFME.Windows.csproj : Error: The project file cannot be opened by the project system, because some critical imports are missing or the referenced SDK kit is not found.

Detailed information:
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk.WindowsDesktop\Sdk not found. Verify that a sufficiently recent.NET Core SDK is installed and/or increase the version specified in global.json.
```

Did I miss a prerequisite to compile the project?
Thanks.

**Comment by mariodivece** [comment]
Tools-> Options and then:
![image](https://user-images.githubusercontent.com/351978/55441155-1000ef80-5567-11e9-82b8-f79da794ccff.png)

Does that work?

**Comment by CyberSinh** [comment]
It is this option that was missing. Good point!

But unfortunately, the problem is still present with the last commit. I have made a sample repro showing the issue, that you can download here: [Download sample repro](https://www.dropbox.com/s/r5efzun30r4gcv1/TestWpf1.zip?dl=0)

Thanks.

**Comment by mariodivece** [comment]
Can you try with a simpler app? I tried loading yours but there is too much noise to determine if it's your code or FFME -- I'm attaching the simplest possible code. I tested with current NuGet release 2.90 and it's fine.
[FFMEPositionChanged.zip](https://github.com/unosquare/ffmediaelement/files/3036362/FFMEPositionChanged.zip)

**Comment by CyberSinh** [comment]
Hi Mario. I could reproduce the issue with your simpler app.

Just changed the line from:
```cs
media.PositionChanged += (s, e) => { label.Content = $"Position: {e.Position}"; };
```
to:
```cs
media.PositionChanged += (s, e) => { label.Content = $"Position: {media.Position}"; };
```

And you can see the `Position` is not updated as expected in your label control.

Hope this helps.

Thanks!

**Comment by mariodivece** [comment]
I just tried and it updates for me...
I tried:
```csharp
media.PositionChanged += (s, e) => { label.Content = $"Position- Media: {media.Position}; Event: {e.Position}"; };
```

and I see:
![image](https://user-images.githubusercontent.com/351978/55513419-dab9d780-5622-11e9-843a-b8a19b84ba8c.png)

**Comment by CyberSinh** [comment]
As I use `MediaElement` for audio playing only, I don't need any visual control.
And the issue seems to happen only when the `MediaElement` control is not shown on screen.
There was no problem with the previous release to get `Position` from an hidden `MediaElement` control. 

Comment the following line to view the issue by yourself:
```cs
//panel.Children.Add(media);
```

**Comment by mariodivece** [comment]
then that is a very different problem. You see, WPF controls should not be `IDisposable`. They should instead handle `Loaded` and `Unloaded` events to perform cleanup. The `Loaded` event is fired whenever a WPF control is attached to a visual stree and the `Unloaded` event is fired whenever the control is detached from a visual tree. The new more compliant implementation of this `MediaElement` control handles those events properly. The possible solution would be to hide the control in the background. By default it does not render anything. You could also set its Vivibility property to Hidden.

**Comment by mariodivece** [comment]
I am considering starting the propertyupdatesworker before the loaded event has occurred... I will consider that also.

**Comment by CyberSinh** [comment]
Using a "fake" control is not a very elegant solution. But I can understand your willingness to comply with standard WPF development rules.  In any case, this change in behaviour is clearly a breaking change.

According to [MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.unloaded?view=netframework-4.7.2), `Unloaded` event is not the best place to perform cleanup code. 

> If you place cleanup code within a handler for the Unloaded event, such as for a Window or a UserControl, it may not be called as expected.

There is [no obvious solution](https://stackoverflow.com/questions/502761/disposing-wpf-user-controls) to fix the problem.

Starting the propertyupdatesworker before the loaded event has occurred could be a solution for initializing, but how could we call the cleanup code in no GUI scenario? Perhaps you could add public method to manually control the initialization and the cleaning process of the component in no GUI scenario?

**Comment by mariodivece** [comment]
Here's what I did: When the control gets instantiated, it immediately starts the property updates worker so you don't have to attach it to the UI. but if you attach it to a visual tree and then remove it, it will close the media and start the property updates worker once again. This seems to work for all scenarios. Give it a test with the latest master commit and let me know if it works for you.

**Comment by CyberSinh** [comment]
The Position property works again in no GUI scenario. 
Should I call specific code for cleaning up the control (as `Unloaded` event will never be called)?
Thanks.

**Comment by mariodivece** [comment]
No. Simply call close on the mediaelement.
