### ISSUE TITLE
stop play automatically

### ISSUE THREAD

**Issue by lmx01** [unosquare/ffmediaelement#374]
# how to let the video not play automatically?
I want to start playing when I click play button,and i set the LoadedBehavior like below,but it didn't work?Can you help me?thanks
## Issue Categories
 - [ ] Question

### XAML
 <ffme:MediaElement x:Name="MediaView" Grid.Row="0" Width="200" Height="auto" 
                           Source="{Binding Path=MediaUrl,RelativeSource={RelativeSource Mode=FindAncestor, 
                                    AncestorType=local:HappyMedia, AncestorLevel=1}}" 
                           Background="Gray" LoadedBehavior="Manual" ScrubbingEnabled="False"/>

**Comment by mariodivece** [comment]
Have you tried LoadedBehavior = Stop?

**Comment by lmx01** [comment]
Yes, I have tried it, but still  not!

**Comment by lmx01** [comment]
Hi，I found it's the "Source" value problem.When I use the swf format, it will have this problem, others will not.Do you know how to solve it? Thanks.
This is my swf url:http://i.xiao84.com/en-yinbiao/x-48yinbiao/kouxing/1.sw

**Comment by mariodivece** [comment]
The container format cannot pause or seek. 
![image](https://user-images.githubusercontent.com/351978/56426931-a6c7ee80-627f-11e9-8080-f64a5591f8c8.png)

**Comment by lmx01** [comment]
ok,thank U!
