### ISSUE TITLE
Dynamic Changes to Video and Audio Filters

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#375]
# Issue Title (*Video Filter change*)

I have managed to get video filter change to partly work with this control.
The code below works as an example to change the video contrast.
The slider bar value is added to the filter string, the mediaelement ChangeMedia() is used to fire the control media changing event as below.
So this works if i change the slider one tick at time left or right at a time. As long as i do it slowly it works and the contrast is changed.
But if i slide the thumb of the slider bar left or right in normal fashion one uses a slider bar the application just exits. There is no exception or error that i can trap. Putting try catch around the code does not catch anything at all. The program just exists. The output window shows: The program '[10428] Tools.exe' has exited with code 3 (0x3).

after some experimenting i think the error is based around calling the ChangeMedia(); event several times in rapid succession. Because the problem still occurs if there is no code in the MediaPlayer_Changing event so i dont think its a problem with applying the filter values.
It seems to be purely calling the Changing event in rapid succession as you would get buy using a slider bar.

Can anyone suggest any thing i might try to correct this

## Issue Categories

 - [X ] Not sure

## Version Information

 - [ ] NuGet Package *4.1.290*

## Steps to Reproduce

 1. Call ChangeMedia() on the control in rapid succession

## Expected Results

 - program will exit and stop running with no errors or exceptions visible
### C#
```private async void TbeVolumeLevel_ValueChanged(object sender, DevExpress.Xpf.Editors.EditValueChangedEventArgs e)
        {
           await _PlayerList[0].UpdateVideoFilter("eq=contrast=" + e.NewValue.ToString());
        }
	public async Task<bool> UpdateVideoFilter(string sFilter)
        {
            Filter =  sFilter;
            var x = await MediaPlayer.ChangeMedia();
            return x;
        }
 	private async void MediaPlayer_Changing(object sender, MediaOpeningEventArgs e)
        {
	   if (e.Options.VideoStream is StreamInfo videoStream)
            {
		 e.Options.VideoFilter = Filter ;
	    }
	}
```

**Comment by mariodivece** [comment]
yeah, like I have shared with you in the past, ChangeMedia is a "heavy" operation. Maybe try adding an MRES that sets when MediaChanged fires and that Waits before calling changemedia. See if that works.

**Comment by mariodivece** [comment]
Real-time video filter changes are now possible without calling ChangeMedia() -- It is an unsupported usage but I have updated the Video Filter-graph to recreate itself when the filter string changes. You can test it using the reference player with keys Y, H, U, J, I, and K. This will dynamically change the contrast, brightness and saturation.

Next, I will make the audio filter string dynamic as well on the `AudioComponent.cs`

**Comment by mariodivece** [comment]
You can also now test dynamic audio filters by pressing the E key on the provided reference media player.
