### ISSUE TITLE
Recording while playing video stream

### ISSUE THREAD

**Issue by h181186** [unosquare/ffmediaelement#378]
Hello!

I am making an application using FFME, and I need to be able to play a DirectShow camera source in an FF MediaElement while saving it to a local file. My current soultion is to use FFmpeg to stream the video over UDP while saving it to file, but this is causing some latency and I want my app to be close to realtime. Is there a way to do this directly in FFME, so that I can skip the streaming step?
I read in the README that it should be possible to record in FFME, but I cannot find this functionality.

**Comment by mariodivece** [comment]
Recording is in fact supported. There is an example in the sample application provided with the source code. Check out: https://github.com/unosquare/ffmediaelement/blob/e5f8b3e466d35f1769fdf87c7f74a7bc22df6118/Unosquare.FFME.Windows.Sample/Foundation/TransportStreamRecorder.cs#L1

If you run the sample application and press the `W` key it will start recoding the stream. Press `W` again and it will stop. The example above simply copies packets to an output stream. Transcoding audio and video is also possible but you will need to be familiar with doing this using the FFmpeg API.

See: https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/transcoding.c
