### ISSUE TITLE
Await seek, position do not change immediately

### ISSUE THREAD

**Issue by RyanYANG52** [unosquare/ffmediaelement#379]
# Issue Title (*Await seek, position do not change immediately*)

Similar to #234 , I'm trying out the new release, find out some behavior related to `Seek` may not be intentional. I created a test project, please take a look. Sample video is also included in the project. https://github.com/RyanYANG52/VideoPlayerTest

In the sample project, I didn't use MediaElement's position as clock source, because I need to sync the video player's clock with other 3D player, so I use a Stopwatch as an unified clock. When stopwatch position changed, it will check the offset time between different player, if offset is too large is will correct the clock time.

Seeking video while playing will cost some time, so I need to stop clock, and await seek completed, then restart the clock.

1. https://github.com/RyanYANG52/VideoPlayerTest/blob/master/VideoPlayerTest/VideoPlayerTest/MainWindow.xaml.cs#L96 
After I call `await _player.Seek(time)`, read `_player.Position` immediately, sometimes it will still be the old position.
2. Seeking cost more time compare to 2.6 version, maybe because sometimes VideoPlayer will show a sequence of Image during Seek operation, even when VideoPlayer is **paused** which I don't think it's by design.

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *3.0*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

**Comment by Ocimandias** [comment]
I have the same effect seince 4.1.280 version and haven't been able to restore the expected behaviour except restoring by 4.0.270 release.
Seems like seeking triggers the render methods while decoding to reach the new position.
The issue appears on different video sources and formats.

**Comment by mariodivece** [comment]
did you guys try disabling fluid seeking?
https://github.com/unosquare/ffmediaelement/blob/e5f8b3e466d35f1769fdf87c7f74a7bc22df6118/Unosquare.FFME/Common/MediaOptions.cs#L172

**Comment by RyanYANG52** [comment]
Hi, I tried setting `IsFluidSeekingDisabled = true`, seeking will only show one Image.  Thanks.
But to get Position immediately after `await Seek`, still be the old position, I have to add `Position = time;` after, to make it work. https://github.com/RyanYANG52/VideoPlayerTest/blob/7aebda8172b5cc18ab3636f7ca99702c6d716f0e/VideoPlayerTest/VideoPlayerTest/Players/FFMEVideoPlayer.cs#L110

**Comment by mariodivece** [comment]
The real issue is that since the Position property is a DependencyProperty, it may take a few ms (next UI dispatcher frame) to get updated with the latest value coming from the `MediaEngine`. Let me see if I can find a way to immediately update the position after the seek

**Comment by Ocimandias** [comment]
> did you guys try disabling fluid seeking?
> https://github.com/unosquare/ffmediaelement/blob/e5f8b3e466d35f1769fdf87c7f74a7bc22df6118/Unosquare.FFME/Common/MediaOptions.cs#L172

It works fine for me.
Any improvement on position change update will be helpful.
Thanks a lot

**Comment by mariodivece** [comment]
Note to self: could add ActualPosition property to read position directly from the media engine.

**Comment by mariodivece** [comment]
you can now use the `ActualPosition` property. Remember Position is a dependency property and it has a synchronized update cycle. With the new `ActualPosition` property you will now be able to read the engine's position directly.

**Comment by Ocimandias** [comment]
Great! Thanks a lot Mario.
