### ISSUE TITLE
Request for new sample code to be vs2017 compatible

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#381]
# Issue Title (*Request for new sample code to be vs2017 compatible *)

*Respectfully request that sample code v2.80 on wards be compatible to open in vs2017.
I see the lib itself has namespace changes from this version on, and the libs themselves are ok in vs2017 but i use the sample code as a how to do things example. Only have vs2017 and have .net 4.72 installed but cant open any of the new sample code projects to see new version how to. 2 of the 3 projects wont load. How to open in 2017 instructions or 2017 compatible would be appreciated. .*

## Issue Categories

 - [ ] Bug
 - [X] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [3.0 ] NuGet Package *Enter Version Number Here*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Load 3.0 source code into vs2017

## Expected Results

 - 2 out of 3 projects wont load in vs2017 for version 3.0

**Comment by mariodivece** [comment]
Sorry, this is not up to me. This is up to MS. See:
https://github.com/dotnet/core-sdk/issues/213

I suggest you download and install VS 2019 preview or VS 2019 RTM (and enable dnc previews).
