### ISSUE TITLE
How to use NewTek NDI

### ISSUE THREAD

**Issue by qinjianzhanqing** [unosquare/ffmediaelement#382]
![error](https://user-images.githubusercontent.com/20415253/56864829-c71f4800-69f9-11e9-8b60-f2a89b9ec8b2.jpg)

**Comment by mariodivece** [comment]
Is your build of ffmpeg ndi compatible?

**Comment by mariodivece** [comment]
Search for related issues and please add what you have tried and how you fixed it or what you tried

**Comment by qinjianzhanqing** [comment]
> Is your build of ffmpeg ndi capable?

No, I use ffmpeg website to download the packages。Let me try build of ffmpeg ndi capable
