### ISSUE TITLE
How to Play in a Specified Interval？

### ISSUE THREAD

**Issue by qinjianzhanqing** [unosquare/ffmediaelement#386]
I want to play a Video form A point() to B point （For example, starting with 3S，End in 10s）and Loop Playback this。

**Comment by mariodivece** [comment]
what have you tried? How would you do it with the standard MediaElement control?

**Comment by Ocimandias** [comment]
> I want to play a Video form A point() to B point （For example, starting with 3S，End in 10s）and Loop Playback this。

Dear qinjianzhanqing,
I do that following this steps

class Clip()
{
public bool Loop;
public int Start;
public int End;
}

void PlayClip(Clip oClip)
{
meplayer.Position=Clip.Start;
meplayer.Play();
}

Bind meplayer.Position to ProgressBar or Label
On ProgressBar.TargetUpdated event handler

Check if meplayer.Position is inside the Clip
if not and Clip.Loop set meplayer.Position=Clip.Start and you will have the effect until pause/stop

Hope this helps,

**Comment by qinjianzhanqing** [comment]
thinkyou

**Comment by qinjianzhanqing** [comment]
> > I want to play a Video form A point() to B point （For example, starting with 3S，End in 10s）and Loop Playback this。
> 
> Dear qinjianzhanqing,
> I do that following this steps
> 
> class Clip()
> {
> public bool Loop;
> public int Start;
> public int End;
> }
> 
> void PlayClip(Clip oClip)
> {
> meplayer.Position=Clip.Start;
> meplayer.Play();
> }
> 
> Bind meplayer.Position to ProgressBar or Label
> On ProgressBar.TargetUpdated event handler
> 
> Check if meplayer.Position is inside the Clip
> if not and Clip.Loop set meplayer.Position=Clip.Start and you will have the effect until pause/stop
> 
> Hope this helps,

Thinks!
