### ISSUE TITLE
Position property starts at value of start time property. Is this normal ?

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#387]
# Position property starts at value of start time property. Is this normal ?

Is it normal for the control position property to start at the same value as the start time property.

## Issue Categories

 - [X ] Question

## Version Information

 - [4.1.3] NuGet Package *Enter Version Number Here*

Hello,
i have come across an unexpected issue that i think may be the same as issue
https://github.com/unosquare/ffmediaelement/issues/365

In that i have a media file when loaded the position property of the control starts at 00:00:10 seconds instead of 00:00:00. Looking around i found a start time property also returns 00:00:10 seconds and the same under FFMPEG.

My question is, is it normal for the position property to start at the Start time of the media instead of zero. 
Is there a flag or property to make position start at 00:00:00 or do i need to always subtract the start time value ?
Im trying to sync the media to a timer that needs to start at 0.

thanks, this controls is great.

cheers

**Comment by mariodivece** [comment]
Correct. FFME cannot change the properties of the media stream being loaded by ffmpeg. If the stream says it starts at 10 seconds, either update you timer to also start at 10 seconds or change the logic to always subtract the media start time. This behavior comes directly from ffmpeg -- not FFME itself.

**Comment by manity42** [comment]
So does one have to apply this same start time offset when you use the seek function as well ?

**Comment by mariodivece** [comment]
correct. The seek parameter specifying the timestamp should be provided in stream-time
