### ISSUE TITLE
Video do not show,but no error Message show

### ISSUE THREAD

**Issue by zhongbodong** [unosquare/ffmediaelement#389]
# Why Video not show,and no message show

*i have do all steps as readme.txt give me,but when i start program ,there is nothing hapen,do i miss something?.*

## Issue Categories
 - [x] Question

## Version Information

 - [x] NuGet Package *FFME.Windows 4.1.300*

## Steps to Reproduce

 1. download a compatible build from the wonderful Zeranoe FFmpeg Builds site: (https://ffmpeg.zeranoe.com/).Copy all of them to a folder  as (c:\ffmpeg)
![image](https://user-images.githubusercontent.com/28446826/57667622-d4ae1200-7636-11e9-8735-d04ef3166142.png)
 2. set Unosquare.FFME.Library.FFmpegDirectory = @"path to ffmpeg binaries from the previous step";
![image](https://user-images.githubusercontent.com/28446826/57667652-f4ddd100-7636-11e9-9a61-55a7113d2810.png)

 3. In my MainForm.xaml, add the namespace: xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
   And then add the FFME control in my window: <ffme:MediaElement x:Name="Media" Background="Gray" LoadedBehavior="Play" UnloadedBehavior="Manual" />
  
![image](https://user-images.githubusercontent.com/28446826/57667744-48e8b580-7637-11e9-9342-258ca498ef58.png)

## Expected Results

 - 
![image](https://user-images.githubusercontent.com/28446826/57681200-d4773c00-7661-11e9-8e8b-28b7f23eb60b.png)

 
 
### XAML
```xml
<MainWindow>
  <Grid>
        <ffme:MediaElement x:Name="Media"  LoadedBehavior="Play" UnloadedBehavior="Manual" />
    </Grid>
</MainWindow>
```

### C#
```csharp
  Unosquare.FFME.Library.FFmpegDirectory = @"C:\ffmpeg";
  Media.Source = new Uri(@"C:\ffmpeg\wuyawang.mp4");
```

**Comment by sam8890** [comment]
me too

**Comment by mariodivece** [comment]
Probably the architecture of your app is not matching the architecture of the ffmpeg binaries. 
Questions:
1. does the sample application work?
2. have you tried the zeranoe FFmpeg binaries for x86 AND x64?
3. What arror messages do you see in the Output window?

**Comment by sam8890** [comment]
Unable to open example envy
![20190516101134](https://user-images.githubusercontent.com/37574821/57821462-2e434780-77c3-11e9-8b06-089e5e74f1f6.png)

**Comment by sam8890** [comment]
![20190516101405](https://user-images.githubusercontent.com/37574821/57821550-8ed28480-77c3-11e9-81c0-a3216b762728.png)
![20190516101433](https://user-images.githubusercontent.com/37574821/57821555-91cd7500-77c3-11e9-9d48-5602189b2f3b.png)
![20190516101452](https://user-images.githubusercontent.com/37574821/57821561-93973880-77c3-11e9-8d2b-2dc00633c81d.png)
![20190516101513](https://user-images.githubusercontent.com/37574821/57821560-92fea200-77c3-11e9-986d-ba6b2d34522a.png)

**Comment by mariodivece** [comment]
None of the screenshots is showing the console output. Also as stated in the documentation you need vs 2019 to open the sample. Vs 2019 community works and it's free

**Comment by sam8890** [comment]
yes, I'm using vs 2019 to open the sample
![20190516102138](https://user-images.githubusercontent.com/37574821/57821815-7f077000-77c4-11e9-9bda-2ac88af89a9f.png)

**Comment by sam8890** [comment]
this is console output
![QQ截图20190516102311](https://user-images.githubusercontent.com/37574821/57821843-a1998900-77c4-11e9-89d4-4328bcf93154.png)

**Comment by mariodivece** [comment]
I can't reproduce the issue. Here's the most basic sample I could write in 30 seconds and it works just fine.
[FFmeBasicSample.zip](https://github.com/unosquare/ffmediaelement/files/3185251/FFmeBasicSample.zip)

**Comment by sam8890** [comment]
ooh my god,why is it still did not work,I don't know what went wrong
![QQ截图20190516112454](https://user-images.githubusercontent.com/37574821/57824395-7d8e7580-77cd-11e9-9e31-888db86262c4.png)

**Comment by mariodivece** [comment]
Try replacing the OnStartup method in App.xaml.cs
What is the console output?

```csharp
        protected override void OnStartup(StartupEventArgs e)
        {
            Library.FFmpegDirectory = @"c:\ffmpeg";
            Library.LoadFFmpeg();
            MediaElement.FFmpegMessageLogged += (s, ev) =>
            {
                System.Diagnostics.Debug.WriteLine(ev.Message);
            };
            base.OnStartup(e);
        }
```

**Comment by sam8890** [comment]
![QQ截图20190516113304](https://user-images.githubusercontent.com/37574821/57824672-67cd8000-77ce-11e9-8915-2f7e1a576f8b.png)
![QQ截图20190516113356](https://user-images.githubusercontent.com/37574821/57824704-7fa50400-77ce-11e9-8249-a63d51bdd408.png)

**Comment by mariodivece** [comment]
did you download the 32-bit or 64-bit version?

**Comment by sam8890** [comment]
use ffmpeg-4.1.3-win64 
![QQ截图20190516123503](https://user-images.githubusercontent.com/37574821/57826721-1e356300-77d7-11e9-8fa0-09109683a229.png)

**Comment by sam8890** [comment]
I downloaded it here before
![QQ截图20190516123619](https://user-images.githubusercontent.com/37574821/57826759-3efdb880-77d7-11e9-8fc6-f3820cc4d61b.png)

**Comment by sam8890** [comment]
Thank you ever so much

**Comment by mariodivece** [comment]
sure.

**Comment by zhongbodong** [comment]
> use ffmpeg-4.1.3-win64
> ![QQ截图20190516123503](https://user-images.githubusercontent.com/37574821/57826721-1e356300-77d7-11e9-8fa0-09109683a229.png)



> sure.

it works very well,thank you  very much ,I used https://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-4.1.3-win32-shared.zip
![image](https://user-images.githubusercontent.com/28446826/57843344-aed46900-7800-11e9-87a6-ab50bacd0857.png)
