### ISSUE TITLE
Implement MediaBlockRendering Event

### ISSUE THREAD

**Issue by whamma** [unosquare/ffmediaelement#39]
I want to show audio level meter in my application.
Thank you.

**Comment by mariodivece** [comment]
The coming MediaBlockRenderingEvent will contain Audio or Picture data in the event arguments.
You will be able to read or change the raw byte data that is being rendered. Under this event you can potentially read the samples, compute the averages and get a loudness signal bound to some notification property for each channel to ultimately display the VU meter. Implementing the event will be high priority. Implementing the VU meter in the sample will be low priority.

**Comment by MrBean2016** [comment]
I need to extract frames, is this function intended for this? When is the 2.0 Milestone planned?
I was thinking of coding one that can pull frames from the MediaBlockBuffer and put them in a separate queue

**Comment by mariodivece** [comment]
Correct. It will be an event providing a single MediaBlock upon rendering, where you can copy or modify the buffer directly but I am still working on making the reading/decoding/rendering more efficient at this point and I have not gotten to this one yet.
I don't know exactly when 2.0 will be released because I am doing this for fun but you can see that I continue to make large progress! Thanks for all the input, feedback and motivation!

**Comment by mariodivece** [comment]
New events have been implemented Please see the reference player for examples.
It is now possible to subscribe to RenderingVideo, RenderingAudio and RenderingSubtitles events, extract the data, and even modify it before it is rendered. Please check it out and close this issue if this is what was needed.

For VU meters, you could simply read a few sample blocks, and average them out to display a "loudness" level. But you will have to do so on your own.

**Comment by mariodivece** [comment]
I am closing this issue now. The VU meter example is looking great too. :)

**Comment by MrBean2016** [comment]
Thank you, this is really good!
So this is a pure recreational project, you are working so hard. with this. I must say that the coding standard and quality is very high. Good work and I if you need some assistance, please let me know.

**Comment by mariodivece** [comment]
Thanks @MrBean2016 !
Would you like to contribute for example, issue #54 via a Pull Request?

**Comment by MrBean2016** [comment]
Sure I can look at #54 to see if I understand what to do.
