### ISSUE TITLE
How to set optimal playing file located over network path?

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#391]
# Issue Title (*How to set optimal playing file located over network path?*)

*Is there a way to improve playing a file stored on a network path. This is not a streamed file, but just play a file stored on a network location. I see there is a buffering property to track how much is being buffered. is there an option to increase buffering or reading larger chunks maybe or caching portions locally perhaps. Would creating an indexing file like in the sample help ?*

any advice appreciated.

## Issue Categories

 - [ *] Question

## Version Information

 - [ 4.1.3] NuGet Package *Enter Version Number Here*

**Comment by mariodivece** [comment]
Have you tried setting https://github.com/unosquare/ffmediaelement/blob/c17fca9836880725f071ce26f863548597708487/Unosquare.FFME/Common/ContainerConfiguration.cs#L35

using:
https://www.ffmpeg.org/ffmpeg-protocols.html#cache

for example, ProtocolPrefix = "cache";

**Comment by manity42** [comment]
Thanks for the suggestion.
Scanning your sample code i found an example where the ContainerConfiguration class was used, and applied this in the
private void FFMEPlayer_MediaInitializing(object sender, MediaInitializingEventArgs e)
      {
        e.Configuration.ProtocolPrefix = "cache";
       }
I can see it is enabled because now in the run time directory of the application, weather local or network stored a cache file is auto created. The cache file has the naming convention style  like this ffcachepyquT7. 

Is there a property i can examine after video load that holds this cache file name ?
Otherwise i will need to do a file delete on app close based on deleting files based on ffcache*.

At this time its hard to see how much of a change there is with this enabled, but i will let it run like this and see. Would you have any additional suggestions please for other properties i could experiment with to improve on this, just in case ?

thanks heaps.

**Comment by mariodivece** [comment]
Another suggestion is to implement your own input stream. It's certainly an advanced usage but it gives you full control over byte reading logic. See:
https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME.Windows.Sample/Foundation/FileInputStream.cs

**Comment by manity42** [comment]
Thanks.
Is there a way to get the name of the specific cache file created when a video is loaded ?
That way i can delete it on video close.

**Comment by mariodivece** [comment]
not sure. This is outside of the scope of this project but you could ask in the ffmpeg project (maybe?).
I am closing this one. Feel free to provide further feedback if you find a solution.
