### ISSUE TITLE
How to open WebDAV path

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#393]
# What is the recommend way to open a WebDAV path?

*I'm trying to open a WebDAV path like `\\192.168.1.18@8080\DavWWWRoot\Music\test.mp3` with ffmediaelement but all all my attempts fail.*

## Issue Categories

 - Question

## Version Information

 - latest master

### C#
I tried this code...

```csharp
string path = @"\\192.168.1.18@8080\DavWWWRoot\Music\test.mp3"
await mediaElement.Open(new Uri(path));
```

...but it throws UriFormatException because of `The hostname could not be parsed` in `Uri`  constructor. I tried to 'cheat' the Uri class by setting `UriKind.Relative` but I get the following error: `This operation is not supported for a relative URI`.

It is a pity to be blocked by the `Uri` class because running `ffplay.exe \\192.168.1.18@8080\DavWWWRoot\Music\test.mp3` plays correctly the file.

I also tried to translate the path to a more standard http url:

```csharp
string path = @"\\192.168.1.18@8080\DavWWWRoot\Music\test.mp3"
if (path.Contains("DavWWWRoot")) path = "http:" + path.Replace('\\', '/');
await mediaElement.Open(new Uri(path));
```

But ffmpeg/ffplay rejects the path (`Protocol not found - I/O error - Unknown error`).

So, what is the best way to open a such path with ffmediaelement/ffmpeg?

Thanks.

**Comment by mariodivece** [comment]
How do you open the same stream using ffplay.exe? Could you please provide full command line arguments?

**Comment by CyberSinh** [comment]
`ffplay.exe \\192.168.1.18@8080\DavWWWRoot\Music\test.mp3` was the full command line used.

**Comment by mariodivece** [comment]
Could you please send me the output of ffprobe using that url?

**Comment by mariodivece** [comment]
have you tried: @"http://192.168.1.18:8080/DavWWWRoot/Music/test.mp3"

**Comment by CyberSinh** [comment]
Yes, the path is correctly played with `http://192.168.1.18:8080/DavWWWRoot/Music/test.mp3`.

I now use the following code for converting WebDAV path to standard Uri. I hope it could helps others.

```csharp
private static string ConvertWebDavPath(string path)
{
      // "\\192.168.1.18@8080\DavWWWRoot\Music\test.mp3" -> "http://192.168.1.18:8080/DavWWWRoot/Music/test.mp3"

      if (!path.Contains("DavWWWRoot"))
         throw new ArgumentException("The argument is not a WebDAV path.", nameof(path));

      var sb = new StringBuilder(path);
      if (path.Contains("@SSL"))
      {
           sb.Replace("@SSL", null);
           sb.Insert(0, "https:");
       }
       else
          sb.Insert(0, "http:");

       sb.Replace('\\', '/');
       sb.Replace('@', ':');

       return sb.ToString();
}
```
