### ISSUE TITLE
Will not stream rtsp:// from live555 testH264VideoStreamer

### ISSUE THREAD

**Issue by elbrandt** [unosquare/ffmediaelement#394]
# FFME will not stream from certain rtsp:// (udp multicast?) streams

I am trying to stream rtsp:// h.264 Elementary Stream from the live555 server. When I run live555's 'testOnDemandRTSPServer' (unicast I believe?), I can stream the rtsp:// uri properly in FFME.

However, when I stream the same rtsp:// h.264 Elementary Stream from live555's 'testH264VideoStreamer (udp multicast I believe?), I get this error in the VS output window:

```
Exception thrown: 'Unosquare.FFME.Common.MediaContainerException' in ffme.win.dll
Exception thrown: 'Unosquare.FFME.Common.MediaContainerException' in ffme.win.dll
[29:53.877 | ERR | FFmpeg.Log          ] [rtsp @ 000001FD46E38940] method SETUP failed: 461 Unsupported Transport
[29:53.885 | ERR | Container           ] Fatal error initializing MediaContainer instance.
MediaContainerException: Could not open 'rtsp://192.168.56.1:8554/testStream'. Error -135: Error number -135 occurred
Stack Trace:
   at Unosquare.FFME.Container.MediaContainer.StreamInitialize() in C:\proj\VA\Software\ffmediaelement\Unosquare.FFME\Container\MediaContainer.cs:line 703
Exception thrown: 'Unosquare.FFME.Common.MediaContainerException' in ffme.win.dll
```

Streams from both live555 sample programs mentioned above will play in VLC Player.

I'm happy to help debug this issue if I have a starting place to work from.  It is our goal to stream using UDP Multicast to achieve the lowest possible latency on local networks for 1-4 client subscribers.

Any assistance you can provide in getting this to work in FFME, which looks like a very awesome, well written control, would be appreciated.

Thanks,
-Eric.

## Issue Categories

 - [ X  ] Bug
 - [ X ] Feature Request
 - [ X ] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
What are the full command-line arguments you use with ffplay.exe?
Remember, this control is not based off VLC libraries.

**Comment by mariodivece** [comment]
Since there was no firther feedback here I'm closing this issue. Feel free to post full ffplay.exe command line arguments.
