### ISSUE TITLE
Media force to closed if user changed docking window layout using AvalonDock

### ISSUE THREAD

**Issue by longlongago-k** [unosquare/ffmediaelement#395]
# Media force to closed, if user changed docking window layout using AvalonDock
I attached FFMediaElement into AvalonDock UIs to achieve docking behavior.
After I updated NuGet version 4.0.290 or newer.  When user changed docking layout, then, FFMediaElement forced to close video. So I tried to reopen the same video, but binding system has broken and it's hard to recover. 

I really appreciate if resolve this issue which depends on the external library.

## Issue Categories
 - [x] Bug?
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information
 - [x] NuGet Package 4.1.290 or newer

## Steps to Reproduce
 1.  Attach FFMediaElement to AvalonDock system in the xaml.
 2.  Change docking UI.

## Expected Results
 - MediaElement keep to video opening.

**Comment by mariodivece** [comment]
I am aware of this issue. If you use a standard MediaElement, what happens?

**Comment by longlongago-k** [comment]
I tried both standard and this FFME by new sample project with another PC as following procedures.
This issue reproduced.

1)Create two LayoutAnchorblePane(Dockable pane in AvalonDock).
2)One pane has standard MediaElement. The other has FFME.
3)Open & Play video.
4)Change docking layout.

**Comment by mariodivece** [comment]
right... what happens with each?

**Comment by longlongago-k** [comment]
Standard MediaElement keep playing. But FFME closed video and diappear video image.

**Comment by mariodivece** [comment]
I see... I think I need to change the behavior of UnloadedBehavior

**Comment by mariodivece** [comment]
You can now set the UnloadedBehavior to something like `Manual` 
There is also a new property called LoopingBehavior that controls what happens when the media reaches its end.
