### ISSUE TITLE
Problem when seeking video

### ISSUE THREAD

**Issue by eliasuardi** [unosquare/ffmediaelement#397]
# Issue Title (*Problem when seeking video*)

I wanted to replay the video once the MediaEnded event was fired by:
1) Setting the `Position` property of my media element
2) Play()
I tried following issue [#347](https://github.com/unosquare/ffmediaelement/issues/347) without any success.
The MediaEnded event is fired correctly but nothing happens afterwards and I get an `ObjectDisposedException`.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *4.1.300*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

### XAML
`<ffme:MediaElement x:Name="_VideoMediaElement" Background="Black" LoadedBehavior="Manual" UnloadedBehavior="Manual" Stretch="None" MediaEnded="_VideoMediaElementMediaEnded" />`

### C#
```
private async void _VideoMediaElementMediaEnded(object sender, EventArgs e)
{
    await _VideoMediaElement.Seek(TimeSpan.Zero);
    await _VideoMediaElement.Play();
}
```

**Comment by mariodivece** [comment]
Weird. What is the source url you are using?

**Comment by eliasuardi** [comment]
I'm getting a embedded video which I load into a temporary Server that I created using an HttpListener.
I then use this to set the source: `_VideoMediaElement.Source = new Uri(_ServerPort);`
Where `_ServerPort = "http://localhost:27480/"`

**Comment by mariodivece** [comment]
Does it happen with a normal file? What is the stack trace of the exception?

**Comment by eliasuardi** [comment]
I tried using a local video

**Comment by eliasuardi** [comment]
Sorry for the delay.
I tried playing a local file and the replay worked fine with the code above.
The ObjectDisposedException just pointed to the mscorlib.dll

**Comment by mariodivece** [comment]
does not sound like the error is FFME's -- it may be your implementation of serving the file. See if it works as expected with ffplay.exe. You could also implement your own `IMediaInputStream` see an example by searching the reference player for the file `FileInputStream.cs`
