### ISSUE TITLE
How to get media properties before source is loaded into the FFME mediaelement 

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#398]
# Issue Title (How to get media properties before source is loaded into the FFME mediaelement*)

I have a small app that loads and plays a media file.
But i need to get the media duration, and start time and frame rate before the file is opened in the player. So i have done this to load that data i need.

 Unosquare.FFME.Library.FFmpegDirectory = @"C:\FFMPEG\x86\";
 Unosquare.FFME.Library.FFmpegLoadModeFlags = FFmpegLoadMode.FullFeatures;
 Library.LoadFFmpeg();

 List<MediaInfo> mediaInfoList = new List<MediaInfo>();
 mediaInfoList.Clear();
 mediaInfoList.Add(Library.RetrieveMediaInfo(@"D:\Videos\HDVideo1.mp4"));
 mediaInfoList.Add(Library.RetrieveMediaInfo(@"D:\Videos\HDVideo2.mp4"));
 mediaInfoList.Add(Library.RetrieveMediaInfo(@"D:\Videos\HDVideo3.mp4"));
 mediaInfoList.Add(Library.RetrieveMediaInfo(@"D:\Videos\HDVideo4.mp4"));

// process data

 mediaInfoList.Clear();
 mediaInfoList = null;

Question is
1. is it ok to do this and load the ffmpeg libs this way before any videos are loaded in the player. Do i need to watch out for or dispose of anything before allowing the player to load videos after doing this ?

Any advice appreciated.

thanks

## Issue Categories

 - [X ] Question

## Version Information

 - [X ] NuGet Package *4.1.3*

**Comment by Ocimandias** [comment]
Dear manity42,
You could use the FFME.MediaEngine.RetrieveMediaInfo(fullmediapath) function to load detailed data from the footage.
Hope this helps

**Comment by mariodivece** [comment]
I suggest you serialize the metadata of the media file and load it when needed. When you load the video, simply overwrite the metadata. Closing since this is outside the scope of this project.
