### ISSUE TITLE
Multiple MediaElement instances :  Just shows the first frame sometimes

### ISSUE THREAD

**Issue by Mitra-M** [unosquare/ffmediaelement#399]
# Multiple MediaElement instances :  Just show the first frame sometimes

* I compiled your great code a few days ago and use 4 MediaElement instances in a simple WPF window. it was working perfectly 
, but last night I downloaded and compiled it again and  realized [this changes](https://github.com/unosquare/ffmediaelement/commit/b0e5b58f7cddfe17c89a4e65e65a4c4827814ebc) has this bug:

Sometimes some MediaElement instances (both files or streams) only show the first frame .  (while opening event is fire.) .
## Issue Categories

 - [x] Bug
 
## Version Information

 - [x] Build From *Master* branch, Commit *[b0e5b58f7cddfe17c89a4e65e65a4c4827814ebc](https://github.com/unosquare/ffmediaelement/commit/7db57f19ede9eaec4d92070e6f15e81f97085f8f)*
 

 This problem happens only occasionally, sorry I can not provide a sample code because I am traveling now.

**Comment by mariodivece** [comment]
Thanks for reporting. Are you using the enablewofmultithreaded video option set to true?

**Comment by Mitra-M** [comment]
No it is disable I have not tried it, can it solve the problem?.

**Comment by mariodivece** [comment]
No. I had seen the problem you have described when that unsupported option is set to true. But it seems to be unrelated. I will try to reproduce your issue. What version of ditnet framework are you using?

**Comment by Mitra-M** [comment]
Thank you,
.nerframework 4.72 
Win 10 1803
.netCore 3

**Comment by mariodivece** [comment]
I can't reproduce your issue. Do you mind sending me a sample project where you observe this behavior? I don't see how property change notifications affect frame rendering. I loaded a few 4k videos on the same window to peg the CPU to 100% and it still rendered -- slowly, but it did.

![image](https://user-images.githubusercontent.com/351978/58742332-b93e5780-83e9-11e9-85ca-190d812c7c77.png)

**Comment by Mitra-M** [comment]
I will test again and send a sample project next week.

**Comment by Mitra-M** [comment]
I tried again and got the same result.

to reproduce  this issue in your above sample set LoadedBehavior to Manual and set all sources dynamically  like this my simple (not MVVM) sample project :
>
      <Window x:Class="WpfApp1.MainWindow"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
             mc:Ignorable="d"
             Title="MainWindow" Height="450" Width="800">
         <Grid>
                           <Grid.RowDefinitions>
                                      <RowDefinition/>
                                      <RowDefinition/>
                                      <RowDefinition Height="25" />
                           </Grid.RowDefinitions>
                           <Grid.ColumnDefinitions>
                                      <ColumnDefinition/>
                                      <ColumnDefinition/>
                           </Grid.ColumnDefinitions>
                           <ffme:MediaElement x:Name="Media1" Background="Silver"  LoadedBehavior="Manual" UnloadedBehavior="Manual" />
                           <ffme:MediaElement x:Name="Media2" Grid.Column="1" Background="Gray" LoadedBehavior="Manual" UnloadedBehavior="Manual" />
                           <ffme:MediaElement x:Name="Media3" Grid.Row="1" Background="Gray" LoadedBehavior="Manual" UnloadedBehavior="Manual" />
                           <ffme:MediaElement x:Name="Media4"  Grid.Row="1" Grid.Column="1" Background="Silver" LoadedBehavior="Manual" UnloadedBehavior="Manual" />
                           <Button Content="SetSources" Click="Button_Click" Width="100"  Grid.Row="2" Grid.ColumnSpan="2"   />
                </Grid>
     </Window> 

 and c# :

>

    using System;
    using System.Windows;
    namespace WpfApp1
    {
            public partial class MainWindow :Window
           {
                      public MainWindow()
                      {
                                 InitializeComponent();
                      }
                      private  void Button_Click(object sender, RoutedEventArgs e)
                      {
                                 //  Media1.Source = new Uri(@"C:\Samples\PAL1.avi"); Media1.Play();
                                 //  Media2.Source = new Uri(@"C:\Samples\PAL2.avi"); Media2.Play();
                                 //  Media3.Source = new Uri(@"C:\Samples\PAL1.avi"); Media3.Play();
                                 //  Media4.Source = new Uri(@"C:\Samples\PAL2.avi"); Media4.Play();

                                 Media1.Open(new Uri(@"C:\Samples\PAL1.avi")); Media1.Play();
                                 Media2.Open(new Uri(@"C:\Samples\PAL2.avi")); Media2.Play();
                                 Media3.Open(new Uri(@"C:\Samples\PAL1.avi")); Media3.Play();
                                 Media4.Open(new Uri(@"C:\Samples\PAL2.avi")); Media4.Play();
                          }
               }
    }

if you click on that button a few times you can see the problem.

**Comment by Mitra-M** [comment]
It seems like I was wrong.

Today, I tried your last Nuget version and realized it does not have this problem ,
 I think (not sure) this issue was due to some my VisualStudio bugs ,  I repaired it , deleted all obj and .vs folders then rebuild , now FFME is working properly.

sorry and thanks!
