### ISSUE TITLE
Audio hardware enumeration count is zero

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#408]
# Issue Title (Audio hardware enumeration count is zero)

When you look at the hardware devices listed under Options.Audiostream in the OnMediaOpening event as seen in this screen shot, it shows Hardware devices and Hardware Decoders count as zero for both, despite the PC having functional audio devices.

Is this value normal if so why ?

Is there a way using FFME to test if the PC has audio devices (eg soundcard) installed and if so get a list of device names to allow a user to select the audio output.

![2019-06-24_18h01_10](https://user-images.githubusercontent.com/39360067/60012029-9ed86080-96ad-11e9-8227-bfb1cd912b32.png)

## Issue Categories
 - [X ] Question

## Version Information

 - [X ] NuGet Package *4.1.3*

**Comment by mariodivece** [comment]
The property on the Audio Stream is not enumerating audio devices on the machine. It is enumerating Video Hardware Decoding devices for the specified audio stream in which case should indeed be zero.

To enumerate audio devices you can call the following static methods:
`Library.EnumerateDirectSoundDevices()`
`Library.EnumerateLegacyAudioDevices()`

To select a specific audio device for output,
handle the `MediaOpening` and/or `MediaChanging` events and:

```csharp
 // the event sender is the MediaElement itself
var media = sender as MediaElement;
media.RendererOptions.DirectSoundDevice = selectedDevice;
```

or, for legacy audio (uses Windows Multimedia Extensions API):
```csharp
 // the event sender is the MediaElement itself
var media = sender as MediaElement;
media.RendererOptions.UseLegacyAudioOut = true;
media.RendererOptions.LegacyAudioDevice = selectedDevice;
```
