### ISSUE TITLE
ElementHostBase, in HandleUnloadedEvent method.

### ISSUE THREAD

**Issue by mariodivece** [unosquare/ffmediaelement#409]
There is another element that doesn't use UnloadedBehavior - it's ElementHostBase, in HandleUnloadedEvent method.
Is it possible to respect the UnloadedBehavior value there too?

_Originally posted by @igvk in https://github.com/unosquare/ffmediaelement/issues/141#issuecomment-502364632_

**Comment by mariodivece** [comment]
Could you elaborate or propose additional conditions on how you would expect this to behave?

**Comment by igvk** [comment]
Ok, in my program I need to remove a panel/window from visual tree (and then reattach it to other part of hierarchy) when there is switching to/from fullscreen mode.
I don't need the automatic function of stopping the playback, so in my case I don't need this built-in unloaded event handling.
I can not override HandleUnloadedEvent, because the ElementHost class is sealed, so I need it to either be empty by default/overridable in derived classes, or there should be a way to configure the unloaded behavior.

**Comment by mariodivece** [comment]
What you describe was clear from the beginning. I still don't know what should be considered expected behavior.
To help me out, please fill in the blanks:
When UnloadedBehavior == Close then HandleUnloadEvent should do: [blank]
When UnloadedBehavior == Stopthen HandleUnloadEvent should do: [blank]
etc.

**Comment by igvk** [comment]
Ok, I understand that there needs to be some logic for the states that are not needed in my case.
Why not just leave the current behavior (in unloaded handler) only when UnloadedBehavior is Close and do nothing in other cases?

**Comment by mariodivece** [comment]
I have added back the Dispose() method. This will get automatically called when UnloadedBehavior is set to Close. Keep in mid Dispose() will not get called if UnloadedBehavior is set to anything else. Could you test with the latest master build and let me know the results?

**Comment by igvk** [comment]
What am I supposed to do for HandleUnloadedEvent in ElementHostBase.cs to not run?
It still calls RemoveLogicalChild/RemoveVisualChild, etc.
This is due to the following line in OnInitialized():
`                Unloaded += HandleUnloadedEvent;

**Comment by mariodivece** [comment]
Oh, I see, so you want the HandleUnloaded even handlert NOT to run unless UnloadedBehavior is set to Close -- is that correct?

**Comment by igvk** [comment]
Correct, I certainly don't want it to run (due to the reasons I described earlier).

**Comment by mariodivece** [comment]
Ok, could you try again with the latest commit?

**Comment by mariodivece** [comment]
I just tried it and it works with the latest. Closing this issue. Thanks for reporting! Release coming shortly!

**Comment by igvk** [comment]
Ok, now it works.
Thanks!
