### ISSUE TITLE
Memory leak error logged when switch from one media file to a new media file

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#410]
# Issue Title (*Memory leak error logged when switch from one media file to a new media file*)

I have added logging to my app and i am seeing a memory leak warning when stopping a media file that is playing and opening a new media file.
this is example of the message
18:45:58.1656  MessageLogged: -> Aspect name: ReferenceCounter, Message Type Error, Time Stamp (UTC): 27/06/2019 10:45:58 AM, Message: Unmanaged references were left alive. This is an indication that there is a memory leak.
    Packet - MediaPacket.cs; Line: 83, Member: CreateReadPacket - Instances: 80
    SwrContext - AudioComponent.cs; Line: 108, Member: MaterializeFrame - Instances: 1
    CodecContext - MediaComponent.cs; Line: 79, Member: .ctor - Instances: 1

this is how i am closing the media file

await FFMEMediaPlayer.Stop();
FFMEMediaPlayer.Source = new Uri("");   // or null
await FFMEMediaPlayer.Close();

this is how opening the new media file

await FFMEMediaPlayer.Open(new Uri(fileNamePath))

Using FFME nuget 4.13
FFMPeg.autogen 4.1.0.5
FFMpeg x86 libs 4.1.1

Also i have 4 instances of the player control playing videos as this is going on.
Each player follows a separate playlist so opens and closes videos as it moves through the list

Is it possible the memory leak warning is just because there are other instances of the control playing at the same time and it picks up the unmanaged references from those other instances.
Maybe that means i can ignore this warning ?

Any advice please on what im doing wrong.

thanks very much for this excellent control.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [X] Not sure

## Version Information

 - [ X] NuGet Package *4.13*

## Steps to Reproduce

 1. Step 1 Open media file in Media Element
 2. Step 2 Stop media element
 3. Step 3 set mediaelement source to new URI("") or null
4. Step 4 Close media element

## Expected Results

MessageLogged error  comes through the media element MessageLogged event indicating memory leak

18:45:58.1656  MessageLogged: -> Aspect name: ReferenceCounter, Message Type Error, Time Stamp (UTC): 27/06/2019 10:45:58 AM, Message: Unmanaged references were left alive. This is an indication that there is a memory leak.
    Packet - MediaPacket.cs; Line: 83, Member: CreateReadPacket - Instances: 80
    SwrContext - AudioComponent.cs; Line: 108, Member: MaterializeFrame - Instances: 1
    CodecContext - MediaComponent.cs; Line: 79, Member: .ctor - Instances: 1

**Comment by mariodivece** [comment]
You are not supposed to use the 2 APIs -- either use `Source = null` or `await Close()` Could you try this with a build from Master and report the results please?

**Comment by manity42** [comment]
Hello,
once i saw you released a new version i updated to test this issue.
using
Using FFME nuget 4.1310
FFMPeg.autogen 4.1.0.5
FFMpeg x86 libs 4.1.3

My app is still logging these same errors(below)
they get logged at every transition from a video playing, then a click and a new video loads in the play list. 
Again may i suggest this might be a false error as i have 4 videos playing at the same time.
Is it possible the "alive" references detected by a single player loading a new video is intact references to the three 3 videos still playing.

also i changed my code at the points a video changes to a new video, i only now use as suggested

await FFMEMediaPlayer.Close();
this is how opening the new media file
await FFMEMediaPlayer.Open(new Uri(fileNamePath))

this has not stopped those unmanged error references being logged.



17:56:32.3132 | ERROR | FFMEVideoPlayerControl.FFMEBaseVideoPlayer | Player Event MessageLogged: -> MediaFile: FCV33 Stbd_20190209072653_2.mp4, Channel Index: 2,  Aspect name: ReferenceCounter, Message Type Error, Message: Unmanaged references were left alive. This is an indication that there is a memory leak.
    Packet - MediaPacket.cs; Line: 83, Member: CreateReadPacket - Instances: 218
    CodecContext - MediaComponent.cs; Line: 79, Member: .ctor - Instances: 6
    SwrContext - AudioComponent.cs; Line: 112, Member: MaterializeFrame - Instances: 3
    SwsContext - VideoComponent.cs; Line: 233, Member: MaterializeFrame - Instances: 3

**Comment by mariodivece** [comment]
Could you please prepare a simple project that reproduces the issue and zip the source here on this thread so I can look at it?

**Comment by manity42** [comment]
I will put together a sample to reproduce what i see.
Will take me some time to get to it.

**Comment by mariodivece** [comment]
Ok, you mentioned 4 videos. This is the same issue as #424 
Feel free to provide further feedback. Closing for now.
