### ISSUE TITLE
Error -1414092869: Immediate exit requested

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#411]
# Issue Title (Error -1414092869: Immediate exit requested)

*Im logging an error, that seems to occur just before application freezing briefly then just shuts down. No exceptions are trapped it just shuts off. Its not consistent and i have not found a way to make it happen all the time. It just seems to happen randomly. I can run for hours at a time with not problem then it happens twice within a few minutes.

I think this message is FFMPEG based and may trigger when it has trouble reading the video stream, but thats a guess based on some FFMPEG forum comments.

Visual studio shows this in output
The program '[17480] Play.exe' has exited with code -1073740940 (0xc0000374).

Google has suggested this is the result of heap corruption
# for hex 0xc0000374 / decimal -1073740940
  STATUS_HEAP_CORRUPTION                                         ntstatus.h
# A heap has been corrupted.

Can anyone suggest how i could proceed

The mediaelement logged error is this
15:36:56.6139 | ERROR | Player.FFME | Player Event MessageLogged: -> MediaFile: FC _20190209191624_4.mp4, Channel Index: 4,  Aspect name: Container, Message Type Error, Message: Fatal error initializing MediaContainer instance.
MediaContainerException: Could not open 'FC _20190209191624_4.mp4 . Error -1414092869: Immediate exit requested
Stack Trace:
   at Unosquare.FFME.Container.MediaContainer.StreamInitialize()              
15:36:56.6139 | ERROR | Player.FFME | Player Event MessageLogged: -> FC_20190209191624_4.mp4, Channel Index: 4,  Aspect name: Engine.Commands, Message Type Error, Message: Direct Command 'Open' execution error
MediaContainerException: Could not open 'FC_20190209191624_4.mp4'. Error -1414092869: Immediate exit requested

Any advice appreciated

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ X] Not sure

## Version Information

 - [ ] NuGet Package *4.13*
FFmpeg.AutoGen v 4.1.0.5
FFmpeg v4.1.1

**Comment by mariodivece** [comment]
does your file work with ffplay.exe
ffplay.exe comes with FFmpeg binaries. Please let me know. If it doesn't there is not much I can do. If it does work, then I will need the video file in order to help.

**Comment by manity42** [comment]
the files im using do play with ffplay.
Its a really random occurrence.
I will see if i can put something together to make it appear consistently.

**Comment by manity42** [comment]
i am closing this issue. I have been unable to make it occur on demand. it has seemed quite random, and unrelated to the media as i have tried different media files.

However it seems like it may  have disappeared after following your advice on opening several media files at the same time and re constituting my project a new in the latest version of the control as per issue https://github.com/unosquare/ffmediaelement/issues/418
