### ISSUE TITLE
Possible to use for edited sequences of video

### ISSUE THREAD

**Issue by maptz** [unosquare/ffmediaelement#412]
Hi,

I just started to play with Ffmediaelement on a little helper project for a movie I was running. I'm really impressed with it. Well done on all your work. It's fab.

Not sure if this the place to post this (I never know with GitHub where to post non-issue material), as I'm after a bit of advice based on your experience writing your codebase.

I'm a film editor and coder. I've always wanted to create a playback engine for edited timelines of audio and video; that is, sequences of video sections from within video files and multiple tracks of audio segments. I want it to be resilient to pretty complicated timelines, as movie scale timelines get pretty intricate. My use case will use only video and audio files in very specific codecs, without intraframe compression and specifically designed for editing so seek speed is snappy.

I've always intended to dig into ffplay.c and the dranger tutorial to try to create a playback engine. I'm pretty experienced with C#, but my C is very thin, so I've never quite found the time to do this. 

It sounds like in writing ffmediaelement that you've done a bit of work with exactly this kind of thing and I wondered if you might be able to give me some perspective. How simple do you think it would be to adapt your playback engine to play edited timelines?

If anyone has any advice would be good to talk it through if you can give me some pointers.

Stephen

**Comment by mariodivece** [comment]
I started writing this library learning from the dranger tutorial, and then moved on to taking some ideas from ffplay.c and the examples on the ffmpeg source. 

As far as using it as a player for audio and video files, sure. Give it a shot and maybe take a look at what other people are doing with this control:
https://github.com/unosquare/ffmediaelement/network/dependents

Off-Topic: recommendation for fast playback:
https://stackoverflow.com/questions/20963042/encoding-for-fastest-decoding-with-ffmpeg

**Comment by maptz** [comment]
Thanks Mario. 

I suppose what I was asking was really about whether - from your experience diving into ffplay.c and the dranger tutorials - whether you thought it was even feasible to do an edited sequence playback engine. Would you recommend me going down the stame route as you did - i.e. start the dranger, and then dig into ffplay.c? Or do you think that is a fools errand?

**Comment by mariodivece** [comment]
It would certainly be a lot of work :) But if you have the time, go ahead! It has worked for me as a hobby.
Check out my comment here:
https://github.com/unosquare/ffmediaelement/issues/413#issuecomment-507003895

You can accomplish scene editing via video (and audio) filters -- it can get very complicated.
And encoding is not too hard, but it is not easy either.

**Comment by maptz** [comment]
Oh time! A luxury I don't have unfortunately :) Baby no.2 arrived on Thursday. 

However, I do stare at this problem every day trying to weigh up whether it's a worthwile way of spending my time. I waste so much time with my commercial editing applications that don't allow me to automate some extremely common aspects of editing, and I feel I could really smooth the workflow. 

As I might have mentioned above, I'm a film editor by trade - coder by hobby. Commercial editing software is all written around adding sexy new features like colour correction and effects work, whereas the majority of the day-to-day in editing is clumping together video clips with layers upon layers of audio tracks. [It's not sexy to market that kind of stuff]. 

My assumption has always been that if I could write a playback engine for video/audio timelines, I could write a very workaday editing application that improve the day-to-day experience of editing simple sequences. 

Pragmatically, I was going to limit myself to using a single video codec  (one specifically designed for fast frame access) at a single framerate, and PCM audio with a single sample rate for the audio. 

I'd love to know what you think the likely complications I might face would be (especially as a result of choosing ffmpeg as the underlying mechanism)?

**Comment by mariodivece** [comment]
I would suggest you get familiar with filtering before anything else
https://trac.ffmpeg.org/wiki/FilteringGuide
https://ffmpeg.org/ffmpeg-filters.html

Start by experimenting using the original ffmpeg.exe -- you will see that filers or any combination of them can be applied as a function of time, framerate, and a number of other variables. You can build very complex filtergraphs that way.

Then create an application that builds filtergraph strings and previews them using FFME
For example, I have provided an example (in the sample app) on how to change brightness, saturation, and contrast in real-time via the VideoFilter property.

Note that FFME does not support multiple stream inputs (not the purpose of this project)  like ffmpeg.exe, does so for filtergraphs with multiple stream inputs you will need to create an ffmpeg output and preview using FFME once ffmpeg joins the files,

You could also get creative and pipe ffmpeg.exe's standard output into a custom IMediaInputStream of FFME and preview it real-time (if your computer encodes fast enough). There is also an example in the sample app of how to build a custom IMediaInputStream -- See FileInputStream.cs

The possibilities are really endless, but it can get very complicated, very fast.

**Comment by maptz** [comment]
That's very helpful. I've done lots of work with FFMPEG filters at the command line in the past. I use it for burnt-in timecode for e.g. and for creating watermarked playouts. 

I'll definitely look into the custom IMediaInputStream example. I've got a custom application that I've been writing for some subtitling tasks, and I could use this to add realtime timecode to the playback in.

Edited tImelines get multi-layered pretty quickly, but for my use case, as long as I could kind of pick which video frame, and add up a 'frame's worth of audio' from multiple sources ad hoc, I think I could get it to work.
