### ISSUE TITLE
Change in FFMPEG shared lib requirements [Question]

### ISSUE THREAD

**Issue by kealist** [unosquare/ffmediaelement#414]
# Update changed shared library requirements

I just updated from my old place in master to the current version.  I run an LGPL version of FFMPEG which has not contained `postproc-55.dll` (it's been a long time since I have built it but don't remember if that is a mostly GPL focused lib) , but it seems after updating this is required to run.  Do you know why / where that change was made?  or if there is a way to work around that?  

I played around `Unosquare.FFME.Library.FFmpegLoadModeFlags` to reduce requirements without success.   

Thank you for your time as always

**Comment by mariodivece** [comment]
In my latest commit you can now do cutom library loading as follows:
```csharp
Library.FFmpegLoadModeFlags = FFmpegLoadMode.LibraryFlags["avcodec"] | FFmpegLoadMode.LibraryFlags["avfilter"] | ...;
```

Check it out and let me know if this works as expected.
Thanks!

**Comment by mariodivece** [comment]
Any feedback here before I close this one?

**Comment by mariodivece** [comment]
No further feedback was provided. Closing.

**Comment by kealist** [comment]
@mariodivece I'm finally able to work on this again.  I do not see any access level to set these pieces.   I can set `FFmpegLoadMode.FullFeatures;` or `FFmpegLoadMode.VideoOnly;`, but not on a piece by piece basis.   
ie. `FFmpegLoadMode.LibraryFlags["avcodec"] | ...` isn't defined (or accessible publicly).

I saw the comment in the other thread, but I have built this version of FFMPEG myself and it used to work with previous versions of FFME

**Comment by kealist** [comment]
Sorry, it worked with `FFmpegLoadMode.MinimumFeatures`, so I am OK.   List of DLLs below if reference is needed at some point.  Noted, [those flags](https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME.Windows.Sample/App.xaml.cs#L28) shouldn't be documented as an option if they do not work 

![image](https://user-images.githubusercontent.com/5009062/65961701-222fed80-e425-11e9-9bf3-fb7e2fbac6c9.png)
