### ISSUE TITLE
A way to access ffplay -loglevel parameter

### ISSUE THREAD

**Issue by Arestihub** [unosquare/ffmediaelement#415]
A way to access ffplay -loglevel parameter

Is there a way I could pass -loglevel parameter when initializing FFME? Weirdly enough I get bad screen tearing when playing RTP streams with a log level above error (using FFPlay from cmd). Any level lower than that, there's absolutely zero tearing. In addition to no tearing, the delay of the stream is also around 0.5 seconds lower. I know you can filter the log messages in the MessageLogged event, but it seems like the internal logging process somehow causes tearing and latency.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x ] Question
 - [ ] Not sure

## Version Information

 - [ x] NuGet Package 4.1.310
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

**Comment by mariodivece** [comment]
Adding `Library.FFmpegLogLevel`

Example:
```csharp
Library.FFmpegLogLevel = ffmpeg.AV_LOG_WARNING;
```

This setting can be changed at any point in time but it is recommended that you set it right after you set the FFmpegDirectory property.

You could have also called the AutoGen API: `ffmpeg.av_log_set_level(ffmpeg.AV_LOG_FATAL);` for example

**Comment by Arestihub** [comment]
Great, thank you for your time and effort!
