### ISSUE TITLE
Change image in design view in visual studio.

### ISSUE THREAD

**Issue by eelos** [unosquare/ffmediaelement#416]
# Issue Title (*change this title!*)

Change image in design view in visual studio.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [x] Not sure

## Version Information

 - [x] NuGet Package *4.1.310*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Question

Is there a way to disable the ffme-preview.png in design view visual studio wpf?
Or change the image so i can see my project more? Or do i need to make a new package myself?

Thank you!

Greetings,

Eelos.

**Comment by mariodivece** [comment]
You can now use the `IsDesignPreviewEnabled` dependency property.

```xml
<ffme:MediaElement Name="Media" Background="Black" LoadedBehavior="Play" IsDesignPreviewEnabled="False" />
```

**Comment by eelos** [comment]
Thank you, there's a beer for you on your paypal!

**Comment by mariodivece** [comment]
Thanks!
