### ISSUE TITLE
minimal latency specification of ffme.win streaming rtsp

### ISSUE THREAD

**Issue by AlexEisenring** [unosquare/ffmediaelement#420]
Mminimal latency specification of ffme.win streaming rtsp

Dear developer

What is the additional minimal latency of ffme.win using WPF and the ffme:MediaElement while streaming for instance rtsp://192.168.1.131/mpeg4/1/media.amp.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [X] Question
 - [ ] Not sure

## Version Information

 - [X] NuGet Package ffme.windows.4.1.310.nupkg
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

**Comment by mariodivece** [comment]
This is related to #352 
I will be working on a solution to get latency down to a minimum since it's been a popular ask.
