### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by Afy65** [unosquare/ffmediaelement#421]
# Issue Title (Demo does not work)
Thought it was me! so asked one of my colleagues at work to try and get this working - installed .net core 3, but the last two projects just wont load no matter what we do? Using VS2019
Unosquare.FFME.Windows (unavailable)
Unosquare.FFME.Windows.Sample (unavailable)

## Issue Categories
 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [x] Not sure

## Version Information
Latest version downloaded from github.com

**Comment by mariodivece** [comment]
You need to enable preview versions of dotnet in visual studio 2019. The current master is built using core 3.0-preview6.
Please see: https://visualstudiomagazine.com/articles/2019/03/08/vs-2019-core-tip.aspx
