### ISSUE TITLE
Dshow device name with "#" gets cut of as Uri into Fragment, can't open media

### ISSUE THREAD

**Issue by rolfis** [unosquare/ffmediaelement#423]
# Dshow device name with "#" gets cut of as Uri into Fragment, can't open media

*When setting a Uri for a dshow video device, such as Webcam, if a device name contains "#" the Uri() method cuts everything after "#" and puts in Fragment(). Such naming conventions happen for example when I have two Logitech HD Pro Webcam C920 connected, they are named "HD Pro Webcam C920 #1" and "HD Pro Webcam C920 ##2" and none of them can be addressed with Uri().*

## Issue Categories

 - [X] Bug

## Version Information

 - [ ] NuGet Package *4.1.310*

## Steps to Reproduce

 1. Connect two USB Webcams with same device name or name with "#" in them.
 2. Add Source to Media Element: Media.Source = new Uri("device://dshow/?video=HD Pro Webcam C920 #1")
 3. Run code. MediaFailed Event will fire with the exception: "Could not open 'video=HD Pro Webcam C920 '. Error -5: I/O error".

## Expected Results

 - That the source video device name is kept as entered in Uri() and that the video opens.

**Comment by mariodivece** [comment]
Could you provide details on how you resolved this issue please?

**Comment by rolfis** [comment]
Sorry, yes of course. The "#" must be URL encoded instead (%23), like: Uri("device://dshow/?video=HD Pro Webcam C920 %231"). Hope this helps.
