### ISSUE TITLE
Multiple instances of Media Element - Unmanaged references were left alive.

### ISSUE THREAD

**Issue by jdwoolcock** [unosquare/ffmediaelement#424]
# Multiple instances of Media Element - Unmanaged references were left alive.

I have a simple WPF application that has multiple instances of the ffmediaelement player. When I close an instance and there are other instances running I get the error  message. _**Unmanaged references were left alive. This is an indication that there is a memory leak.**_
Is this actually a problem or just an erroneous error message.

## Issue Categories

 - [ *] Bug
 - [*] Question

## Version Information

 - [ ] NuGet Package
"FFME.Windows" version="4.1.310" 
"FFmpeg.AutoGen" version="4.1.0.5" 

## Steps to Reproduce

I have attached a simple example FfmeTest that illustrates the problem. 
It has 4 media panels each one has a play and stop button.
Start playing multiple instances and then press stop on one of the windows.

The following error message is logged

[34:18.002 | ERR | ReferenceCounter    ] Unmanaged references were left alive. This is an indication that there is a memory leak.
    CodecContext - MediaComponent.cs; Line: 79, Member: .ctor - Instances: 2
    SwrContext - AudioComponent.cs; Line: 112, Member: MaterializeFrame - Instances: 1
    Packet - MediaPacket.cs; Line: 83, Member: CreateReadPacket - Instances: 22
    SwsContext - VideoComponent.cs; Line: 233, Member: MaterializeFrame - Instances: 1

[FfmeTest.zip](https://github.com/unosquare/ffmediaelement/files/3416383/FfmeTest.zip)

### Commands to play and close
```csharp
private RelayCommand<MediaElement> playCommand;
        public RelayCommand<MediaElement> PlayCommand
        {
            get
            {
                return playCommand
                       ?? (playCommand = new RelayCommand<MediaElement>(
                           async e => { await e.Open(new Uri("rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov")); }));
            }
        }
       
        private RelayCommand<MediaElement> stopCommand;
        public RelayCommand<MediaElement> StopCommand
        {
            get
            {
                return stopCommand
                       ?? (stopCommand = new RelayCommand<MediaElement>(
                           async e => { await e.Close(); }));
            }
        }
```

**Comment by mariodivece** [comment]
FFMe has an internal reference counter for unmanaged allocations. This message is an indication that there is a real memory leak. Let me check out your code.

**Comment by mariodivece** [comment]
Ok, I see what the problem is. The reference counter keeps track of unmanaged references for all media container instances. When there are more media containers, this message appears. Note how the message does not appear when you close the last MediaElement. Since this meant for development diagnostics only, I have updated the message being logged to a more proper explanation.

Thanks for the report!
