### ISSUE TITLE
How do I pull audio buffer from media element

### ISSUE THREAD

**Issue by shuZro** [unosquare/ffmediaelement#428]
How do I pull audio buffer from media element?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x ] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
There is an example on how to do that here:
https://github.com/unosquare/ffmediaelement/blob/c17fca9836880725f071ce26f863548597708487/Unosquare.FFME.Windows.Sample/MainWindow.MediaRendering.cs#L117
