### ISSUE TITLE
Shrinking Audio Samples creates Sound Artifacts

### ISSUE THREAD

**Issue by guoluming** [unosquare/ffmediaelement#43]
thank you very much, this project helped me a lot！It's fantastic！
There are two issues below.
Issues 1、When I frequently switch the source, command does not work.can`t play anymore.
Issues 2、Long time off the net，After the network is restored,， command does not work,can`t play anymore.
        /// <summary>
        /// Executes this command asynchronously
        /// by starting the associated promise and awaiting it.
        /// </summary>
        /// <returns></returns>
        public async Task ExecuteAsync()
        {
            var m = Manager.MediaElement;
            if (m.Commands.ExecutingCommand != null)
                await m.Commands.ExecutingCommand.Promise;//Issues 1 &Issues 2,Can not jump out，Dead here

            m.Commands.ExecutingCommand = this;
            Promise.Start();
            await Promise;
            m.Commands.ExecutingCommand = null;

        }

**Comment by mariodivece** [comment]
Let me look into this. Thanks for reporting. I appreciate it.

**Comment by guoluming** [comment]
thanks for you reply, another Issue here.There is a problem with audio rendering. When speed is set to 2, the sound is intermittent

**Comment by mariodivece** [comment]
The commanding has chanhed a bit so ccould you try it again.

As far as the audio goes, I need a sample gile so I can test. Could you please provide me with one?

**Comment by mariodivece** [comment]
@guoluming Could you please try this stuff again? Commanding has changed significantly. If issues still appear, could you provide some sample streams/files?

**Comment by guoluming** [comment]
thanks for your reply,speedRatio improves a lot ,if speedRatio>1,how to make audio samples sound normal？Instead of  shrunken.
i try to  change the ReadAndShrink function code like this, however,,the samples still exist dense heartbeat or pit-a-pat during the time of people speaking.
private void ReadAndShrink(int requestedBytes)
        {
            var bytesToRead = (int)(requestedBytes * SpeedRatio).ToMultipleOf(SampleBlockSize);
            var sourceOffset = 0;

            if (bytesToRead > AudioBuffer.ReadableCount)
            {
                Seek();
                return;
            }

            AudioBuffer.Read(bytesToRead, ReadBuffer, sourceOffset);
}

**Comment by mariodivece** [comment]
Hey @guoluming I am having a hard time understanding what you mean. Specifically:

> still exist dense heartbeat or pit-a-pat during the time of people speaking
and
The code you provided (what do you intend with that piece of code)

Thanks in advance for the clarifications.

**Comment by guoluming** [comment]
hi，I mean, if SpeedRatio >1, the voice isn't smooth，

**Comment by guoluming** [comment]
The code I provided was meant to make the samples sound normal rather than sharp.

**Comment by mariodivece** [comment]
ahhh... I see... I might have a rounding error when grouping the samples together... I will revise that sample shrinking method... Try values like 1.5 and 2.0 and you will see it sounds smooth. That's why I can tell there's a rounding issue.

In the meantime, you can always do something like:
```csharp
OnPropertyChanged += (s, e) { 
    if e.PropertyName == nameof(MediaElement.SpeedRatio) && (s as MediaElement).SpeedRatio > 1.0 
    { 
        (s as MediaElement).IsMuted = true; 
     }
     else
     {
        (s as MediaElement).IsMuted = false;
      }
```
or something similar...

**Comment by guoluming** [comment]
Thanks for your advice...The sound is necessary for me. IsMuted cannot be set to true...At the same time, I'm trying to improve it...

**Comment by guoluming** [comment]
would you please let me know after the sample shrinking method improved,very thanks...

**Comment by mariodivece** [comment]
yep will do... Thanks again for your feedback.

**Comment by mariodivece** [comment]
I believe it's fixed now with the latest commit. Could you please test and send me your comments?

**Comment by mariodivece** [comment]
Closing as there was no further feedback and the audio pitch changes smoothly and no artifacts are created.
