### ISSUE TITLE
FFME causes RTSP stream to become corrupted

### ISSUE THREAD

**Issue by ryanmcbrideusf** [unosquare/ffmediaelement#431]
# FFME causes RTSP stream to become corrupted

I've noticed an issue where FFME consistently causes an RTSP stream to become corrupted. The stream is coming from an Extron SME 211 (hardware media encoder), which provides a URL like `rtsp://192.168.1.100/stream1`. If I try playing the stream in any other video player, including VLC, MPV, and ffplay, it works perfectly and I can close and reopen the stream over and over with no issue. 

However, if I open the stream just once in FFME, it always results in a corrupted video full of artifacts. Even after closing FFME, the other video players are suddenly unable to play the stream anymore and they all begin reporting tons of errors. The only way to fix this is to reboot the encoder.

After some testing, I've discovered that the encoder provides a "Client Session Count", which increases by 1 whenever the stream is opened in VLC/MPV/ffplay and drops back to 0 after closing the stream. FFME causes the count to increase by 2, and drops back to 1 (not 0) after closing the app completely. It's as if FFME opens two connections to the device and the second one remains open which interferes with any new connections.

After even more testing, I narrowed down the issue to [this line](https://github.com/unosquare/ffmediaelement/blob/31674e9ab8ae595a79229e31a988ea3073c1a177/Unosquare.FFME/Container/MediaContainer.cs#L739) in MediaContainer.cs:
``` csharp
ffmpeg.av_read_play(InputContext);
```

If I comment out that line and rebuild FFME, the stream plays normally, and the device reports 1 connection. I'm not sure what other side effects this change has, though.

## Issue Categories

 - [X] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [X] NuGet Package 4.1.310

## Steps to Reproduce

 1. Since I can't give you our hardware encoder, download this [RTSP server](http://www.happytimesoft.com/products/rtsp-server/index.html) instead (the 64 bit version) and simply run `RtspServer.exe` (no configuration is needed). 
 2. On the same PC, run ffplay with the URL that was provided in RtspServer's command line, and append it with /test.mp4. For me, this ends up being `ffplay rtsp://10.0.2.15/test.mp4`
 3. Once ffplay begins playing the stream, open the `ipsee.txt` log inside RtspServer's folder. The series of RTSP commands sent to the server should be as follows: OPTIONS, DESCRIBE, SETUP (video), SETUP (audio), SETUP (metadata), PLAY.
 4. Close ffplay, open the same URL in FFME's sample player, and reopen the log. The new commands should look like this: OPTIONS, DESCRIBE, SETUP (video), SETUP (audio), SETUP (metadata), PLAY, PLAY. Notice the duplicate PLAY command. Even though the video plays using RtspServer, this same process would corrupt our hardware encoder.
 5. Comment out that line in MediaContainer.cs, and do step 4 again. Notice how there's only 1 PLAY command this time, just like ffplay. This process works fine on our hardware encoder.

## Expected Results

 - FFME is able to play an RSTP stream from an Extron SME 211, and not cause subsequent connections to fail. It should be sending a single PLAY command to the RTSP server, just like ffplay does.

### Command line ffplay
```batch
ffplay rtsp://10.0.2.15/test.mp4
```

### Sample log files

[ipsee_ffplay.txt](https://github.com/unosquare/ffmediaelement/files/3456755/ipsee_ffplay.txt)
[ipsee_ffmeplay.txt](https://github.com/unosquare/ffmediaelement/files/3456756/ipsee_ffmeplay.txt)
[ipsee_ffmeplay_with_workaround.txt](https://github.com/unosquare/ffmediaelement/files/3456757/ipsee_ffmeplay_with_workaround.txt)

**Comment by mariodivece** [comment]
I had been debating for several months whether to remove that line from the stream initialization logic. I realized this gets called automatically when the packet reading worker reads for the first time. I have commented it out. Thanks for providing full logs and all the details!
