### ISSUE TITLE
sound problems .wmv

### ISSUE THREAD

**Issue by davaz11** [unosquare/ffmediaelement#432]
# Sound problems .wmv

I have sound problems with .wmv files, I tried to make changes in OnMediaOpening event that I found in this forum but any configuration avoid this problem, trying to avoid latency enabling sync produces a strange distorted sound

## Issue Categories

 - [+ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## ffmediaelement-3.10.0

 - [ ] NuGet Package *Enter Version Number Here*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Configuration 1

media.RendererOptions.AudioDisableSync =true;
media.RendererOptions.UseLegacyAudioOut =true;
e.Options.IsTimeSyncDisabled =false;

RESULT 
A/C +500    Hight latency 

## Configuration 2
media.RendererOptions.AudioDisableSync=false
media.RendererOptions.UseLegacyAudioOut =true;
e.Options.IsTimeSyncDisabled =false;

RESULT

A/C +010 latency is good but sound is not good (there is a strange echo and distorsion like if sound skips and repeat triyng to keep the frame)

**Comment by mariodivece** [comment]
Have you tried your wmv files with ffplay? What is the result? Any chance you could provide the wmv files?

**Comment by davaz11** [comment]
Hi Mario, sorry my late reply 
I tried the wmv files in ffplay and sound is good
From this url : https://standaloneinstaller.com/blog/big-list-of-sample-videos-for-testers-124.html you can download DLP_PART_2_768k.wmv file as example. 
I found that the problem is only in wmv3 video codec files
Thank you

**Comment by Legion-5** [comment]
It’s still properly not working.
