### ISSUE TITLE
Tried to follow "Quick Usage Guide for WPF Apps" without success amd sample solution not building.

### ISSUE THREAD

**Issue by kdpkke** [unosquare/ffmediaelement#433]
Greetings, I've got two problems:

1) I tried to follow "Quick Usage Guide for WPF Apps" paragraph without success: I created a new WPF project, I inserted the media element in XAML as stated in the Quick Usage Guide but even if I add a source (.flv video), when I start the application in debug mode the media element is grey and it doesn't stream the video.
![Immagine2](https://user-images.githubusercontent.com/6454277/62586224-fd077e80-b8bc-11e9-8d3a-0c6e20ac5a72.png)

![Immagine3](https://user-images.githubusercontent.com/6454277/62586230-ff69d880-b8bc-11e9-8b24-00fa4ff0d4f2.png)

2) I tried to open up the sample project as stated in "Windows: Compiling, Running and Testing" paragraph, but I've got builds error.
![Immagine](https://user-images.githubusercontent.com/6454277/62586047-1825be80-b8bc-11e9-9def-95066117a224.png)

What can I do for these two problems? 
Thank you in advance.

**Comment by mariodivece** [comment]
Are you sure you are using Shared ffmpeg binaries, pointing at the right folder, and your application architecture matches that of the ffmpeg binaries?

Check out:
https://github.com/unosquare/ffmediaelement/blob/3e1f2d4662f73ecedf23223d279f7035c622736d/Unosquare.FFME.Windows.Sample/App.xaml.cs#L22

As far as building and testing, you will need visual studio 2019 preview and .net core 3.0 preview 7 SDK or above installed.

**Comment by gotsring** [comment]
What was the solution to this? I also can't play videos using the NuGet package. The code compiles but the video never plays. I tried moving the FFMPEG dlls to the executable directory, but this didn't appear to do anything. Inspecting the MediaElement instance shows that IsInitialized = true, but IsOpen and IsOpening are false. Is there a flag indicating that the DLLs were loaded correctly?

I am using:
 - 64-bit Windows 10
 - NuGet package FFME.Windows v4.1.310
 - FFMPEG 4.2 Win x64 shared libraries (latest stable release)
 - Visual Studio 2019 v16.2.2
 - New WPF project with Target .NET Framework 4.6.1 or 4.7.2 (neither worked)

**Comment by Prime8bit** [comment]
For those who have had this issue, I faced the same issue. Enabling prerelease versions and using the latest prerelease nuget package worked for me. It would be nice if the stable package was updated more often since the last stable release was three versions ago in 2021.
