### ISSUE TITLE
How to open NamedPipe stream? 

### ISSUE THREAD

**Issue by a44281071** [unosquare/ffmediaelement#434]
Must I instead it use local socket?
But I need to display 100 screens（from android H264 Annex B NALU byte[]）. Is this operation impossible?
I can't imagine what happened after I instantiated 100 Unosquare.FFME.MediaElement.

**Comment by mariodivece** [comment]
you will need to implement your own IMediaInputStream
An example is provided here:
https://github.com/unosquare/ffmediaelement/blob/c17fca9836880725f071ce26f863548597708487/Unosquare.FFME.Windows.Sample/Foundation/FileInputStream.cs

Reading from named pipes is easy and there are plenty of examples available:
https://www.google.com/search?q=c%23+read+named+pipes&cad=h

As far as supporting concurrent 100 screens, I don't think ffme (or any other control) would be able to handle that many.
