### ISSUE TITLE
Proper way to closing media while / after opening

### ISSUE THREAD

**Issue by Arestihub** [unosquare/ffmediaelement#435]
Proper way to closing media while / after opening

Hello!

My application has multiple tabs, every tab having multiple stream elements. When switching tabs, I'm trying to properly close all streams in the previous tab while opening the streams in the next tab. Everything works flawlessly if I do it slowly enough. However, if I'm switching between tabs quickly I sometimes encounter errors. Sometimes the streams don't have time to open properly before I try to close them, which leads them to stay active in the background tab. If I keep switching tabs many times a second, this can lead to high RAM usage and eventually the program might crash.

## Issue Categories

 - [x ] Question

## Version Information

 - [ x] NuGet Package 4.1.310

## Steps to Reproduce

1. Call await MediaElement.open(source)
2. Call await MediaElement.Close()

(In theory this could be repeated many times a second)

--> If the media didn't have time to open properly before trying to close it, you get the following error:

Direct Command 'Close' not accepted. Open media before closing or changing media.

## Expected Results

Media can be closed even if it's opening (via canceling or waiting for it to correctly open)
 
Is there a problem in the async-pattern or should I implement a retry-strategy of some sort to make sure the streams I want to close actually get closed? Should I be able to just call await open / close potentially multiple times a seconds without problems?

**Comment by LouisCPro** [comment]
@Arestihub,

I notice exactly the same Problem ! I did not see if as I, you're on WPF but in the case yes, then have a look on the fact that TabControl Items switching does an unload on children controls, which is the case of the ffme element for me !
This understood, I'm also trying at the moment to manipulate Load / Unload Events on the ffme element to see how I could properly manage the problem. It seems to be OK with the unload where I close properly the stream, but when I came back and try to open again, it fails !!!

...Tests in progress but without luck til then !

**Comment by LouisCPro** [comment]
@Arestihub,

Finally Done !

There's a combination of 2 parts to make this goes well !

1. Implement An ExtendedTabControl class that extend TabControl, and contains code to make the TabItem Collection not to be unloaded each time we change the selected Tab,
2. Avoid trying to do thing with code behind regarding the open/close of the ffme component.

For the First point, have a look at :
https://stackoverflow.com/questions/3601125/wpf-tabcontrol-preventing-unload-on-tab-change

For the second one, look at this :
* Implement the Media Events on your ctor, and use them only to show onscreen message for debug purposes,
* If you use a Datacontext as I do, implement StreamViewerView_DataContextChanged Event and in this method, only do that : Media.Source = <your_uri>
* In your XAML MediaElement control, add : LoadedBehavior="Play" UnloadedBehavior="Close" and that is all !!!!

Grouping all these parts will make your UI more performant on Tab Changes as it will avoid reloading each time you change the selected tab, and it will ensure the ffme control to have the right behavior, without troobleshooting when you finally close your main window.

If it helps, please tag this answer.

Regards

**Comment by Arestihub** [comment]
> @Arestihub,
> 
> Finally Done !
> 
> There's a combination of 2 parts to make this goes well !
> 
> 1. Implement An ExtendedTabControl class that extend TabControl, and contains code to make the TabItem Collection not to be unloaded each time we change the selected Tab,
> 2. Avoid trying to do thing with code behind regarding the open/close of the ffme component.
> 
> For the First point, have a look at :
> https://stackoverflow.com/questions/3601125/wpf-tabcontrol-preventing-unload-on-tab-change
> 
> For the second one, look at this :
> 
> * Implement the Media Events on your ctor, and use them only to show onscreen message for debug purposes,
> * If you use a Datacontext as I do, implement StreamViewerView_DataContextChanged Event and in this method, only do that : Media.Source = <your_uri>
> * In your XAML MediaElement control, add : LoadedBehavior="Play" UnloadedBehavior="Close" and that is all !!!!
> 
> Grouping all these parts will make your UI more performant on Tab Changes as it will avoid reloading each time you change the selected tab, and it will ensure the ffme control to have the right behavior, without troobleshooting when you finally close your main window.
> 
> If it helps, please tag this answer.
> 
> Regards


Thank you! I will have a go with this solution as soon as I can (hopefully before the weekend) and report back to you. Does this work for you even if you switch tabs very fast, even multiple times a seconds?

**Comment by LouisCPro** [comment]
@Arestihub,

As the MediaElement is now unloaded anymore, it does not operate any change when switching, even nor stopping the stream, so you can switch from one to another without seeing any problem.
But, Everything there is also related to your PC Video Card capabilities, meaning that some lakes could appear if your videocard has no hard stream decoding caps. But this is another thing….
In my case, it is an H264 network stream coming from a camera, MY video card is a GTX1050, and effectively I do not see any lake when switching even multiple times a seconds.

Hope this help !

**Comment by Arestihub** [comment]
@LouisCPro 

So if I understand correctly, your intention is not to close the streams on the background tab but instead keep them playing?

For that kind of functionality this should work. Unfortunately I am trying to keep the background streams closed (there are a lot of simultaneous streams which would take quite a lot of memory if they ran in the background)

**Comment by LouisCPro** [comment]
@Arestihub,

Not exactly. In my app each stream is defined in a separate control. And for each stream I have multiple tabitems to describe the stream and other stuffs.
When I switch from 1 item to another, It does effectively keep the stream on, but if I switch from one stream definition to another, the stream is stopped.

In a certain way, I have both of the behaviors...And what I noticed is that effectively managing the fmpeg object behavior is not a good way to go. The best is to play with the parent control behavior and let the ffmpeg manage the rules its own way...

**Comment by mariodivece** [comment]
@Arestihub if you are looking into waiting for open and close commands to complete I would suggest you implement a queue that waits for commands sequentially. FFME should also handle closing the media while its opening. The sample app shows a close button while loading a stream and if you click on it it immediately tries to abort the open operation.

**Comment by mariodivece** [comment]
Closing as no further feedback was provided.
