### ISSUE TITLE
Memory leak in MediaBlock.Allocate

### ISSUE THREAD

**Issue by ryanmcbrideusf** [unosquare/ffmediaelement#436]
# Memory leak in MediaBlock.Allocate

I discovered a memory leak in MediaBlock's Allocate() function, while playing a mp4 recording of the same RTSP stream in issue #431. Even though FFME does play the video, memory usage slowly rises until an out of memory exception occurs. I know playing a corrupted mp4 is obviously not supported by FFME, but the leak it causes can easily be fixed:

```csharp
...
using (writeLock)
{
    Deallocate(); // Add this line

    m_Buffer = (IntPtr)ffmpeg.av_malloc((ulong)bufferLength);
    m_BufferLength = bufferLength;
    return true;
}
```

From my observations, the mp4 repeatedly changes its own frame width/height during playback, and this causes Allocate() to create a new buffer, but without deallocating the old one.

## Issue Categories

 - [X] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [X] NuGet Package 4.1.310

## Steps to Reproduce

 1. Play any sort of media that would cause the buffer length to change during playback. (Sorry, I'm not allowed to provide the mp4 recording, it's company policy)
 2. Observe that ffmpeg.av_malloc() is called and m_Buffer is modified. The old buffer is now lost but still allocated.

## Expected Results

 - Memory usage remains mostly constant during playback

**Comment by mariodivece** [comment]
Thanks for the bug report!
