### ISSUE TITLE
Looping Media

### ISSUE THREAD

**Issue by iwarp** [unosquare/ffmediaelement#44]
Trying to get the media element to loop, currently ive been trying in the media_ended event to set the 
```
position=0;
play();
```

Because the position is a dependancyobject its returning when play is called the media isnt ready yet so it never starts.

Ive attempted to do something like this however when ive got muliple players running its they all get quite out of sync. 
```
position=0;
await Task.Run(() => {
    while (mediaME.HasMediaEnded) {
          Task.Delay(1);
    }
});
await Task.Delay(1);
play();
```

Is there a better way to loop the video?

Thanks

**Comment by mariodivece** [comment]
Correct. I still need to fix the commands. I'm getting there. Thanks for your patience.

**Comment by iwarp** [comment]
Anything you could point me at that i could help with a PR?

**Comment by mariodivece** [comment]
you can try the following in the meantime:
```csharp
        private void Media_MediaEnded(object sender, RoutedEventArgs e)
        {
            Media.Stop();
            Media.Play();
        }
```

The problem is that the position need to be a queued property and not reflected directly as it is right now. It should really be a command to update the position if it coming from the dependency property. I'll get there...

Let me know if the above works.

**Comment by mariodivece** [comment]
So? Did this work? It sure works for me...

**Comment by iwarp** [comment]
Yep happy with that as a workaround. 

Thanks

**Comment by mariodivece** [comment]
This is working now that the commanding has been fixed.
```csharp
            Media.MediaEnded += (s, e) =>
            {
                Media.Position = TimeSpan.Zero;
                Media.Play();
            };
```
Please test and reopen if I missed something. Thanks!

**Comment by MrBean2016** [comment]
Great!

**Comment by Symbai** [comment]
For some reason this no longer works. I've applied the code to your sample project but the video is not looping.

**Comment by chengcong** [comment]
you can try this code
 
System.Windows.Application.Current.Dispatcher.Invoke(new Action(() =>
            {
                this.mePlayer.Position = TimeSpan.Zero;
                this.mePlayer.Play();
            }));`
