### ISSUE TITLE
Stretch+Library.EnableWpfMultiThreadedVideo Inconsistently Working

### ISSUE THREAD

**Issue by eatkinola** [unosquare/ffmediaelement#440]
**Stretch+Library.EnableWpfMultiThreadedVideo Inconsistently Working**

When setting Library.EnableWpfMultiThreadedVideo to true, the Stretch property seems to work inconsistently in WPF.  I realize multi-threading is still experimental, though perhaps I am doing something wrong here?

## Issue Categories

 - [x] Bug

## Version Information

 - [x] NuGet Package 4.1.310

 1. Library.EnableWpfMultiThreadedVideo = true
 2. Open and play a video within a WPF application

## Expected Results

 - Sometimes the video is stretched appropriately in its parent container
 - Sometimes it's not stretched and just retains its native aspect ratio
 
P.s. really great library by the way

**Comment by mariodivece** [comment]
I will look into this when I get a chance but please remember that the setting `EnableWpfMultiThreadedVideo` is not supported.
