### ISSUE TITLE
Video doesn't always play when source is changed

### ISSUE THREAD

**Issue by chkmte21** [unosquare/ffmediaelement#441]
Video doesn't always play when source is changed

The issue is that when changing the source, it doesn't always play.

## Issue Categories

 - [x] Bug

## Version Information

  - [x] NuGet Package *4.1.310*

## Steps to Reproduce

 1. Step 1 - Create Mediaelement
 2. Step 2 - Create playlist
 3. Step 3 - Click on an item in playlist to play

## Expected Results

 - Result 1 - The media will play
 - Result 2 - the media will not play
 
### XAML
<UserControl x:Class="Player1"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
             xmlns:local="clr-namespace:ffmeTEST"
             mc:Ignorable="d" 
             d:DesignHeight="238" d:DesignWidth="567">

    <Grid x:Name="WorkGrid" Background="#FFBBBBBB">

        <ffme:MediaElement x:Name="Media" Background="Black" Stretch="Fill" LoadedBehavior="Play" UnloadedBehavior="Manual"/>

    </Grid>

</UserControl>

### .net
Imports System.IO
Imports System.Threading

Public Class Player1

    Public Sub setSource(path As String)

        If File.Exists(path) Then

            Media.Source = New Uri(path)

        End If

    End Sub

    Private Sub Media_MediaEnded(sender As Object, e As EventArgs) Handles Media.MediaEnded

        If Form1.InvokeRequired = True Then
            Form1.Invoke(Sub() Form1.gotoNext())
        Else
            Form1.gotoNext()
        End If

    End Sub

    Friend Sub setsize(width As Integer, height As Integer)

        Media.Height = height
        Media.Width = width

    End Sub

    Private Sub Media_FFmpegMessageLogged(sender As Object, e As Unosquare.FFME.Common.MediaLogMessageEventArgs) Handles Media.FFmpegMessageLogged
        'Console.WriteLine(e.ToString)
    End Sub
End Class

###  .net Main app

Imports System.Globalization
Imports System.IO
Imports System.Threading
Imports AForge.Video
Imports AForge.Video.DirectShow

Public Class Form1

    Dim pWindow1 As New Player1

    Public VideoDevices As New FilterInfoCollection(DirectShow.FilterCategory.VideoInputDevice)

    Public CapDevice As DirectShow.FilterInfo

    Public WithEvents positionChanged As New medPosition

    Public Property indexSelected As Integer

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

        'Path to ffmpeg library -4.2
        Unosquare.FFME.Library.FFmpegDirectory = ($"{Application.StartupPath}\ffmpeg")

        'create integration elementhost
        Dim ElementHost1 As New Integration.ElementHost()

        With ElementHost1
            .BackColor = System.Drawing.Color.Black
            .Name = "ElementHost1"
            .Width = 567
            .Height = 238
            .Child = pWindow1
        End With

        'add the control
        Me.Controls.Add(ElementHost1)
        ElementHost1.Location = New System.Drawing.Point(221, 200)

        'list capture devices
        If Not VideoDevices.Count = 0 Then

            For Each CapDevice In VideoDevices

                ListBox2.Items.Add(CapDevice.Name)

            Next

        End If

        'load some videos
        ListBox1.Items.AddRange(Directory.GetFiles($"{Application.StartupPath}\sampleVideos"))

    End Sub

    Private Sub ListBox2_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListBox2.SelectedIndexChanged

        'play capture device
        pWindow1.Media.Source = New Uri($"device://dshow/?video={ListBox2.SelectedItem}")

    End Sub

    Private Sub ListBox1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListBox1.SelectedIndexChanged

        'set the source
        pWindow1.setSource(ListBox1.SelectedItem)

    End Sub

    Public Sub gotoNext()

        'go to the next item in the playlist

        Dim countItems As Integer = ListBox1.Items.Count - 1

        If ListBox1.SelectedIndex = countItems Then
            ListBox1.SelectedIndex = 0
        Else
            ListBox1.SelectedIndex += 1
        End If

    End Sub

End Class

https://1drv.ms/v/s!AiBujLdr2flClXhBOhCQ-R8fOjjy?e=bKfp4q

**Comment by mariodivece** [comment]
Correct. Your use case is more suited for the API rather than the Dependency Property itself.
The the asynchronous API insted. For example:
1. On selected index changed, disable changing the index.
```csharp
ListBox.Enabled = false;
await media.Open(url);
```

2. Handle the MediaOpened and MediaFailed events
```csharp
await Media.Play();
ListBox.Enabled = true;
```

**Comment by mariodivece** [comment]
Related to issue #252
