### ISSUE TITLE
frames Skipping  with hls in wowza streaming engine

### ISSUE THREAD

**Issue by ghaith100994** [unosquare/ffmediaelement#444]
# Issue Title (*change this title!*)
Hi, I'd like to say thank you for your hard work. I have an question。
I'm using wowza streaming engine to stream vod as hls 
but when i receive the stream through ffpaly or  your windows app 
it's always give me this warning and skip frames

[mpegts @ 000001fd9c444ec0] PES packet size mismatch=    0B f=0/0
[h264 @ 000001fda4b61800] Invalid NAL unit 8, skipping.  0B f=0/0
[h264 @ 000001fda4b61800] error while decoding MB 65 17, bytestream -7
[h264 @ 000001fda4b61800] Cannot use next picture in error concealment

Note: 
although seems like the stream is corrupted when using Vlc no problem occurred 
## Issue Categories
 - [*] Question

## Version Information
This problem appears in 4.2 ffmpeg

## Expected Results
No frame Skipping

**Comment by ghaith100994** [comment]
When I change steaming  protocol from http to rtsp and set tcp_trans to tcp it's work without frames skipping so can i ask why that's happend

**Comment by mariodivece** [comment]
Thanks for your feedback. Correct. This seems to be a problem with ffmpeg itself and not FFME. I can't help you here, but maybe try filing a bug with the ffmpeg team?
