### ISSUE TITLE
Document shortcut keys for the demo app

### ISSUE THREAD

**Issue by glenn-slayden** [unosquare/ffmediaelement#445]
I wasn't able to easily find any user documentation for the demo app. It might be nice to include (e.g.) at least the following info (or more) in a `readme` somewhere, for those who are just trying out your binary release without actually building or having the source code handy.

    'G'                  Example of toggling subtitle color
    Left                 Seek to left
    Right                Seek to right
    '+', VolumeUp        Volume Up
    '-', VolumeDown      Volume Down
    'M', VolumeMute      Mute/Unmute
    Up                   Increase speed
    Down                 Decrease speed
    'A'                  Cycle Through Audio Streams
    'S'                  Cycle Through Subtitle Streams
    'Q'                  Cycle Through Video Streams
    'C'                  Cycle through closed captions
    'R'                  Reset changes
    'Y' / 'H'            Contrast Controls
    'U' / 'J'            Brightness Controls
    'I' / 'K'            Saturation Controls
    'E'                  Example of cycling through audio filters
    'T'                  Capture Screenshot to desktop
    'W'                  Example of recording packets (no transcoding) into a transport stream.
    Escape               Exit fullscreen
    MouseWheel           Zoom

**Comment by mariodivece** [comment]
All added to the readme! Thanks so much!
