### ISSUE TITLE
playing synchronously with multiple players

### ISSUE THREAD

**Issue by qinjianzhanqing** [unosquare/ffmediaelement#447]
I'm playing synchronously with multiple players, but when I detect that the time is consistent and exceeds the set threshold (such as 30ms), then I let the player seek the position, but when the seek is completed, it will wait for a period of time to continue playing, Causing another lag. Failure to achieve the goal of corrective time。What is the solution to this situation?

**Comment by mariodivece** [comment]
See if this helps you: #390

**Comment by mariodivece** [comment]
Closing, since no further feedback was provided.
