### ISSUE TITLE
Can not open the RTP stream via SDP file

### ISSUE THREAD

**Issue by falkerain** [unosquare/ffmediaelement#448]
this client.sdp (the fowlowing data) can be opened by the vlc directly and I thoght, I can open it with ffmedialement too. As soon as I tried to open the sdp file directly in the mediaelement, there is a exception from mediaContainer, this can not be opened because of invalid data... 
The stream server is writing to rtp://127.0.0.1:5004 

v=0

o=- 0 0 IN IP4 127.0.0.1

s=No Name

c=IN IP4 127.0.0.1

t=0 0

a=tool:libavformat 58.20.100

m=video 5004 RTP/AVP 96

a=rtpmap:96 H264/90000

a=fmtp:96 packetization-mode=1;

If I tried to open it by using rtp://@127.0.0.1:5004 ,  and the result is No Audio, no Video or subtitle streams found to decode...

Any idea about how can I open it with ffmediaelement? I have been searching for a long time without any solution. Thank you!

**Comment by Vasilich** [comment]
Please, read the readme for this project.
this project in no form connected to VLC. It uses FFMPEG libraries, and should play every media, that can be played by FFPlay (not VLC!).

**Comment by mariodivece** [comment]
Thanks for your input @Vasilich. Closing as no full command line arguments to `ffplay.exe` were provided.
