### ISSUE TITLE
Passing file location and automatic play

### ISSUE THREAD

**Issue by davidgdoria** [unosquare/ffmediaelement#452]
Hi there, is there a way possible to give the player a location with a file and when it opens reproduce the file automatically?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ X] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
Yes. Something like this (not exact code) should work:
```csharp
mediaEl.LoadedBehavior = Play;
await mediaEl.Open(new Uri(@"c:\myfile.mp4"));
```

The key here is to set the `LoadedBehavior` to `Play` before opening the file. You only need to set this once.

**Comment by davidgdoria** [comment]
Hello again, that was not my question. I asked a way to pass the path the file as exterior param, like querystring.

sorry if it was not explicit
