### ISSUE TITLE
Using the same ffme instance on two windows

### ISSUE THREAD

**Issue by DanVUT** [unosquare/ffmediaelement#453]
Using the same ffme instance on two windows

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [X] Question
 - [ ] Not sure

## Version Information

 - [X] NuGet Package 4.1.310
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

Hi. I would like to ask if it is possible to use one instance of FFME in two different windows? (Or redirect output from one instance in one window into another instance in another window). Because I am trying to do one editing window with smaller preview where I am doing some overlays etc. and second fullscreen window that would contain the mirror image of this first window. If yes, could you tell me how? 

Thank you

**Comment by mariodivece** [comment]
Sure. Take a look at issue #121 - Make sure you read through all the comments because the event arguments have been updated.
