### ISSUE TITLE
how to set the video PlaybackStartTime  and PlaybackEndTime

### ISSUE THREAD

**Issue by qinjianzhanqing** [unosquare/ffmediaelement#454]
1、how to set the video PlaybackStartTime  and PlaybackEndTime；NOW，This property is read-only。
2、The other two videos can fade in and out when switching.

**Comment by mariodivece** [comment]
Sorry, these values are derived from what FFmpeg reads about the media that was loaded. I can't make those writable as there is logic that depends on those being correct. I would suggest you clone the code and experiment with writing to those values. I certainly don't recommend it. Why not use the playback position property to execute your custom code?
