### ISSUE TITLE
Play() Function Doesn't Work

### ISSUE THREAD

**Issue by kimkkh95** [unosquare/ffmediaelement#456]
# Play() Doesn't Work

I made a really simple video player code below, and it doesn't go well

## Question

CS::

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            Unosquare.FFME.Library.FFmpegDirectory = @"C:\ffmpeg";
            InitializeComponent();
        }
        private void Button_Click(object sender, RoutedEventArgs e)
        {
                Media.Source = new Uri(@"C:\Users\Kim\Desktop\bird.avi");
                Media.Volume = 1; 
                Media.SpeedRatio = 1;
                string abc;
                try
                {
                    Media.Play();
                }
                catch (Exception ez)
                {
                    abc = ez.Message;
                }
        }
    }

XAML ::

        <Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
        <Grid Margin="0,0,128,66">
        <ffme:MediaElement x:Name="Media" Background="Gray" LoadedBehavior="Play" UnloadedBehavior="Manual" Margin="51,37,37,-37" />
        <Button Content="파일선택" HorizontalAlignment="Left" Margin="627,55,0,0" VerticalAlignment="Top" Width="75" Click="Button_Click"/>

    </Grid>
    </Window>

FFMPEG Folder::
![FFMPEG](https://user-images.githubusercontent.com/19545569/67443204-d7c61900-f63e-11e9-8dd5-485eae0b86da.PNG)

## Version Information

4.1.310

**Comment by mariodivece** [comment]
Maybe try calling `await media.Play()` in a `media.MediaReady` handler. In your code Play might be called before the video finishes loading. If you want to load and play under the same handler, don't use the `Source` dependency property. Use `await media.Open(...)` and the `await media.Play()`
