### ISSUE TITLE
Add video control controls (play, stop, pause button, etc)

### ISSUE THREAD

**Issue by zgabi** [unosquare/ffmediaelement#457]
# Add video control controls (play, stop, pause button, etc)

The Sample project contains a nice control (ControllerPanelControl.xaml) for the video player. I think it would be useful to add this control to the main nuget package. It would be even better if the different buttons visibility would be configurable. For example in our application we are playing video files without audio. So I'd like to show only the pause, play, stop and full screen icons and the time slider.
We also playing rtsp video stream, it needs no time slider, no icons, except the full screen.

## Issue Categories

 - [X] Feature Request

**Comment by mariodivece** [comment]
Thanks for the compliment! The sample app is just that -- a sample. You are free to use my code to package that control in a NuGet -- that'd be nice. The UI controls themselves are outside the scope of this project.
