### ISSUE TITLE
source link changed when play

### ISSUE THREAD

**Issue by hengway** [unosquare/ffmediaelement#459]
source link changed when play

If the link content %2A%2F will be convert to %252A%252F, this issue happened on sample project as well

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [x] Build From *Master* branch, Commit commit id. : 634ea3b *
 - [x] Build from *Branch Name*, Commit commit id. : 9634627*

## Steps to Reproduce

 1. Input video link to sample project
 2. Hit enter
 3. Error show

![2019-11-01 17_32_58-](https://user-images.githubusercontent.com/6492598/68019753-3474a400-fccf-11e9-919a-695012f4e488.png)

## Expected Results

 - Should be able to play without issue 
 
### Command line ffplay

When using ffplay command no issue
command ffplay:  C:/ffmepg/x64/ffplay "{VIDEO LINK}"

![2019-11-01 17_45_42-Play stream with ffmpeg (ffplay) - Wowza Community](https://user-images.githubusercontent.com/6492598/68020011-ced4e780-fccf-11e9-8335-396c62050fed.png)

**Comment by hengway** [comment]
Hi, I found it cause by this line: var mediaSource = Uri.EscapeUriString(source.ToString());
below is screenshot I capture from autos

![2019-11-01 18_06_51-Unosquare FFME (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/6492598/68020904-866af900-fcd2-11e9-8258-29eec85b0639.png)

**Comment by mariodivece** [comment]
Thanks for the bug report! Could you test with my latest commit please?

**Comment by mariodivece** [comment]
Closing since there was no further feedback
