### ISSUE TITLE
Playback / rendering timing error

### ISSUE THREAD

**Issue by karelholubicka** [unosquare/ffmediaelement#466]
# Playback / rendering timing error
I have a playback problem with FFME,
video frames randomly stutter.

## Issue Categories

 - [ ] Bug
 - [ ] Question

## Version Information
I have originally problem with another application which uses Unosquare MediaElement,
but this behaviour appeared also when I downloaded last FFME version and compiled Windows Sample application.
So I guess it will be enough to track it down directly via Windows Sample app.

 - [ ] Build From *Master* branch

## Steps to Reproduce

Play sample file PBTestAnim60pMute.mov uploaded to 
https://www.uschovna.cz/en/zasilka/SQDVL5GJHPB8E6JE-AKK/39XYXD8D38

## Expected Results

Expected smooth playback, linear movement of red line and all components.
But my resuls is this - see Timing Problems,mp4::
https://www.uschovna.cz/en/zasilka/SQDVL5GJHPB8E6JE-AKK/39XYXD8D38
 
## Detailed description:
Hello, 
I have a playback problem with FFME,
but was unable to track it down enough to supply correct bug report.

Video source and captured result are here:
https://www.uschovna.cz/en/zasilka/SQDVL5GJHPB8E6JE-AKK/39XYXD8D38
PBTestAnim60pMute.mov:
- excludes audio to avoid syncing problems
- 60p to match screen fps and avoid framerate conversion
- H264 MP4 FullHD to avoid any codec and size conversions

And I recorded Timing Problems,mp4:
Captured via vMix Screen capture,
Bigger screen is direct Sample application output to capturer,
smaller is Sample application window captured on comp screen, than cropped and placed over above.
It is delayed 1 frame, otherwise almost identical with direct output.

The capture shows exactly what I get & see.
Machine is poweful enough, so stuttering is not caused by capturing and recording.

I tracked everything back and forth,
including possibility of High precision timer etc.
But through all things I tracked I saw - the
MediaElement.RenderingVideo event
is fired ontime, with reasonable drift.
But image onscreen stutters.

Even When I capture each bitmap at
MediaElement.RenderingVideo event
and send them out via NDI, they run smooth in sequence,
showing even frames that are finally skipped on screen output.

Weird details:
Position indicator  (blue dot) stutters in similar manner as video.
Even when I do not render anything and renderer quickly returns null frames.
But logged CLK values from renderer and from cycle loop 
do look OK and do not explain anything.

Questions:
1/ Do you see also the same problem? I have tested four machines,
Win 10 + Win 7, nVidia, AMD - always stutters. 
WMP, VLC, MPC players play testing file fine.

2/ Any thoughts what it is, to be fixed?

regards, 
Karel Holubicka
Prague
karel@polas.cz

**Comment by mariodivece** [comment]
Stuttering issues should be gone now. Could you try with my latest commit. This issue is related to #446

**Comment by karelholubicka** [comment]
Hi Mario,
yes, latest commit is definitely better.
I believe this part of stuttering issue is fixed now.
 
But still I think it is not fixed completely.
After running several tries of my test file – results:
https://www.uschovna.cz/en/zasilka/SR2783GA5FX92WE7-L2T/EZXIVG5DBG
 
1/ YES - I can get completely smooth playback. But only sometimes, like 10% of tries.
 
2/ BUT-  Other tries have some form of skipping frames, sometimes of repeating pattern.
Interestingly, it manifests mainly on the screen capture, while capturing direct app output is less prone to this,
 
I examined test recording and have found:
There exist frames, which were presented on app output, but did not reach screen.
I believe there is still some form of V-syncing issue,
where some playback runs fits within the sync window and play fine,
but others are partly out of it, 
so stutter on screen, even when all frames are presented on the app output.
 
See my tests, play in your app for yourselves.
 <http://www.uschovna.cz/en/zasilka/SQDVL5GJHPB8E6JE-ZXT> www.uschovna.cz/en/zasilka/SQDVL5GJHPB8E6JE-ZXT
 
Thank you foro your time,
Karel Holubicka
 
BTW I used this almost fixed build DLL into the other app I need to fix,
and surprisingly it did not help at all there ☹.
But this is another story.

**Comment by mariodivece** [comment]
You are correct. I am still experimenting with a number of things. It might be WPF itself. I have tried with WriteableBitmap and InteropBitmab and the results are the same. I am now considering rendering via a D3D image and see if that smoothens things. I will keep you posted.

**Comment by karelholubicka** [comment]
Hi,
 
I mentioned in last post possible problém with V-sync, 
but now I believe it is not the case,
as if you succesfully get image to the screen.
it is always complete, without tearing.
 
But the key is to
get playback timing controlled by V sync timing,
so each rendered frame is presented just once 
(when fps of monitor and playback are equal).
 
It means to render frames with accurate safe time margin 
so they are able to reach screen.
 
When doing VR, which is very rendering and timing demanding,
in openvr API there is function
GetTimeSinceLastVsync(ref float pfSecondsSinceLastVsync,ref ulong pulFrameCounter)
which can give some feedback, 
dunno how it is in WPF, though.
 
Thank you for your effort.
 
Karel Holubicka

**Comment by Mitra-M** [comment]
@mariodivece
>... It might be WPF itself. 

I don't think so , because WPF-Mediaelement is smoother yet. 


@karelholubicka  
> When doing VR, which is very rendering and timing demanding,
in openvr API there is function
GetTimeSinceLastVsync(ref float pfSecondsSinceLastVsync,ref ulong pulFrameCounter)
which can give some feedback,
dunno how it is in WPF

CompositionTarget.Rendering event is equivalent of that in WPF.

also we can use DWM.Fluse() ,  But in my experience it's not accurate.

**Comment by mariodivece** [comment]
@Mitra-M The default MediaElement rendering uses DirectShow as its pipeline. I am making really good progress but the CPU usage is somwhat higher...

**Comment by Mitra-M** [comment]
@mariodivece, I think both problems (stutter and high CPU usage) are related to your timers , As you know for 60 fps we need to 16.66 ms timer , so 
I suggest you use something like [OBS os_sleepto_ns function](https://github.com/obsproject/obs-studio/blob/master/libobs/util/platform-windows.c) to make exact timer (or for sleeping a thread) :

       `   bool os_sleepto_ns(uint64_t time_target)
         {
      	uint64_t t = os_gettime_ns();
      	uint32_t milliseconds;
  
	if (t >= time_target)
		return false;

	milliseconds = (uint32_t)((time_target - t) / 1000000);
	if (milliseconds > 1)
		Sleep(milliseconds - 1);

	for (;;) {
		t = os_gettime_ns();
		if (t >= time_target)
			return true;

		Sleep(0);   // Note :  this gives other threads a chance to run
     	}
       } `

You can make MicroStopwatch (or nano) class  in c# like this :
   
           `public class MicroStopwatch : System.Diagnostics.Stopwatch
           {
               readonly double _microSecPerTick =
                  1000000D / System.Diagnostics.Stopwatch.Frequency;

         public MicroStopwatch()
        {
            if (!System.Diagnostics.Stopwatch.IsHighResolution)
            {
                throw new Exception("On this system the high-resolution " +
                                    "performance counter is not available");
            }
        }

        public long ElapsedMicroseconds
        {
            get
            {
                return (long)(ElapsedTicks * _microSecPerTick);
            }
        }
    }`

Anyway thank you for your effort and your great project.

**Comment by karelholubicka** [comment]
Please do not forget that fps of screen may vary,
We use often 25p, 50i or 50p screen to match playback to TV production.
And we play 25p or 50p content,
so 16.667 ms counter will ruin this scenario.

thank you
Karel Holubicka

**Comment by mariodivece** [comment]
Thanks so much guys for your feedback. Could you please test with my latest commit and give me some more feedback? Thanks so much in advance!

**Comment by andrew-mi** [comment]
Could someone kindly publish this build somewhere for those of us without the VS Preview. Or alternatively, maybe the CI system could be adjusted to publish an artifact for each build.

**Comment by Mitra-M** [comment]
@mariodivece  , I tested it and compared 3 versions.
 Result:
latest official release    CPU usage = %6 ,      Stuttering : too much
2 days ago                   CPU usage = %19 ,    Stuttering : sometimes
Last commit                 CPU usage = %14 ,    Stuttering : sometimes (the same as 2 days ago)

**Comment by Mitra-M** [comment]
@andrew-mi , [last ffme build](http://media4dco.com/downloads/FFME.zip)

**Comment by karelholubicka** [comment]
Hi Mario,
I agree with Mitra.
 
Having slightly more poweful CPU, my numbers are
2 days ago CPU usage = %9 , Stuttering : sometimes
Last commit CPU usage = %6 , Stuttering : sometimes (the same as 2 days ago)
What I see on my playback test:
I believe, the stuttering comes, when playback timer gets in certain  phase with screen refresh.
How to describe:
V refresh is 16.667 ms exact.
Playback timer tries to match this,
but when both are unlocked (timed separately), the playback time update is 16.667 in average,
but real interval can vary say from 15-18 ms (just a guess)
depending on what just happenes in the system. 
 
So what happenes:
During time both unlocked timers shift.
If their difference is „say“ 0,1%, one frame is missed or repeated each 20 seconds.
This is usually hardly noticeable.
But, this would be ideal case.
As playback timer varies 15-18 ms, 
not only 1 frame is affected.
Each 20 seconds image stutters for 2-3 seconds,
as at this time some bitmap updates are fast enough and some not.
After this „short“ stuttering period, playback is then fine again for some time,
until this situation reappears.
 
Solution? Sadly, I am not expert on WPF.
When I wrote Virtual studio, I had to watch output timing interval on BMD decklink device (i.e. its V sync)
and force all bitmap updates to be performed right after output update,
so all updated were succesful and 1:1. No  frame lost, no repeated.
 
regards,
Karel
 
 
 
So.

**Comment by karelholubicka** [comment]
Hi Mario,
I just tested the last build to see the progress 
and yes, 
it uses less CPU, appx 4% instead of 9% on my machine,
but the playback stutters so much that is almost unusable.
 
Should I set some value to get back higher CPU & better timing?
FrameIdealDelayMin?
 
regards,
Karel

**Comment by mariodivece** [comment]
With my latest commit referenced above I see a further reduction in CPU usage and I only see minor stuttering when WPF animations occur. Can you provide feedback using my commit above?

**Comment by karelholubicka** [comment]
Hi,
some tries are perfect (over 50%), but otherwise some complete stuttering disaster may happen. Sometime it stutters, but "recovers" within second or two. 
I did not find any clue yet. 
I will have to record output,
and go through timing logs, frame by frame and find, what actually happenes,
I can do this sometime next week, this requires lots of time.
Anyway, current status is far better than before  :-)
Karel

**Comment by mariodivece** [comment]
I have noticed it stutters when wpf animations occur but it's I believe more related to WPFs rendering thread than the timing itself. You can out put frame-by-frame timing info by examining

```csharp
CycleDurations.Enqueue( ...
```

In my case it stutters very rarely (maybe 1% of the time).
I find that there few and very minor corrections in the CycleDurations list...
Thanks for supporting the project with your time and feedback.

**Comment by Mitra-M** [comment]
@mariodivece ,Thank you a lot ,  ffme is much smoother now. (but not always)

Now the timing is much more accurate than before, but I think you have to synchronize it with the monitor refresh rate to get completely smooth rendering. Because even video players written with native C and C ++ code need VSync to get smooth rendering.

For a test if you play [my video sample file](https://github.com/unosquare/ffmediaelement/files/3659190/VideoSample.zip) with  MPC-HC (I tested ver 1.8.8.22) and change position (by its seek bar) you will see stuttering that is exactly the same as ffme stuttering.
But MPC-HC has a Vsync option (View -> Rendering Settings -> Vsync ) , if you enable vsync then rendering will be smooth absolutely..

**Comment by mariodivece** [comment]
These articles thoroughly explain what I went through:
https://rhnatiuk.wordpress.com/2008/12/21/wpf-video-playback-problems/
https://dzimchuk.net/rendering-video-content-in-wpf-using-a-custom-evr-presenter-and-d3dimage/

In short, WPF does not use a constant framerate. If you try the videos in the Windows 10 `Movies and TV` app you will see the same effects jarking and stuttering effects. Now, both issues #446 and #466 have motivated me to vastly improve the situation. The callbacks are performed on exact time frames but it is impossible to perfectly synchronize such calls to WPF's variable framerate system.

I am all out of ideas at this point on how to v-sync without ugly HwndHost solutions that suffer from airspace issues. Using a custom DirectShow filter with custom EVR presenters that you would need to register on the machine (ax file) as the WPF Media Kit does is also out of the question and would still require the HwndHost solution.

Check out my latest commit and let me know what you think.
Thanks guys!

**Comment by Mitra-M** [comment]
@mariodivece , Thanks for your good explain and links.

1 - I tested your last commit, I think rendering before than your last commit was a little  smoother, tested both  `VideoRendererImageType.WriteableBitmap` and `VideoRendererImageType.InteropBitmap` and believe they have the same result.

2 - My knowledge is much lower than yours but I have an idea :
we can block a thread until the next WPF present by [DwmFlush ](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmflush)API.

in c# :
   
      
       [DllImport("DwmApi.dll")]
        public static extern void DwmFlush();
     
 

I dont know how exactly but maybe you can use that to sync the rendering callback with vertical scan.

**Comment by mariodivece** [comment]
1. Ok thanks for testing again and the feedback. You will notice that every time you fire up the application (and even between opening and closing the same or different files) you will get different "smoothness" results. I do know my thread timing is right at this point. Search the code for `CycleDurations` It is very accurate and compensates with sub-millisecond precision. Cehck it out.

2. Let me try with that! I will report the results using this API.

**Comment by mariodivece** [comment]
Another Option to DwmFlush:
D3DKMTWaitForVerticalBlankEvent

Just tested with DwmFlush and so far looks very promising!

**Comment by mariodivece** [comment]
It looks like dwmflush is very effective! Not perfect, nut shows a great improvement. I need more time to test out D3DKMTWaitForVerticalBlankEvent but I have added the interop code to do it. Could you test with the current commit please and let me know your feedback @Mitra-M ?

I also need to test with multiple videos at the same time and see if dwmflush can be called from multiple instances without a major loss in performance.

**Comment by karelholubicka** [comment]
YES!!
Much better performance, really close what a player should do!
 
So I also compiled net461 version of Unosquare.FFME.Windows
and replaced it in my application,
where I also fixed `Source` dependency property change.
BUT
results there are far worse than in your original Unosquare.FFME.Windows.Sample app.
(yet better, than before).
 
I believed all timig / playback changes were inside Unosquare.FFME.Windows project,
did I miss any special change in Sample app?
 
thank you for your work,
Karel

**Comment by Mitra-M** [comment]
@mariodivece , I was not ware of `D3DKMTWaitForVerticalBlankEvent ` , Thank you so much for it.
Your last commit is worse than before (at least for me) , but VerticalSyncContext class is grate and I am playing with it in your source code .

please keep up , It seems `D3DKMTWaitForVerticalBlankEvent ` is way to go , because in my experience wdm.Flush is not very accurate .

these are 3 new video sample files:
[VideoSamples.zip](https://github.com/unosquare/ffmediaelement/files/3967177/VideoSamples.zip)

**Comment by Mitra-M** [comment]
@karelholubicka , I think you should compile in release mode and test exe file out of VS. when I run it in VS performance is not good although I don't know why.

**Comment by karelholubicka** [comment]
>> I think you should compile in release mode and test exe file out of VS

Yes, I know and I am doing it.
In VS especially first 2-3 runs are "settling down", cannot be taken in account.

Karel

**Comment by Mitra-M** [comment]
it seems CycleDurations  is really accurate.

**Comment by Mitra-M** [comment]
@mariodivece , congratulation , You did the impossible.
I got absolutely smooth rendering with small changes in your code.

**Comment by mariodivece** [comment]
Sorry guys I am returning from a business trip. I will continue the research in a couple of days. Exciting stuff @Mitra-M ! I am looking forward to testing your suggestions!

**Comment by mariodivece** [comment]
Guys you should see all the improvements in the latest master commit including lower CPU usage. V-sync is enabled by default but you can disable it from the UI (first button bottom left corner).
Please post your feedback. I will be hardening the VerticalSyncContext class next.

**Comment by Mitra-M** [comment]
@mariodivece ,  enabled / disable V-sync from UI is perfect , Thank you for your efforts.

Small tip:
Many people use refresh rates other than 60 Hz like 50Hz  , please consider it.
For example in the following code snippet if the refresh rate of the monitor is set to 50 Hz, RefreshRateHz gets a wrong number. (I think)
    
      if (RefreshCount >= 60)
                    {
                        RefreshRateHz = RefreshCount / RefreshStopwatch.Elapsed.TotalSeconds;
                        RefreshStopwatch.Restart();
                        RefreshCount = 0;
                    }

**Comment by mariodivece** [comment]
you mean because of the `if (RefreshCount >= 60)`?
It should just give you the refresh counts per second every 60 cycles but changing it to 50, 100 or 1000 should give you the same results. Give it a shot. I have tested it. Thanks for all your feedback! Finally closing issue now :)

**Comment by karelholubicka** [comment]
Hi Mario,
 
after returning from holidays I tested final version and few older.
Always release, outside VS.
 
Using your Sample App all play better than before (4.1.XXX), 
but none 100% perfect, even with Vsync on.
And in the other my app the version dated 29.11.2019 plays better/smoother than any newer.
Having no idea why.
 
If you are sure your playback is perfect now, 
I must have some problem with my double monitor configuration, graphic driver or something.
 
Have a nice New Year
 
Karel Holubicka
