### ISSUE TITLE
Is x265 supported?

### ISSUE THREAD

**Issue by chiefmb** [unosquare/ffmediaelement#468]
# Is x265 videos are supported?

I didn't see any thing about it in doc and tags and i like to know is this media element support x265?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package 4.2.320
 - [ ] Build From *Master* branch
 - [ ] Build from *Branch Name*

**Comment by mariodivece** [comment]
It depends on your ffmpeg build. Te zeranoe build do have support for h.265
