### ISSUE TITLE
When stepping frame forward/backward a couple of times with arrow keys, an assertion is hit.

### ISSUE THREAD

**Issue by MrBean2016** [unosquare/ffmediaelement#47]
Debug - [h264 @ 146ebe80] Reinit context to 1280x544, pix_fmt: yuv420p
     Debug - SEEK R: Elapsed:     44 | Target:     41.270 | Seek:          0 | P0: 27,607.266 | P1: 27,319.266 
     Debug - SEEK D: Elapsed:     45
     Debug - SEEK L: Elapsed:      0 | Target:     41.229 | Seek:    989,489 | P0: 28,027.181 | P1: 28,027.181 
     Error - Assertion ret <= avpkt->size failed at src/libavcodec/utils.c:2486
     Debug - [h264 @ 146ebe80] Reinit context to 1280x544, pix_fmt: yuv420p
     Debug - SEEK R: Elapsed:     38 | Target:     41.229 | Seek:          0 | P0: 28,027.181 | P1: 27,287.266 
     Debug - SEEK D: Elapsed:     38
     Debug - EVENT START: BufferingStarted
     Debug - EVENT DONE : BufferingStarted

**Comment by mariodivece** [comment]
yeah... I was also wondering about that strange message. Could you please investigate and let me know what is going on???

**Comment by MrBean2016** [comment]
I can look into it, I fetched the latest version with the smoother reverse stepping and it seems that the problem is not there anymore or more difficult to reproduce.

**Comment by mariodivece** [comment]
Are you talking about the master branch or the rapidblocks branch?

**Comment by mariodivece** [comment]
I investigated this issue a little further and it is expected behavior. If I lower the verbosity of the logger the message disappears so it's not an error or anything. 
![image](https://user-images.githubusercontent.com/351978/29618990-65658d52-87df-11e7-807c-46fab8eb7f1c.png)

Closing as there was no further feedback and it's not a problem or error.
