### ISSUE TITLE
Where do I set IsFluidSeekingDisabled = true?

### ISSUE THREAD

**Issue by Symbai** [unosquare/ffmediaelement#472]
# Where do I set IsFluidSeekingDisabled = true?

I noticed the video is playing for 0.5 - 1 second when I jump to a position and the video is paused. I saw a couple of posts (#379, #360, #443)  probably related to that and it was said to set IsFluidSeekingDisabled to true. These posts were more than half a year ago and the nuget package is from December 28, 2019.

However I cannot find where exactly this property is. 

## Issue Categories

 - [X] Question

## Version Information

 - [X] NuGet Package *4.2.330*

**Comment by Symbai** [comment]
Nvm, it has been renamed to IsScrubbingEnabled.

**Comment by mariodivece** [comment]
Correct. The dependency property name is called `ScrubbingEnabled`
