### ISSUE TITLE
Setter of MediaElement.Source property.

### ISSUE THREAD

**Issue by zgabi** [unosquare/ffmediaelement#475]
Setter of MediaElement.Source property.

 - [X] Feature Request
 - [X] NuGet Package 4.2.330

In version 4.2.330 the MediaElement.Source property was changed to get only. Please add back the setter since I'm using this property with WPF data binding. (Normal MediaElement also has a setter for the Source property)
Thanks.

**Comment by tensei** [comment]
same here, i need the setter back

**Comment by zgabi** [comment]
Now the bot will close all the issues which is not solved? :(

**Comment by TechnikEmpire** [comment]
And spam our emails
