### ISSUE TITLE
stream stop on rtsp

### ISSUE THREAD

**Issue by ghaith100994** [unosquare/ffmediaelement#476]
# Issue Title (*change this title!*)
With rtsp stream when stream is paused and buffer reach 💯% which mean that is after 4-6 minutes then resume the stream the stream stop

## Issue Categories

 - Bug
 - Question

## Version Information

 - [ ] NuGet Package 4.2.330

## Steps to Reproduce

 1. Stream from wowza with video on demand
 2. Connect to stream through the sample from the site
 3. Pause for 10 minute then resume 

## Expected Results

 - Reconnect to the stream

**Comment by mariodivece** [comment]
what happens if you do the same in ffplay.exe? Underlying connections are handled by FFmpeg -- not FFME itself so that might be the problem... Let me know your results please.

**Comment by ghaith100994** [comment]
I tried doing what you ask and played the video then pause it 
The same problem happened 🤔🤔🤔
