### ISSUE TITLE
Rendering a single frame

### ISSUE THREAD

**Issue by AndreGroeschel** [unosquare/ffmediaelement#485]
# Rendering a single frame

* We would like to render a WebRTC stream and have frames with data in YUV already coming in. What would be the basic approach to render a single frame? How can we take the WebRTC frame data and display it using FFME?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x ] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
How would you do it in ffmpeg's ffplay.exe?
