### ISSUE TITLE
MediaElement.Open Unable to load FFmpeg libraries

### ISSUE THREAD

**Issue by Hof-Mib** [unosquare/ffmediaelement#486]
# MediaElement.Open FileNotFound Exception
I'm just trying to play a local file. 
Your sample application works fine.
But in my simple app I get an error 
Exception thrown: 'System.IO.FileNotFoundException' in ffme.win.dll
Unable to load FFmpeg libraries.

The Library.FFmpegDirectory is set to the same as in the sample application.

Do anyone have an idea?
Thanks
Greetz
## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [X] Question
 - [ ] Not sure

## Version Information

 - [X] NuGet Package 4.2.330
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

 
### XAML
```xml
 <ffme:MediaElement Grid.Row="0" Name="Media" Background="Black" 
                           LoadedBehavior="Play" IsDesignPreviewEnabled="True"/>
```

### C#
```csharp
       public App()
        {
            Library.FFmpegDirectory = @"E:\ffmpeg shared\bin";
            Library.FFmpegLoadModeFlags = FFmpegLoadMode.FullFeatures;
            Library.EnableWpfMultiThreadedVideo = !Debugger.IsAttached; // test with true and false
        }

await Main.MediaElement.Open(new Uri(FileName));
```

**Comment by Hof-Mib** [comment]
Ok, I got it. 
Was a stupid mistake
My "Any CPU" configuration started a 32Bit process. 
But I only have the 64bit ffmpeg.

That's all. Thank you

**Comment by ju2pom** [comment]
No so stupid question! Thanks for posting the solution because I had the same issue.
