### ISSUE TITLE
Hang on Dispose

### ISSUE THREAD

**Issue by olegsavelos** [unosquare/ffmediaelement#487]
I updated today both Media element and FFMpeg and started to have the application hanging while trying to dispose media element.

FFMPeg latest version 
Media Element 4.2.330

The dispose hangs with this simple code

```
Unosquare.FFME.MediaElement mediaView = new Unosquare.FFME.MediaElement();
mediaView.Open(new Uri("http://techslides.com/demos/sample-videos/small.mp4"));
mediaView.Play();
mediaView.Close();
mediaView.Dispose(); //Hangs here
```
Downgrading to 4.2.270 removes the issue.

**Comment by lamposu** [comment]
I also met this issue

**Comment by mariodivece** [comment]
Yeah. You need to await the Open, Play, and Close calls. Or if not under asynchronous code, use 
.Play.GetAwaiter().GetResult()
