### ISSUE TITLE
RTSP with Digest authentication

### ISSUE THREAD

**Issue by mazurekj** [unosquare/ffmediaelement#488]
# RTSP with Digest authentication

I am trying to connect to an RTSP stream (IP camera) with Digest authentication. But I can't. Trying to use rtsp://<user>:<password>@<ip> does not work (for basic authentication). I do not know how to set user and password in your control.

Using any WPF VLC control, there is a way to set these values through control parameters: 
--rtsp-user 
--rtsp-pwd

## Issue Categories

 - [ x] Feature Request

## Version Information

 - [x ] NuGet Package 4.2.330

**Comment by ememadegbola** [comment]
I think this would be great to see too as the Uri class doesn't allow the credentials to be inlined
