### ISSUE TITLE
Freeze of video

### ISSUE THREAD

**Issue by openlisp** [unosquare/ffmediaelement#5]
Added line in 

Unosquare.FFmpegMediaElement\FFmpeg.Autogen\FFmpeg.avutil.g.cs

public AVBufferRef* hw_frames_ctw;

causing not functionality of video rendering. Video is frozen on the first frame

**Comment by mariodivece** [comment]
@openlisp did you add the line you are suggestion and that fixed the issue or you believe that line is causing the issue?

**Comment by openlisp** [comment]
I was running old version of your project with no problem. The issue started to occur when I updated to current Head. Removing line added in commit  
https://github.com/unosquare/ffmediaelement/commit/9b918043d2fccb66c2842969d3d9a5a0212a37ab
resolved it.

**Comment by mariodivece** [comment]
I don't see how commenting out a variable that is reference nowhere changes anything. In any case, I have taken your suggestion and pushed the change to master

**Comment by superware** [comment]
Seems VERY related to issue #3, once I comment that line it appears everything is playing nicely.
Since AVFrame is a struct, "order" and "alignment" are extremely important, which leads to the conclusion that there's a possible mismatch between the struct definition and used FFmpeg binaries (I'm currently running a 32 bit OS, might behave differently otherwise).

**Comment by mariodivece** [comment]
Order and alignment only matter within a struct itself. It doesn't matter where you define it. It seems very strange indeed...

**Comment by superware** [comment]
Please see [StructLayoutAttribute Class remarks](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.structlayoutattribute(v=vs.110).aspx#Anchor_7): "C#, Visual Basic, and C++ compilers apply the Sequential layout value to structures by default." and [Sequential](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.layoutkind(v=vs.110).aspx#Anchor_1) is "The members of the object are laid out sequentially, in the order in which they appear when exported to unmanaged memory. The members are laid out according to the packing specified in StructLayoutAttribute.Pack, and can be noncontiguous."

So by commenting that field you effectively cut the struct memory size and shifted all following fields up. According to [this](https://www.ffmpeg.org/doxygen/3.0/structAVFrame.html), there's no "hw_frames_ctw" between "chroma_location" and "best_effort_timestamp"... and there might be other differences.

**Comment by mariodivece** [comment]
Ah you're right. I thought you were referring to the definition of the hw_frames_ctw itself. I did not realize it was within a struct itself.
