### ISSUE TITLE
Windows form hangs forever when playing video and hit close button

### ISSUE THREAD

**Issue by namcigar** [unosquare/ffmediaelement#502]
# Windows form hang forever

I used FFME in a simple windows form project (host media element with ElementHost) and it hanged when I play a video and hit Close button. Please help.

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [x] Not sure

## Version Information

 - [x] NuGet Package 4.2.330
 - [x] Build From *Master* branch, Commit e3cac5d

## Steps to Reproduce

 1. Hit play button:
```csharp
private async void btnPlay_Click(object sender, EventArgs e)
        {
            var url = textBox1.Text;
            var target = new Uri(url);
            await mediaElement.Open(target);
            await mediaElement.Play();
        }
```
 2. Form closing event:
```csharp
private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            mediaElement.Close();
        }
```
 3. Hit close button and form will hang forever
 4. Here are log messages:
```
[57:35.989 | DBG | Engine.Commands     ] Direct Command 'Close' accepted. Perparing execution.
[57:36.062 | INF | Container           ] OnStreamReadInterrupt was requested an immediate read exit.
[57:36.100 | DBG | Engine.Commands     ] Dispose Entered. Waiting for Command Manager processor to stop.
[57:36.100 | DBG | Engine.Commands     ] Dispose is waiting for pending direct commands.
```

**Comment by EgoistDeveloper** [comment]
try this
````
mediaElement.Dispose();
```

**Comment by namcigar** [comment]
Thank you, I tried that too but it's still the same.
As you can see in this log messages:
```
[11:04.968 | DBG | Engine.Commands     ] Dispose Entered. Waiting for Command Manager processor to stop.
[11:04.968 | DBG | Engine.Commands     ] Dispose is waiting for pending direct commands.
[11:04.968 | DBG | Engine.Commands     ] Dispose is closing media.
[11:04.985 | INF | Container           ] OnStreamReadInterrupt was requested an immediate read exit.
```
The form is hanged again.

**Comment by namcigar** [comment]
Any ideas?

**Comment by EgoistDeveloper** [comment]
I think it is a kind of bug. Bu I have solution (actually ignore). Download source code go to **[this](https://github.com/unosquare/ffmediaelement/blob/e3cac5df0cb06254501b9a2507d7735aacb479e4/Unosquare.FFME/Container/MediaContainer.cs#L1010)** method and remove all contents, then add `return 0;` You will not get any more interrupt exceptions. But if you are not using net core app but you can probably get the following error **[#496](https://github.com/unosquare/ffmediaelement/issues/496)**.

**Comment by namcigar** [comment]
Thank you,

I tried another workaround:

Go to [this file](https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME/Commands/CommandManager.cs)

Comment out some lines in method **OnDisposing()** like this:

```
            // wait for any pending direct commands (unlikely)
            //this.LogDebug(Aspects.EngineCommand, "Dispose is waiting for pending direct commands.");
            //while (IsDirectCommandPending)
            //    Task.Delay(Constants.DefaultTimingPeriod).Wait();

            this.LogDebug(Aspects.EngineCommand, "Dispose is closing media.");
            try
            {
                // Execute the close media logic directly
                //CommandCloseMedia();
                PostProcessDirectCommand(DirectCommandType.Close, null, false);
            }
            catch (Exception ex)
            {
                this.LogError(Aspects.EngineCommand, "Dispose had issues closing media. This is most likely a bug.", ex);
            }
```
then it worked!

But I still wondering while so I asked for help from you all.

**Comment by EgoistDeveloper** [comment]
This package is working fine with local files or hosted (web) files but streaming part isn't good. Stream latency, buffering etc. I think author should fix these parts but he is seems busy.
