### ISSUE TITLE
Crash when open some files

### ISSUE THREAD

**Issue by defrl** [unosquare/ffmediaelement#503]
A crash occurs when opening some files with MedieElement. No errors in logs or exceptions
With `ffplay` it opens fine
Attached one of the files for example

UPD. Most likely, this is due to the non-standard height and width of the video. In my case, it is 1278x720

## Issue Categories
 - [+] Bug

## Version Information
 - [+] NuGet Package 4.2.330 
 - [+] Build From *Master* branch, Commit e3cac5df0cb06254501b9a2507d7735aacb479e4

### XAML
```xml
<MainWindow>
    <ffme:MediaElement Name="Player" MinWidth="800" MinHeight="450" LoadedBehavior="Manual" UnloadedBehavior="Manual" />
</MainWindow>
```

### C#
```csharp
Player.MessageLogged += (o, args) =>
{
    if (args == null) return;
    Console.WriteLine($"{args.MessageType} | {args.Message}");
};
Player.Loaded += async (sender, args) =>
{
    await Player.Open(new Uri(@"C:\OUTPUT.mp4"));
};
```
[OUTPUT.zip](https://github.com/unosquare/ffmediaelement/files/4675361/OUTPUT.zip)

**Comment by namcigar** [comment]
You can view this project example at [this file](https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME.Windows.Sample/AppCommands.cs)

Look for OpenCommand command and use it.

Ex:
```
var uriString = a as string;
if (string.IsNullOrWhiteSpace(uriString))
    return;

var target = new Uri(uriString);
var m = Player; // your player
var target = new Uri(uriString);
if (target.ToString().StartsWith(FileInputStream.Scheme, StringComparison.OrdinalIgnoreCase))
    await m.Open(new FileInputStream(target.LocalPath));
else
    await m.Open(target);
```

Remember to take [this file's source code](https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME.Windows.Sample/Foundation/FileInputStream.cs) from this project example too :)

**Comment by defrl** [comment]
The problem occurs when opening a some file with a non-standard size (1278x720, 854x480).
I also tried to open this files in a sample project, it also crashes.

**Comment by namcigar** [comment]
You should view this pull request, maybe it's the problem:
https://github.com/unosquare/ffmediaelement/pull/493

**Comment by Th3K1pp3r** [comment]
Whilst not the solution, I came up with a minor modification to the calling client that allows badly sized videos to play.
In the Sample app > MediaRendering > OnMediaOpening there is a line that checks for 'videoStream.PixelHeight' > 1080. When this condition is true a line is appended to the videoFilter 'videoFilter.Append("scale=-1:1080,")'. Parse the videoStream height and width and regularize the values to known video sizes (718, 576 becomes 720,576) and append a line to the videoFilter  'videoFilter.Append("scale=720:576")'. The video now plays as expected.
