### ISSUE TITLE
Rtsp streaming url is not streaming other then vlc, from live555 testH264VideoStreamer

### ISSUE THREAD

**Issue by Bhavyashri** [unosquare/ffmediaelement#510]
I am trying to stream rtsp:// h.264 Elementary Stream from the live555 server.its playing fine with VLC,when ever I checked with other streaming application it is showing that  Sub session: unsupported transport 461.
why it is happening? here im using 8554 port.

Thanks and Regard
Bhavana

**Comment by mariodivece** [comment]
Could you provide me with the full ffplay.exe (NOT FFME) command line args that work for you?
