### ISSUE TITLE
Why m3u8 file is not where users can see it

### ISSUE THREAD

**Issue by telase** [unosquare/ffmediaelement#511]
I will ask my question below
------------------------------------
I changed some parts
1:
App.xaml.cs
           " // Change the default location of the ffmpeg binaries (same directory as application)
            // You can get the 64-bit binaries here: https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-latest-win64-shared.zip
            Library.FFmpegDirectory = @"**C:\Program Files\FFMPEG**" + (Environment.Is64BitProcess ? @"\x64" : string.Empty);"
I created exe for this
https://raw.githubusercontent.com/telase/PRO/master/FFMPEG/Output/FFMPEG.exe
2:
PlaylistViewModel.cs
       "PlaylistFilePath = Path.Combine(root.AppDataDirectory, "**iptv.m3u**");"
the whole list works when we put any iptv m3u in the folder
Note:
any iptv list works as iptv.m3u
Okay,all working
But
AppData\Roaming\Unosquare FFME-Play in normal user cannot see this folder and put any m3u file
I tried to change the folder "PlaylistFilePath" but there was always an error

How can we change the playlist folder on my videos, documents or desktop 
"PlaylistFilePath = Path.Combine(**root.AppDataDirectory**, "iptv.m3u");"

**Comment by telase** [comment]
I found the answer to my question, maybe it will help others

RootViewModel.cs
"AppDataDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.**MyVideos**), ProductName);"
I change it **MyVideos**

to see other folders if you want
[https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=netcore-3.1](url)

**Comment by mariodivece** [comment]
Glad you found the answer yourself! Remember the sample app is just that -- a sample.
