### ISSUE TITLE
Jitter while scrubbing

### ISSUE THREAD

**Issue by dkuc** [unosquare/ffmediaelement#513]
# Jitter while scrubbing

*When scrubbing video, the playback will incorrectly jitter back and fourth between past and future frames.  This is especially noticeable when scrubbing backwards.*

## Issue Categories

 - [X] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [X] NuGet Package *4.2.330*
 - [X] Build From *Master* branch, Commit e3cac5df0cb06254501b9a2507d7735aacb479e4
 - [ ] Build from *Branch Name*

## Steps to Reproduce

 1. Open a video in the sample app
 2. Slowly drag the the position scroll to scrub.
 3. Notice that even when dragging in one direction, it will jitter back and forth incorrectly between frames. 

## Expected Results

 - When scrubbing forward, each frame is played in chronological order and never snaps back to a previous frame.
 - When scrubbing backwards, each frame is played in reverse chronological order and never snaps back to a future frame.
 
## Sample Code

NA- sample app

### Command line ffplay
N/A - sample app

**Comment by mariodivece** [comment]
see issue #483
