### ISSUE TITLE
I can't fix Stuttering when change time position

### ISSUE THREAD

**Issue by tuongtd** [unosquare/ffmediaelement#515]
# I can't fix "Stuttering when seeking backwards"

*I have tried several ways, including this one #483 , but it still hasn't solved the problem.*

## Issue Categories
 - [x] Question

## Version Information

 - [x] NuGet Package *4.2.330*
 - [x] ffmpeg-4.2.2-win64-shared

### XAML
```xml
<ffme:MediaElement x:Name="mediaMain" x:FieldModifier="public" Background="Black" MediaOpened="mediaMain_MediaOpened" OpacityMask="Black" LoadedBehavior="Pause"/>
```

### C#
```csharp
mediaMain.Seek(TimeSpan.FromSeconds(sliderSeek.Value));
```

What other ways can I try now?
Thank!

**Comment by qinjianzhanqing** [comment]
await试试

**Comment by tuongtd** [comment]
> await试试

nothing changes :)

**Comment by qinjianzhanqing** [comment]
opening事件中的配置全部取消掉就可以了
