### ISSUE TITLE
Question: Playback from memory stream

### ISSUE THREAD

**Issue by george-vlahakis** [unosquare/ffmediaelement#516]
Is there a way to play videos from a memory stream? We have very large videos that we would like to load into memory to avoid disk reads in favor of performance.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x ] Question
 - [ ] Not sure

## Version Information

 - [x ] NuGet Package *4.2.330*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

**Comment by CodingOctocat** [comment]
I also need this feature, I also tried `Vlc.DotNet.Wpf` (`VlcMediaPlayer`) and it didn't load successfully either, I'm not very good with that stuff.
