### ISSUE TITLE
Question: Grab raw decoded frames rather than format coverted Bgra frames

### ISSUE THREAD

**Issue by joedemax** [unosquare/ffmediaelement#520]
Hi

Great library. In my application sometiems I need to process frames on the GPU. I see the RenderingVideo event which provides a Bitmap, which always seems to be Bgra32, where as the stream is YUV420. I would like to grab the frames as YUV420 for GPU upload, thus saving memory bandwidth. Is this possible?

Best,

Joe de Max

**Comment by mariodivece** [comment]
This is outside the scope of this project and you should be able to find lengthy discussions on integrating WPF with GPU surfaces (search issues in this project). I have attempted to implement a direct link from a GPU surface to the WPF display system multiple times and so far I have been unable to do so. You could start exploring `VideoComponent.cs`
Search for calls to `HardwareAccelerator.ExchangeFrame` and `MaterializeFrame`

Let me know if you get anywhere...
