### ISSUE TITLE
player state Inaccurate values BUG

### ISSUE THREAD

**Issue by a44281071** [unosquare/ffmediaelement#522]
Demo Code:

```csharp
var player =new Unosquare.FFME.MediaElement();
// ..... load video.
await player.Play();
Console.WriteLine(player.IsPlaying);
// display:
// > false
Console.WriteLine(player.MediaState);
// display:
// > Play
```
correct value is true. But `IsPlaying` property read the result by `MediaCore.Timing.IsRunning`, this is not correct. But `MediaState` have a right play state, and return by `AtomicInteger.Value`.

Nuget package ver: 4.2.330
.net Framework: 4.6.1

**Comment by mariodivece** [comment]
The `IsPlaying` property shows if the clock and the media are running. Sometimes it takes a few milliseconds to get the clocks and media streams going before this property is updated. This is by design.
