### ISSUE TITLE
Is there a way to integrate cryptography? like this command : ffplay -srtp_in_suite AES_CM_128_HMAC_SHA1_80 -srtp_in_params zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz srtp://239.0.0.1:20000 

### ISSUE THREAD

**Issue by dida1it** [unosquare/ffmediaelement#523]
# Issue Title (*change this title!*)

*Please enter a general description for the issue. Delete sections that are not relevant and provide additional sections if necessary.*

## Issue Categories

 - [ ] Bug
 - [x] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Step 1
 2. Step 2
 3. Step 3

## Expected Results

 - Result 1
 - Result 2
 
### XAML
```xml
<MainWindow>
</MainWindow>
```

### C#
```csharp
System.Console.WriteLine("Change Me Please!");
```

### Command line ffplay
```batch
ffplay "hello.mp4"
```
## Delete This Section
- Please consider a donation here: https://www.paypal.me/mariodivece/50usd 
- I work on this project for fun and on my free time.
- Provide as much information as possible and any sample files

**Comment by dida1it** [comment]
ffplay -srtp_in_suite AES_CM_128_HMAC_SHA1_80 -srtp_in_params zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz srtp://239.0.0.1:20000

**Comment by dida1it** [comment]
I found a solution           if (e.MediaSource.StartsWith("srtp://", StringComparison.OrdinalIgnoreCase))
            {
                e.Configuration.PrivateOptions["srtp_in_suite"] = "AES_CM_128_HMAC_SHA1_80";
                e.Configuration.PrivateOptions["srtp_in_params"] = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz";
            }

**Comment by dida1it** [comment]
if (e.MediaSource.StartsWith("srtp://", StringComparison.OrdinalIgnoreCase))
            {
                e.Configuration.PrivateOptions["srtp_in_suite"] = "AES_CM_128_HMAC_SHA1_80";
                e.Configuration.PrivateOptions["srtp_in_params"] = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz";
            }

**Comment by mariodivece** [comment]
Correct! Thanks for sharing your solution!
