### ISSUE TITLE
Question: Edit the segments from m3u8 at runtime

### ISSUE THREAD

**Issue by nr2info** [unosquare/ffmediaelement#524]
Edit segments(.ts) details on runtime

In the mediaelement , I can play the simple m3u8 file from the URL , but I have the URL which have encrypted videos, there are some keys that need to be provided for segments on runtime to decrypt and play.
So , I want to know the detail how the m3u8 file is played and if I want to edit/append some keys in the segments list how can I do that, any help is is greatly appreciated

**Comment by nr2info** [comment]
Still waiting for any help from the community. I am new to ffmpeg based system, so please help me

**Comment by mariodivece** [comment]
Hi @nr2info m3u8 streams are handled internally by FFmpeg. There is no way to change this at runtime. I suggest you write a small web server that constantly reads the m3u8 file from the target URL, modify that file your needs, and finally serve that modified version in your local http server to be played back by ffme. You can easily write a simple web server by using [EmbedIO](https://github.com/unosquare/embedio), another one of our libs :)
