### ISSUE TITLE
Where to get FFMPEG now that ffmpeg.zeranoe.com is down.

### ISSUE THREAD

**Issue by kylewill0725** [unosquare/ffmediaelement#525]
# Where to get FFMPEG now that ffmpeg.zeranoe.com is down.

ffmpeg.zeranoe.com went down on September 18th and I cannot find 4.2.1 shared binaries anywhere else. I would compile it myself but I'm not sure how to target specifically version 4.2.1 using Media Autobuild Suite .

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

**Comment by kylewill0725** [comment]
Currently, this worked for me: https://web.archive.org/web/20200919011114/https://ffmpeg.zeranoe.com/builds/

**Comment by mariodivece** [comment]
I have updated the documentation. Please use the following links (available in the official FFmpeg Dowloads page)
https://www.gyan.dev/ffmpeg/builds/
https://github.com/BtbN/FFmpeg-Builds/releases

Make sure you get the **shared** version for your app architexture (most likely x64)
