### ISSUE TITLE
Allow setting MaxSpeedRatio

### ISSUE THREAD

**Issue by kylelaverty** [unosquare/ffmediaelement#532]
# Allow setting MaxSpeedRatio, missing from current release

Issue https://github.com/unosquare/ffmediaelement/issues/473 was supposed to be a part of release 3.40 and is tracked as part of it but the current code does not actually support setting the max speed ratio.

This change would most likely revolve around setting a value that then gets used in a max compare here:
https://github.com/unosquare/ffmediaelement/blob/c928b1001ec38f0042df436f5fe7142a6a2355be/Unosquare.FFME/Engine/MediaEngineState.cs#L107

## Issue Categories

 - [X] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [X] NuGet Package *4.3.340*

## Expected Results

- Allow for the setting of this value as an optional override to the constant.

**Comment by kylelaverty** [comment]
@mariodivece the bot seems to have marked this as stale and wontfix but you have assigned this to a milestone.

**Comment by mariodivece** [comment]
Changing MaxSpeedRatioContants to 100. Use at your own risk. :)
