### ISSUE TITLE
Use of a reference to .NET5 System.Runtime assembly in .NET48 project

### ISSUE THREAD

**Issue by stf1981** [unosquare/ffmediaelement#535]
# Use of a reference to .NET5 "System.Runtime" assembly in .NET48 project

*NuGet PackageManager says "Unsupported" on the newest version, where are the frameworks listed. When building the app a error comes up that says, that the "System.Runtime" from .NET5 is used but not exists.*

## Issue Categories

 - [ x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [ x] NuGet Package *Unsupported*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Make a .NET48 project
 2. Install the Nuget Package
 3. Use and build it

**Comment by Nisse123** [comment]
It is easy to fix. 
You need to clone the repo  and not use the nuget package
Edit Unosquare.FFME.Windows.csproj
replace the line 
`
<TargetFrameworks>net5.0-windows</TargetFrameworks> with  
<TargetFrameworks>net461;net472;net5.0-windows</TargetFrameworks>
`
Edit Unosquare.FFME.Windows.Sample.csproj
replace the line 
`
<TargetFrameworks>net5.0-windows</TargetFrameworks> with  
<TargetFrameworks>net461;net472;net5.0-windows</TargetFrameworks>
`
In MediaBlockBuffer.cs a system.indexer [^1] (C#8) is used, replaced it with Linq last i.e. change
`
var lastBlock = PlaybackBlocks.Count > 0 ? PlaybackBlocks[^1] : null;
to
var lastBlock = PlaybackBlocks.Count > 0 ? PlaybackBlocks.Last() : null;
`
In LegacyAudioExceptions.cs add
`
using System.Security.Permissions;
`
Rebuild and the .Netframework dlls are found in
Unosquare.FFME.Windows\bin\Release\net472

I suggest that .Netframework compabiltity is maintained.

**Comment by mariodivece** [comment]
fixed in the latest commit. will release new package
