### ISSUE TITLE
Raise an event in case of ReadTimeout

### ISSUE THREAD

**Issue by Arestihub** [unosquare/ffmediaelement#536]
# Raise an event in case of ReadTimeout

Hello.

I am using FFME for RTSP streaming. If the stream is closed in a proper way by the sender there will be an event (MediaEnded or MediaClosed), which can be used to detect the need for stream retry etc.

However if the stream is forced shut by the sender or these is a network error, the only way to detect it seems to be setting ReadTimeout and then looking at the MessageLogged event, which logs an error in case of OnStreamReadInterrupt:
```
https://github.com/unosquare/ffmediaelement/blob/b449fbb960078b3770b52c4bf26dfb0d2cefc5e6/Unosquare.FFME/Container/MediaContainer.cs
```
The mediaelement itself doesn't seem to react to the event in any way. The state of the stream is still playing, the bitrate seems to be fine, there is no buffering ended event etc.

Could OnStreamReadInterrupt event be added to MediaEvents? Is there some other way of detecting the timeout?

## Issue Categories

 - [ ] Bug
 - [x] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package 4.2.320
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Handle OnMediaInitializing event 
 2. Set Configuration.ReadTimeout (5 seconds, for instance)
 3. --> The only event raised in case of timeout seems to be the MessageLogged event

## Expected Results

- Get some sort of proper event in case of stream read timeout
 
### C#
Media Initializing configuration:

```csharp
                e.Configuration.GlobalOptions.FlagNoBuffer = true;
                e.Configuration.GlobalOptions.ProbeSize = 32;
                e.Configuration.PrivateOptions["fflags"] = "nobuffer";
                e.Configuration.PrivateOptions["rtbufsize"] = "10M";
                e.Configuration.PrivateOptions["buffer_size"] = "256k";
                e.Configuration.PrivateOptions["rtsp_transport"] = "tcp";
                e.Configuration.ReadTimeout = TimeSpan.FromSeconds(5);
```

**Comment by Vasilich** [comment]
unstale this in hope that this project isn't abandoned yet..

**Comment by Vasilich** [comment]
unstale

**Comment by mariodivece** [comment]
I've wired it up in the latest commit. Check it out!
