### ISSUE TITLE
Support loading subtitle-only URLs

### ISSUE THREAD

**Issue by mariodivece** [unosquare/ffmediaelement#55]
Currently, there is no way to specify or automatically load a subtitle file. Implement a SubtitleInputContext in the container supporting Play, Stop, Pause and seek operations.

**Comment by bbougot** [comment]
It would be awesome to have thie feature! Do you think it is complex to implement?

**Comment by Ravenglass** [comment]
Hi,

This would be awesome. Any ideas on when we can expect this? Right now I'm loading and adding subtitles separately as an overlay. Would be cool to be able to select external subtitle files. Thanx, this is by far the best MediaElement alternative I've used.

Cheers,

**Comment by mariodivece** [comment]
No exact target date yet. I need to release the 2.0 version this weekend. I will start working on 3.0 features soon enough. If it is any help to you, the Mediaelement contains a good subtitles control already that displays the subtitle stream inside a media file

**Comment by Ravenglass** [comment]
Hi @mariodivece,

Thanx. That might be much better than having a separate textbox. But how would I access and update the text value of the existing control? Could you point me in the right direction?

Cheers,

**Comment by mariodivece** [comment]
In my latest commit you are able to set the attached property like this:
```csharp
Subtitles.SetText(Media, "HEY THERE!");
```

**Comment by mariodivece** [comment]
Latest Commit. See example of side-loading subtitles:
```csharp
        private void Media_MediaOpening(object sender, MediaOpeningRoutedEventArgs e)
        {
            // Example of automatically side-loading SRT subs
            try
            {
                var inputUrl = e.Info.InputUrl;
                var url = new Uri(inputUrl);
                if (url.IsFile || url.IsUnc)
                {
                    inputUrl = System.IO.Path.ChangeExtension(url.LocalPath, "srt");
                    if (System.IO.File.Exists(inputUrl))
                        e.Options.SubtitlesUrl = inputUrl;
                }
            }
            catch { }
        }
```
