### ISSUE TITLE
How to play videos in chunks

### ISSUE THREAD

**Issue by ReDesignedJP** [unosquare/ffmediaelement#550]
# Play video in chunks

*I want to use MediaInputStream to dynamically load bytes of video and play it. What should I do?*

## Issue Categories
 - [x] Question

## Version Information

 - [] NuGet Package *4.2.330*

## Expected Results

- I hope the video continues to play without interruption

**Comment by mariodivece** [comment]
Please refer to issue #434 and related. You need to implement a custom stream.
Hint: totally possible and not that hard. Hope it helps!
