### ISSUE TITLE
Audio in bink files plays too fast

### ISSUE THREAD

**Issue by LorenzoDePasquale** [unosquare/ffmediaelement#554]
# Audio in bink files plays too fast

Opening a bink file causes audio to play too fast and be out of sync with the video. This happens with the sample player too, but doesn't happen with ffplay.exe. In contrast seeking is broken on ffplay.exe but works with your player

This is a really small problem that I am posting here just for curiosity, I don't expect you to support such a niche video format

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

All versions

## Steps to Reproduce

Open any bink video with audio (I can't link any because of copyright, but can send one privately if you are curious)

Anyway many thanks for this awesome project

**Comment by mariodivece** [comment]
Do you see the same results when playing it with ffplay.exe?

**Comment by LorenzoDePasquale** [comment]
Yes, ffplay always worked (but is strangely unable to seek bink files). ffmediaelement could seek but was unable to reproduce audio correctly. 
Anyway I tried again with ffmpeg new 4.4 binaries and now audio works perfectly! I guess the problem was with ffmpeg but I have no idea why ffplay worked
