### ISSUE TITLE
NUGET Package for 4.2.430 Last stable version does not install on .NET Framework 4.8

### ISSUE THREAD

**Issue by LouisCPro** [unosquare/ffmediaelement#555]
When trying to upgrade my FFMPEG package to 4.2.340, VS2019 refuse to finalize because not information of .NET 4.8 Compliance is available in the package !
It is not the case for the 4.2.330, so I mean that it is a dependency problem....

- [X ] Bug

## Version Information

 - NuGet Package *4.2.340*

**Comment by Nisse123** [comment]
You need to clone the repo and not use the nuget package
Edit Unosquare.FFME.Windows.csproj
replace the line
<TargetFrameworks>net5.0-windows</TargetFrameworks>
with
<TargetFrameworks>net461;net472;net48;net5.0-windows</TargetFrameworks>
Edit Unosquare.FFME.Windows.Sample.csproj
replace the line
<TargetFrameworks>net5.0-windows</TargetFrameworks>
with
<TargetFrameworks>net461;net472;net5.0-windows</TargetFrameworks>
In MediaBlockBuffer.cs a system.indexer [^1] (C#8) is used, replaced it with Linq last i.e. change
var lastBlock = PlaybackBlocks.Count > 0 ? PlaybackBlocks[^1] : null;
to
var lastBlock = PlaybackBlocks.Count > 0 ? PlaybackBlocks.Last() : null;
In LegacyAudioExceptions.cs add
using System.Security.Permissions;
Rebuild and the .Netframework dlls are found in
Unosquare.FFME.Windows\bin\Release\net48

**Comment by mariodivece** [comment]
fixed in the latest commit. will release new package

**Comment by LouisCPro** [comment]
Thanks Mario.
