### ISSUE TITLE
Video stuck with SEEK TP warnings

### ISSUE THREAD

**Issue by pieriv** [unosquare/ffmediaelement#557]
# Video stuck with SEEK TP warnings

We have an application that plays some .m4v videos of 7 seconds in looping mode (*LoadedBehavior="Play"* and *LoopingBehavior="Play"*).
Most of the times the videos are played without any issues, but sometimes the played video freezes during its first second and the following warning is output several times (see log in attachment).
```
SEEK TP: Target Pos      0.000 not between 0.040 and 0.320
```
We never call the *seek()* function explicitly, only 
```
mediaElement.Stop();
mediaElement.Close();
mediaElement.ChangeMedia();
mediaElement.Open(uri);
mediaElement.Play();
```

I tried to reproduce the issue playing our videos within the Reference Player, but without success.

Any idea what could be the problem here? Or any suggestion for a workaround that could avoid the freeze?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package 4.2.330, ffmpeg library version 4.2
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Attachment

[FrozenVideoWithSeekWarnings.txt](https://github.com/unosquare/ffmediaelement/files/6051421/FrozenVideoWithSeekWarnings.txt)

**Comment by mariodivece** [comment]
yes... all those operations are asynchronous. Use the `await mediaElement.Stop();`, `mediaElement.Close();`, etc. Hope it helps!
