### ISSUE TITLE
how to play NamedPipe Stream in FFME

### ISSUE THREAD

**Issue by newsoneisb** [unosquare/ffmediaelement#559]
i'm trying to play named pipe source in ffme but i think i'm not giving pipe url in correct way because it is not contacting with server
i tested with below commands but none of this working
await Media.Open(new Uri("pipe://pipename"));
await Media.Open(new Uri("device://pipe/pipename")); 
await Media.Open(new Uri("\\.\pipe\pipename"));

and ffplay is playing with "ffplay -i \\.\pipe\pipename"

and yes other input sources are working correctly in ffme like
await Media.Open(new Uri("udp://127.0.0.1:4222"));

## Issue Categories
Not sure

## Version Information
 FFME Windows 4.3.340

## Steps to Reproduce

 1. await Media.Open(new Uri("device://pipe/pipename"));
 2. await Media.Open(new Uri("pipe://pipename"));

**Comment by newsoneisb** [comment]
continue

**Comment by mariodivece** [comment]
Please refer to issue #434
Hint: totally possible and not that hard. Hope it helps!
