### ISSUE TITLE
[Question] How to get screencaps?

### ISSUE THREAD

**Issue by hutterm** [unosquare/ffmediaelement#569]
# Is there a way to get screencaps from a video with this library?

I want to implement some kind of preview onto a time slider when hovering with the mouse.
Is there a convenient way to use this library for that or do I have to resort to external ways?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

**Comment by MattE303** [comment]
the ability to obtain a keyframe image for a specified timecode/position would be useful to me as well.

**Comment by hutterm** [comment]
the way I solved it for now is to open the file in a secondary `MediaElement` as well and then use `Seek` and `CaptureBitmapAsync` but this feels quite hackish

**Comment by mariodivece** [comment]
the `CaptureBitmapAsync` method works. If you'd need a more precise and complex alternative, subscribe to the `RenderingVideo` event of the control.
