### ISSUE TITLE
Support for SMPTE timecode

### ISSUE THREAD

**Issue by MrBean2016** [unosquare/ffmediaelement#59]
It would be very nice to have support to SMPTE timecode.
It is implemented in https://www.ffmpeg.org/doxygen/2.1/libavutil_2timecode_8c.html and maybe it is already available?
One need the current frame number as input.

**Comment by mariodivece** [comment]
I am unsure how this would help... I read about this and it's basically the information on coded picture number + PTS. Could you explain how you would benefit from this?

**Comment by MrBean2016** [comment]
The SMPTE code is very useful when editing and composing video and audio tracks and it is an industry standard.  http://support.3playmedia.com/hc/en-us/articles/227730848-SMPTE-Timecode-Explained
FFMPEG already has library for this and by providing the current frame number, one get the SMPTE-code so that is rather easy. 
Is the current frame number known?
In the sample app, the current position is displayed with millisecond, replace milliseconds with the frame number, then we have the SMPTE-code, but it must be from the ffmpeg library since it take missing frames in account.
Example of SMPTE display https://static1.squarespace.com/static/54d696e5e4b05ca7b54cff5c/t/5847cdaa9de4bb12d1b98ffb/1481101471071/SMPTE+timecode+layout?format=750w

**Comment by MrBean2016** [comment]
The sample app then should have toggle play/pause with the space key and single frame step forward/backward with arrows key.

**Comment by MrBean2016** [comment]
Great, I asked Ruslan-B to include timecode in FFMpeg.AutoGen so he did a new version, was going to create Pull Req for that but the job was already done.

**Comment by mariodivece** [comment]
Ok, so there is a new property available called VideoSmtpeTimecode
Check it out and let me know if this is what you were expecting. If so, please go ahead and close this issue.
![image](https://user-images.githubusercontent.com/351978/29035415-2101339e-7b61-11e7-9610-49f01ba4613b.png)

**Comment by MrBean2016** [comment]
Great! I have tested with some files with different framerates and the calculation seems to be correct.
Good decision with the Cancel-implementation!
