### ISSUE TITLE
Reducing latency for live network streams

### ISSUE THREAD

**Issue by superware** [unosquare/ffmediaelement#6]
`InputFormatContext->iformat->flags |= ffmpeg.AVFMT_FLAG_NOBUFFER | ffmpeg.AVFMT_FLAG_NOFILLIN;`

Reduces latency in the FFmpeg layer, but how is it possible to reduce latency in the player? In my case, I need it to be very low, something like 250-350 ms.

**Comment by mariodivece** [comment]
I setup a VideoFramesCache and an AudioFramesCache they both are setup to contain 1 second worth of frames: 0.5 backwards and 0.5 seconds forward. So by default ffme lags by about 500ms. Check this out:
<pre>
this.VideoFramesCache = new FFmpegMediaFrameCache(this.VideoFrameRate, MediaFrameType.Video);
</pre>

**Comment by mariodivece** [comment]
Thanks for the flags tip. I have just pushed your flags suggestion to master.

**Comment by superware** [comment]
Hi Mario, thanks! I'm still experimenting with these flags, I'll let you know the results ASAP.

Regarding buffering (is "cache" the right term? :) ), and you know the code much better, is it possible to have an IsBufferingEnabled property that will indicate the player to render frames as soon as they arrive from FFmpeg? effectively overriding any buffering mechanism.

I see you already have an internal IsLiveStream, maybe it will be a good idea to include a BufferDuration TimeSpan property, and if it's zero then disable buffering all together.

What do you think?

**Comment by mariodivece** [comment]
Buffering is to wait for a certain number of frames to arrive from media stream, while Caching is the saving of those buffered or non-buffered frames to a temporary location so you can reuse them and do stuff like moving to previous frames without seeking (seeking is expensive) and being able to play at 4x or 8x speed. If you simply remove the cache you will lose all these features and you will end up with a stuck player most of the time. As far as reducing the size of the audio and video caches, you can give it a shot and see how it behaves for you here:

FFmpegMedia.cs, lines 95 and 96
Example: Change
<pre>
this.VideoFramesCache = new FFmpegMediaFrameCache(this.VideoFrameRate, MediaFrameType.Video);
this.AudioFramesCache = new FFmpegMediaFrameCache(this.AudioSampleRate / 1000M, MediaFrameType.Audio);
</pre>

To:

<pre>
this.VideoFramesCache = new FFmpegMediaFrameCache(10, MediaFrameType.Video);
this.AudioFramesCache = new FFmpegMediaFrameCache(this.AudioSampleRate / 10000M, MediaFrameType.Audio);
</pre>

And try how it behaves.

**Comment by mariodivece** [comment]
No firther comments received and flags were implemented as suggested. Closing issue.
