### ISSUE TITLE
Playing files with multiple video tracks

### ISSUE THREAD

**Issue by ruffoa** [unosquare/ffmediaelement#61]
Is there a way to play video files with multiple video streams and display all of the streams at once?  Currently I am using 4 FFMediaElements, with one per stream, however playback is not always in sync due to the slight delay between opening the first stream and the last one.  In addition, I am having issues keeping the videos in sync while seeking, using the reference player.

Apologies if this is the wrong place to ask for help, I could not find anywhere else.
Thanks!

**Comment by mariodivece** [comment]
You are doing the right thing: 1 media element per file. You should be able to keep them synchronized by setting the loadbehavior of all media elements to pause and calling play on all of them. Use a dispatcher timer to check for the position property of all elements. If one or more go out of sync, simply set the position property and call play again. I hope I made sense.
