### ISSUE TITLE
Please update to ffmpeg ver_5.x

### ISSUE THREAD

**Issue by a44281071** [unosquare/ffmediaelement#617]
ffmpeg new version is 5.x. And the old version 4.4.x Win32 have some bugs. Like that audio device capture did not work.

**Comment by SCAR101** [comment]
+1

**Comment by MaxIvanov8** [comment]
+1

**Comment by MrBean2016** [comment]
There is a fork that took all PRs, built FFMediaElement against .Net 6 and FFMpeg 6 and published a Nuget-package

https://www.nuget.org/packages/zgabi.FFME.Windows/

https://github.com/zgabi/ffmediaelement/commits/master/
