### ISSUE TITLE
Please update to ffmpeg5.0.Everyone is waiting For YOU.GOGO~

### ISSUE THREAD

**Issue by Dhy931010** [unosquare/ffmediaelement#619]
# Issue Title (*change this title!*)

*Please enter a general description for the issue. Delete sections that are not relevant and provide additional sections if necessary.*

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Step 1
 2. Step 2
 3. Step 3

## Expected Results

 - Result 1
 - Result 2
 
### XAML
```xml
<MainWindow>
</MainWindow>
```

### C#
```csharp
System.Console.WriteLine("Change Me Please!");
```

### Command line ffplay
```batch
ffplay "hello.mp4"
```
## Delete This Section
- Please consider a donation here: https://www.paypal.me/mariodivece/50usd 
- I work on this project for fun and on my free time.
- Provide as much information as possible and any sample files

**Comment by cqgis** [comment]
+1

**Comment by SCAR101** [comment]
+1

**Comment by LeoCarriere** [comment]
+1

**Comment by kuangxj** [comment]
Buy KFC for Mario Di Vece, There are quite a few APIs in the new version.

**Comment by MrBean2016** [comment]
There is a fork that took all PRs, built FFMediaElement against .Net 6 and FFMpeg 6 and published a Nuget-package

https://www.nuget.org/packages/zgabi.FFME.Windows/

https://github.com/zgabi/ffmediaelement/commits/master/

**Comment by mariodivece** [comment]
I just updated the source to .net 8 and FFMpeg 7. I'm gathering some fixes from other forks of the projects. I'll release a preview NuGet.
