### ISSUE TITLE
Throw a 'StreamReadInterrupt timed out' after pause more than 1 min

### ISSUE THREAD

**Issue by RyanYANG52** [unosquare/ffmediaelement#62]
Hi, first of all, awesome project, looking forward to the stable release!

I am try to find a replacement for media element, it needs extra codec on client machine to play mkv file on win7. So I try with the example, found a couple of things:

1. Load and play a local video file(mkv, h264), pause, then wait about 1 min, **click** on the PositionSlider. The position will go to the end. In 'SeekCommand' ->'m.Blocks[main].RangeEndTime' will became TimeSpan.Zero. With the following exception on output window.

   Info - INIT FFMPEG: 3.3.2
   Warning - Invalid format option: 'usetoc'
   Warning - Invalid format option: 'user_agent'
   Warning - Invalid format option: 'headers'
   Warning - Invalid format option: 'multiple_requests'
   Warning - Invalid format option: 'reconnect'
   Warning - Invalid format option: 'reconnect_at_eof'
   Warning - Invalid format option: 'reconnect_streamed'
   Warning - Invalid format option: 'reconnect_delay_max'
Exception thrown: 'System.InvalidOperationException' in WindowsBase.dll
     Debug - OpenCommand: Entered
     Debug - COMP AUDIO: Start Offset:      0.000; Duration:    389.376
     Debug - COMP VIDEO: Start Offset:      0.000; Duration:    389.376
     Debug - OpenCommand: Completed
     Debug - SYNC BUFFER: Buffering Started.
     Debug - SYNC BUFFER: Buffering Finished. Clock set to      0.000
   Warning - SYNC AUDIO: LATENCY:      0.169 | SKIP (samples being rendered too late)
     Debug - SEEK D: Elapsed:     48 | Target:    177.417
The thread 0x27d0 has exited with code 0 (0x0).
     **Error - StreamReadInterrupt timed out with      84.000**
     **Error - [matroska,webm @ 06af10e0] Read error**
   Warning - SEEK TP: Target Pos    163.601 not between 0.000 and 0.000
     Debug - SEEK D: Elapsed:     31 | Target:    163.601
     Debug - SYNC BUFFER: Buffering Started.
     Debug - SYNC BUFFER: Buffering Finished. Clock set to      0.000

     I try with 3 diff video, all have the same result(all mkv, h264)

2. Local file name contain '@' will cause 'Invalid URI: The format of the URI could not be determined.' 

3. When a video is playing, change the position will pause the video, I don't know if that was by design. I saw you use 'WasPlaying' in your example to resume playing after mouse up, but it will not work the first time you **click** on the slider, 'WasPlaying' is false. If you drag the thumb while playing if will work, and after that you can click to seek and resume play. I think that is an issue for the example, something with position changed and mouse down which came first.

4. Three Video I tested, two have audio,  When setting LoadedBehavior = "Pause", the one without audio will pause to the first video frame, the other two will be black, and if you don't play just drag slider, it will remain black screen. And... if you load another file before you play the video, the program will stuck at CloseCommand -> handle.WaitOne();

5. Two progressbars in the example BufferingProgress and DownloadProgress, best have a Mode=OneWay in the binding expression, because RangeBase.Value is BindsTwoWayByDefault, and  BufferingProgress is readonly. Will cause a exception when switch to .net 4.6.2

Finally, if you can not reproduce those small issues , please let me know. 
Best regards

**Comment by mariodivece** [comment]
This is exactly the kind of feedback that is extremely helpful!! Thanks so much I will work on these.

**Comment by mariodivece** [comment]
I cannot reproduce the 2 item. I was able to play the file with an @ character in its filename without issues. Could you please provide and example Uri?

**Comment by RyanYANG52** [comment]
maybe it's my os'problem, '2@.en.mkv' 
I will try with another pc when I am back to office next Monday, let you know then

**Comment by mariodivece** [comment]
Part 1 should now be fixed. Very good catch!
Part 4 should also be fixed. If not, could you provide the sample files?

**Comment by RyanYANG52** [comment]
Hi,  mariodivece
I tested all the issues I found, worked perfectly! Url problem should be my OS'problem. You can close the issue now, I will continue play with your library this week, if something new came up, I'll let you know.

**Comment by mariodivece** [comment]
Ok, I appreciate your feedback @RyanYANG52 
Thanks again!
