### ISSUE TITLE
Does not compile with VS2015

### ISSUE THREAD

**Issue by Mitra-M** [unosquare/ffmediaelement#63]
I can't compile it with VS2015 , Is it for VS2017 only?

**Comment by mariodivece** [comment]
It is not because of VS. It is because this project uses c# 6 features. Try enabling c# 6 in VS2015. https://blogs.msdn.microsoft.com/webdev/2015/12/07/new-feature-to-enable-c-6-vb-14/

**Comment by Mitra-M** [comment]
It works.
Thank you very much for the great project.
