### ISSUE TITLE
Can't load ffmpeg in a signed project

### ISSUE THREAD

**Issue by saturne1606** [unosquare/ffmediaelement#64]
I'm trying to use your library in a signed project.
On ffmeg assemblies loading, i have an exception because assemblies have not à strong name.
You do a great work. Thanks

**Comment by mariodivece** [comment]
Hey thanks. The ffmpeg dlls are not assemblies. They are unmanaged c libraries. I suppose you would need to sign the ffmpeg dlls with something like signtool. What is the error message you are getting?

**Comment by MrBean2016** [comment]
You can load unsigned assemblies dynamically, it is rather easy to implement,
https://stackoverflow.com/a/14859591/4146066

You can also try so signed them yourself. 
@saturne1606 You can try this ( https://brutaldev.com/post/NET-Assembly-Strong-Name-Signer ) and update the issue if this solves your problem.

**Comment by saturne1606** [comment]
Sorry for my inexperience. I forgot to sign FFmpeg.Autogen :-( . It works like a charm after that.
I have another issue, but it's not related, i will create another thread for it.
