### ISSUE TITLE
Audio pitch is changing when increasing the speed ratio

### ISSUE THREAD

**Issue by RaoHammas** [unosquare/ffmediaelement#643]
Is there a way to keep the audio pitch the same as the original while changing the speed ratio of the video?

Thanks.

**Comment by Mitra-M** [comment]
Yes, just copy SoundTouch.dll to ffmpeg folder

**Comment by mariodivece** [comment]
Thanks for replying @RaoHammas. That is correct. [Here's the link to the lib](https://www.surina.net/soundtouch/).

**Comment by fushihara** [comment]
このissueを見た人への説明
動画の再生速度を変更した時にオーディオのピッチを維持したい場合は
SoundTouch Audio Processing Library の バージョン 2.1.1 が必要です。

DLのリンク先はこちら
https://www.surina.net/soundtouch/download.html#:~:text=SoundTouch%20DLL%20library%202.1.1%20for%20Windows
zipファイルの中にあるdllを、 SoundTouch.dll にリネームしてffmpeg と同じフォルダに配置します。

各ファイルのハッシュ値は以下の通り
soundtouch_dll-2.1.1.zip 190,656 byte , CRC32: 0D87C9F9
SoundTouch.dll  146,624 byte, CRC: 45FA1D6A
SoundTouch_x64.dll 174,272 byte , CRC: 45FA1D6A

ffmediaelement レポジトリのreadmeにも記載されています。
> If you'd like audio to not change pitch while changing the SpeedRatio property, you'll need the `SoundTouch.dll` library v2.1.1 available on the same directory as the FFmpeg binaries. You can get the [SoundTouch library here](https://www.surina.net/soundtouch/).

コミット 72f2c791dfbb74234b8976ef5ae43f2dc46f678e で確認
