### ISSUE TITLE
Using as a WPF User Control

### ISSUE THREAD

**Issue by KodeKooker** [unosquare/ffmediaelement#68]
Hi, is it possible to convert sample project (Unosquare.FFME.Sample) to a WPF User Control?
If yes, how to reference ffmpeg binaries putting them inside my project? Can you provide an example, please?

**Comment by mariodivece** [comment]
Sure it is possible to convert the sample app into a User Control. But you need to do that on your own. I am closing this issue because it is not related to FFME. https://msdn.microsoft.com/en-us/library/cc294992(v=expression.40).aspx
