### ISSUE TITLE
HorizontalAlignment="Center" when Stretch="UniformToFill"

### ISSUE THREAD

**Issue by dmansurov83** [unosquare/ffmediaelement#7]
I want align widescreen video by center when its playling fullscreen.
Inbuild MediaElement works correctly with HorizontalAlignment="Center"

**Comment by mariodivece** [comment]
Could you attach some screenshots of what you want to accomplish? I am not sure I understand what you mean.

**Comment by dmansurov83** [comment]
![2016-09-20_15-10-02](https://cloud.githubusercontent.com/assets/17178991/18669617/7e905734-7f44-11e6-92e7-2fdf2a1d2d76.png)
![2016-09-20_15-10-53](https://cloud.githubusercontent.com/assets/17178991/18669620/7eacce46-7f44-11e6-84a2-18e060520edf.png)

**Comment by dmansurov83** [comment]
I solve this by override HorisontalAligment property in MediaElement.cs
`public new HorizontalAlignment HorizontalAlignment
        {
            get
            {
                return base.HorizontalAlignment;
            }
            set
            {
                ViewBox.HorizontalAlignment = value;
                base.HorizontalAlignment = value;
            }
        }`

**Comment by mariodivece** [comment]
I just committed your suggested change
