### ISSUE TITLE
Higher SpeedRatios (>1) produce high-pitch audio.

### ISSUE THREAD

**Issue by MonkeyDoll** [unosquare/ffmediaelement#70]
`<ffme:MediaElement Name="VideoPlayer1" SpeedRatio="2" />`
With this setting, Video's audio will be generated a high pitched audio.

**Comment by mariodivece** [comment]
Correct. That is the expected behavior. What were you expecting?

**Comment by MonkeyDoll** [comment]
I see, I am expected the normal audio pitch. In this case any solution to customize/config a player ?
I am doing multiple cross platform video player which is Android iOS OS X when set speed ratio will result that audio playing at normal pitched. but Windows will result different one.
You also can try Youtube's 2X speed.
Is that possible ?

**Comment by mariodivece** [comment]
Any additional comments to help out here?

**Comment by MonkeyDoll** [comment]
Thank you very much, I will use current behavior first and integrate later if any further algorithm available. And also if i able to fix it by my self will share code here.

**Comment by guoluming** [comment]
@MonkeyDoll    if u expected the normal audio pitch,try soundtouch.dll ,it`s works well.
```
public int Read(byte[] targetBuffer, int targetBufferOffset, int requestedBytes)
        {
            lock (SyncLock)
            {
                try
                {
                    WaitForReadyEvent.Set();

                    // Render silence if we don't need to output anything
                    if (MediaElement.IsPlaying == false || SpeedRatio <= 0d || MediaElement.HasAudio == false || AudioBuffer.ReadableCount <= 0)
                    {
                        Array.Clear(targetBuffer, targetBufferOffset, requestedBytes);
                        return requestedBytes;
                    }

                    // Ensure a preallocated ReadBuffer
                    if (ReadBuffer == null || ReadBuffer.Length < (int)(requestedBytes * Constants.MaxSpeedRatio))
                        ReadBuffer = new byte[(int)(requestedBytes * Constants.MaxSpeedRatio)];

                    if (stBuffer == null || stBuffer.Length < (int)(requestedBytes * Constants.MaxSpeedRatio))
                        stBuffer = new short[(int)(requestedBytes * Constants.MaxSpeedRatio / BytesPerSample)];
                    // Perform AV Synchronization if needed
                    if (MediaElement.HasVideo && Synchronize(targetBuffer, targetBufferOffset, requestedBytes) == false)
                        return requestedBytes;

                    // Perform DSP
                    //if (SpeedRatio < 1.0)
                    //{
                    //    ReadAndSlowDown(requestedBytes);
                    //}
                    //else if (SpeedRatio > 1.0)
                    //{
                    //    ReadAndSpeedUp(requestedBytes, true);
                    //}
                    if (SpeedRatio != 1.0)
                    {
                        st.SetTempo((float)SpeedRatio);
                        var bytesToRead = (int)(requestedBytes * SpeedRatio).ToMultipleOf(SampleBlockSize);

                        var samplesToRead = bytesToRead / SampleBlockSize;
                        var samplesToRequest = requestedBytes / SampleBlockSize;
                        while (st.NumSamples() < samplesToRequest && AudioBuffer != null)
                        {
                            var realBytesToRead = Math.Min(AudioBuffer.ReadableCount, bytesToRead);
                            realBytesToRead = (int)(realBytesToRead * 1.0).ToMultipleOf(SampleBlockSize);
                            AudioBuffer.Read(realBytesToRead, ReadBuffer, 0);

                            Buffer.BlockCopy(ReadBuffer, 0, stBuffer, 0, realBytesToRead);

                            st.PutSamples_i16(stBuffer, (uint)(realBytesToRead / SampleBlockSize));
                        }

                        uint numSamples = st.soundtouch_receiveSamples_i16(stBuffer, (uint)samplesToRequest);
                        Array.Clear(ReadBuffer, 0, ReadBuffer.Length);
                        Buffer.BlockCopy(stBuffer, 0, ReadBuffer, 0, (int)(numSamples * SampleBlockSize));
                    }
                    else
                    {
                        if (requestedBytes > AudioBuffer.ReadableCount)
                        {
                            Array.Clear(targetBuffer, targetBufferOffset, requestedBytes);
                            return requestedBytes;
                        }

                        AudioBuffer.Read(requestedBytes, ReadBuffer, 0);
                    }

                    ApplyVolumeAndBalance(targetBuffer, targetBufferOffset, requestedBytes);
                }
                catch (Exception ex)
                {
                    MediaElement.Logger.Log(MediaLogMessageType.Error, $"{ex.GetType()} in {nameof(AudioRenderer)}.{nameof(Read)}: {ex.Message}. Stack Trace:\r\n{ex.StackTrace}");
                    Array.Clear(targetBuffer, targetBufferOffset, requestedBytes);
                }

                return requestedBytes;
            }
        }
```
[](http://www.surina.net/soundtouch/sourcecode.html)

**Comment by guoluming** [comment]
http://www.surina.net/soundtouch/sourcecode.html

**Comment by MonkeyDoll** [comment]
@guoluming Thank you very much !

**Comment by mariodivece** [comment]
@guoluming could you provide me with better instructions? what the st object you are referring to? How do you import the dll? Are there any DllImports? My idea is that if soundtouch.dll is available in the FFmpeg directory, then load it up and use it to perform the DSP.

**Comment by mariodivece** [comment]
Nevermind. I see all that I need here:
http://www.surina.net/soundtouch/soundtouch_dll-2.0.0.zip

**Comment by guoluming** [comment]
fine. SoundTouch source codes .zip contains c# examples.http://www.surina.net/soundtouch/soundtouch-2.0.0.zip.

**Comment by guoluming** [comment]
just put soundtouch.dll in the execution directory,add soundtouch.cs in project.
	
	```
////AudioRenderer.cs
	using soundtouch;
	
	internal sealed class AudioRenderer : IDisposable, IRenderer, IWaveProvider
    {
	    public SoundTouch st;
	}
	
	/// <summary>
    /// Initializes the audio renderer.
    /// Call the Play Method to start reading samples
    /// </summary>
    private void Initialize()
    {
	    st = new SoundTouch();
        st.SetChannels((uint)WaveFormat.Channels);
        st.SetSampleRate((uint)WaveFormat.SampleRate);
	}
	
	public int Read(byte[] targetBuffer, int targetBufferOffset, int requestedBytes)
    {
	//Refer to the above comments
	}
```

**Comment by guoluming** [comment]
just put soundtouch.dll in the execution directory,add soundtouch.cs in project.
	
```
	////AudioRenderer.cs
	using soundtouch;
	
	internal sealed class AudioRenderer : IDisposable, IRenderer, IWaveProvider
    {
	    public SoundTouch st;
		private short[] stBuffer = null;
	}
	
	/// <summary>
    /// Initializes the audio renderer.
    /// Call the Play Method to start reading samples
    /// </summary>
    private void Initialize()
    {
	    st = new SoundTouch();
        st.SetChannels((uint)WaveFormat.Channels);
        st.SetSampleRate((uint)WaveFormat.SampleRate);
	}
	
	public int Read(byte[] targetBuffer, int targetBufferOffset, int requestedBytes)
    {
	//Refer to the above comments
	}
```

**Comment by guoluming** [comment]
just put soundtouch.dll in the execution directory,add soundtouch.cs in project.
	
	```
////AudioRenderer.cs
	using soundtouch;
	
	internal sealed class AudioRenderer : IDisposable, IRenderer, IWaveProvider
       {
	    public SoundTouch st;
	   private short[] stBuffer = null;
	}
	
	/// <summary>
       /// Initializes the audio renderer.
       /// Call the Play Method to start reading samples
       /// </summary>
       private void Initialize()
       {
	 st = new SoundTouch();
        st.SetChannels((uint)WaveFormat.Channels);
        st.SetSampleRate((uint)WaveFormat.SampleRate);
	}
	
	public int Read(byte[] targetBuffer, int targetBufferOffset, int requestedBytes)
        {
	//Refer to the above comments
	}
```

**Comment by guoluming** [comment]
just put soundtouch.dll in the execution directory,add soundtouch.cs in project.
	
```
////AudioRenderer.cs
using soundtouch;
	
internal sealed class AudioRenderer : IDisposable, IRenderer, IWaveProvider
{
    public SoundTouch st;
    private short[] stBuffer = null;
}

/// <summary>
/// Initializes the audio renderer.
/// Call the Play Method to start reading samples
/// </summary>
private void Initialize()
{
    st = new SoundTouch();
    st.SetChannels((uint)WaveFormat.Channels);
    st.SetSampleRate((uint)WaveFormat.SampleRate);
}

public int Read(byte[] targetBuffer, int targetBufferOffset, int requestedBytes)
{
    //Refer to the above comments
}
```

**Comment by mariodivece** [comment]
I have implemented with all the recommendations from @guoluming 
It is currently an experimental feature. If it finds SoundTouch.dll in the binary directory or in the ffmpeg directory, then it uses it automatically. 
I noticed the higher speedratio values work very well, but smaller speedratios sound choppy. Do you gys experience the same issues. Could you test and let me know?

**Comment by whim77** [comment]
I too. If it is smaller than 1x, it will be broken.

**Comment by alex-buraykin** [comment]
Any ideas how to fix for smaller speedratios?

**Comment by alex-buraykin** [comment]
If set 

```
SyncThesholdMilliseconds = 0.25 * DesiredLatency.TotalMilliseconds; // ~25% sync threshold for audio samples 
```

Then lower speedratios work fine

**Comment by mariodivece** [comment]
This issue has been resolved. Thanks for your help. Beta 8 coming in the next few days!

**Comment by maptz** [comment]
Hi, 

Did audio pitch correction for speed-ratios ever get baked into the release? Did you find a way of getting it to work?

**Comment by mariodivece** [comment]
it has been available for a long time. You need SoundTouch.dll on the same folder as the ffmpeg binaries.
https://www.surina.net/soundtouch/download.html

**Comment by maptz** [comment]
Thanks for the quick response. 

I've downloaded that placed the DLL into the same folder as the binary file, and included SoundTouch.cs in my WPF project? 

How do I register that with the MediaElement? Is there a way of turning it on/off without recompiling (ie depending on a setting in the App)?

**Comment by mariodivece** [comment]
no, you don't need the cs file or anything. Just place the SoundTouch.dll file in the same folder where the ffmpeg libraries are. These instructions right in the Readme.md file.
![image](https://user-images.githubusercontent.com/351978/60375318-5337f680-99ce-11e9-9b33-709ae01df1c1.png)

**Comment by maptz** [comment]
Thanks. I literally just saw that in the readme. Will try that now.

Is it possible to turn the pirch corr xtion on and off when running, or is it just based on presence of the DLL?

**Comment by mariodivece** [comment]
no way to turn it on or off. You can always submit a new issue as a feature request!

**Comment by maptz** [comment]
Ok. I got that working. 

For anyone who comes across this thread, and who has difficulties getting the sound-correction to work, if you are running the app as x64, you need to copy the the SoundTouch_64.dll into your FFMPEG binary folder, and rename it to SoundTouch.dll.

**Comment by chanai-m** [comment]
As far as i remember is that it is not really need to put SoundTouch.dll into project directory. 
You just can compile normal project and put dll into application folder later and it will affect accordingly.
So my idea for workaround is that to do on/off you just rename dll into something else for off state and rename to SoundTouch.dll for on state.
(Maybe need to restart application)

**Comment by Mitra-M** [comment]
I tested SoundTouch.dll with many files , it works great for Win 10 , but has noise on Win 7 , any idea?

**Comment by TMS-Namespace** [comment]
Anyone can advice how to resolve the choppy sound on small speed ratio? tested this on different videos, and the sound is choppy, even with the provide sample in the source code (I am using the x64 version of SoundTouch dll, after renaming it to remove the x64 prefix, otherwise it dose not work at all, v 2.1.1 as required).
