### ISSUE TITLE
Unable to delete media file after opening it

### ISSUE THREAD

**Issue by MrBean2016** [unosquare/ffmediaelement#73]
The setup is that the user captures a series of videos, reviews them and delete some from the application by using  File.Delete. I discovered that the file is not deleted from disk until the application terminates. 

Basically the flow is
Media.Close();
Media.Source = null;
...
File.Delete.
I even moved the File.Delete to a BackgroundWorker with a delay, but the file is not deleted from disk until application terminates, the file will also be locked.

With some Goole-fu, the problem is the feature delete-on-last-close and that the file is not opened with the flag FILE_SHARE_DELETE 
https://stackoverflow.com/a/13209717/4146066

I am not sure if it possible to address this somehow by changing the dispose or stream handling, maybe it is inside this function avformat_open_input?

Maybe I have to find a workaround, hiding files marked for deletion in the application GUI or something.

**Comment by mariodivece** [comment]
Hmmm... strange... I open a media file, call Close on the media element (no need to call dispose). Tried deleting and the file deletes without a problem. In other words, I can't reproduce the issue. Maybe this is related to you own directory permissions?

**Comment by MrBean2016** [comment]
Ok, I have to review my code again, thanks for looking into it. I will close it for now.
