### ISSUE TITLE
Windows 7 produce lagging video

### ISSUE THREAD

**Issue by MonkeyDoll** [unosquare/ffmediaelement#76]
Hello,
Below is what i have tested.

-Windows 10 x64 with ffmediaelement, work fine.
-Windows 7 x64 with ffmediaelement, lagging.
-Windows 10 x64 with mediaelement, work fine.
-Windows 7 x64 with mediaelement, work fine.

All testing was done by same spec and i also tried to use virtual machine with fresh Windows 7, Windows 10 install.

**Comment by MonkeyDoll** [comment]
Oh, I am sorry. Just found related issue #75. Will update and feedback again

**Comment by mariodivece** [comment]
I will close this one then. Are you making sure you are running the latest version of FFME? Please reopen #75 with your feedback if you are still experiencing issues.
