### ISSUE TITLE
AccessViolationException when calling Close command while Seeking

### ISSUE THREAD

**Issue by guoluming** [unosquare/ffmediaelement#77]
The program crashes when the video source is turned off or switched off immediately during seeking.In online video playback,it occurs inevitably.
after CloseCommand execute,InputContext has been set free. Cause an exception System.AccessViolationException 

//crash here ，
var readResult = ffmpeg.av_read_frame(InputContext, readPacket);

        /// <summary>
        /// Releases unmanaged and - optionally - managed resources.
        /// </summary>
        /// <param name="alsoManaged">
        ///   <c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
        private void Dispose(bool alsoManaged)
        {
            if (IsDisposed) return;

            if (alsoManaged)
            {
                if (m_Components != null)
                    m_Components.Dispose();
            }

            if (InputContext != null)
            {
                StreamReadSuspend();
                fixed (AVFormatContext** inputContext = &InputContext)
                    ffmpeg.avformat_close_input(inputContext);

                ffmpeg.avformat_free_context(InputContext);
                InputContext = null;
            }

            IsDisposed = true;
        }

**Comment by mariodivece** [comment]
@guoluming I see that my reference counter reports a leak when testing with HLS streaming (i.e. seek and Close while seeking). Could you send me the stream you are testing with and the steps to reproduce. Trying to troubleshoot this issue. Checking for null on InputContext is certainly a hack. Disposal logic should be as clean as possible.

**Comment by guoluming** [comment]
http://mpv.videocc.net/68040382d0/c/68040382d06f36b6ee7a8a0401cc5c4c_1.mp4
Any online video have this issue (i.e. seek and Close while seeking)
