### ISSUE TITLE
Some RTSP delay 20s

### ISSUE THREAD

**Issue by DG-Wangtao** [unosquare/ffmediaelement#78]
Thanks to your work I get a way to play videos in rtsp with low CPU consumption. In most cases it works well , however, some erro I meet when I want to play some rtsp. In your sample a rtspl start show pictures after 20 seconds, and allway be delayd in that timespan. 
I setup flow code and it doesnot work:
```
private void Media_MediaOpening(object sender , MediaOpeningRoutedEventArgs e)
        {
            e.Options.EnableFastDecoding = true;
            e.Options.ProbeSize = 32;
            e.Options.MaxAnalyzeDuration = TimeSpan.Zero;
        }
``` 
In the end, I found that time is spend at `MediaContainer.cs` ,function `StreamOpen()`,
```
 CanReadSuspend = ffmpeg.av_read_pause(InputContext) == 0;
            ffmpeg.av_read_play(InputContext);
```
I'm sorry that my uri of rtsp is in my local area network so that I cannot give it, and is most cases I donnot meet the erro.
I have found ealy issues or other doc, but I cannot solve my problem, so,can you help me?

**Comment by DG-Wangtao** [comment]
Sorry to trouble, I have found that I should set the `e.Options.ReadTimeout` to small.

**Comment by mariodivece** [comment]
So you were able to fix this? What did you set the ReadTimeout to?

**Comment by DG-Wangtao** [comment]
When I set the ReadTimeout to 3 seconds it work in 2~3s 's delay. I think the reason is somewrong with my flow.
My next work is to make the vedio play in unrestricted view, shadowy image always show.


王涛
 
From: Mario Di Vece
Date: 2017-09-18 10:35
To: unosquare/ffmediaelement
CC: DG-Wangtao; State change
Subject: Re: [unosquare/ffmediaelement] Some RTSP delay 20s (#78)
So you were able to fix this? What did you set the ReadTimeout to?
