### ISSUE TITLE
How to set the source from the player?

### ISSUE THREAD

**Issue by Dokman** [unosquare/ffmediaelement#79]
So how i can use the function?

Uri url = new Uri(path);
Player.Source = url;
Player.Play();

if i do this to test it doesn't do anything

**Comment by mariodivece** [comment]
Any debug console messages (you need to subscribe to the corresponding events and output them)? What is your LoadedBehavior set to?

**Comment by Dokman** [comment]
i know that in menu is not a good idea to set up the player, but is for testing and then try to use it in his own window

public Menu()
        {
            InitializeComponent();
            play();
        }

        public void play()
        {
            var path = @"D:\Bibliotecas\Anime\11 eyes\11 Eyes 1.mp4";
            Uri url = new Uri(path);
            Player.Source = url;
            Player.Play();
        }


        // testing code
        private void Player_Loaded(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("He hecho algo","tatan");
            play();
        }

        private void Player_Initialized(object sender, EventArgs e)
        {
            MessageBox.Show("He hecho algo", "tatan");
            play();
        }

**Comment by mariodivece** [comment]
Menu? Could you follow the directions as stated in the readme please?
![image](https://user-images.githubusercontent.com/351978/30603028-f26bd024-9d2b-11e7-930e-657c00ed1411.png)

**Comment by Dokman** [comment]
yes is like this but nothing works XAML:

<TabItem Header="New">
                <Grid >
                    <FFME:MediaElement HorizontalAlignment="Left" Height="414" Margin="10,0,0,0" VerticalAlignment="Top" Width="866" RenderTransformOrigin="-0.618,-0.739" Name="Player" Loaded="Player_Loaded" Initialized="Player_Initialized" LoadedBehavior="Play" UnloadedBehavior="Manual"/>
                </Grid>
            </TabItem>

**Comment by mariodivece** [comment]
So, the sample does not work either then?

**Comment by Dokman** [comment]
the sample work but when i use 
`Palyer.Source = @"mypath"`
i doesn not load the file so when i try to play it not works

**Comment by Dokman** [comment]
okay i will send you the project

**Comment by mariodivece** [comment]
you can attach your project file here in the issue

**Comment by Dokman** [comment]
then i will upload the project tomorrow

**Comment by DG-Wangtao** [comment]
I think you forget set this:
```
 Unosquare.FFME.MediaElement.FFmpegDirectory = dllSource;
```
Hope useful.

**Comment by mariodivece** [comment]
I am closing this one as no further feedback was provided. @DG-Wangtao Thanks for providing him with hopefully some help!
