### ISSUE TITLE
A Trail Of Discovery: Adding Referrer support and User-agent into the library.

### ISSUE THREAD

**Issue by 9Arca9** [unosquare/ffmediaelement#8]
How well is rtmp supported? 
(Answer: RTMP Is supported but only specific video encoding. MP4 being the best i think)

Additionally, how would i go about handling HD m3u8 files. Avoiding this error:
(Resolved, See Edit 2)
```
MediaFailed Event Fired System.Exception: Could not load sream frames in a timely manner. Timed out in 00:00:02
   at Unosquare.FFmpegMediaElement.FFmpegMedia..ctor(String filePath, MediaErrorOccurredCallback errorCallback) in C:\Users\Luke\Downloads\ffmediaelement-master\Unosquare.FFmpegMediaElement\FFmpegMedia.cs:line 146
   at Unosquare.FFmpegMediaElement.MediaElement.OpenMedia(Uri sourceUri) in C:\Users\Luke\Downloads\ffmediaelement-master\Unosquare.FFmpegMediaElement\MediaElement.MediaProperties.cs:line 241
```

EDIT 1: I changed the constant to 15 seconds to give it extra time after poking around but it didn't seem to do anything for loading.

EDIT 2: Fixed the issue with the m3u8. The file contained multiple links and this was confusing the player. Need to manual strip out the first/best working link from the m3u8 file.

EDIT 3: Now seem to be having issues ~~with select files pointing to a list of TS links~~ M3u8 files that require user-agent. It's throwing file could not be opened. Link was working a-okay in VLC's Player. FFMPEG is throwing this value as an error.
-858797304

Edit 4: 
-858797304 to hex = -0x333034F8
-0x333034F8 to ascii = ?304 (Flipped) is 403.
 
Seems like the video player doesn't have a "set" http client like VLC. Going to see if i can resolve by making ffmpeg use a User-Agent header in its request to the url. This should hopefully resolve the issue with 403 in this case.

EDIT 5:
Fixed issue with m3u8 file not playing due to lacking user-agent by adding
`ffmpeg.av_dict_set(&optionsDict, "user-agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36", 0);`

to FFmpeg.MediaDecoding.cs at line 89

Whew, finally got that done after 3 hours of research..

EDIT 6: 
Trying to figure out how to assign referrer header to request.. Doesn't work like previous method.

EDIT 7:
Figure out how to set referer used
` ffmpeg.av_dict_set(&optionsDict, "headers", "Referer:"+referer, 0);`

EDIT 8:
I added in support for using `MediaElement.Referer = ""` and `MediaElement.UserAgent = ""` into the library.
This is sloppy so if anyone comes along feel free to redo this
FFMpegMedia.Decoding.cs at lines 84 to 109
```
private void InitializeMedia(string filePath, string referer, string useragent)
        {
            // Create the input format context by opening the file
            InputFormatContext = ffmpeg.avformat_alloc_context();
            AVDictionary* optionsDict = null;
            ffmpeg.av_dict_set_int(&optionsDict, "usetoc", 1, 0);
            if (referer != null) {
                ffmpeg.av_dict_set(&optionsDict, "headers", "Referer:"+referer, 0);
            }

            if (useragent != null)
            {
                ffmpeg.av_dict_set(&optionsDict, "user-agent", useragent, 0);
            }
            else
            {
                ffmpeg.av_dict_set(&optionsDict, "user-agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36", 0);
            }
            

            fixed (AVFormatContext** inputFormatContextRef = &InputFormatContext)
            {
                int result = ffmpeg.avformat_open_input(inputFormatContextRef, filePath, null, &optionsDict);
                if (result != 0)
                   throw new Exception(string.Format("Could not open file '{0}' with error '{1}'", filePath, result));
            }
```

FFMpeg.Media line 92
`this.InitializeMedia(filePath, referer, userAgent);`

MediaElement.MediaProperties line 241
` this.Media = new FFmpegMedia(inputPath, OnMediaError, useragent, referer);`

MediaElement.DependencyProperties

32-33
`private static string intReferer = "";
 private static string intUserAgent = "";`
77
`  element.OpenMedia(uri, intReferer, intUserAgent);`
97-105
`   public string Referer {
            get { return intReferer; }
            set { intReferer = value; }
        }
        public string UserAgent
        {
            get { return intUserAgent; }
            set { intUserAgent = value; }
        }`

MediaElement.Controls 

13,27,41
`this.OpenMedia(Source, Referer, UserAgent);`

**Comment by mariodivece** [comment]
Adding referer and user agent support ads dependency properties.
Thanks for all this info @9Arca9 !
