### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by Basslk** [unosquare/ffmediaelement#81]
I'm randomly receiving an exception of type MediaContainerException in MediaContainer.cs 
`if (openResult < 0)
                        {
                            throw new MediaContainerException($"Could not open '{MediaUrl}'. "
                                + $"Error {openResult}: {FFmpegEx.GetErrorMessage(openResult)}");
                        }`

The video source is working smoothly outside, and there is no pattern for this exception

**Comment by mariodivece** [comment]
You need to provide the media file. Otherwise I can't help you. what happens when you do ```ffplay "inputfilehere"``` ?

**Comment by mariodivece** [comment]
Any updates here? Any test files I can use? What is your FFmpeg build?

**Comment by mariodivece** [comment]
Closing this issue as there was no further feedback reported in a month and it is an ffmpeg issue and not an FFME issue.
