### ISSUE TITLE
Async Commands and Implementation Pattern

### ISSUE THREAD

**Issue by deltasem** [unosquare/ffmediaelement#84]
I have some trouble with open command - it freez UI thread in this loop:
```c#
private void ExecuteAndWaitFor(MediaCommand command)
{
.....
    while (waitTask.IsCompleted == false)
    {
        // Pump invoke
        Dispatcher.CurrentDispatcher.Invoke(
            DispatcherPriority.Background,
                new Action(() => { }));
    }
}
```
I try to make it async (only Open command for now). It work fine. Can you review this? If all ok, I can rewrite all commands with async. My changes in [this commit](https://github.com/deltasem/ffmediaelement/commit/0af848188794f06204ed2c3d2404f4299a89685a)

**Comment by mariodivece** [comment]
I have been debating the command implementation pattern for some time now myself and I am happy you are joining th conversation @deltasem . I have gone back and forth between Async and Sync-and-background-wait commands. The reason I am trying to go for the latter is that I waned to make FFME as compatible with the regular mediaelement as possible. But the synchronous background wait pattern seems to be causing a ton of issues. Let me think about this a little more and update the issue.

**Comment by mariodivece** [comment]
Async commanding now completed! All that pumping and waiting is gone for good. Closing this issue. Please reopen if you find more issues.
