### ISSUE TITLE
Pause for RTSP streams

### ISSUE THREAD

**Issue by deltasem** [unosquare/ffmediaelement#86]
RTSP streams can be not-live streams. And RTSP can be paused (and seekable), work great with ffplay. For now property MediaElement.IsLiveStream (Container.IsStreamRealtime) depend from LiveStreamFormatNames and LiveStreamUrlPrefixes, I think is not correct.

**Comment by mariodivece** [comment]
true... You are right. What do you think about the following logic:
MediaElement.IsLiveStream = Container.IsStreamRealtime && Duration.IsIndeterminate

**Comment by deltasem** [comment]
I think Container.MediaDuration can't be garaunteed indicator for Live streams. For example I have some RTSP not-Live streams, and duration they have less then zero, but greater MinValue. And I think CanPause should not depend from IsStreamSeekable. So, this work for me:
```c#
        public bool CanPause
        {
            get { return IsOpen ? !IsLiveStream : false; }
        }
        public bool IsLiveStream
        {
            get { return IsOpen ? Container.IsStreamRealtime && Container.MediaDuration == TimeSpan.MinValue : false; }
        }
```
I can create pull request with this changes, what do you think about this?

**Comment by mariodivece** [comment]
I think your logic is good. I will test with more streams and reopen if necessary.
