### ISSUE TITLE
Unable to seek or replay WMV files after they ended

### ISSUE THREAD

**Issue by tpetrina** [unosquare/ffmediaelement#87]
Certain WMV files have issues in sample player. Once playback is complete, seeking or replaying video is impossible.

You can use the sample files from here http://samples.mplayerhq.hu/V-codecs/WVC1/ to reproduce the issue easily. It seems that seeking back doesn't decode anything. Clicking play starts playing, but video is not actually played.

**Comment by tpazman** [comment]
There is a video frame with no timestamp at the end of this file :

[FRAME]
media_type=video
stream_index=1
key_frame=0
pkt_pts=N/A
pkt_pts_time=N/A
pkt_dts=N/A
pkt_dts_time=N/A
best_effort_timestamp=N/A
best_effort_timestamp_time=N/A
pkt_duration=16
pkt_duration_time=0.016000
pkt_pos=5621343
pkt_size=4135
width=852
height=480
pix_fmt=yuv420p
sample_aspect_ratio=1:1
pict_type=P
coded_picture_number=1494
display_picture_number=0
interlaced_frame=0
top_field_first=0
repeat_pict=0
[/FRAME]

VideoFrame (and AudioFrame, for that matter) constructor gives AV_NOPTS frames a StartTime of "MediaStartTimeOffset" which is zero here. Then this frame added to the start of PlaybackBlocks so the list contains the first frame and (buffer - 1) final frames. With this, the IsInRange method will return true for any position in the video.

As a test I added a NoPts flag to VideoFrame and then in AddBlocks foreach loop:

                if (frames.Count == 1 && frame is VideoFrame && ((VideoFrame)frame).NoPts)
                {
                    continue;
                }

which solves the problem in this specific case. Anyone know a proper solution for this?

**Comment by mariodivece** [comment]
@tpetrina This issue is closely related to #29 
Let me examine what I can do.

**Comment by mariodivece** [comment]
Ok, I think we have a good approach here. I have reviewed the code in ffmpeg.c and looked at how it addresses the lack of PTS information in the frame. It basically just guesses it from the prior frame. I have done the same. The WMV files play well, can be seeked, etc. Test again and check if it is fixed for you. Close the issue if no further action is required.

**Comment by tpetrina** [comment]
Thanks @mariodivece, I will look into it and report after testing.

**Comment by mariodivece** [comment]
Any updates here @tpetrina ?

**Comment by mariodivece** [comment]
@tpetrina I am closing this issue as there was no further feedback. Please reopen if needed. Thanks.

**Comment by tpetrina** [comment]
The bug was fixed, thanks for your help!
