### ISSUE TITLE
Running MediaElement in second window

### ISSUE THREAD

**Issue by vedrantrebovic** [unosquare/ffmediaelement#9]
When running MediaElement in second window it throws "The calling thread cannot access this object because a different thread owns it.". Exception is first thrown when raising FFmpegMedia.PropertyChanged event.
Second window is running on different thread than Main thread. 
I debugged it, and event is raised on thread that second window is running on, and MediaElement should be created on the same thread (but it doesn't seem like it).

**Comment by vedrantrebovic** [comment]
The problem was Application.Current.Dispatcher.BeginInvoke(...) call which was always invoking method on application Main thread. It should be replaced with Dispatcher.CurrentDispatcher.BeginInvoke(...) so it will always invoke it on correct thread.
I hope this helps someone else too.

**Comment by mariodivece** [comment]
Could you tell me file name and line number?
Being this an open source project, you are welcome to provide your Pull Requests..

**Comment by vedrantrebovic** [comment]
It is MediaElement class in namespace Unosquare.FFmpegMediaElement.
Methods:  HandleMediaPropertyChanged and OnMediaError

**Comment by mariodivece** [comment]
Ok, thanks. I have updated the code and tested and it works well.
Closing now.
