### ISSUE TITLE
Hangs when running on a Atom processor.

### ISSUE THREAD

**Issue by dmmaster** [unosquare/ffmediaelement#91]
Situation - a constant change of videos (every 7 seconds), sometimes hangs when you start the next clip up to 1-6 seconds. 
2 MediaElement's have сonsistently changing. The first MediaElement plays the video, the second MediaElement loads the next video, then they change.
All videos have the same duration (7000 msec +/- 100 msec). Hangs is not always, on different videos. 
The program runs on different computers, hangs are detected only on D2500 Atom processors (15-30% CPU utilization), 32bit Windows Embedded Standard. .NET 4.6. 
How to increase the priority of playback, minimize any delay?

**Comment by mariodivece** [comment]
In the OpenCommand.cs, find the following lines:
```csharp
                // Create the thread runners
                m.PacketReadingTask = new Thread(m.RunPacketReadingWorker)
                { IsBackground = true, Name = nameof(m.PacketReadingTask), Priority = ThreadPriority.Normal };

                m.FrameDecodingTask = new Thread(m.RunFrameDecodingWorker)
                { IsBackground = true, Name = nameof(m.FrameDecodingTask), Priority = ThreadPriority.AboveNormal };

                m.BlockRenderingTask = new Thread(m.RunBlockRenderingWorker)
                { IsBackground = true, Name = nameof(m.BlockRenderingTask), Priority = ThreadPriority.Normal };
```

Pleay around with the ThreadPriority parameters and let me know which combination fixes the issue.
Thanks!

**Comment by mariodivece** [comment]
Any updates here? This probably won't work until full hardware acceleration support is available. Partial HW acceleration support is available.

**Comment by mariodivece** [comment]
I am closing this for lack of updates. This will most likely be solved when hardware decoding is fully implemented. If you have further updates please reopen this issue.
