### ISSUE TITLE
Buggy GIF Playback

### ISSUE THREAD

**Issue by nehz** [unosquare/ffmediaelement#92]
Seems to have issues with GIF playback.
NaturalDuration not populated and cannot play after GIF finishes (e.g cannot loop)

**Comment by mariodivece** [comment]
hmmm strange behavior when loading GIFs (had not tried GIFs before). I see they play but sometimes it gets stuck. Let me take a look. Could you provide some gif examples you are testing with?

**Comment by nehz** [comment]
This is the GIF I tested with:
![giphy](https://user-images.githubusercontent.com/151358/31231446-748eee48-aa19-11e7-9052-e2022bf9674c.gif)

NaturalDuration seems to contain no duration.
And after GIF finishes if you do
```
media.seek(0)
media.play()
```
doesn't seem to play

**Comment by mariodivece** [comment]
I tested with my latest commit and looks like the issue is timing properties missing like you said. The GIF plays normally, but nothing else can be done after or during playback. Let me see how I could possibly extract the duration.

**Comment by mariodivece** [comment]
per my tests with ffprobe and ffplay, the duration of a gif file cannot be determined in advance. I simply enabled the stop button when the media has ended so it rewinds it. Seeking creates a ton of ffmpeg error messages and artifacts in the image -- try with ffplay. See my latest commit. If you want to loop the gif, simply handle the media ended event, call the stop method and then call the play method.

**Comment by ashelleyPurdue** [comment]
A quick google search unearthed this method for finding the duration of a gif: 
https://stackoverflow.com/questions/47343230/how-do-you-get-the-duration-of-a-gif-file-in-c

I'm using it right now to display the progress of a gif, and it's working great.  Is there any particular reason you can't use it in ffme?

**Comment by mariodivece** [comment]
That's not using ffmpeg. Good you can use it outside. Outside the scope of this project.
