### ISSUE TITLE
Audio devices not checked for state

### ISSUE THREAD

**Issue by guoluming** [unosquare/ffmediaelement#93]
Audio rendering is only initialized during the opening, and it would be better to have real-time detection if audio devices were disabled and turned on.In the current version, if the audio device is disabled, initialization fails and the audio device is turned on again without being initialized.

**Comment by mariodivece** [comment]
Are you planning on providing a PR for this? Or is this just an item for the back-burner?

**Comment by guoluming** [comment]
It`s an item.

**Comment by mariodivece** [comment]
There is now a new event: `AudioDeviceStopped` It is fired whenever the audio out loses its buffer. You can simply call the `ChangeMedia` command and it will re-open the newly selected audio device, or handle the `MediaChanging` event and select the new AudioDevice.
Example:
```csharp
            Media.AudioDeviceStopped += (s, e) =>
            {
                // If we detect that the audio device has stopped, simply
                // call the changemedia command so the default audio device gets selected
                // and reopened. See issue #93
                var task = Media.ChangeMedia();
            };
```
