### ISSUE TITLE
MSVC++ Runtime Library Error

### ISSUE THREAD

**Issue by nischal-km** [unosquare/ffmediaelement#94]
I am currently using the library to play multiple udp stream in my application but after playing one stream it gives Runtime Error.

![capture](https://user-images.githubusercontent.com/31039585/31572211-1ef72120-b0be-11e7-9510-f245c8792472.JPG)

**Comment by mariodivece** [comment]
You need to provide the sample application with sorce for me to reproduce and debug the issue

**Comment by nischal-km** [comment]
Well I have made changes in the sample provided and created two Media Element component in the UI and on one play command I started players like this:-

` MediaEl.Source=New Uri("udp://127.0.0.1:5012");`
`MediaElOther.Source=New Uri("udp://127.0.0.5:5015");`

Sometimes it plays the stream in both and sometimes it gives error.
Is there something wrong with this?

**Comment by mariodivece** [comment]
what happens if you simultaneously use ffplay.exe to play both streams? Does that work?

**Comment by mariodivece** [comment]
any updates here?

**Comment by nischal-km** [comment]
Multiple players works fine but sometimes application crashes while playing the stream or video with no exception.
Is there any way to handle those?

**Comment by mariodivece** [comment]
I have noticed those and I am right now clueless on how to handle those. I don't know what is causing them or how to find the root cause. Any help is greatly appreciated!

**Comment by flibX0r** [comment]
I hit a similar issue in a very non-deterministic fashion when creating a number of MediaElements from code with their Source property defined at creation. Looks like it's a thread locking issue with ffmpeg. 

The error I get from `MediaElement.FFmpegMessageLogged`:
````
[NULL @ 1861bc60] Insufficient thread locking. At least 2 threads are calling avcodec_open2() at the same time right now.
````

I'm currently solving the issue locally by only setting the source property one MediaElement at a time, waiting on the MediaOpened event to set the next.

**Comment by mariodivece** [comment]
@flibX0r I am so sorry I have taken this long to respond. I have been terribly busy. In my latest commit I have added locking when calling avcodec_open2. Could you try again (either @nischal-km or @flibX0r )?
Please reopen the issue if this error continues to appear. Thanks.
