### ISSUE TITLE
Synhronization problem

### ISSUE THREAD

**Issue by deltasem** [unosquare/ffmediaelement#97]
Trouble around MediaElement.Container - it disposing and setting null in CloseCommand. But it still available in worker threads as null and cause NullReferenceException.

**Comment by mariodivece** [comment]
@deltasem your PR is way too big because it contains a ton of critical code that has been tested extensively. I cannot just change all that stuff! Can you address all the stuff you did one by one?

**Comment by deltasem** [comment]
Not a problem, I'll do it directly in PR

**Comment by deltasem** [comment]
Done. Really not a big changes, just ignore whitespaces :) https://github.com/unosquare/ffmediaelement/pull/98/files?w=1

**Comment by mariodivece** [comment]
I will be reviewing the perfromance considerations between thread.Sleep and await Task.Delay

**Comment by mariodivece** [comment]
Please see my last commit -- CPU usage is too high with Thread.Sleep compared to Task.Delay

**Comment by deltasem** [comment]
@mariodivece please look at [this commit](https://github.com/deltasem/ffmediaelement/commit/305d618c55e9ac38a9a6109490058f6dcf74bfd4) 
There demonstration of problem. 
About CPU usage with Thread.Sleep - may be it just faster then Task.Delay? I'm not sure, but may be better sleep more longer? I think Task.Delay wait for .Net worker thread pool and therefore less CPU usage.

**Comment by deltasem** [comment]
I measured really sleep time with Task.Delay and Thread.Sleep. In my case around 3 200 000 ticks with Task.Delay and 1 800 000 ticks with Thread.Sleep

**Comment by deltasem** [comment]
I measured it. In my case with Task.Sleep(1) real sleep around 30000 ticks, with Thread.Sleep(1) - around 5000. Thread.Sleep faster in 6 times!

**Comment by mariodivece** [comment]
Reopening this one and closing the new issue

**Comment by mariodivece** [comment]
@deltasem you say the problem persists. Any fixes you recommend? Maybe a PR?

**Comment by deltasem** [comment]
@mariodivece sory for the long answer, I'll create PR in the coming days.

**Comment by deltasem** [comment]
@mariodivece with latests commits works fine! Thank you!
